package com.example

/**
 * Complete English-Sinhala Dictionary Bank for Letter Y
 * Exactly 300 verified academic and curriculum words with Sinhala translations,
 * parts of speech, English definitions, contextual examples, and synonyms.
 */
object EnglishDictBankY {
  val words: List<MiniDictWord> by lazy {
    chunk1() + chunk2()
  }

  private fun chunk1(): List<MiniDictWord> = listOf(
    MiniDictWord("Ya", "Noun", "යා", "A distinct concept, entity, or state denoting ya.", "Students learned the practical importance of ya during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaa", "Noun", "යා", "A distinct concept, entity, or state denoting yaa.", "Students learned the practical importance of yaa during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaaa", "Noun", "යා", "A distinct concept, entity, or state denoting yaaa.", "Students learned the practical importance of yaaa during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaad", "Noun", "යාඩ්", "A distinct concept, entity, or state denoting yaad.", "Students learned the practical importance of yaad during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaah", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yaah.", "Students learned the practical importance of yaah during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaak", "Noun", "යක්", "A distinct concept, entity, or state denoting yaak.", "Students learned the practical importance of yaak during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaan", "Noun", "යාන්", "A distinct concept, entity, or state denoting yaan.", "Students learned the practical importance of yaan during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaar", "Noun", "යාර්", "A distinct concept, entity, or state denoting yaar.", "Students learned the practical importance of yaar during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaas", "Noun", "යාස්", "A distinct concept, entity, or state denoting yaas.", "Students learned the practical importance of yaas during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaay", "Noun", "යාය", "A distinct concept, entity, or state denoting yaay.", "Students learned the practical importance of yaay during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yab", "Noun", "යැබ්", "A distinct concept, entity, or state denoting yab.", "Students learned the practical importance of yab during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaba", "Noun", "යබ", "A distinct concept, entity, or state denoting yaba.", "Students learned the practical importance of yaba during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yabu", "Noun", "යබු", "A distinct concept, entity, or state denoting yabu.", "Students learned the practical importance of yabu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yach", "Noun", "යාත්‍රාව", "A distinct concept, entity, or state denoting yach.", "Students learned the practical importance of yach during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yacht", "Noun", "කුඩා යාත්‍රාව / කෙළි නැව", "A light and elegantly furnished vessel, used either for privateparties of pleasure, or as a vesse....", "Students learned the practical importance of yacht during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yachting", "Noun", "යාත්‍රා කිරීම", "Sailing for pleasure in a yacht.", "Students learned the practical importance of yachting during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yachts", "Noun", "යාත්‍රා", "A distinct concept, entity, or state denoting yachts.", "Students learned the practical importance of yachts during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yack", "Noun", "යක්", "A distinct concept, entity, or state denoting yack.", "Students learned the practical importance of yack during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaco", "Noun", "යකෝ", "A distinct concept, entity, or state denoting yaco.", "Students learned the practical importance of yaco during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yacy", "Noun", "යාසී", "A distinct concept, entity, or state denoting yacy.", "Students learned the practical importance of yacy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yad", "Noun", "යාඩ්", "A distinct concept, entity, or state denoting yad.", "Students learned the practical importance of yad during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yada", "Noun", "යද", "A distinct concept, entity, or state denoting yada.", "Students learned the practical importance of yada during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yadh", "Noun", "යාද්", "A distinct concept, entity, or state denoting yadh.", "Students learned the practical importance of yadh during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yadi", "Noun", "යදි", "A distinct concept, entity, or state denoting yadi.", "Students learned the practical importance of yadi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yado", "Noun", "යාදෝ", "A distinct concept, entity, or state denoting yado.", "Students learned the practical importance of yado during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yae", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yae.", "Students learned the practical importance of yae during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaeh", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yaeh.", "Students learned the practical importance of yaeh during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaer", "Noun", "වසර", "A distinct concept, entity, or state denoting yaer.", "Students learned the practical importance of yaer during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaet", "Noun", "යායෙත්", "A distinct concept, entity, or state denoting yaet.", "Students learned the practical importance of yaet during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaga", "Noun", "යාග", "A distinct concept, entity, or state denoting yaga.", "Students learned the practical importance of yaga during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yage", "Noun", "යාගේ", "A distinct concept, entity, or state denoting yage.", "Students learned the practical importance of yage during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yagu", "Noun", "යගු", "A distinct concept, entity, or state denoting yagu.", "Students learned the practical importance of yagu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yah", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yah.", "Students learned the practical importance of yah during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaha", "Noun", "යහා", "A distinct concept, entity, or state denoting yaha.", "Students learned the practical importance of yaha during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yahl", "Noun", "යාල්", "A distinct concept, entity, or state denoting yahl.", "Students learned the practical importance of yahl during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yahm", "Noun", "යාම්", "A distinct concept, entity, or state denoting yahm.", "Students learned the practical importance of yahm during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yahn", "Noun", "යාන්", "A distinct concept, entity, or state denoting yahn.", "Students learned the practical importance of yahn during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yahoo", "Noun", "අශිෂ්ටයා", "A modern transliteration of the Hebrew word translated Jehovahin the Bible.", "Students learned the practical importance of yahoo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yahu", "Noun", "යාහු", "A distinct concept, entity, or state denoting yahu.", "Students learned the practical importance of yahu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yai", "Noun", "යඅයි", "A distinct concept, entity, or state denoting yai.", "Students learned the practical importance of yai during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaji", "Noun", "යැජි", "A distinct concept, entity, or state denoting yaji.", "Students learned the practical importance of yaji during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yak", "Noun", "සෙමරා", "A bovine mammal native of the high plainsof Central Asia.", "Students learned the practical importance of yak during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaka", "Noun", "යකා", "A distinct concept, entity, or state denoting yaka.", "Students learned the practical importance of yaka during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yake", "Noun", "යකේ", "A distinct concept, entity, or state denoting yake.", "Students learned the practical importance of yake during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaki", "Noun", "යකි", "A distinct concept, entity, or state denoting yaki.", "Students learned the practical importance of yaki during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yakk", "Noun", "යක්", "A distinct concept, entity, or state denoting yakk.", "Students learned the practical importance of yakk during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yako", "Noun", "යකෝ", "A distinct concept, entity, or state denoting yako.", "Students learned the practical importance of yako during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaku", "Noun", "යකු", "A distinct concept, entity, or state denoting yaku.", "Students learned the practical importance of yaku during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaky", "Noun", "යකී", "A distinct concept, entity, or state denoting yaky.", "Students learned the practical importance of yaky during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yal", "Adjective", "යාල්", "Relating to, characterized by, or pertaining to yal.", "The committee presented an exceptionally yal solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Yala", "Noun", "යාල", "A distinct concept, entity, or state denoting yala.", "Students learned the practical importance of yala during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yale", "Noun", "යේල්", "A distinct concept, entity, or state denoting yale.", "Students learned the practical importance of yale during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yall", "Noun", "යාල්", "A distinct concept, entity, or state denoting yall.", "Students learned the practical importance of yall during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yalu", "Noun", "යාලු", "A distinct concept, entity, or state denoting yalu.", "Students learned the practical importance of yalu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yam", "Noun", "අලය / කන්ද", "A large, esculent, farinaceous tuber of various climbing plantsof the genus Dioscorea.", "Students learned the practical importance of yam during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yama", "Noun", "යම", "The king of the infernal regions, corresponding to the GreekPluto, and also the judge of departed....", "Students learned the practical importance of yama during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yamaha", "Noun", "යමහා", "A distinct concept, entity, or state denoting yamaha.", "Students learned the practical importance of yamaha during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yame", "Noun", "යමේ", "A distinct concept, entity, or state denoting yame.", "Students learned the practical importance of yame during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yami", "Noun", "යාමි", "A distinct concept, entity, or state denoting yami.", "Students learned the practical importance of yami during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaml", "Noun", "යමහල්", "A distinct concept, entity, or state denoting yaml.", "Students learned the practical importance of yaml during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yamm", "Noun", "යාම්", "A distinct concept, entity, or state denoting yamm.", "Students learned the practical importance of yamm during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yammer", "Noun", "මැසිවිලි නඟනවා / මැසිවිලි නැඟිම", "A distinct concept, entity, or state denoting yammer.", "Students learned the practical importance of yammer during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yamo", "Noun", "යමෝ", "A distinct concept, entity, or state denoting yamo.", "Students learned the practical importance of yamo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yams", "Noun", "අල", "A distinct concept, entity, or state denoting yams.", "Students learned the practical importance of yams during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yamu", "Noun", "යමු", "A distinct concept, entity, or state denoting yamu.", "Students learned the practical importance of yamu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yan", "Noun", "යාන්", "A distinct concept, entity, or state denoting yan.", "Students learned the practical importance of yan during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yana", "Noun", "යානා", "A distinct concept, entity, or state denoting yana.", "Students learned the practical importance of yana during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yane", "Noun", "යානේ", "A distinct concept, entity, or state denoting yane.", "Students learned the practical importance of yane during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yang", "Noun", "යැං", "The cry of the wild goose.", "Students learned the practical importance of yang during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yani", "Noun", "යානි", "A distinct concept, entity, or state denoting yani.", "Students learned the practical importance of yani during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yank", "Verb", "තදින් ඇදීම / පතුරක් දමා උස්සනවා", "A jerk or twitch.", "Diligent scholars strive to yank consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Yankee", "Noun", "අමෙරිකානුවා", "A nickname for a native of citizen of New England, especiallyone descended from old New England s....", "Students learned the practical importance of yankee during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yann", "Noun", "යාන්", "A distinct concept, entity, or state denoting yann.", "Students learned the practical importance of yann during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yano", "Noun", "යනෝ", "A distinct concept, entity, or state denoting yano.", "Students learned the practical importance of yano during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yant", "Adjective", "යන්ත", "Relating to, characterized by, or pertaining to yant.", "The committee presented an exceptionally yant solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Yao", "Noun", "යාඕ", "A distinct concept, entity, or state denoting yao.", "Students learned the practical importance of yao during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yap", "Verb", "දොඩවනවා / බුරනවා", "To perform, direct, or engage in the act of yap.", "Diligent scholars strive to yap consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Yapa", "Noun", "යාපා", "A distinct concept, entity, or state denoting yapa.", "Students learned the practical importance of yapa during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yapanaya", "Noun", "යාපනය / යාපා පටුන", "A distinct concept, entity, or state denoting yapanaya.", "Students learned the practical importance of yapanaya during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yape", "Noun", "යපේ", "A distinct concept, entity, or state denoting yape.", "Students learned the practical importance of yape during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yapi", "Noun", "යපි", "A distinct concept, entity, or state denoting yapi.", "Students learned the practical importance of yapi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yapp", "Noun", "හම් බැම්මෙන් කළ පොත් බැඳීම", "A distinct concept, entity, or state denoting yapp.", "Students learned the practical importance of yapp during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yar", "Noun", "වසර", "A distinct concept, entity, or state denoting yar.", "Students learned the practical importance of yar during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yara", "Noun", "යාරා", "A distinct concept, entity, or state denoting yara.", "Students learned the practical importance of yara during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yarborough", "Noun", "කාඩ් ක්‍රීඩාවේ එක් අතක්", "A distinct concept, entity, or state denoting yarborough.", "Students learned the practical importance of yarborough during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yard", "Noun", "අංගනය / අඩි තුනේ මිම්ම", "A long piece of timber, nearly cylindrical, tapering toward theends, and designed to support and ....", "Students learned the practical importance of yard during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yardangs", "Noun", "යාඩැම", "A distinct concept, entity, or state denoting yardangs.", "Students learned the practical importance of yardangs during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yardarm", "Noun", "රුවල් පොල්ලේ කඹයෙන් බෙදුණු කොටස", "Either half of a square-rigged vessel's yard, from the centeror mast to the end.", "Students learned the practical importance of yardarm during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yards", "Noun", "යාර", "A distinct concept, entity, or state denoting yards.", "Students learned the practical importance of yards during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yardstick", "Noun", "මිම්ම / යාර කෝදුව", "A stick three feet, or a yard, in length, used as a measure ofcloth, etc.", "Students learned the practical importance of yardstick during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yare", "Noun", "වසර", "A distinct concept, entity, or state denoting yare.", "Students learned the practical importance of yare during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yari", "Noun", "යාරි", "A distinct concept, entity, or state denoting yari.", "Students learned the practical importance of yari during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yarl", "Noun", "යාල්", "A distinct concept, entity, or state denoting yarl.", "Students learned the practical importance of yarl during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yarmulka", "Noun", "යුදෙව් පිරිමින් පළඳින තොප්පිය", "A distinct concept, entity, or state denoting yarmulka.", "Students learned the practical importance of yarmulka during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yarmulke", "Noun", "යුදෙව් පිරිමින් පළඳින තොප්පිය", "A distinct concept, entity, or state denoting yarmulke.", "Students learned the practical importance of yarmulke during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yarn", "Noun", "කථාන්තර කියනවා / කැටිනූල්", "One of the threads of which the strands of a rope are composed.", "Students learned the practical importance of yarn during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yarr", "Noun", "යාර", "To growl or snarl as a dog.", "Students learned the practical importance of yarr during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yarrow", "Noun", "වර්ෂස්ථායී පැළෑටියක්", "An American and European composite plant with very finely dissected leaves and small white corymb....", "Students learned the practical importance of yarrow during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yars", "Noun", "අවුරුදු", "A distinct concept, entity, or state denoting yars.", "Students learned the practical importance of yars during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yart", "Noun", "යාට්", "A distinct concept, entity, or state denoting yart.", "Students learned the practical importance of yart during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yary", "Adjective", "යාරි", "Relating to, characterized by, or pertaining to yary.", "The committee presented an exceptionally yary solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Yarâ", "Noun", "යාරා", "A distinct concept, entity, or state denoting yarâ.", "Students learned the practical importance of yarâ during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yas", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yas.", "Students learned the practical importance of yas during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yasa", "Noun", "යස", "A distinct concept, entity, or state denoting yasa.", "Students learned the practical importance of yasa during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yase", "Noun", "යසේ", "A distinct concept, entity, or state denoting yase.", "Students learned the practical importance of yase during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yash", "Noun", "යෂ්", "A distinct concept, entity, or state denoting yash.", "Students learned the practical importance of yash during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yashmak", "Noun", "ඇස් හැර මුහුණ වැසෙන සේ මුස්ලිම් කාන්තාවන් පළද", "A distinct concept, entity, or state denoting yashmak.", "Students learned the practical importance of yashmak during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yasi", "Noun", "යසි", "A distinct concept, entity, or state denoting yasi.", "Students learned the practical importance of yasi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaso", "Noun", "යසෝ", "A distinct concept, entity, or state denoting yaso.", "Students learned the practical importance of yaso during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yass", "Noun", "යස්", "A distinct concept, entity, or state denoting yass.", "Students learned the practical importance of yass during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yast", "Noun", "යීස්ට්", "A distinct concept, entity, or state denoting yast.", "Students learned the practical importance of yast during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yasu", "Noun", "යසු", "A distinct concept, entity, or state denoting yasu.", "Students learned the practical importance of yasu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yat", "Noun", "යට්", "A distinct concept, entity, or state denoting yat.", "Students learned the practical importance of yat during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yata", "Noun", "යට", "A distinct concept, entity, or state denoting yata.", "Students learned the practical importance of yata during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yate", "Verb", "යේට්", "To perform, direct, or engage in the act of yate.", "Diligent scholars strive to yate consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Yates", "Noun", "යේට්ස්", "A distinct concept, entity, or state denoting yates.", "Students learned the practical importance of yates during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yati", "Noun", "යති", "A distinct concept, entity, or state denoting yati.", "Students learned the practical importance of yati during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yato", "Noun", "යතෝ", "A distinct concept, entity, or state denoting yato.", "Students learned the practical importance of yato during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yatt", "Noun", "යාට්", "A distinct concept, entity, or state denoting yatt.", "Students learned the practical importance of yatt during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yau", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yau.", "Students learned the practical importance of yau during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaun", "Noun", "යවුන්", "A distinct concept, entity, or state denoting yaun.", "Students learned the practical importance of yaun during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaw", "Verb", "චණ්ඩ මුහුද නිසා නැවක දිශාව මාරුකර ගමන්කිරීම / මඟ වැරදී හැරෙනවා", "To rise in blisters, breaking in white froth, as cane juice inthe clarifiers in sugar works.", "Diligent scholars strive to yaw consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Yawl", "Noun", "රුවල් බෝට්ටුව", "A small ship's boat, usually rowed by four or six oars.", "Students learned the practical importance of yawl during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yawn", "Verb", "ආනනවා / ඈනවිලි අරිනවා", "To perform, direct, or engage in the act of yawn.", "Diligent scholars strive to yawn consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Yawning", "Noun", "ඇරී තිබෙන / ඈනුම", "A distinct concept, entity, or state denoting yawning.", "Students learned the practical importance of yawning during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaws", "Noun", "පරංගි", "A disease, occurring in the Antilles and in Africa,characterized by yellowish or reddish tumors, ....", "Students learned the practical importance of yaws during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yay", "Noun", "යෑයි", "A distinct concept, entity, or state denoting yay.", "Students learned the practical importance of yay during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yaz", "Noun", "යාස්", "A distinct concept, entity, or state denoting yaz.", "Students learned the practical importance of yaz during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yazoo", "Noun", "යැසුම", "A distinct concept, entity, or state denoting yazoo.", "Students learned the practical importance of yazoo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ybe", "Noun", "ඔව්", "A distinct concept, entity, or state denoting ybe.", "Students learned the practical importance of ybe during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yclept", "Noun", "නමැති", "A distinct concept, entity, or state denoting yclept.", "Students learned the practical importance of yclept during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yd", "Noun", "ය", "A distinct concept, entity, or state denoting yd.", "Students learned the practical importance of yd during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yds", "Noun", "යාර", "A distinct concept, entity, or state denoting yds.", "Students learned the practical importance of yds during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ye", "Noun", "තා / තෙපි", "An old method of printing the article the , the \"y\"being used in place of the Anglo-Saxon thorn.", "Students learned the practical importance of ye during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yea", "Noun", "එසේය / එහෙයි", "An affirmative vote.", "Students learned the practical importance of yea during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeah", "Noun", "එසේය / එහෙයි", "A distinct concept, entity, or state denoting yeah.", "Students learned the practical importance of yeah during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Year", "Noun", "අවුරුද්ද / වර්ෂය", "Age, or old age.", "Students learned the practical importance of year during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yearbook", "Noun", "ඉයර්බුක්", "A book containing annual reports of cases adjudged in thecourts of England.", "Students learned the practical importance of yearbook during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yearling", "Noun", "අවුරුද්දක් වයසැති සතා", "An animal one year old, or in the second year of its age.", "Students learned the practical importance of yearling during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yearly", "Adverb", "අවුරුදු පතා / වාර්ෂික", "In a manner characterized by or expressing yearly.", "She articulated her thoughts yearly before the audience.", listOf("Term", "Concept")),
    MiniDictWord("Yearn", "Verb", "දැඩිව ආශා කරනවා / ප්‍රාර්ථනා කරනවා", "Have an intense feeling of longing for something.", "Expats often yearn for the comforting flavors of home-cooked rice and curry.", listOf("Long", "Crave", "Desire")),
    MiniDictWord("Yearning", "Noun", "අභිලාෂය", "A distinct concept, entity, or state denoting yearning.", "Students learned the practical importance of yearning during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Years", "Noun", "අවුරුදු", "A distinct concept, entity, or state denoting years.", "Students learned the practical importance of years during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeast", "Noun", "යීස්ට්", "A form of fungus which grows as indvidual rounded cells, ratherthan in a mycelium, and reproduces....", "Students learned the practical importance of yeast during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeasty", "Noun", "මුහුන් සහිත", "A distinct concept, entity, or state denoting yeasty.", "Students learned the practical importance of yeasty during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeb", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yeb.", "Students learned the practical importance of yeb during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yec", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yec.", "Students learned the practical importance of yec during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yee", "Noun", "යී", "A distinct concept, entity, or state denoting yee.", "Students learned the practical importance of yee during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yef", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yef.", "Students learned the practical importance of yef during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeg", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yeg.", "Students learned the practical importance of yeg during their lesson.", listOf("Term", "Concept"))
  )

  private fun chunk2(): List<MiniDictWord> = listOf(
    MiniDictWord("Yeh", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yeh.", "Students learned the practical importance of yeh during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yei", "Noun", "යී", "A distinct concept, entity, or state denoting yei.", "Students learned the practical importance of yei during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yek", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yek.", "Students learned the practical importance of yek during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yell", "Noun", "මොරදෙනවා / මොරහඬ", "To cry out, or shriek, with a hideous noise.", "Students learned the practical importance of yell during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yellow", "Noun", "කසාවන් / කහ", "Being of a bright saffronlike color.", "Students learned the practical importance of yellow during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yellowbelly", "Adverb", "බඩවත කහ පැහැ සත්තු", "In a manner characterized by or expressing yellowbelly.", "She articulated her thoughts yellowbelly before the audience.", listOf("Term", "Concept")),
    MiniDictWord("Yellowhammer", "Noun", "සමාන පක්ෂියෙක්", "A distinct concept, entity, or state denoting yellowhammer.", "Students learned the practical importance of yellowhammer during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yellowing", "Noun", "කසායනය", "The act or process of making yellow.", "Students learned the practical importance of yellowing during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yellowish", "Adjective", "කහපාටට හුරු", "Somewhat yellow.", "The committee presented an exceptionally yellowish solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Yellowness", "Noun", "කහපාටට හුරුකම", "A distinct concept, entity, or state denoting yellowness.", "Students learned the practical importance of yellowness during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yellowstone", "Noun", "යෙලෝස්ටෝන්", "A distinct concept, entity, or state denoting yellowstone.", "Students learned the practical importance of yellowstone during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yelp", "Verb", "බුරනවා", "A sharp, quick cry.", "Diligent scholars strive to yelp consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Yemen", "Noun", "යේමනය", "A distinct concept, entity, or state denoting yemen.", "Students learned the practical importance of yemen during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yemon", "Noun", "කුඩා ඉඩම් හිමි ගොවියා / යෝමනයා", "A distinct concept, entity, or state denoting yemon.", "Students learned the practical importance of yemon during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yen", "Noun", "ජපන් රටේ කාසියක් / යෙන්", "The unit of value and account in Japan.", "Students learned the practical importance of yen during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeo", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yeo.", "Students learned the practical importance of yeo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeoman", "Noun", "ගොවියා / ලොකු වතු කළමණාකරුවෙක්", "An interior officer under the boatswain, gunner, or carpenters,charged with the stowage, account,....", "Students learned the practical importance of yeoman during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeomanry", "Noun", "ගොවිජනයා", "A distinct concept, entity, or state denoting yeomanry.", "Students learned the practical importance of yeomanry during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yep", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yep.", "Students learned the practical importance of yep during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yer", "Noun", "යර්", "A distinct concept, entity, or state denoting yer.", "Students learned the practical importance of yer during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yes", "Noun", "එසේය / එහෙයි", "A distinct concept, entity, or state denoting yes.", "Students learned the practical importance of yes during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yester", "Noun", "ඊයේ / පසුගිය", "A distinct concept, entity, or state denoting yester.", "Students learned the practical importance of yester during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yesterday", "Noun", "අතීතය / ඊයේ", "On the day last past.", "Students learned the practical importance of yesterday during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yesternight", "Noun", "ඊයේ", "The last night.", "Students learned the practical importance of yesternight during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yesteryear", "Noun", "ගිය අවුරුද්ද", "The year last past.", "Students learned the practical importance of yesteryear during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yet", "Noun", "ඇරත් / ඉදිරියේදී", "Any one of several species of large marine gastropods belongingto the genus Yetus, or Cymba.", "Students learned the practical importance of yet during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeti", "Noun", "හිමාලයේ හිම මිනිසා", "A distinct concept, entity, or state denoting yeti.", "Students learned the practical importance of yeti during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yeu", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yeu.", "Students learned the practical importance of yeu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yev", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yev.", "Students learned the practical importance of yev during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yew", "Noun", "යූ", "A distinct concept, entity, or state denoting yew.", "Students learned the practical importance of yew during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yey", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yey.", "Students learned the practical importance of yey during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yez", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yez.", "Students learned the practical importance of yez during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ygo", "Noun", "යිගෝහි", "A distinct concept, entity, or state denoting ygo.", "Students learned the practical importance of ygo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yha", "Noun", "යා", "A distinct concept, entity, or state denoting yha.", "Students learned the practical importance of yha during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yhe", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yhe.", "Students learned the practical importance of yhe during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yhi", "Noun", "යි", "A distinct concept, entity, or state denoting yhi.", "Students learned the practical importance of yhi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yi", "Noun", "වයි", "A distinct concept, entity, or state denoting yi.", "Students learned the practical importance of yi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yiddish", "Adjective", "යුදෙව්වන්ගේ භාෂා විශේෂයක්", "A language used by German and other Jews, being a Middle Germandialect developed under Hebrew and....", "The committee presented an exceptionally yiddish solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Yie", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yie.", "Students learned the practical importance of yie during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yield", "Verb / Noun", "ඵලදාව දෙනවා / අස්වැන්න", "Produce or provide a natural, agricultural, or industrial product.", "Modern organic fertilizer techniques yield richer vegetable harvests.", listOf("Produce", "Provide", "Generate")),
    MiniDictWord("Yielding", "Noun", "උපයා දෙන / එබෙන", "Inclined to give way, or comply.", "Students learned the practical importance of yielding during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yields", "Noun", "අස්වැන්න", "A distinct concept, entity, or state denoting yields.", "Students learned the practical importance of yields during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yih", "Noun", "යි", "A distinct concept, entity, or state denoting yih.", "Students learned the practical importance of yih during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yim", "Noun", "යිම්", "A distinct concept, entity, or state denoting yim.", "Students learned the practical importance of yim during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yin", "Noun", "යින්", "A Chinese weight of 2.", "Students learned the practical importance of yin during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yippee", "Noun", "හෝ හෝ", "A distinct concept, entity, or state denoting yippee.", "Students learned the practical importance of yippee during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yis", "Noun", "ඔව්", "\"Yis, sir,\" quod he, \"yis, host.", "Students learned the practical importance of yis during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yiu", "Noun", "යූ", "A distinct concept, entity, or state denoting yiu.", "Students learned the practical importance of yiu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yle", "Noun", "යේල්", "\"The barren yle.", "Students learned the practical importance of yle during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ylem", "Noun", "ඉලම", "A distinct concept, entity, or state denoting ylem.", "Students learned the practical importance of ylem during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yna", "Noun", "යනා", "A distinct concept, entity, or state denoting yna.", "Students learned the practical importance of yna during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yo", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yo.", "Students learned the practical importance of yo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yod", "Noun", "යොදුන්", "A distinct concept, entity, or state denoting yod.", "Students learned the practical importance of yod during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoe", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yoe.", "Students learned the practical importance of yoe during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yog", "Noun", "යෝග", "A distinct concept, entity, or state denoting yog.", "Students learned the practical importance of yog during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoga", "Noun", "යෝග / යෝග අභ්‍යාස ක්‍රමය", "A species of asceticism among the Hindoos, which consists in acomplete abstraction from all world....", "Students learned the practical importance of yoga during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoghurt", "Noun", "කිරිවලින් සාදන යෝගට්", "A distinct concept, entity, or state denoting yoghurt.", "Students learned the practical importance of yoghurt during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yogi", "Noun", "යෝගක්‍රම පිළි පදින්නා", "A follower of the yoga philosophy.", "Students learned the practical importance of yogi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yogurt", "Noun", "යෝගට්", "A distinct concept, entity, or state denoting yogurt.", "Students learned the practical importance of yogurt during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoh", "Noun", "යෝ", "A distinct concept, entity, or state denoting yoh.", "Students learned the practical importance of yoh during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoi", "Noun", "යෝයි", "A distinct concept, entity, or state denoting yoi.", "Students learned the practical importance of yoi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yok", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yok.", "Students learned the practical importance of yok during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoke", "Verb", "අවහිරය / ඈඳනවා", "To be joined or associated.", "Diligent scholars strive to yoke consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Yokel", "Noun", "ගමයා / පිටිසරයා", "A country bumpkin.", "Students learned the practical importance of yokel during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yol", "Noun", "යෝඑල්", "A distinct concept, entity, or state denoting yol.", "Students learned the practical importance of yol during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yolk", "Noun", "බිත්තරයේ කහමදය", "An oily secretion which naturally covers the wool of sheep.", "Students learned the practical importance of yolk during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yom", "Noun", "යොම්", "A distinct concept, entity, or state denoting yom.", "Students learned the practical importance of yom during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yomp", "Verb", "බර අවි දරමින් දුර්ගයේ පෙළට ගමන් කරනවා", "To perform, direct, or engage in the act of yomp.", "Diligent scholars strive to yomp consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Yon", "Noun", "අර", "At a distance, but within view.", "Students learned the practical importance of yon during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yonder", "Noun", "අර", "At a distance, but within view.", "Students learned the practical importance of yonder during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoo", "Noun", "යූ", "A distinct concept, entity, or state denoting yoo.", "Students learned the practical importance of yoo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yop", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yop.", "Students learned the practical importance of yop during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yor", "Noun", "ඔබේ", "A distinct concept, entity, or state denoting yor.", "Students learned the practical importance of yor during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yore", "Noun", "ආදිකාලය", "In time long past.", "Students learned the practical importance of yore during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("York", "Verb", "බිම නොවැදී පිත්ත කෙළවරටම පන්දුව යවනවා", "To perform, direct, or engage in the act of york.", "Diligent scholars strive to york consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Yorker", "Noun", "ක්‍රිකට් ක්‍රීඩාවේ යෝකර පන්දුව / පිත්ත යටට ම කෙළින් ම එන පන්දුව", "A distinct concept, entity, or state denoting yorker.", "Students learned the practical importance of yorker during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yorkshire", "Noun", "යෝක්ෂයර්", "A county in the north of England.", "Students learned the practical importance of yorkshire during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoruba", "Noun", "යොරුබා", "A distinct concept, entity, or state denoting yoruba.", "Students learned the practical importance of yoruba during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yos", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yos.", "Students learned the practical importance of yos during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yosemite", "Noun", "යොසමිටි", "A distinct concept, entity, or state denoting yosemite.", "Students learned the practical importance of yosemite during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yot", "Noun", "යොට්", "To unite closely.", "Students learned the practical importance of yot during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("You", "Noun", "උඹ / උඹලා", "The pronoun of the second person, in the nominative, dative,and objective case, indicating the pe....", "Students learned the practical importance of you during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Young", "Noun", "අලුත් / ඉළන්දාරි", "The offspring of animals, either a single animal or offspringcollectively.", "Students learned the practical importance of young during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Younger", "Noun", "කනිෂ්ඨ", "A distinct concept, entity, or state denoting younger.", "Students learned the practical importance of younger during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Youngest", "Noun", "ලාබාලතම", "A distinct concept, entity, or state denoting youngest.", "Students learned the practical importance of youngest during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Youngster", "Noun", "ගැටයා / ගැටවරයා", "A young person.", "Students learned the practical importance of youngster during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Your", "Noun", "ඔබගේ", "The form of the possessive case of the personal pronoun you.", "Students learned the practical importance of your during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yours", "Noun", "ඔබගේ ම", "See the Note under Your.", "Students learned the practical importance of yours during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yourself", "Noun", "ඔබම / නුඹම", "An emphasized or reflexive form of the pronoun of the secondperson.", "Students learned the practical importance of yourself during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yourselves", "Noun", "නුඹලා ම", "A distinct concept, entity, or state denoting yourselves.", "Students learned the practical importance of yourselves during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Youself", "Noun", "ඔබම / නුඹම", "A distinct concept, entity, or state denoting youself.", "Students learned the practical importance of youself during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Youth", "Noun", "ඉළන්දාරියා / උද්‍යෝගය", "A distinct concept, entity, or state denoting youth.", "Students learned the practical importance of youth during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Youthful", "Adjective", "උද්‍යෝගී / තරුණ", "Also used figuratively.", "The committee presented an exceptionally youthful solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Youths", "Noun", "යෞවනයන්", "A distinct concept, entity, or state denoting youths.", "Students learned the practical importance of youths during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yowl", "Noun", "සතෙකු වේදනාවෙන් කෑගැසීම", "To utter a loud, long, and mournful cry, as a dog.", "Students learned the practical importance of yowl during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoy", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yoy.", "Students learned the practical importance of yoy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yoü", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yoü.", "Students learned the practical importance of yoü during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ype", "Noun", "ඔව්", "A distinct concept, entity, or state denoting ype.", "Students learned the practical importance of ype during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yr", "Noun", "වසර", "A distinct concept, entity, or state denoting yr.", "Students learned the practical importance of yr during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yra", "Noun", "වසර", "A distinct concept, entity, or state denoting yra.", "Students learned the practical importance of yra during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yrd", "Noun", "යාර", "A distinct concept, entity, or state denoting yrd.", "Students learned the practical importance of yrd during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yre", "Noun", "වසර", "A distinct concept, entity, or state denoting yre.", "Students learned the practical importance of yre during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yrr", "Noun", "වසර", "A distinct concept, entity, or state denoting yrr.", "Students learned the practical importance of yrr during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yrs", "Noun", "වසර", "A distinct concept, entity, or state denoting yrs.", "Students learned the practical importance of yrs during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yrâ", "Noun", "වසර", "A distinct concept, entity, or state denoting yrâ.", "Students learned the practical importance of yrâ during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ys", "Noun", "ඔව්", "A distinct concept, entity, or state denoting ys.", "Students learned the practical importance of ys during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yse", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yse.", "Students learned the practical importance of yse during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ytterbium", "Noun", "ලෝහමය මූලද්‍රව්‍යයක්", "A rare element of the boron group, sometimes associated withyttrium or other related elements, as....", "Students learned the practical importance of ytterbium during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yttrium", "Noun", "ඉට්ට්‍රියම් / ලෝහමය මූලද්‍රව්‍යයක්", "A rare metallic element of the boron-aluminium group, found ingadolinite and other rare minerals,....", "Students learned the practical importance of yttrium during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yu", "Noun", "යූ", "A distinct concept, entity, or state denoting yu.", "Students learned the practical importance of yu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yua", "Noun", "යුවා", "A distinct concept, entity, or state denoting yua.", "Students learned the practical importance of yua during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuan", "Noun", "යුවාන්", "A distinct concept, entity, or state denoting yuan.", "Students learned the practical importance of yuan during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yue", "Noun", "යූ", "A distinct concept, entity, or state denoting yue.", "Students learned the practical importance of yue during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yug", "Noun", "යුග්", "A distinct concept, entity, or state denoting yug.", "Students learned the practical importance of yug during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yugoslav", "Noun", "යුගෝස්ලාවියානුවා", "A distinct concept, entity, or state denoting yugoslav.", "Students learned the practical importance of yugoslav during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yugoslavia", "Noun", "යුගෝස්ලාවියාව", "A distinct concept, entity, or state denoting yugoslavia.", "Students learned the practical importance of yugoslavia during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yugoslavian", "Noun", "යුගෝස්ලාවියානු", "A distinct concept, entity, or state denoting yugoslavian.", "Students learned the practical importance of yugoslavian during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuh", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yuh.", "Students learned the practical importance of yuh during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuk", "Noun", "යූකේ", "A distinct concept, entity, or state denoting yuk.", "Students learned the practical importance of yuk during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yukon", "Noun", "යුකොන්", "A distinct concept, entity, or state denoting yukon.", "Students learned the practical importance of yukon during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yul", "Noun", "යූල්", "A distinct concept, entity, or state denoting yul.", "Students learned the practical importance of yul during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yule", "Noun", "නත්තල / නත්තල් උත්සවය", "Christmas or Christmastide.", "Students learned the practical importance of yule during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuletide", "Noun", "නත්තල් කාලය", "Christmas time.", "Students learned the practical importance of yuletide during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuloh", "Noun", "නත්තල", "A distinct concept, entity, or state denoting yuloh.", "Students learned the practical importance of yuloh during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yum", "Noun", "යිම්", "A distinct concept, entity, or state denoting yum.", "Students learned the practical importance of yum during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yummy", "Noun", "ප්‍රණීත / රසැති", "A distinct concept, entity, or state denoting yummy.", "Students learned the practical importance of yummy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yun", "Noun", "යූඑන්", "A distinct concept, entity, or state denoting yun.", "Students learned the practical importance of yun during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yup", "Noun", "යිප්", "A distinct concept, entity, or state denoting yup.", "Students learned the practical importance of yup during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuppie", "Noun", "නගරයේ වැඩ කරන මැද පන්ති තරුණ වෘත්තිකයා", "A distinct concept, entity, or state denoting yuppie.", "Students learned the practical importance of yuppie during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuppy", "Noun", "නගරයේ වැඩ කරන මැද පන්ති තරුණ වෘත්තිකයා", "A distinct concept, entity, or state denoting yuppy.", "Students learned the practical importance of yuppy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yur", "Noun", "ඔබේ", "A distinct concept, entity, or state denoting yur.", "Students learned the practical importance of yur during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yus", "Noun", "යූස්", "A distinct concept, entity, or state denoting yus.", "Students learned the practical importance of yus during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yut", "Noun", "යුතැ", "A distinct concept, entity, or state denoting yut.", "Students learned the practical importance of yut during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuu", "Noun", "යූ", "A distinct concept, entity, or state denoting yuu.", "Students learned the practical importance of yuu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuv", "Noun", "යුව", "A distinct concept, entity, or state denoting yuv.", "Students learned the practical importance of yuv during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuz", "Noun", "යූස්", "A distinct concept, entity, or state denoting yuz.", "Students learned the practical importance of yuz during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yuè", "Noun", "යූ", "A distinct concept, entity, or state denoting yuè.", "Students learned the practical importance of yuè during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yves", "Noun", "යූව්ස්", "A distinct concept, entity, or state denoting yves.", "Students learned the practical importance of yves during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yán", "Noun", "යාන්", "A distinct concept, entity, or state denoting yán.", "Students learned the practical importance of yán during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yè", "Noun", "ඔව්", "A distinct concept, entity, or state denoting yè.", "Students learned the practical importance of yè during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yêu", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yêu.", "Students learned the practical importance of yêu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yóu", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yóu.", "Students learned the practical importance of yóu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yôm", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yôm.", "Students learned the practical importance of yôm during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yö", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yö.", "Students learned the practical importance of yö during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yù", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yù.", "Students learned the practical importance of yù during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yú", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yú.", "Students learned the practical importance of yú during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yún", "Noun", "යූන්", "A distinct concept, entity, or state denoting yún.", "Students learned the practical importance of yún during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yû", "Noun", "ඔබ", "A distinct concept, entity, or state denoting yû.", "Students learned the practical importance of yû during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yü", "Noun", "යූ", "A distinct concept, entity, or state denoting yü.", "Students learned the practical importance of yü during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Yüz", "Noun", "යූස්", "A distinct concept, entity, or state denoting yüz.", "Students learned the practical importance of yüz during their lesson.", listOf("Term", "Concept"))
  )
}
