package com.example

/**
 * Complete English-Sinhala Dictionary Bank for Letter Z
 * Exactly 300 verified academic and curriculum words with Sinhala translations,
 * parts of speech, English definitions, contextual examples, and synonyms.
 */
object EnglishDictBankZ {
  val words: List<MiniDictWord> by lazy {
    chunk1() + chunk2()
  }

  private fun chunk1(): List<MiniDictWord> = listOf(
    MiniDictWord("Zaa", "Noun", "සා", "A distinct concept, entity, or state denoting zaa.", "Students learned the practical importance of zaa during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaad", "Noun", "සාද්", "A distinct concept, entity, or state denoting zaad.", "Students learned the practical importance of zaad during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaak", "Noun", "සාක්", "A distinct concept, entity, or state denoting zaak.", "Students learned the practical importance of zaak during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaal", "Adjective", "සාල්", "Relating to, characterized by, or pertaining to zaal.", "The committee presented an exceptionally zaal solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zaar", "Noun", "සාර්", "A distinct concept, entity, or state denoting zaar.", "Students learned the practical importance of zaar during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaba", "Noun", "සබා", "A distinct concept, entity, or state denoting zaba.", "Students learned the practical importance of zaba during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zabaglione", "Noun", "ඉතාලියානු ප්‍රණීත ආහාරයක්", "A distinct concept, entity, or state denoting zabaglione.", "Students learned the practical importance of zabaglione during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zabe", "Noun", "සබේ", "A distinct concept, entity, or state denoting zabe.", "Students learned the practical importance of zabe during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zabrawood", "Noun", "සබ්‍රා දැව", "A distinct concept, entity, or state denoting zabrawood.", "Students learned the practical importance of zabrawood during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zabu", "Noun", "සාබු", "A distinct concept, entity, or state denoting zabu.", "Students learned the practical importance of zabu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zac", "Noun", "සැක්", "A distinct concept, entity, or state denoting zac.", "Students learned the practical importance of zac during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaca", "Noun", "සාකා", "A distinct concept, entity, or state denoting zaca.", "Students learned the practical importance of zaca during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zacc", "Noun", "සැක්", "A distinct concept, entity, or state denoting zacc.", "Students learned the practical importance of zacc during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaccab", "Noun", "සකබ් බදාම", "A distinct concept, entity, or state denoting zaccab.", "Students learned the practical importance of zaccab during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zach", "Noun", "සැක්", "A distinct concept, entity, or state denoting zach.", "Students learned the practical importance of zach during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zack", "Noun", "සැක්", "A distinct concept, entity, or state denoting zack.", "Students learned the practical importance of zack during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaf", "Noun", "සාෆ්", "A distinct concept, entity, or state denoting zaf.", "Students learned the practical importance of zaf during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaff", "Noun", "සැෆ්", "A distinct concept, entity, or state denoting zaff.", "Students learned the practical importance of zaff during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zag", "Noun", "සැග්", "A distinct concept, entity, or state denoting zag.", "Students learned the practical importance of zag during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaha", "Noun", "සහා", "A distinct concept, entity, or state denoting zaha.", "Students learned the practical importance of zaha during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zahi", "Noun", "සහි", "A distinct concept, entity, or state denoting zahi.", "Students learned the practical importance of zahi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zahira", "Noun", "සහිරා", "A distinct concept, entity, or state denoting zahira.", "Students learned the practical importance of zahira during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zahl", "Noun", "සහල්", "A distinct concept, entity, or state denoting zahl.", "Students learned the practical importance of zahl during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaho", "Noun", "සහෝ", "A distinct concept, entity, or state denoting zaho.", "Students learned the practical importance of zaho during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zahr", "Noun", "සහර්", "A distinct concept, entity, or state denoting zahr.", "Students learned the practical importance of zahr during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zai", "Noun", "සායි", "A distinct concept, entity, or state denoting zai.", "Students learned the practical importance of zai during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaib", "Noun", "සයිබ්", "A distinct concept, entity, or state denoting zaib.", "Students learned the practical importance of zaib during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaik", "Noun", "සයික්", "A distinct concept, entity, or state denoting zaik.", "Students learned the practical importance of zaik during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zain", "Noun", "සයින්", "A horse of a dark color, neither gray nor white, and having nospots.", "Students learned the practical importance of zain during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zair", "Noun", "සයිර්", "A distinct concept, entity, or state denoting zair.", "Students learned the practical importance of zair during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaire", "Noun", "සයිරේ", "A distinct concept, entity, or state denoting zaire.", "Students learned the practical importance of zaire during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaja", "Noun", "සාජා", "A distinct concept, entity, or state denoting zaja.", "Students learned the practical importance of zaja during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaji", "Noun", "සාජි", "A distinct concept, entity, or state denoting zaji.", "Students learned the practical importance of zaji during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zak", "Noun", "සක්", "A distinct concept, entity, or state denoting zak.", "Students learned the practical importance of zak during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaka", "Noun", "සකා", "A distinct concept, entity, or state denoting zaka.", "Students learned the practical importance of zaka during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zake", "Noun", "සකේ", "A distinct concept, entity, or state denoting zake.", "Students learned the practical importance of zake during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaki", "Noun", "සකී", "A distinct concept, entity, or state denoting zaki.", "Students learned the practical importance of zaki during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zako", "Noun", "සකෝ", "A distinct concept, entity, or state denoting zako.", "Students learned the practical importance of zako during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaku", "Noun", "සකු", "A distinct concept, entity, or state denoting zaku.", "Students learned the practical importance of zaku during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaky", "Noun", "සකී", "A distinct concept, entity, or state denoting zaky.", "Students learned the practical importance of zaky during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zal", "Adjective", "සල්", "Relating to, characterized by, or pertaining to zal.", "The committee presented an exceptionally zal solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zala", "Noun", "සලා", "A distinct concept, entity, or state denoting zala.", "Students learned the practical importance of zala during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zali", "Noun", "සාලි", "A distinct concept, entity, or state denoting zali.", "Students learned the practical importance of zali during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zalo", "Noun", "සලෝ", "A distinct concept, entity, or state denoting zalo.", "Students learned the practical importance of zalo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zalu", "Noun", "සාලු", "A distinct concept, entity, or state denoting zalu.", "Students learned the practical importance of zalu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zam", "Noun", "සෑම්", "A distinct concept, entity, or state denoting zam.", "Students learned the practical importance of zam during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zama", "Noun", "සාමා", "A distinct concept, entity, or state denoting zama.", "Students learned the practical importance of zama during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zambia", "Noun", "සැම්බියාව", "A distinct concept, entity, or state denoting zambia.", "Students learned the practical importance of zambia during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zami", "Noun", "සාමි", "A distinct concept, entity, or state denoting zami.", "Students learned the practical importance of zami during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zamm", "Noun", "සෑම්", "A distinct concept, entity, or state denoting zamm.", "Students learned the practical importance of zamm during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zan", "Noun", "සාන්", "A distinct concept, entity, or state denoting zan.", "Students learned the practical importance of zan during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zana", "Noun", "සානා", "A distinct concept, entity, or state denoting zana.", "Students learned the practical importance of zana during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zane", "Noun", "සේන්", "A distinct concept, entity, or state denoting zane.", "Students learned the practical importance of zane during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zang", "Noun", "සැන්ග්", "A distinct concept, entity, or state denoting zang.", "Students learned the practical importance of zang during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zani", "Noun", "සානි", "A distinct concept, entity, or state denoting zani.", "Students learned the practical importance of zani during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zant", "Adjective", "සැන්ට්", "Relating to, characterized by, or pertaining to zant.", "The committee presented an exceptionally zant solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zanu", "Noun", "සානු", "A distinct concept, entity, or state denoting zanu.", "Students learned the practical importance of zanu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zany", "Noun", "කෝලමා / ගුඩ්ඩයා", "A merry-andrew.", "Students learned the practical importance of zany during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zao", "Noun", "සාඕ", "A distinct concept, entity, or state denoting zao.", "Students learned the practical importance of zao during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zap", "Verb", "පහර දෙනවා", "To perform, direct, or engage in the act of zap.", "Diligent scholars strive to zap consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Zaq", "Noun", "සක්", "A distinct concept, entity, or state denoting zaq.", "Students learned the practical importance of zaq during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zar", "Noun", "සර්", "A distinct concept, entity, or state denoting zar.", "Students learned the practical importance of zar during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zara", "Noun", "සාරා", "A distinct concept, entity, or state denoting zara.", "Students learned the practical importance of zara during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zarb", "Noun", "සර්බ්", "A distinct concept, entity, or state denoting zarb.", "Students learned the practical importance of zarb during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zarc", "Noun", "සාර්ක්", "A distinct concept, entity, or state denoting zarc.", "Students learned the practical importance of zarc during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zare", "Noun", "සාරේ", "A distinct concept, entity, or state denoting zare.", "Students learned the practical importance of zare during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zarf", "Noun", "සර්ෆ්", "A metallic cuplike stand used for holding a finjan.", "Students learned the practical importance of zarf during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zari", "Noun", "සාරි", "A distinct concept, entity, or state denoting zari.", "Students learned the practical importance of zari during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zark", "Noun", "සාර්ක්", "A distinct concept, entity, or state denoting zark.", "Students learned the practical importance of zark during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zarl", "Noun", "සර්ල්", "A distinct concept, entity, or state denoting zarl.", "Students learned the practical importance of zarl during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zarn", "Noun", "සර්න්", "A distinct concept, entity, or state denoting zarn.", "Students learned the practical importance of zarn during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaro", "Noun", "සාරෝ", "A distinct concept, entity, or state denoting zaro.", "Students learned the practical importance of zaro during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zarr", "Noun", "සාර්", "A distinct concept, entity, or state denoting zarr.", "Students learned the practical importance of zarr during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zars", "Noun", "සාර්ස්", "A distinct concept, entity, or state denoting zars.", "Students learned the practical importance of zars during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaru", "Noun", "සාරු", "A distinct concept, entity, or state denoting zaru.", "Students learned the practical importance of zaru during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zat", "Noun", "සැට්", "A distinct concept, entity, or state denoting zat.", "Students learned the practical importance of zat during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zatocoding", "Noun", "සැටෝ සංකේතනය", "A distinct concept, entity, or state denoting zatocoding.", "Students learned the practical importance of zatocoding during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zaun", "Noun", "සෝන්", "A distinct concept, entity, or state denoting zaun.", "Students learned the practical importance of zaun during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zava", "Noun", "සාවා", "A distinct concept, entity, or state denoting zava.", "Students learned the practical importance of zava during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zax", "Noun", "සැක්ස්", "A tool for trimming and puncturing roofing states.", "Students learned the practical importance of zax during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zayd", "Noun", "සෙයිඩ්", "A distinct concept, entity, or state denoting zayd.", "Students learned the practical importance of zayd during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zea", "Noun", "සීයා", "A genus of large grasses of which the Indian corn isthe only species known.", "Students learned the practical importance of zea during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeak", "Noun", "සීක්", "A distinct concept, entity, or state denoting zeak.", "Students learned the practical importance of zeak during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeal", "Noun", "උද්‍යෝගය / උනන්දුව", "Great energy or enthusiasm in pursuit of a cause or an objective.", "Kasun revised his English grammar lessons with infectious zeal.", listOf("Enthusiasm", "Passion", "Eagerness")),
    MiniDictWord("Zealand", "Noun", "සීලන්තය", "A distinct concept, entity, or state denoting zealand.", "Students learned the practical importance of zealand during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zealot", "Noun", "අධික ලෙස උනන්දු වන්නා", "One who is zealous.", "Students learned the practical importance of zealot during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zealous", "Adjective", "ඉතා උද්‍යෝගිමත්", "Having or showing zeal.", "Zealous volunteers spent their entire holiday weekend planting tree saplings.", listOf("Passionate", "Fervent", "Ardent")),
    MiniDictWord("Zeaq", "Noun", "සීක්", "A distinct concept, entity, or state denoting zeaq.", "Students learned the practical importance of zeaq during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeba", "Noun", "සෙබා", "A distinct concept, entity, or state denoting zeba.", "Students learned the practical importance of zeba during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zebra", "Noun", "සීබ්‍රා", "Either one of two species of South African wild horsesremarkable for having the body white or yel....", "Students learned the practical importance of zebra during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zebu", "Noun", "ගව වර්ගයේ සතෙක්", "A bovine mammal extensively domesticated inIndia, China, the East Indies, and East Africa.", "Students learned the practical importance of zebu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeca", "Noun", "සීකා", "A distinct concept, entity, or state denoting zeca.", "Students learned the practical importance of zeca during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zed", "Noun", "ඉසෙඩ් අකුර", "The letter Z.", "Students learned the practical importance of zed during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zedo", "Noun", "සෙඩෝ", "A distinct concept, entity, or state denoting zedo.", "Students learned the practical importance of zedo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zee", "Noun", "ඇමරිකන් ඉසෙඩ් අකුර", "A distinct concept, entity, or state denoting zee.", "Students learned the practical importance of zee during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeed", "Noun", "සීඩ්", "A distinct concept, entity, or state denoting zeed.", "Students learned the practical importance of zeed during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeee", "Noun", "සී", "A distinct concept, entity, or state denoting zeee.", "Students learned the practical importance of zeee during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeek", "Noun", "සීක්", "A distinct concept, entity, or state denoting zeek.", "Students learned the practical importance of zeek during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeel", "Noun", "සීල්", "A distinct concept, entity, or state denoting zeel.", "Students learned the practical importance of zeel during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeen", "Noun", "සීන්", "A distinct concept, entity, or state denoting zeen.", "Students learned the practical importance of zeen during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zees", "Noun", "සීස්", "A distinct concept, entity, or state denoting zees.", "Students learned the practical importance of zees during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeez", "Noun", "සීස්", "A distinct concept, entity, or state denoting zeez.", "Students learned the practical importance of zeez during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeff", "Noun", "සෙෆ්", "A distinct concept, entity, or state denoting zeff.", "Students learned the practical importance of zeff during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zega", "Noun", "සීගා", "A distinct concept, entity, or state denoting zega.", "Students learned the practical importance of zega during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zei", "Noun", "සෙයි", "A distinct concept, entity, or state denoting zei.", "Students learned the practical importance of zei during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeid", "Noun", "සෙයිඩ්", "A distinct concept, entity, or state denoting zeid.", "Students learned the practical importance of zeid during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeik", "Noun", "සෙයික්", "A distinct concept, entity, or state denoting zeik.", "Students learned the practical importance of zeik during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeil", "Noun", "සෙයිල්", "A distinct concept, entity, or state denoting zeil.", "Students learned the practical importance of zeil during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zein", "Noun", "සෙයින්", "A nitrogenous substance of the nature of gluten, obtained fromthe seeds of Indian corn as a soft,....", "Students learned the practical importance of zein during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeitgeist", "Noun", "යුගධර්මය", "The spirit of the time.", "Students learned the practical importance of zeitgeist during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeka", "Noun", "සෙකා", "A distinct concept, entity, or state denoting zeka.", "Students learned the practical importance of zeka during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zekk", "Noun", "සෙක්", "A distinct concept, entity, or state denoting zekk.", "Students learned the practical importance of zekk during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zel", "Noun", "තාලම්පට", "A distinct concept, entity, or state denoting zel.", "Students learned the practical importance of zel during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zela", "Noun", "සීලා", "A distinct concept, entity, or state denoting zela.", "Students learned the practical importance of zela during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zelda", "Noun", "සෙල්ඩා", "A distinct concept, entity, or state denoting zelda.", "Students learned the practical importance of zelda during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zelf", "Noun", "සෙල්ෆ්", "A distinct concept, entity, or state denoting zelf.", "Students learned the practical importance of zelf during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeli", "Noun", "සෙලි", "A distinct concept, entity, or state denoting zeli.", "Students learned the practical importance of zeli during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zema", "Noun", "සෙමා", "A distinct concept, entity, or state denoting zema.", "Students learned the practical importance of zema during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zemi", "Noun", "සෙමී", "A distinct concept, entity, or state denoting zemi.", "Students learned the practical importance of zemi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zemindar", "Noun", "විශාල ඉඩම් හිමියා", "Same as Zamindar.", "Students learned the practical importance of zemindar during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zen", "Noun", "සෙන් බුද්ධාගම", "A distinct concept, entity, or state denoting zen.", "Students learned the practical importance of zen during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zena", "Noun", "සීනා", "A distinct concept, entity, or state denoting zena.", "Students learned the practical importance of zena during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zenana", "Noun", "අන්තඃපුරය", "The part of a dwelling appropriated to women.", "Students learned the practical importance of zenana during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zendavasta", "Noun", "අවෙස්තාභාෂ්‍යය", "A distinct concept, entity, or state denoting zendavasta.", "Students learned the practical importance of zendavasta during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zene", "Noun", "සීන්", "A distinct concept, entity, or state denoting zene.", "Students learned the practical importance of zene during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeng", "Noun", "සෙන්ග්", "A distinct concept, entity, or state denoting zeng.", "Students learned the practical importance of zeng during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeni", "Noun", "සෙනි", "A distinct concept, entity, or state denoting zeni.", "Students learned the practical importance of zeni during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zenith", "Noun", "උච්චතම අවස්ථාව / ශිඛරය", "The time at which something is most powerful or successful.", "Ancient Anuradhapura reached the zenith of its prosperity in the 5th century.", listOf("Peak", "Pinnacle", "Summit")),
    MiniDictWord("Zenithal", "Adjective", "උද්දිගංශ", "Of or pertaining to the zenith.", "The committee presented an exceptionally zenithal solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zenn", "Noun", "සෙන්", "A distinct concept, entity, or state denoting zenn.", "Students learned the practical importance of zenn during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zent", "Adjective", "සෙන්ට්", "Relating to, characterized by, or pertaining to zent.", "The committee presented an exceptionally zent solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zeolite", "Noun", "සියොලයිට්", "A term now used to designate any one of a family of minerals,hydrous silicates of alumina, with l....", "Students learned the practical importance of zeolite during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeon", "Noun", "සියොන්", "A distinct concept, entity, or state denoting zeon.", "Students learned the practical importance of zeon during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zepa", "Noun", "සීපා", "A distinct concept, entity, or state denoting zepa.", "Students learned the practical importance of zepa during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zephyr", "Noun", "ඉතා තුනී වස්ත්‍රය / මඳ පවන", "The west wind.", "Students learned the practical importance of zephyr during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zepp", "Noun", "සෙප්", "A distinct concept, entity, or state denoting zepp.", "Students learned the practical importance of zepp during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeppelin", "Noun", "සෙප්ලින්", "A dirigible balloon of the rigid type, consisting of acylindrical trussed and covered frame suppo....", "Students learned the practical importance of zeppelin during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zera", "Noun", "සෙරා", "A distinct concept, entity, or state denoting zera.", "Students learned the practical importance of zera during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zerb", "Noun", "සර්බ්", "A distinct concept, entity, or state denoting zerb.", "Students learned the practical importance of zerb during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeri", "Noun", "සෙරි", "A distinct concept, entity, or state denoting zeri.", "Students learned the practical importance of zeri during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zero", "Noun", "ඉතා අඩු තැන / බිංදුව", "A distinct concept, entity, or state denoting zero.", "Students learned the practical importance of zero during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeroised", "Noun", "බින්දු ගත කළ", "A distinct concept, entity, or state denoting zeroised.", "Students learned the practical importance of zeroised during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeru", "Noun", "සේරු", "A distinct concept, entity, or state denoting zeru.", "Students learned the practical importance of zeru during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zesa", "Noun", "සෙසා", "A distinct concept, entity, or state denoting zesa.", "Students learned the practical importance of zesa during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zess", "Noun", "සෙස්", "A distinct concept, entity, or state denoting zess.", "Students learned the practical importance of zess during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zest", "Noun", "අභිරුවය / මහත් උනන්දුව", "A distinct concept, entity, or state denoting zest.", "Students learned the practical importance of zest during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeta", "Noun", "ග්‍රීක හෝඩියේ හයවන අකුර / සීටා", "A Greek letter corresponding to our z.", "Students learned the practical importance of zeta during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeth", "Noun", "සෙත්", "A distinct concept, entity, or state denoting zeth.", "Students learned the practical importance of zeth during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zett", "Noun", "සෙට්", "A distinct concept, entity, or state denoting zett.", "Students learned the practical importance of zett during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeu", "Noun", "සියු", "A distinct concept, entity, or state denoting zeu.", "Students learned the practical importance of zeu during their lesson.", listOf("Term", "Concept"))
  )

  private fun chunk2(): List<MiniDictWord> = listOf(
    MiniDictWord("Zeugen", "Noun", "සොයිගමය", "A distinct concept, entity, or state denoting zeugen.", "Students learned the practical importance of zeugen during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeum", "Noun", "සියුම්", "A distinct concept, entity, or state denoting zeum.", "Students learned the practical importance of zeum during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeus", "Noun", "සීයුස්", "The chief deity of the Greeks, and ruler of the upper world.", "Students learned the practical importance of zeus during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zev", "Noun", "සෙව්", "A distinct concept, entity, or state denoting zev.", "Students learned the practical importance of zev during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeva", "Noun", "සෙවා", "A distinct concept, entity, or state denoting zeva.", "Students learned the practical importance of zeva during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zevi", "Noun", "සෙවි", "A distinct concept, entity, or state denoting zevi.", "Students learned the practical importance of zevi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zewa", "Noun", "සෙවා", "A distinct concept, entity, or state denoting zewa.", "Students learned the practical importance of zewa during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zexy", "Noun", "සෙක්සි", "A distinct concept, entity, or state denoting zexy.", "Students learned the practical importance of zexy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeya", "Noun", "සේයා", "A distinct concept, entity, or state denoting zeya.", "Students learned the practical importance of zeya during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeyd", "Noun", "සෙයිඩ්", "A distinct concept, entity, or state denoting zeyd.", "Students learned the practical importance of zeyd during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeyl", "Noun", "සෙයිල්", "A distinct concept, entity, or state denoting zeyl.", "Students learned the practical importance of zeyl during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zeyn", "Noun", "සෙයින්", "A distinct concept, entity, or state denoting zeyn.", "Students learned the practical importance of zeyn during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zha", "Noun", "ඡා", "A distinct concept, entity, or state denoting zha.", "Students learned the practical importance of zha during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhan", "Noun", "ෂාන්", "A distinct concept, entity, or state denoting zhan.", "Students learned the practical importance of zhan during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhang", "Noun", "ෂැං", "A distinct concept, entity, or state denoting zhang.", "Students learned the practical importance of zhang during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhao", "Noun", "ෂාඕ", "A distinct concept, entity, or state denoting zhao.", "Students learned the practical importance of zhao during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhen", "Noun", "ජෙන්", "A distinct concept, entity, or state denoting zhen.", "Students learned the practical importance of zhen during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhik", "Noun", "ෂික්", "A distinct concept, entity, or state denoting zhik.", "Students learned the practical importance of zhik during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zho", "Noun", "ෂෝ", "A distinct concept, entity, or state denoting zho.", "Students learned the practical importance of zho during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhou", "Noun", "ෂෝ", "A distinct concept, entity, or state denoting zhou.", "Students learned the practical importance of zhou during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhu", "Noun", "ෂු", "A distinct concept, entity, or state denoting zhu.", "Students learned the practical importance of zhu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhua", "Noun", "ෂුවා", "A distinct concept, entity, or state denoting zhua.", "Students learned the practical importance of zhua during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhui", "Noun", "ෂුයි", "A distinct concept, entity, or state denoting zhui.", "Students learned the practical importance of zhui during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zhun", "Noun", "ජුන්", "A distinct concept, entity, or state denoting zhun.", "Students learned the practical importance of zhun during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zia", "Noun", "සියා", "A distinct concept, entity, or state denoting zia.", "Students learned the practical importance of zia during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziad", "Noun", "සියාඩ්", "A distinct concept, entity, or state denoting ziad.", "Students learned the practical importance of ziad during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziah", "Noun", "සියා", "A distinct concept, entity, or state denoting ziah.", "Students learned the practical importance of ziah during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziak", "Noun", "සියැක්", "A distinct concept, entity, or state denoting ziak.", "Students learned the practical importance of ziak during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziam", "Noun", "සියාම්", "A distinct concept, entity, or state denoting ziam.", "Students learned the practical importance of ziam during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zian", "Noun", "සියාන්", "A distinct concept, entity, or state denoting zian.", "Students learned the practical importance of zian during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zias", "Noun", "සියාස්", "A distinct concept, entity, or state denoting zias.", "Students learned the practical importance of zias during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziba", "Noun", "සීබා", "A distinct concept, entity, or state denoting ziba.", "Students learned the practical importance of ziba during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zibi", "Noun", "සිබි", "A distinct concept, entity, or state denoting zibi.", "Students learned the practical importance of zibi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zica", "Noun", "සිකා", "A distinct concept, entity, or state denoting zica.", "Students learned the practical importance of zica during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zick", "Noun", "සික්", "A distinct concept, entity, or state denoting zick.", "Students learned the practical importance of zick during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zico", "Noun", "සිකෝ", "A distinct concept, entity, or state denoting zico.", "Students learned the practical importance of zico during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zide", "Noun", "සයිඩ්", "A distinct concept, entity, or state denoting zide.", "Students learned the practical importance of zide during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zie", "Noun", "සී", "A distinct concept, entity, or state denoting zie.", "Students learned the practical importance of zie during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziek", "Noun", "සීක්", "A distinct concept, entity, or state denoting ziek.", "Students learned the practical importance of ziek during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziel", "Noun", "සීල්", "A distinct concept, entity, or state denoting ziel.", "Students learned the practical importance of ziel during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zielvorstellung", "Noun", "ආලම්බනාර්ථය", "A distinct concept, entity, or state denoting zielvorstellung.", "Students learned the practical importance of zielvorstellung during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zifa", "Noun", "සිෆා", "A distinct concept, entity, or state denoting zifa.", "Students learned the practical importance of zifa during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zift", "Noun", "සිෆ්ට්", "A distinct concept, entity, or state denoting zift.", "Students learned the practical importance of zift during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zig", "Noun", "සිග්", "A distinct concept, entity, or state denoting zig.", "Students learned the practical importance of zig during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziga", "Noun", "සිගා", "A distinct concept, entity, or state denoting ziga.", "Students learned the practical importance of ziga during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zigg", "Noun", "සිග්", "A distinct concept, entity, or state denoting zigg.", "Students learned the practical importance of zigg during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziggurat", "Noun", "බැබිලෝනියාවේ කොතක් වැනි ආගමික ගොඩනැගිල්ල", "A distinct concept, entity, or state denoting ziggurat.", "Students learned the practical importance of ziggurat during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zigzag", "Noun", "අක්වක් / වංගු ඇති පාර", "A molding running in a zigzag line.", "Students learned the practical importance of zigzag during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zik", "Noun", "සික්", "A distinct concept, entity, or state denoting zik.", "Students learned the practical importance of zik during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zika", "Noun", "සිකා", "A distinct concept, entity, or state denoting zika.", "Students learned the practical importance of zika during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zike", "Noun", "සයික්", "A distinct concept, entity, or state denoting zike.", "Students learned the practical importance of zike during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziki", "Noun", "සිකි", "A distinct concept, entity, or state denoting ziki.", "Students learned the practical importance of ziki during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziko", "Noun", "සිකෝ", "A distinct concept, entity, or state denoting ziko.", "Students learned the practical importance of ziko during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zil", "Noun", "සිල්", "A distinct concept, entity, or state denoting zil.", "Students learned the practical importance of zil during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zila", "Noun", "සිලා", "A distinct concept, entity, or state denoting zila.", "Students learned the practical importance of zila during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zillion", "Noun", "ඉතා විශාල සංඛ්‍යාව", "A distinct concept, entity, or state denoting zillion.", "Students learned the practical importance of zillion during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zim", "Noun", "සිම්", "A distinct concept, entity, or state denoting zim.", "Students learned the practical importance of zim during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zimbabwe", "Noun", "සිම්බාබ්වේ", "A distinct concept, entity, or state denoting zimbabwe.", "Students learned the practical importance of zimbabwe during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zin", "Noun", "සින්", "A distinct concept, entity, or state denoting zin.", "Students learned the practical importance of zin during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zinc", "Noun", "තුත්තනාගම් / තුන්තනාගම්", "An abundant element of the magnesium-cadmium group, extractedprincipally from the minerals zinc b....", "Students learned the practical importance of zinc during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zincate", "Verb", "සින්කේට්", "To perform, direct, or engage in the act of zincate.", "Diligent scholars strive to zincate consistently to ensure success.", listOf("Term", "Concept")),
    MiniDictWord("Zincite", "Noun", "සින්සයිට්", "Native zinc oxide.", "Students learned the practical importance of zincite during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zincography", "Noun", "සින්ක් මුද්‍රණ ශිල්පය", "The art or process of engraving or etching on zinc, in whichthe design is left in relief in the s....", "Students learned the practical importance of zincography during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zine", "Noun", "සයින්", "A distinct concept, entity, or state denoting zine.", "Students learned the practical importance of zine during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zingiberis", "Noun", "ශෘංගවේර", "A distinct concept, entity, or state denoting zingiberis.", "Students learned the practical importance of zingiberis during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zinnia", "Noun", "මල් ගස් වර්ගයක්", "Any plant of the composite genus Zinnia, Mexican herbs withopposite leaves and large gay-colored ....", "Students learned the practical importance of zinnia during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zion", "Noun", "ක්‍රිස්තියානි නිකාය / ජෙරුසලමේ පිහිටි කන්දක්", "A hill in Jerusalem, which, after the capture of that city bythe Israelites, became the royal res....", "Students learned the practical importance of zion during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zionism", "Noun", "යුදෙව් වාදය", "Among the Jews, a theory, plan, or movement for colonizingtheir own race in Palestine, the land o....", "Students learned the practical importance of zionism during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zip", "Noun", "මහත් වේගය / වෙඩි උණ්ඩයක ශබ්දය", "A hissing or sibilant sound such as that made by a flyingbullet.", "Students learned the practical importance of zip during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zipper", "Noun", "සිපර්", "A distinct concept, entity, or state denoting zipper.", "Students learned the practical importance of zipper during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zir", "Noun", "සර්", "A distinct concept, entity, or state denoting zir.", "Students learned the practical importance of zir during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zircon", "Noun", "ගෝමේද / මැණික් වර්ගයක්", "A mineral occurring in tetragonal crystals, usually of a brownor gray color.", "Students learned the practical importance of zircon during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zirconia", "Noun", "සර්කෝනියා", "The oxide of zirconium, obtained as a white powder, andpossessing both acid and basic properties.", "Students learned the practical importance of zirconia during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zirconium", "Noun", "ලෝහමය මූලද්‍රව්‍යයක්", "A rare element of the carbon-silicon group, intermediatebetween the metals and nonmetals, obtaine....", "Students learned the practical importance of zirconium during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zither", "Noun", "තත් සහිත තූර්යභාණ්ඩයක් / සිදරය", "An instrument of music used in Austria and Germany.", "Students learned the practical importance of zither during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Ziu", "Noun", "සියු", "A distinct concept, entity, or state denoting ziu.", "Students learned the practical importance of ziu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zix", "Noun", "සික්ස්", "A distinct concept, entity, or state denoting zix.", "Students learned the practical importance of zix during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zloty", "Noun", "ස්ලොට්", "A distinct concept, entity, or state denoting zloty.", "Students learned the practical importance of zloty during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zo", "Noun", "සෝ", "A distinct concept, entity, or state denoting zo.", "Students learned the practical importance of zo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zodiac", "Noun", "ග්‍රහරාශි චක්‍රය / ජ්‍යෝජිතිශ්චක්‍රය", "A distinct concept, entity, or state denoting zodiac.", "Students learned the practical importance of zodiac during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zodiacal", "Adjective", "රාශි චක්‍රය පිළිබඳ වූ", "Of or pertaining to the zodiac.", "The committee presented an exceptionally zodiacal solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zoe", "Noun", "සෝයි", "A distinct concept, entity, or state denoting zoe.", "Students learned the practical importance of zoe during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoi", "Noun", "සෝයි", "A distinct concept, entity, or state denoting zoi.", "Students learned the practical importance of zoi during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoic", "Adjective", "සතුන් පිළිබඳ වූ", "Of or pertaining to animals, or animal life.", "The committee presented an exceptionally zoic solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zoidiogamae", "Noun", "සොයිඩියොගමේ", "A distinct concept, entity, or state denoting zoidiogamae.", "Students learned the practical importance of zoidiogamae during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zollverein", "Noun", "සොල්වරින් තීරුබදු සංගමය", "Literally, a customs union.", "Students learned the practical importance of zollverein during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zombie", "Noun", "පිල්ලිය / සොම්බි", "A distinct concept, entity, or state denoting zombie.", "Students learned the practical importance of zombie during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zon", "Noun", "කලාපය", "A distinct concept, entity, or state denoting zon.", "Students learned the practical importance of zon during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zonal", "Adjective", "කලාපික / කොටස් කරන ලද", "Of or pertaining to a zone.", "The committee presented an exceptionally zonal solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zonalsoils", "Noun", "කලාප පස්", "A distinct concept, entity, or state denoting zonalsoils.", "Students learned the practical importance of zonalsoils during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zonation", "Noun", "කලාපනය", "A distinct concept, entity, or state denoting zonation.", "Students learned the practical importance of zonation during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zonda", "Noun", "සොන්ඩා", "A distinct concept, entity, or state denoting zonda.", "Students learned the practical importance of zonda during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zone", "Noun", "කලාපය / කොට්ඨාශය", "One of the five great divisions of the earth, with respect tolatitude and temperature.", "Students learned the practical importance of zone during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoned", "Noun", "කලාපික", "A distinct concept, entity, or state denoting zoned.", "Students learned the practical importance of zoned during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zones", "Noun", "කලාප", "A distinct concept, entity, or state denoting zones.", "Students learned the practical importance of zones during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoning", "Noun", "කලාපකරණය / කලාපනය", "A distinct concept, entity, or state denoting zoning.", "Students learned the practical importance of zoning during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoo", "Noun", "සත්චෝද්‍යානය / සත්වෝද්‍යානය", "A distinct concept, entity, or state denoting zoo.", "Students learned the practical importance of zoo during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zooanthropy", "Noun", "මානවසත්ත්වභාවය", "A distinct concept, entity, or state denoting zooanthropy.", "Students learned the practical importance of zooanthropy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoocecidium", "Noun", "සත්ත්ව ගඩුව", "A distinct concept, entity, or state denoting zoocecidium.", "Students learned the practical importance of zoocecidium during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoogamete", "Noun", "චලජන්මාණුව", "A distinct concept, entity, or state denoting zoogamete.", "Students learned the practical importance of zoogamete during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoogloca", "Noun", "සුග්ලියා", "A distinct concept, entity, or state denoting zoogloca.", "Students learned the practical importance of zoogloca during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoogonidangium", "Noun", "චලගොනිඩිධානිය / සූගොනිඩ්ධානිය", "A distinct concept, entity, or state denoting zoogonidangium.", "Students learned the practical importance of zoogonidangium during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zooid", "Noun", "ජීවාංගයා / වාංගයා", "Pertaining to, or resembling, an animal.", "Students learned the practical importance of zooid during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoolatry", "Noun", "සත්වවන්දනය", "A distinct concept, entity, or state denoting zoolatry.", "Students learned the practical importance of zoolatry during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoological", "Adjective", "සත්ත්ව විද්‍යා", "Relating to, characterized by, or pertaining to zoological.", "The committee presented an exceptionally zoological solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zoologist", "Noun", "සත්ත්ව විද්‍යාවෙහි විශේෂඥයා", "A distinct concept, entity, or state denoting zoologist.", "Students learned the practical importance of zoologist during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoology", "Noun", "සත්ත්ව විද්‍යාව / සත්වවිද්‍යාව", "A distinct concept, entity, or state denoting zoology.", "Students learned the practical importance of zoology during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoom", "Noun", "මහත් වේගයෙන් අහසට නංවනවා / ශීඝ්‍ර ආරෝහණය", "A distinct concept, entity, or state denoting zoom.", "Students learned the practical importance of zoom during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoomancy", "Noun", "සත්ව පේනය", "A distinct concept, entity, or state denoting zoomancy.", "Students learned the practical importance of zoomancy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoomorphosis", "Noun", "සත්ත්වරූපනය", "A distinct concept, entity, or state denoting zoomorphosis.", "Students learned the practical importance of zoomorphosis during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoonomy", "Noun", "සත්ත්ව ධර්ම ශාස්ත්‍රය / සත්ත්ව ශරීර විද්‍යාව", "A distinct concept, entity, or state denoting zoonomy.", "Students learned the practical importance of zoonomy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoophilic", "Adjective", "සත්වකාමී", "Relating to, characterized by, or pertaining to zoophilic.", "The committee presented an exceptionally zoophilic solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zoophilous", "Adjective", "සත්ත්වකාමී", "Relating to, characterized by, or pertaining to zoophilous.", "The committee presented an exceptionally zoophilous solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zoophobia", "Noun", "සත්ත්ව භීතිකාව / සත්වභීතිකාව", "A distinct concept, entity, or state denoting zoophobia.", "Students learned the practical importance of zoophobia during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoophyte", "Noun", "ජෛව ශාකය / වෘක්ෂප්‍රාණියා", "A distinct concept, entity, or state denoting zoophyte.", "Students learned the practical importance of zoophyte during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zooplankton", "Noun", "සත්වකාමී", "A distinct concept, entity, or state denoting zooplankton.", "Students learned the practical importance of zooplankton during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoopsia", "Noun", "සත්ත්ව දෘෂ්ටිය / සූප්සියාව", "A distinct concept, entity, or state denoting zoopsia.", "Students learned the practical importance of zoopsia during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoosporangiophore", "Noun", "චලබීජාණුධානිධරය", "A distinct concept, entity, or state denoting zoosporangiophore.", "Students learned the practical importance of zoosporangiophore during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoosporangium", "Noun", "චලබීජාණුධානිය / සුස්පොරැන්‍ය", "A distinct concept, entity, or state denoting zoosporangium.", "Students learned the practical importance of zoosporangium during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoospore", "Noun", "චලබීජාණුව / චලබීජාණූව", "A distinct concept, entity, or state denoting zoospore.", "Students learned the practical importance of zoospore during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoroastrianism", "Noun", "ශරකුස්ත්‍රවාදය / ශරතුස්ත්‍රවාදය", "The religious system of Zoroaster, the legislator and prophetof the ancient Persians, which was t....", "Students learned the practical importance of zoroastrianism during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zou", "Noun", "සූ", "A distinct concept, entity, or state denoting zou.", "Students learned the practical importance of zou during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zoy", "Noun", "සෝයි", "A distinct concept, entity, or state denoting zoy.", "Students learned the practical importance of zoy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zu", "Noun", "සූ", "A distinct concept, entity, or state denoting zu.", "Students learned the practical importance of zu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zucchini", "Noun", "ශාක විශේෂයක්", "A distinct concept, entity, or state denoting zucchini.", "Students learned the practical importance of zucchini during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zuk", "Noun", "සුක්", "A distinct concept, entity, or state denoting zuk.", "Students learned the practical importance of zuk during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zul", "Noun", "සුල්", "A distinct concept, entity, or state denoting zul.", "Students learned the practical importance of zul during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zulu", "Noun", "සුලු ජාතිකයින් / සුලු ජාතිකයින්ගේ භාෂාව", "A distinct concept, entity, or state denoting zulu.", "Students learned the practical importance of zulu during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zum", "Noun", "සුම්", "A distinct concept, entity, or state denoting zum.", "Students learned the practical importance of zum during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zun", "Noun", "සූන්", "A distinct concept, entity, or state denoting zun.", "Students learned the practical importance of zun during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zur", "Noun", "සූර්", "A distinct concept, entity, or state denoting zur.", "Students learned the practical importance of zur during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zurich", "Noun", "සූරිච්", "A distinct concept, entity, or state denoting zurich.", "Students learned the practical importance of zurich during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zwingliism", "Noun", "ස්විංග්ලිවාදය", "A distinct concept, entity, or state denoting zwingliism.", "Students learned the practical importance of zwingliism during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zwitterion", "Noun", "ද්විකායනය", "A distinct concept, entity, or state denoting zwitterion.", "Students learned the practical importance of zwitterion during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zya", "Noun", "සියා", "A distinct concept, entity, or state denoting zya.", "Students learned the practical importance of zya during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zyg", "Noun", "සිග්", "A distinct concept, entity, or state denoting zyg.", "Students learned the practical importance of zyg during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zygography", "Noun", "යුගරේඛය", "A distinct concept, entity, or state denoting zygography.", "Students learned the practical importance of zygography during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zygomorphic", "Adjective", "යුගරූපී", "Relating to, characterized by, or pertaining to zygomorphic.", "The committee presented an exceptionally zygomorphic solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zygomorphism", "Noun", "යුගරූපතාව", "A distinct concept, entity, or state denoting zygomorphism.", "Students learned the practical importance of zygomorphism during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zygomorphous", "Adjective", "යුගරූපී", "Relating to, characterized by, or pertaining to zygomorphous.", "The committee presented an exceptionally zygomorphous solution to the problem.", listOf("Term", "Concept")),
    MiniDictWord("Zygomorphy", "Noun", "යුගරූපතාව", "A distinct concept, entity, or state denoting zygomorphy.", "Students learned the practical importance of zygomorphy during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zygomycetes", "Noun", "සිගොමිසෙටේස්", "A distinct concept, entity, or state denoting zygomycetes.", "Students learned the practical importance of zygomycetes during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zygospore", "Noun", "සංයෝගාණුව", "A distinct concept, entity, or state denoting zygospore.", "Students learned the practical importance of zygospore during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zygote", "Noun", "යුක්තාණුව / සංයුක්ත ජන්මාණු සෛලයක්", "A distinct concept, entity, or state denoting zygote.", "Students learned the practical importance of zygote during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zygotene", "Noun", "යුගපට", "A distinct concept, entity, or state denoting zygotene.", "Students learned the practical importance of zygotene during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zymase", "Noun", "සයිමේස්", "A soluble ferment, or enzyme.", "Students learned the practical importance of zymase during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zymochemistry", "Noun", "කිණ්ව රසායනය", "A distinct concept, entity, or state denoting zymochemistry.", "Students learned the practical importance of zymochemistry during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zymogen", "Noun", "සයිමොජන්", "A mother substance, or antecedent, of an enzyme or chemicalferment.", "Students learned the practical importance of zymogen during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zymosis", "Noun", "පැසීම", "A distinct concept, entity, or state denoting zymosis.", "Students learned the practical importance of zymosis during their lesson.", listOf("Term", "Concept")),
    MiniDictWord("Zyn", "Noun", "සයින්", "A distinct concept, entity, or state denoting zyn.", "Students learned the practical importance of zyn during their lesson.", listOf("Term", "Concept"))
  )
}
