package com.example

object OlSubjectToolsScienceData {
  val tools: List<OlSubjectToolItem> by lazy {
    listOf(
      // --- GROUP 1: යාන්ත්‍ර විද්‍යාව සහ චලිතය (1-10) ---
      OlSubjectToolItem(
        id = "sci_tool_01",
        subject = "විද්‍යාව",
        toolNumber = 1,
        groupNumber = 1,
        titleSinhala = "ප්‍රවේගය සහ ත්වරණය ගණකය",
        titleEnglish = "Velocity & Acceleration Calculator",
        category = "භෞතික විද්‍යාව",
        icon = "🚀",
        quickSummary = "චලිත වන වස්තුවක ප්‍රවේගය, කාලය සහ ත්වරණය අතර සම්බන්ධය.",
        formulaOrRule = "v = u + at | a = (v - u) / t (ඒකකය: m/s²)",
        practicalApplication = "නිශ්චලතාවයෙන් ඇරඹී (u=0) තත්පර 5 කදී ප්‍රවේගය 20 m/s වූ රථයක ත්වරණය: a = (20 - 0) / 5 = 4 m/s².",
        examTip = "💡 විභාගයේදී ත්වරණය ඍණ අගයක් ලැබුණහොත් එය 'මන්දනය' ලෙස ලියන්න."
      ),
      OlSubjectToolItem(
        id = "sci_tool_02",
        subject = "විද්‍යාව",
        toolNumber = 2,
        groupNumber = 1,
        titleSinhala = "නිව්ටන්ගේ දෙවන චලිත නියම මෙවලම",
        titleEnglish = "Newton's 2nd Law (F = ma) Tool",
        category = "භෞතික විද්‍යාව",
        icon = "⚖️",
        quickSummary = "වස්තුවක් මත යෙදූ අසමතුලිත බලය සහ ජනිත වන ත්වරණය අතර අනුපාතය.",
        formulaOrRule = "F = m × a (F = බලය N, m = ස්කන්ධය kg, a = ත්වරණය m/s²)",
        practicalApplication = "ස්කන්ධය 1200 kg වූ මෝටර් රථයකට 2 m/s² ක ත්වරණයක් ලබාදීමට අවශ්‍ය බලය: F = 1200 × 2 = 2400 N.",
        examTip = "💡 ස්කන්ධය ග්‍රෑම් (g) වලින් දුන් විට අනිවාර්යයෙන්ම 1000න් බෙදා කිලෝග්‍රෑම් (kg) වලට හරවා ගන්න."
      ),
      OlSubjectToolItem(
        id = "sci_tool_03",
        subject = "විද්‍යාව",
        toolNumber = 3,
        groupNumber = 1,
        titleSinhala = "ගුරුත්වාකර්ෂණ විභව ශක්ති මෙවලම",
        titleEnglish = "Gravitational Potential Energy (Ep = mgh)",
        category = "භෞතික විද්‍යාව",
        icon = "⛰️",
        quickSummary = "පොළව මට්ටමේ සිට උසකට එසවූ වස්තුවක ගබඩා වන යාන්ත්‍රික විභව ශක්තිය.",
        formulaOrRule = "E_p = m × g × h (g = 10 m/s² or N/kg)",
        practicalApplication = "50 kg ස්කන්ධයක් 10 m උසකට එසවූ විට ගබඩා වන විභව ශක්තිය: Ep = 50 × 10 × 10 = 5000 J (5 kJ).",
        examTip = "💡 ශක්තියේ ජාත්‍යන්තර සම්මත ඒකකය ජූල් (J) වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_04",
        subject = "විද්‍යාව",
        toolNumber = 4,
        groupNumber = 1,
        titleSinhala = "චාලක ශක්ති විවරණ මෙවලම",
        titleEnglish = "Kinetic Energy (Ek = ½mv²)",
        category = "භෞතික විද්‍යාව",
        icon = "🏎️",
        quickSummary = "චලනය වන වස්තුවක් සතු ශක්තිය ප්‍රවේගයේ වර්ගයට අනුලෝමව සමානුපාතික වේ.",
        formulaOrRule = "E_k = ½ m v² (m = kg, v = m/s, Ek = J)",
        practicalApplication = "1000 kg රථයක් 20 m/s ප්‍රවේගයෙන් යනවිට Ek = 0.5 × 1000 × 20² = 200,000 J = 200 kJ.",
        examTip = "💡 ප්‍රවේගය දෙගුණ වුවහොත් චාලක ශක්තිය 4 ගුණයක් (2²=4) වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_05",
        subject = "විද්‍යාව",
        toolNumber = 5,
        groupNumber = 1,
        titleSinhala = "ඝනත්වය සහ සාපේක්ෂ ඝනත්ව මෙවලම",
        titleEnglish = "Density & Relative Density Tool",
        category = "භෞතික විද්‍යාව",
        icon = "🧱",
        quickSummary = "ඒකක පරිමාවක අඩංගු ස්කන්ධය සහ ජලයේ ඝනත්වයට සාපේක්ෂ අනුපාතය.",
        formulaOrRule = "ඝනත්වය ρ = m / V (kg/m³ හෝ g/cm³) | සාපේක්ෂ ඝනත්වය = ද්‍රව්‍යයේ ඝනත්වය / ජලයේ ඝනත්වය (ඒකක රහිතයි)",
        practicalApplication = "ස්කන්ධය 540g වන ඇලුමිනියම් කුට්ටියක පරිමාව 200 cm³ නම්: ρ = 540 / 200 = 2.7 g/cm³ = 2700 kg/m³.",
        examTip = "💡 g/cm³ අගය 1000න් ගුණ කළ විට kg/m³ අගය ලැබේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_06",
        subject = "විද්‍යාව",
        toolNumber = 6,
        groupNumber = 1,
        titleSinhala = "දියර පීඩනය සහ උත්ප්ලාවකතා රීතිය",
        titleEnglish = "Liquid Pressure & Upthrust (P = hρg)",
        category = "භෞතික විද්‍යාව",
        icon = "🌊",
        quickSummary = "ස්ථානීය ද්‍රව කඳක පතුලේ පීඩනය ගැඹුර, ඝනත්වය සහ ගුරුත්වජ ත්වරණය මත රඳා පවතී.",
        formulaOrRule = "P = h × ρ × g (P = Pa හෝ N/m²)",
        practicalApplication = "ජලයේ (ρ=1000 kg/m³) 5 m ගැඹුරකදී පීඩනය: P = 5 × 1000 × 10 = 50,000 Pa = 50 kPa.",
        examTip = "💡 දියරයක පීඩනය බඳුනේ හැඩය හෝ හරස්කඩ වර්ගඵලය මත රඳා නොපවතී; රඳා පවතින්නේ සිරස් ගැඹුර මත පමණි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_07",
        subject = "විද්‍යාව",
        toolNumber = 7,
        groupNumber = 1,
        titleSinhala = "කාර්යය සහ ජවය ගණන යන්ත්‍රය",
        titleEnglish = "Work & Power Calculator",
        category = "භෞතික විද්‍යාව",
        icon = "⚙️",
        quickSummary = "බලයක් මගින් වස්තුවක් විස්ථාපනය කිරීම සහ කාර්යය කිරීමේ සීඝ්‍රතාවය.",
        formulaOrRule = "W = F × d (J) | P = W / t (W = වොට්)",
        practicalApplication = "200 N බලයකින් 6 m දුරක් තත්පර 4 කදී ඇදගෙන ගියහොත්: W = 200 × 6 = 1200 J; P = 1200 / 4 = 300 W.",
        examTip = "💡 1 kW = 1000 W. ජවය අශ්වබල (hp) වලින් දුනහොත් 1 hp = 746 W වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_08",
        subject = "විද්‍යාව",
        toolNumber = 8,
        groupNumber = 1,
        titleSinhala = "ආකිමිඩීස් නියමය සහ පාවීමේ නීතිය",
        titleEnglish = "Archimedes' Principle & Law of Flotation",
        category = "භෞතික විද්‍යාව",
        icon = "🚢",
        quickSummary = "වස්තුවක් තරලයක ගිල්වූ විට ක්‍රියාකරන උඩුකුරු තෙරපුම එය මගින් විස්ථාපිත තරලයේ බරට සමාන වේ.",
        formulaOrRule = "උඩුකුරු තෙරපුම U = V × ρ × g (V = විස්ථාපිත පරිමාව)",
        practicalApplication = "නෞකාවක් පාවීමේදී: නෞකාවේ මුළු බර = විස්ථාපනය කළ ජල පරිමාවේ බර.",
        examTip = "💡 පාවෙන වස්තුවක සම්ප්‍රයුක්ත බලය ශුන්‍ය වේ (බර = උඩුකුරු තෙරපුම)."
      ),
      OlSubjectToolItem(
        id = "sci_tool_09",
        subject = "විද්‍යාව",
        toolNumber = 9,
        groupNumber = 1,
        titleSinhala = "ඝර්ෂණ බල සහ සාධක විශ්ලේෂකය",
        titleEnglish = "Friction Force & Factors Analyzer",
        category = "භෞතික විද්‍යාව",
        icon = "🛞",
        quickSummary = "ස්පර්ශ පෘෂ්ඨ අතර සාපේක්ෂ චලිතයට ප්‍රතිවිරුද්ධව හටගන්නා ප්‍රතිරෝධී බලය.",
        formulaOrRule = "සීමාකාරී ඝර්ෂණ බලය F_R = μ × R (R = අභිලම්භ ප්‍රතික්‍රියාව)",
        practicalApplication = "ටයර් කට්ට කැපීමෙන් ඝර්ෂණය වැඩි කර ලිස්සා යාම වළක්වයි; බෙයාරිං සහ ලිහිසි තෙල් මගින් ඝර්ෂණය අඩු කරයි.",
        examTip = "💡 ඝර්ෂණ බලය ස්පර්ශ පෘෂ්ඨවල වර්ගඵලය මත රඳා නොපවතී; පෘෂ්ඨවල ස්වභාවය සහ ලම්බ තෙරපුම මත රඳා පවතී."
      ),
      OlSubjectToolItem(
        id = "sci_tool_10",
        subject = "විද්‍යාව",
        toolNumber = 10,
        groupNumber = 1,
        titleSinhala = "බල ඝූර්ණය සහ ලීවර මූලධර්මය",
        titleEnglish = "Moment of Force & Lever Principle",
        category = "භෞතික විද්‍යාව",
        icon = "🔧",
        quickSummary = "භ්‍රමණ අක්ෂයේ සිට බලයේ ක්‍රියා රේඛාවට ඇති ලම්භ දුර හා බලයේ ගුණිතය.",
        formulaOrRule = "ඝූර්ණය M = F × d (N m) | සමතුලිතතාවයේදී: ඔරලෝසු දිශා ඝූර්ණ = ප්‍රති-ඔරලෝසු දිශා ඝූර්ණ",
        practicalApplication = "දොර අගුල සරනේරුවේ සිට ඈතින් සවිකර ඇත්තේ ලම්භ දුර (d) වැඩි කර අඩු බලයකින් (F) වැඩි ඝූර්ණයක් ලබා ගැනීමටයි.",
        examTip = "💡 ඝූර්ණයේ ඒකකය නිව්ටන් මීටර (N m) වේ."
      ),

      // --- GROUP 2: තාපය සහ තරංග (11-20) ---
      OlSubjectToolItem(
        id = "sci_tool_11",
        subject = "විද්‍යාව",
        toolNumber = 11,
        groupNumber = 2,
        titleSinhala = "විශිෂ්ට තාප ධාරිතා ගණක මෙවලම",
        titleEnglish = "Specific Heat Capacity (Q = mcΔθ)",
        category = "භෞතික විද්‍යාව",
        icon = "🌡️",
        quickSummary = "ද්‍රව්‍යයක ඒකක ස්කන්ධයක (1 kg) උෂ්ණත්වය 1 °C (හෝ 1 K) කින් ඉහළ නැංවීමට අවශ්‍ය තාපය.",
        formulaOrRule = "Q = m × c × Δθ (c ඒකකය: J kg⁻¹ °C⁻¹)",
        practicalApplication = "ජලයේ c = 4200 J kg⁻¹ °C⁻¹. 2 kg ජලයේ උෂ්ණත්වය 30 °C සිට 80 °C (Δθ=50) කිරීමට: Q = 2 × 4200 × 50 = 420,000 J = 420 kJ.",
        examTip = "💡 ජලයේ විශිෂ්ට තාප ධාරිතාව ඉතා ඉහළ බැවින් මෝටර් රථ සිසිලනකාරකයක් ලෙස සහ උණුසුම් ජල බෝතල් සඳහා යොදාගනී."
      ),
      OlSubjectToolItem(
        id = "sci_tool_12",
        subject = "විද්‍යාව",
        toolNumber = 12,
        groupNumber = 2,
        titleSinhala = "විශිෂ්ට ගුප්ත තාප සූත්‍රය",
        titleEnglish = "Specific Latent Heat (Q = mL)",
        category = "භෞතික විද්‍යාව",
        icon = "❄️",
        quickSummary = "උෂ්ණත්වය වෙනස් නොවී පදාර්ථයේ අවස්ථාව වෙනස් කිරීමට අවශ්‍ය තාප ශක්තිය.",
        formulaOrRule = "Q = m × L (L_f = විලයනයේ ගුප්ත තාපය, L_v = වාෂ්පීකරණයේ ගුප්ත තාපය, J/kg)",
        practicalApplication = "0 °C අයිස් 1 kg දියවීමට අවශ්‍ය තාපය: Q = 1 × 336,000 = 336 kJ.",
        examTip = "💡 අවස්ථා විපර්යාසයේදී (දියවීම/නැටීම) උෂ්ණත්වය නියතව පවතී."
      ),
      OlSubjectToolItem(
        id = "sci_tool_13",
        subject = "විද්‍යාව",
        toolNumber = 13,
        groupNumber = 2,
        titleSinhala = "තරංග ප්‍රවේග සමීකරණ මෙවලම",
        titleEnglish = "Wave Equation (v = f λ)",
        category = "භෞතික විද්‍යාව",
        icon = "〰️",
        quickSummary = "ඕනෑම තරංගයක (ශබ්ද, ආලෝක, ජල) ප්‍රවේගය, සංඛ්‍යාතය සහ තරංග ආයාමය අතර අන්තර් සම්බන්ධය.",
        formulaOrRule = "v = f × λ (v = m/s, f = Hz, λ = m)",
        practicalApplication = "ගුවන්විදුලි තරංගයක f = 100 MHz (10^8 Hz), ආලෝක ප්‍රවේගය v = 3 × 10^8 m/s නම්: λ = v / f = 3 m.",
        examTip = "💡 තරංගයක් එක් මාධ්‍යයකින් තවත් මාධ්‍යයකට යනවිට සංඛ්‍යාතය (f) කිසිවිටෙකත් වෙනස් නොවේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_14",
        subject = "විද්‍යාව",
        toolNumber = 14,
        groupNumber = 2,
        titleSinhala = "ශබ්දයේ දෝංකාරය සහ ගැඹුර මැනුම් මෙවලම",
        titleEnglish = "Echo & SONAR Distance Tool",
        category = "භෞතික විද්‍යාව",
        icon = "🔊",
        quickSummary = "පරාවර්තනය වී පැමිණෙන ශබ්ද තරංග මගින් දුර හෝ මුහුදු පතුලේ ගැඹුර ගණනය කිරීම.",
        formulaOrRule = "2d = v × t => d = (v × t) / 2",
        practicalApplication = "මුහුදු ජලයේ ශබ්ද ප්‍රවේගය 1500 m/s වනවිට යැවූ සංඥාව තත්පර 2 කින් නැවත ආවේ නම්: d = (1500 × 2) / 2 = 1500 m.",
        examTip = "💡 ශබ්දය ගොස් නැවත පැමිණීමට ගමන් කරන මුළු දුර 2d වන බව මතක තබාගන්න."
      ),
      OlSubjectToolItem(
        id = "sci_tool_15",
        subject = "විද්‍යාව",
        toolNumber = 15,
        groupNumber = 2,
        titleSinhala = "ස්නෙල්ගේ නියමය සහ වර්තන අංකය",
        titleEnglish = "Snell's Law & Refractive Index",
        category = "භෞතික විද්‍යාව",
        icon = "🔍",
        quickSummary = "ආලෝකය එක් මාධ්‍යයක සිට වෙනත් මාධ්‍යයකට ගමන් කිරීමේදී කිරණ නැමීමේ නියමය.",
        formulaOrRule = "n = sin(i) / sin(r) = v₁ / v₂ = c / v",
        practicalApplication = "වීදුරුවල වර්තන අංකය n = 1.5 නම්, වීදුරු තුළ ආලෝක ප්‍රවේගය: v = c / 1.5 = (3 × 10^8) / 1.5 = 2 × 10^8 m/s.",
        examTip = "💡 විරල මාධ්‍යයේ සිට ඝන මාධ්‍යයට කිරණ යනවිට අභිලම්භය දෙසට නැමේ (i > r)."
      ),
      OlSubjectToolItem(
        id = "sci_tool_16",
        subject = "විද්‍යාව",
        toolNumber = 16,
        groupNumber = 2,
        titleSinhala = "අවධි කෝණය සහ පූර්ණ අභ්‍යන්තර පරාවර්තනය",
        titleEnglish = "Critical Angle & Total Internal Reflection",
        category = "භෞතික විද්‍යාව",
        icon = "💎",
        quickSummary = "ඝන මාධ්‍යයක සිට විරල මාධ්‍යයට කිරණ යනවිට වර්තන කෝණය 90° වන පතන කෝණය අවධි කෝණයයි.",
        formulaOrRule = "sin(C) = 1 / n (පතන කෝණය > C විට පූර්ණ අභ්‍යන්තර පරාවර්තනය සිදුවේ)",
        practicalApplication = "ඔප්ටිකල් ෆයිබර් (Optical Fibres) සහ දියමන්ති දිලිසීම පූර්ණ අභ්‍යන්තර පරාවර්තනයේ යෙදීම් වේ.",
        examTip = "💡 පූර්ණ අභ්‍යන්තර පරාවර්තනය වීමට කොන්දේසි 2ක් අවශ්‍ය වේ: 1. කිරණය ඝන මාධ්‍යයේ සිට විරල මාධ්‍යයට යා යුතුය. 2. පතන කෝණය අවධි කෝණයට වඩා විශාල විය යුතුය."
      ),
      OlSubjectToolItem(
        id = "sci_tool_17",
        subject = "විද්‍යාව",
        toolNumber = 17,
        groupNumber = 2,
        titleSinhala = "උත්තල හා අවතල කාච ප්‍රතිබිම්බ නීති",
        titleEnglish = "Lens Image Formation Rules (1/f = 1/v - 1/u)",
        category = "භෞතික විද්‍යාව",
        icon = "👓",
        quickSummary = "කාච සූත්‍රය සහ නාභිය දුර අනුව තාත්වික හෝ අතාත්වික ප්‍රතිබිම්බ සෑදීමේ ලක්ෂණ.",
        formulaOrRule = "රේඛීය විශාලනය m = v / u = ප්‍රතිබිම්බ උස / වස්තු උස",
        practicalApplication = "උත්තල කාචයක නාභිය සහ කාචය අතර (u < f) වස්තුව තැබූ විට විශාලිත, උඩුකුරු, අතාත්වික ප්‍රතිබිම්බයක් සෑදේ (අත් කාචය).",
        examTip = "💡 අවතල කාචයකින් සෑම විටම ලැබෙන්නේ කුඩා වූ, උඩුකුරු, අතාත්වික ප්‍රතිබිම්බයකි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_18",
        subject = "විද්‍යාව",
        toolNumber = 18,
        groupNumber = 2,
        titleSinhala = "දෘෂ්ටි ඌනතා නිවැරදි කිරීමේ මෙවලම",
        titleEnglish = "Eye Vision Defects & Lens Corrector",
        category = "භෞතික විද්‍යාව",
        icon = "👁️",
        quickSummary = "අවිදුර දෘෂ්ටිකත්වය (Myopia) සහ දුර දෘෂ්ටිකත්වය (Hypermetropia) නිවැරදි කරන ක්‍රමය.",
        formulaOrRule = "අවිදුර දෘෂ්ටිකත්වය -> අවතල කාච | දුර දෘෂ්ටිකත්වය -> උත්තල කාච",
        practicalApplication = "අවිදුර දෘෂ්ටිකත්වයේදී ප්‍රතිබිම්බය දෘෂ්ටිවිතානයට ඉදිරියෙන් වැටෙන බැවින් ආලෝකය අපසාරී කිරීමට අවතල කාච භාවිත වේ.",
        examTip = "💡 විභාගයේදී කාච සටහන අඳින විට කිරණවල ඊතල හිස් නිවැරදිව දැක්විය යුතුය."
      ),
      OlSubjectToolItem(
        id = "sci_tool_19",
        subject = "විද්‍යාව",
        toolNumber = 19,
        groupNumber = 2,
        titleSinhala = "විද්‍යුත් චුම්භක වර්ණාවලිය සහ ප්‍රයෝජන",
        titleEnglish = "Electromagnetic Spectrum Explorer",
        category = "භෞතික විද්‍යාව",
        icon = "📡",
        quickSummary = "ගුවන්විදුලි, ක්ෂුද්‍ර, අධෝරක්ත, දෘශ්‍ය, පාරජම්බුල, X-කිරණ, ගැමා කිරණ තරංග ආයාම අනුපිළිවෙල.",
        formulaOrRule = "තරංග ආයාමය අඩුවන විට (λ↓) ශක්තිය සහ සංඛ්‍යාතය වැඩිවේ (f↑, E = hf)",
        practicalApplication = "ගැමා කිරණ -> පිළිකා සෛල විනාශයට; X-කිරණ -> අස්ථි බිඳීම් පරීක්ෂාවට; අධෝරක්ත -> දුරස්ථ පාලක (Remote control).",
        examTip = "💡 රික්තය තුළ සියලුම විද්‍යුත් චුම්භක තරංග ගමන් කරන්නේ ආලෝකයේ ප්‍රවේගයෙනි (3 × 10^8 m/s)."
      ),
      OlSubjectToolItem(
        id = "sci_tool_20",
        subject = "විද්‍යාව",
        toolNumber = 20,
        groupNumber = 2,
        titleSinhala = "තාප සංක්‍රාමණ විධි (සන්නයනය, සංවහනය, විකිරණය)",
        titleEnglish = "Heat Transfer Methods (Conduction, Convection, Radiation)",
        category = "භෞතික විද්‍යාව",
        icon = "☀️",
        quickSummary = "තාපය වැඩි ස්ථානයක සිට අඩු ස්ථානයට සම්ප්‍රේෂණය වන ක්‍රම 3.",
        formulaOrRule = "සන්නයනය (ඝන ද්‍රව්‍ය) | සංවහනය (ද්‍රව සහ වායු) | විකිරණය (මාධ්‍යයක් අවශ්‍ය නොවේ)",
        practicalApplication = "රික්ත ප්ලාස්කුවේ (Thermos flask) රිදී ආලේපිත ද්විත්ව බිත්ති මගින් විකිරණය වළක්වයි; රික්තය මගින් සන්නයනය සහ සංවහනය වළක්වයි.",
        examTip = "💡 අඳුරු රළු පෘෂ්ඨ තාපය හොඳින් අවශෝෂණය මෙන්ම විමෝචනය කරයි; සුදු ඔප දැමූ පෘෂ්ඨ තාපය පරාවර්තනය කරයි."
      ),

      // --- GROUP 3: විද්‍යුතය සහ චුම්භකත්වය (21-30) ---
      OlSubjectToolItem(
        id = "sci_tool_21",
        subject = "විද්‍යාව",
        toolNumber = 21,
        groupNumber = 3,
        titleSinhala = "ඕම්ගේ නියමය සහ ප්‍රතිරෝධ ගණකය",
        titleEnglish = "Ohm's Law Solver (V = IR)",
        category = "විද්‍යුතය",
        icon = "⚡",
        quickSummary = "නියත උෂ්ණත්වයේ පවතින සන්නායකයක දෙකෙළවර විභව අන්තරය ධාරාවට අනුලෝමව සමානුපාතික වේ.",
        formulaOrRule = "V = I × R | I = V / R | R = V / I (V = Volt, I = Ampere, R = Ohm Ω)",
        practicalApplication = "12 V බැටරියකට 4 Ω බල්බයක් සම්බන්ධ කළ විට ගලන ධාරාව: I = 12 / 4 = 3 A.",
        examTip = "💡 සූත්‍රිකා බල්බ ඕම්ගේ නියමයට අවනත නොවේ; මක්නිසාද ධාරාව ගලනවිට උෂ්ණත්වය ඉහළ යන බැවිනි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_22",
        subject = "විද්‍යාව",
        toolNumber = 22,
        groupNumber = 3,
        titleSinhala = "ශ්‍රේණිගත සහ සමාන්තරගත ප්‍රතිරෝධක මෙවලම",
        titleEnglish = "Series & Parallel Resistors Tool",
        category = "විද්‍යුතය",
        icon = "🔀",
        quickSummary = "පරිපථයක ප්‍රතිරෝධක සම්බන්ධ කරන ප්‍රධාන ආකාර 2 සහ සමක ප්‍රතිරෝධය සෙවීම.",
        formulaOrRule = "ශ්‍රේණිගත: R_eq = R₁ + R₂ + ... | සමාන්තරගත: 1/R_eq = 1/R₁ + 1/R₂ (ප්‍රතිරෝධක 2ක් නම්: R = (R₁×R₂)/(R₁+R₂))",
        practicalApplication = "6 Ω සහ 3 Ω සමාන්තරගතව සම්බන්ධ කළ විට සමක ප්‍රතිරෝධය: R = (6 × 3) / (6 + 3) = 18 / 9 = 2 Ω.",
        examTip = "💡 නිවෙස්වල උපකරණ සමාන්තරගතව සවි කරන්නේ සෑම උපකරණයකටම සම්පූර්ණ වෝල්ටීයතාව (230V) ලැබීමට සහ ස්වාධීනව පාලනය කිරීමටයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_23",
        subject = "විද්‍යාව",
        toolNumber = 23,
        groupNumber = 3,
        titleSinhala = "විද්‍යුත් ජවය සහ බලශක්ති සූත්‍රය",
        titleEnglish = "Electric Power & Energy (P = VI, E = VIt)",
        category = "විද්‍යුතය",
        icon = "💡",
        quickSummary = "විදුලි උපකරණයක් ක්‍රියාත්මක වීමේදී ඒකක කාලයකදී වැයවන විද්‍යුත් ශක්තිය.",
        formulaOrRule = "P = V × I = I²R = V²/R (Watt) | E = P × t (Joule)",
        practicalApplication = "230 V ජාලයට සම්බන්ධ 1000 W (1 kW) විදුලි හීටරයකින් ගලන ධාරාව: I = 1000 / 230 ≈ 4.35 A.",
        examTip = "💡 පරිපථයක ෆියුස් අගය (Fuse rating) තෝරා ගැනීමේදී ක්‍රියාකාරී ධාරාවට වඩා මඳක් වැඩි අගයක් තෝරාගත යුතුය (උදා: 4.35 A ට 5 A ෆියුස් එකක්)."
      ),
      OlSubjectToolItem(
        id = "sci_tool_24",
        subject = "විද්‍යාව",
        toolNumber = 24,
        groupNumber = 3,
        titleSinhala = "විදුලි බිල ගණනය කිරීමේ ඒකක (kWh) මෙවලම",
        titleEnglish = "Electricity Bill Unit (kWh) Calculator",
        category = "විද්‍යුතය",
        icon = "🧾",
        quickSummary = "ගෘහස්ථ විදුලි ඒකකයක් යනු කිලෝවොට් පැය 1ක් (1 kWh = 1 Unit = 3,600,000 J) වේ.",
        formulaOrRule = "විදුලි ඒකක ගණන = (ජවය W × භාවිත කළ පැය ගණන) / 1000",
        practicalApplication = "2000 W ගීසරයක් දිනකට පැය 2ක් බැගින් දින 30ක් භාවිත කළහොත්: ඒකක = (2000 × 2 × 30) / 1000 = 120 Units.",
        examTip = "💡 ජවය වොට් වලින් ඇත්නම් අනිවාර්යයෙන්ම 1000න් බෙදිය යුතුය."
      ),
      OlSubjectToolItem(
        id = "sci_tool_25",
        subject = "විද්‍යාව",
        toolNumber = 25,
        groupNumber = 3,
        titleSinhala = "ෆ්ලෙමින්ගේ වමත් නීතිය සහ මෝටර් මූලධර්මය",
        titleEnglish = "Fleming's Left Hand Rule (Motor Effect)",
        category = "චුම්භකත්වය",
        icon = "🖐️",
        quickSummary = "චුම්භක ක්ෂේත්‍රයක තබා ඇති ධාරාවක් රැගෙන යන සන්නායකයක් මත බලයක් ක්‍රියාකිරීම.",
        formulaOrRule = "මහපටැඟිල්ල = චලිත දිශාව (බලය F) | දබරැඟිල්ල = චුම්භක ක්ෂේත්‍රය (B) | මැදඟිල්ල = ධාරාව (I)",
        practicalApplication = "විදුලි මෝටරය (Electric Motor) මෙම මූලධර්මයට ක්‍රියා කරයි: විද්‍යුත් ශක්තිය චාලක/යාන්ත්‍රික ශක්තිය බවට පත් කරයි.",
        examTip = "💡 ක්ෂේත්‍රය උතුරු ධ්‍රැවයේ සිට දකුණු ධ්‍රැවයට (N -> S) යොමුවේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_26",
        subject = "විද්‍යාව",
        toolNumber = 26,
        groupNumber = 3,
        titleSinhala = "විද්‍යුත් චුම්භක ප්‍රේරණය සහ ඩයිනමෝව",
        titleEnglish = "Electromagnetic Induction & Generator",
        category = "චුම්භකත්වය",
        icon = "🔄",
        quickSummary = "සන්නායකයක් හා චුම්භක ක්ෂේත්‍රයක් අතර සාපේක්ෂ චලිතයක් ඇතිවිට සන්නායකයේ වි.ගා.බ. ප්‍රේරණය වීම.",
        formulaOrRule = "ප්‍රේරිත ධාරාව වැඩි කිරීමට: 1. දඟර වට ගණන වැඩිකිරීම 2. ප්‍රබල චුම්භක භාවිතය 3. භ්‍රමණ වේගය වැඩිකිරීම",
        practicalApplication = "පාපැදි ඩයිනමෝව සහ බලාගාර ජනක යන්ත්‍ර (Generators) මගින් ප්‍රත්‍යාවර්ත ධාරාව (AC) නිපදවයි.",
        examTip = "💡 ඩයිනමෝවේදී යාන්ත්‍රික ශක්තිය විද්‍යුත් ශක්තිය බවට පරිවර්තනය වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_27",
        subject = "විද්‍යාව",
        toolNumber = 27,
        groupNumber = 3,
        titleSinhala = "පරිණාමක සූත්‍රය (Transformer Equation)",
        titleEnglish = "Transformer Turns & Voltage Ratio",
        category = "විද්‍යුතය",
        icon = "🔋",
        quickSummary = "ප්‍රත්‍යාවර්ත වෝල්ටීයතාවක් වැඩි කරන (අපරිණාමක) හෝ අඩු කරන (අවපරිණාමක) උපකරණය.",
        formulaOrRule = "V_p / V_s = N_p / N_s = I_s / I_p",
        practicalApplication = "ප්‍රාථමිකයේ වට 1000ක් හා 230V ඇතිවිට, ද්විතීයිකයේ වට 100ක් නම්: V_s = 230 × (100 / 1000) = 23 V (අවපරිණාමකයකි).",
        examTip = "💡 පරිණාමක ක්‍රියාකරන්නේ ප්‍රත්‍යාවර්ත ධාරාවෙන් (AC) පමණි; සරල ධාරාවෙන් (DC) ක්‍රියා නොකරයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_28",
        subject = "විද්‍යාව",
        toolNumber = 28,
        groupNumber = 3,
        titleSinhala = "අර්ධ සන්නායක ඩයෝඩ සහ සෘජුකරණය",
        titleEnglish = "Semiconductor Diode & Rectification",
        category = "ඉලෙක්ට්‍රොනික",
        icon = "🔺",
        quickSummary = "ධාරාව එක් දිශාවකට පමණක් ගමන් කිරීමට ඉඩදෙන p-n සන්ධි උපකරණය.",
        formulaOrRule = "පෙර නැඹුරුවේදී (Forward bias) ධාරාව ගලයි | පසු නැඹුරුවේදී (Reverse bias) ධාරාව අවහිර කරයි",
        practicalApplication = "AC විදුලිය DC විදුලිය බවට පත්කිරීම (සෘජුකරණය) සඳහා ඩයෝඩ 4කින් යුත් පාලම් සෘජුකාරක (Bridge rectifiers) භාවිත වේ.",
        examTip = "💡 LED (ආලෝක විමෝචක ඩයෝඩය) ආලෝකය නිකුත් කරන්නේ පෙර නැඹුරුවේදී පමණි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_29",
        subject = "විද්‍යාව",
        toolNumber = 29,
        groupNumber = 3,
        titleSinhala = "මූලික තාර්කික ද්වාර (Logic Gates: AND, OR, NOT)",
        titleEnglish = "Basic Logic Gates & Truth Tables",
        category = "ඉලෙක්ට්‍රොනික",
        icon = "🚪",
        quickSummary = "ද්වීමය (0 සහ 1) සංඥා මගින් තීරණ ගන්නා ඩිජිටල් ඉලෙක්ට්‍රොනික පරිපථ.",
        formulaOrRule = "AND: සියලු ආදාන 1 නම් ප්‍රතිදානය 1 | OR: ඕනෑම ආදානයක් 1 නම් ප්‍රතිදානය 1 | NOT: ප්‍රතිදානය ආදානයේ ප්‍රතිලෝමයයි",
        practicalApplication = "ස්වයංක්‍රීය වීදි ලාම්පුවල ආලෝකය නොමැති විට (0) ලාම්පුව දැල්වීමට (1) NOT ද්වාර භාවිත කරයි.",
        examTip = "💡 NAND සහ NOR විශ්ව ද්වාර ලෙස හඳුන්වන්නේ ඒවා භාවිතයෙන් අනෙකුත් සියලු ද්වාර ගොඩනැගිය හැකි බැවිනි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_30",
        subject = "විද්‍යාව",
        toolNumber = 30,
        groupNumber = 3,
        titleSinhala = "ගෘහස්ථ විදුලි පරිපථ ආරක්ෂණ මෙවලම්",
        titleEnglish = "Domestic Electrical Safety Devices",
        category = "විද්‍යුතය",
        icon = "🛡️",
        quickSummary = "විදුලි සැර වැදීම් සහ ගිනි ගැනීම් වළක්වන MCB, RCCB/ELCB, භූගත කම්බිය සහ ෆියුස්.",
        formulaOrRule = "RCCB: සජීව හා උදාසීන කම්බි අතර ධාරා වෙනස හඳුනාගෙන මිලි තත්පර 30කින් විසන්ධි වේ.",
        practicalApplication = "ලෝහ ආවරණ සහිත උපකරණවල පිටත කවරය භූගත කම්බියට (Earth wire) සම්බන්ධ කර ඇත්තේ ධාරා කාන්දුවකදී විදුලි සැර වැදීම වැළැක්වීමටයි.",
        examTip = "💡 ස්විච සහ ෆියුස් සෑම විටම සවි කළ යුත්තේ සජීවී කම්බියට (Live wire) පමණි."
      ),

      // --- GROUP 4: පදාර්ථයේ ව්‍යුහය සහ ආවර්තිතා වගුව (31-40) ---
      OlSubjectToolItem(
        id = "sci_tool_31",
        subject = "විද්‍යාව",
        toolNumber = 31,
        groupNumber = 4,
        titleSinhala = "පරමාණුක ව්‍යුහය සහ උප-පරමාණුක අංශු",
        titleEnglish = "Atomic Structure & Subatomic Particles",
        category = "රසායන විද්‍යාව",
        icon = "⚛️",
        quickSummary = "ප්‍රෝටෝන (p), නියුට්‍රෝන (n) සහ ඉලෙක්ට්‍රෝන (e) පිහිටීම, ආරෝපණ සහ ස්කන්ධ.",
        formulaOrRule = "පරමාණුක ක්‍රමාංකය (Z) = p = e (උදාසීන විට) | ස්කන්ධ ක්‍රමාංකය (A) = p + n",
        practicalApplication = "₁₁²³Na පරමාණුවේ: ප්‍රෝටෝන = 11, ඉලෙක්ට්‍රෝන = 11, නියුට්‍රෝන = 23 - 11 = 12.",
        examTip = "💡 සමස්ථානික යනු එකම පරමාණුක ක්‍රමාංකය (Z) සහ වෙනස් ස්කන්ධ ක්‍රමාංක (A) ඇති එකම මූලද්‍රව්‍යයේ පරමාණු වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_32",
        subject = "විද්‍යාව",
        toolNumber = 32,
        groupNumber = 4,
        titleSinhala = "ඉලෙක්ට්‍රෝන වින්‍යාස මෙවලම (Z = 1 සිට 20)",
        titleEnglish = "Electron Configuration (2, 8, 8, 2) Tool",
        category = "රසායන විද්‍යාව",
        icon = "🪐",
        quickSummary = "පරමාණුවේ ශක්ති මට්ටම්වල (K, L, M, N) ඉලෙක්ට්‍රෝන පිරී පවතින පිළිවෙල (2n² නීතිය).",
        formulaOrRule = "1වන කවචය: උපරිම 2 | 2වන කවචය: උපරිම 8 | 3වන කවචය: උපරිම 8 (පළමු 20ට) | 4වන: 2",
        practicalApplication = "ක්ලෝරීන් ₁₇Cl: 2, 8, 7; කැල්සියම් ₂₀Ca: 2, 8, 8, 2.",
        examTip = "💡 සංයුජතා ඉලෙක්ට්‍රෝන ගණනින් මූලද්‍රව්‍යය අයත් කාණ්ඩයද, ශක්ති මට්ටම් ගණනින් ආවර්තයද තීරණය වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_33",
        subject = "විද්‍යාව",
        toolNumber = 33,
        groupNumber = 4,
        titleSinhala = "සංයුජතාව සහ රසායනික සූත්‍ර තනන්නා",
        titleEnglish = "Valency & Chemical Formula Maker",
        category = "රසායන විද්‍යාව",
        icon = "🧪",
        quickSummary = "මූලද්‍රව්‍ය හෝ බහුපරමාණුක අයන අතර සංයුජතා හුවමාරු කර සංයෝග සූත්‍ර සෑදීම.",
        formulaOrRule = "සංයුජතා මාරු කිරීම: Al³⁺ (සංයුජතාව 3) සහ O²⁻ (සංයුජතාව 2) => Al₂O₃",
        practicalApplication = "මැග්නීසියම් ක්ලෝරයිඩ්: Mg (2) සහ Cl (1) => MgCl₂; ඇමෝනියම් සල්ෆේට්: NH₄⁺ (1) සහ SO₄²⁻ (2) => (NH₄)₂SO₄.",
        examTip = "💡 බහුපරමාණුක අයනයක් දෙවරක් හෝ ඊට වැඩි ගණනක් යෙදෙන විට වරහන් යෙදීම අනිවාර්ය වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_34",
        subject = "විද්‍යාව",
        toolNumber = 34,
        groupNumber = 4,
        titleSinhala = "අයනික සහ සහසංයුජ බන්ධන විවරණය",
        titleEnglish = "Ionic vs Covalent Bonding Analyzer",
        category = "රසායන විද්‍යාව",
        icon = "🔗",
        quickSummary = "ඉලෙක්ට්‍රෝන හුවමාරුවෙන් සෑදෙන අයනික බන්ධන සහ ඉලෙක්ට්‍රෝන හවුලේ තබා සෑදෙන සහසංයුජ බන්ධන.",
        formulaOrRule = "ලෝහ + අලෝහ -> අයනික (උදා: NaCl) | අලෝහ + අලෝහ -> සහසංයුජ (උදා: H₂O, CO₂)",
        practicalApplication = "අයනික සංයෝග ඝන අවස්ථාවේ විදුලිය නොගෙනියයි; ජලීය හෝ විලයන අවස්ථාවේ නිදහස් අයන මගින් විදුලිය සන්නයනය කරයි.",
        examTip = "💡 සහසංයුජ සංයෝග විදුලිය සන්නයනය නොකරයි (ග්ලූකෝස්, මධ්‍යසාර)."
      ),
      OlSubjectToolItem(
        id = "sci_tool_35",
        subject = "විද්‍යාව",
        toolNumber = 35,
        groupNumber = 4,
        titleSinhala = "රසායනික සමීකරණ තුලනය කිරීමේ මෙවලම",
        titleEnglish = "Chemical Equation Balancing Assistant",
        category = "රසායන විද්‍යාව",
        icon = "⚖️",
        quickSummary = "ස්කන්ධ සංස්ථිති නියමයට අනුව ප්‍රතික්‍රියකවල සහ ඵලවල එක් එක් පරමාණු ගණන සමාන කිරීම.",
        formulaOrRule = "ප්‍රතික්‍රියක පරමාණු ගණන = ඵල පරමාණු ගණන",
        practicalApplication = "යකඩ මලකඩ කෑම: 4Fe + 3O₂ + 2xH₂O -> 2Fe₂O₃·xH₂O; ප්‍රභාසංස්ලේෂණය: 6CO₂ + 6H₂O -> C₆H₁₂O₆ + 6O₂.",
        examTip = "💡 තුලනය කිරීමේදී උපසිරැසි (subscripts) වෙනස් නොකර ඉදිරියෙන් ඇති සංගුණක (coefficients) පමණක් වෙනස් කරන්න."
      ),
      OlSubjectToolItem(
        id = "sci_tool_36",
        subject = "විද්‍යාව",
        toolNumber = 36,
        groupNumber = 4,
        titleSinhala = "මවුල සංකල්පය සහ මවුලික ස්කන්ධ ගණකය",
        titleEnglish = "Mole Concept & Molar Mass Calculator",
        category = "රසායන විද්‍යාව",
        icon = "🧮",
        quickSummary = "ඕනෑම ද්‍රව්‍යයක මවුල 1 ක අඩංගු අංශු ගණන ඇවගාඩ්‍රෝ නියතයට (6.022 × 10²³) සමාන වේ.",
        formulaOrRule = "මවුල ගණන n = ස්කන්ධය (m) / මවුලික ස්කන්ධය (M)",
        practicalApplication = "ජලයේ (H₂O) මවුලික ස්කන්ධය = (1×2) + 16 = 18 g/mol. ජලය 36 g ඇති මවුල ගණන: n = 36 / 18 = 2 mol.",
        examTip = "💡 සාමාන්‍ය උෂ්ණත්වයේ හා පීඩනයේදී (STP) ඕනෑම වායුවක මවුල 1 ක පරිමාව 22.4 dm³ (හෝ 24 dm³ කාමර උෂ්ණත්වයේදී) වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_37",
        subject = "විද්‍යාව",
        toolNumber = 37,
        groupNumber = 4,
        titleSinhala = "ද්‍රාවණයක සාන්ද්‍රණය සෙවීමේ මෙවලම",
        titleEnglish = "Solution Concentration (C = n/V) Tool",
        category = "රසායන විද්‍යාව",
        icon = "🥛",
        quickSummary = "ද්‍රාවණයක ඒකක පරිමාවක (1 dm³ = 1 L) දියවී ඇති ද්‍රාව්‍යයේ මවුල ගණන.",
        formulaOrRule = "C = n / V (C = mol dm⁻³, n = මවුල, V = පරිමාව dm³ වලින්)",
        practicalApplication = "ජලය 500 cm³ (0.5 dm³) තුළ NaCl මවුල 1ක් දිය කළ විට සාන්ද්‍රණය: C = 1 / 0.5 = 2 mol dm⁻³.",
        examTip = "💡 cm³ අගයක් dm³ කිරීමට 1000න් බෙදන්න."
      ),
      OlSubjectToolItem(
        id = "sci_tool_38",
        subject = "විද්‍යාව",
        toolNumber = 38,
        groupNumber = 4,
        titleSinhala = "ආවර්තිතා ප්‍රවණතා විශ්ලේෂකය",
        titleEnglish = "Periodic Trends Analyzer (Radius, Electronegativity)",
        category = "රසායන විද්‍යාව",
        icon = "📊",
        quickSummary = "ආවර්තයක් ඔස්සේ දකුණට යනවිට සහ කාණ්ඩයක් ඔස්සේ පහළට යනවිට මූලද්‍රව්‍ය ලක්ෂණ වෙනස්වීම.",
        formulaOrRule = "වමේ සිට දකුණට: පරමාණුක අරය ↓, විද්‍යුත් සෘණතාවය ↑, ප්‍රථම අයනීකරණ ශක්තිය ↑ | ඉහළ සිට පහළට: පරමාණුක අරය ↑, ලෝහක ගුණය ↑",
        practicalApplication = "ආවර්තිතා වගුවේ වඩාත්ම විද්‍යුත් සෘණ මූලද්‍රව්‍යය ෆ්ලෝරීන් (F) වන අතර වඩාත්ම සක්‍රීය ලෝහය සීසියම්/ෆ්‍රැන්සියම් වේ.",
        examTip = "💡 ආවර්තයක් ඔස්සේ දකුණට යනවිට න්‍යෂ්ටික ආරෝපණය වැඩිවන බැවින් ඉලෙක්ට්‍රෝන තදින් ඇදගනී; එමනිසා පරමාණුක අරය කුඩා වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_39",
        subject = "විද්‍යාව",
        toolNumber = 39,
        groupNumber = 4,
        titleSinhala = "අයන හා විද්‍යුත් විච්ඡේද්‍ය පරීක්ෂක",
        titleEnglish = "Ions & Electrolytes Checker",
        category = "රසායන විද්‍යාව",
        icon = "⚡",
        quickSummary = "කැටායන (ධන අයන), ඇනායන (සෘණ අයන) සහ විදුලිය සන්නයනය කරන ප්‍රබල/දුබල විද්‍යුත් විච්ඡේද්‍ය.",
        formulaOrRule = "කැතෝඩය (-) දෙසට කැටායනද, ඇනෝඩය (+) දෙසට ඇනායනද ඇදී ගොස් විසර්ජනය වේ.",
        practicalApplication = "තනුක H₂SO₄ ජල විච්ඡේදනයේදී: කැතෝඩයේ H₂ වායුවද, ඇනෝඩයේ O₂ වායුවද පිටවේ (පරිමා අනුපාතය 2 : 1).",
        examTip = "💡 H₂ වායුව දැල්වූ හුලක්කුවක් මගින් 'පොප්' හඬින් දැවේ; O₂ වායුව නිවුණු හුලක්කුවක් නැවත දල්වයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_40",
        subject = "විද්‍යාව",
        toolNumber = 40,
        groupNumber = 4,
        titleSinhala = "ඇලෝට්‍රෝප (බහුරූපී ප්‍රභේද) ගවේෂක",
        titleEnglish = "Allotropes Explorer (Carbon: Diamond, Graphite)",
        category = "රසායන විද්‍යාව",
        icon = "💎",
        quickSummary = "එකම මූලද්‍රව්‍යය එකම භෞතික අවස්ථාවේ පවතින විවිධ ව්‍යුහාත්මක ස්වරූප.",
        formulaOrRule = "කාබන්: දියමන්ති (දෘඪ, විදුලිය නොගෙනියයි, චතුස්තලීය), මිනිරන් (ස්තර ව්‍යුහය, ලිහිසි, විදුලිය සන්නයනය කරයි).",
        practicalApplication = "මිනිරන්වල එක් කාබන් පරමාණුවකට මුදාහැරුණු නිදහස් ඉලෙක්ට්‍රෝනයක් ඇති බැවින් එය විද්‍යුතය සන්නයනය කරයි.",
        examTip = "💡 වියළි කෝෂවල ඉලෙක්ට්‍රෝඩ සඳහා මිනිරන් (ග්‍රැෆයිට්) දඬු යොදාගනී."
      ),

      // --- GROUP 5: රසායනික ප්‍රතික්‍රියා සහ අම්ල භස්ම (41-50) ---
      OlSubjectToolItem(
        id = "sci_tool_41",
        subject = "විද්‍යාව",
        toolNumber = 41,
        groupNumber = 5,
        titleSinhala = "ප්‍රතික්‍රියා සීඝ්‍රතා සාධක මෙවලම",
        titleEnglish = "Rate of Reaction Factors Tool",
        category = "රසායන විද්‍යාව",
        icon = "⏱️",
        quickSummary = "රසායනික ප්‍රතික්‍රියාවක වේගය කෙරෙහි බලපාන සාධක 5: සාන්ද්‍රණය, උෂ්ණත්වය, පෘෂ්ඨ වර්ගඵලය, උත්ප්‍රේරක, පීඩනය.",
        formulaOrRule = "උෂ්ණත්වය 10 °C කින් වැඩි කරන විට බොහෝ ප්‍රතික්‍රියාවල සීඝ්‍රතාව දෙගුණ වේ (ඵලදායී ගැටුම් සංඛ්‍යාව වැඩිවීම).",
        practicalApplication = "ඝන කැබලි කුඩු කළ විට පෘෂ්ඨ වර්ගඵලය වැඩිවී ප්‍රතික්‍රියා සීඝ්‍රතාව වේගවත් වේ (උදා: CaCO₃ කැට වෙනුවට කුඩු).",
        examTip = "💡 උත්ප්‍රේරකයක් මගින් ප්‍රතික්‍රියාවේ සක්‍රියන ශක්තිය (Activation Energy) අඩු කර ප්‍රතික්‍රියාව වේගවත් කරයි; ප්‍රතික්‍රියාව අවසානයේදී උත්ප්‍රේරකය නොවෙනස්ව පවතී."
      ),
      OlSubjectToolItem(
        id = "sci_tool_42",
        subject = "විද්‍යාව",
        toolNumber = 42,
        groupNumber = 5,
        titleSinhala = "තාපදායක හා තාපඅවශෝෂක ප්‍රතික්‍රියා",
        titleEnglish = "Exothermic & Endothermic Reactions Tool",
        category = "රසායන විද්‍යාව",
        icon = "🔥",
        quickSummary = "පරිසරයට තාපය පිටකරන (තාපදායක, ΔH < 0) සහ පරිසරයෙන් තාපය උරාගන්නා (තාපඅවශෝෂක, ΔH > 0) ප්‍රතික්‍රියා.",
        formulaOrRule = "තාපදායක: උෂ්ණත්වය ඉහළ යයි (උදා: දහනය, අම්ල-භස්ම උදාසීනීකරණය) | තාපඅවශෝෂක: උෂ්ණත්වය පහළ බසී (උදා: NH₄Cl ජලයේ දියවීම)",
        practicalApplication = "ක්ෂණික සිසිලන පැකට්වල (Instant cold packs) ඇමෝනියම් නයිට්‍රේට් ජලයේ දියවීමේ තාපඅවශෝෂක ක්‍රියාවලිය භාවිත වේ.",
        examTip = "💡 ශක්ති මට්ටම් සටහනක තාපදායක ප්‍රතික්‍රියාවක ඵලවල ශක්තිය ප්‍රතික්‍රියකවල ශක්තියට වඩා පහළින් පිහිටයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_43",
        subject = "විද්‍යාව",
        toolNumber = 43,
        groupNumber = 5,
        titleSinhala = "pH පරිමාණය සහ දර්ශක සටහන",
        titleEnglish = "pH Scale & Indicators Reference",
        category = "රසායන විද්‍යාව",
        icon = "🌈",
        quickSummary = "ද්‍රාවණයක ආම්ලික/භස්මික ප්‍රබලතාවය මනින 0-14 පරිමාණය සහ ලිට්මස්, මෙතිල් ඔරේන්ජ්, ෆිනොප්තලීන් වර්ණ.",
        formulaOrRule = "pH < 7 (අම්ල) | pH = 7 (උදාසීන) | pH > 7 (භස්ම/ක්ෂාර)",
        practicalApplication = "ෆිනොප්තලීන්: අම්ලවලදී අවර්ණයි, භස්මවලදී රෝස පාටයි; මෙතිල් ඔරේන්ජ්: අම්ලවලදී රතුයි, භස්මවලදී කහයි.",
        examTip = "💡 ප්‍රබල අම්ලයක (උදා: HCl) pH අගය 1-2 වන අතර දුබල අම්ලයක (උදා: CH₃COOH) pH අගය 4-5 පමණ වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_44",
        subject = "විද්‍යාව",
        toolNumber = 44,
        groupNumber = 5,
        titleSinhala = "ලෝහ සක්‍රීයතා ශ්‍රේණි මෙවලම",
        titleEnglish = "Metal Reactivity Series Tool",
        category = "රසායන විද්‍යාව",
        icon = "🏅",
        quickSummary = "K > Na > Ca > Mg > Al > Zn > Fe > Pb > (H) > Cu > Ag > Au",
        formulaOrRule = "සක්‍රීයතාව වැඩි ලෝහයකට සක්‍රීයතාව අඩු ලෝහයක් එහි ලවණ ද්‍රාවණයෙන් විස්ථාපනය කළ හැක.",
        practicalApplication = "තඹ සල්ෆේට් (CuSO₄) ද්‍රාවණයකට යකඩ ඇණයක් දැමූ විට යකඩ මගින් තඹ විස්ථාපනය වී ඇණය මත තඹ තැන්පත් වේ (Fe + CuSO₄ -> FeSO₄ + Cu).",
        examTip = "💡 හයිඩ්‍රජන්ට (H) ඉහළින් ඇති ලෝහ තනුක අම්ල සමග ප්‍රතික්‍රියා කර H₂ වායුව පිට කරයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_45",
        subject = "විද්‍යාව",
        toolNumber = 45,
        groupNumber = 5,
        titleSinhala = "යකඩ නිස්සාරණය සහ වායු ධාරා උදුන",
        titleEnglish = "Iron Extraction & Blast Furnace",
        category = "රසායන විද්‍යාව",
        icon = "🏭",
        quickSummary = "හේමටයිට් (Fe₂O₃), කෝක් (C) සහ හුණුගල් (CaCO₃) යොදා යකඩ ඔක්සිහරණය කිරීම.",
        formulaOrRule = "Fe₂O₃ + 3CO -> 2Fe + 3CO₂ | අපද්‍රව්‍ය ඉවත් කිරීම: CaO + SiO₂ -> CaSiO₃ (යකඩ මළ)",
        practicalApplication = "වායු ධාරා උදුනෙන් ලැබෙන ඌෂ්මක යකඩවල (Pig iron) කාබන් 4%ක් පමණ අඩංගු බැවින් බිඳෙනසුලුය.",
        examTip = "💡 මෙහි ප්‍රධාන ඔක්සිහාරකයා වන්නේ කාබන් මොනොක්සයිඩ් (CO) වායුවයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_46",
        subject = "විද්‍යාව",
        toolNumber = 46,
        groupNumber = 5,
        titleSinhala = "මලකඩ කෑම සහ ආරක්ෂණ ක්‍රම",
        titleEnglish = "Rusting of Iron & Prevention Methods",
        category = "රසායන විද්‍යාව",
        icon = "🛡️",
        quickSummary = "යකඩ මලකඩ කෑමට ඔක්සිජන් (O₂) සහ ජලය (H₂O) අනිවාර්යයෙන්ම අවශ්‍ය වේ.",
        formulaOrRule = "මලකඩ රසායනික සූත්‍රය: Fe₂O₃·xH₂O (ජලීය ෆෙරික් ඔක්සයිඩ්)",
        practicalApplication = "ආරක්ෂණ ක්‍රම: තීන්ත ආලේපය, ගැල්වනයිස් කිරීම (Zn ආලේපය), කැතෝඩික ආරක්ෂණය (Mg/Zn කුට්ටි සවි කිරීම).",
        examTip = "💡 ගැල්වනයිස් කළ යකඩවල සින්ක් ආවරණය සීරී ගියද යකඩට වඩා සින්ක් සක්‍රීය බැවින් සින්ක් කැපවී යකඩ ආරක්ෂා කරයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_47",
        subject = "විද්‍යාව",
        toolNumber = 47,
        groupNumber = 5,
        titleSinhala = "රසායනාගාරයේදී වායු පිළියෙල කිරීමේ මෙවලම",
        titleEnglish = "Lab Gas Preparation (O₂, H₂, CO₂)",
        category = "රසායන විද්‍යාව",
        icon = "💨",
        quickSummary = "O₂, H₂ සහ CO₂ වායු පිළියෙල කරන ප්‍රතික්‍රියක සහ එකතු කරගන්නා ආකාරය.",
        formulaOrRule = "O₂: 2H₂O₂ (MnO₂ උත්ප්‍රේරක) -> 2H₂O + O₂ | H₂: Zn + 2HCl -> ZnCl₂ + H₂ | CO₂: CaCO₃ + 2HCl -> CaCl₂ + H₂O + CO₂",
        practicalApplication = "O₂ සහ H₂ ජලයේ පහළට විස්ථාපනයෙන් එකතු කරගනී; CO₂ වාතයට වඩා බර බැවින් වාතයේ ඉහළට විස්ථාපනයෙන් එකතු කරගනී.",
        examTip = "💡 CO₂ වායුව හුණු දියර (Ca(OH)₂) තුළින් යැවූ විට කිරි පාට වේ (CaCO₃ සෑදීම නිසා); වැඩිදුරටත් යැවූ විට අවර්ණ වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_48",
        subject = "විද්‍යාව",
        toolNumber = 48,
        groupNumber = 5,
        titleSinhala = "අම්ල වැසි සහ පාරිසරික බලපෑම්",
        titleEnglish = "Acid Rain & Environmental Chemistry",
        category = "රසායන විද්‍යාව",
        icon = "🌧️",
        quickSummary = "SO₂ සහ NO₂ වායු වැසි ජලයේ දියවී සල්ෆියුරික් හා නයිට්‍රික් අම්ල සෑදීම (pH < 5.6).",
        formulaOrRule = "SO₂ + H₂O -> H₂SO₃ | 2SO₂ + O₂ + 2H₂O -> 2H₂SO₄",
        practicalApplication = "පිළිම සහ ගොඩනැගිලි ඛාදනය වීම (CaCO₃ + H₂SO₄ -> CaSO₄ + H₂O + CO₂), පස ආම්ලික වීම සහ ජලජ ජීවීන් මියයාම.",
        examTip = "💡 සාමාන්‍ය වැසි ජලයද CO₂ දියවීම නිසා මඳක් ආම්ලිකය (pH ≈ 5.6)."
      ),
      OlSubjectToolItem(
        id = "sci_tool_49",
        subject = "විද්‍යාව",
        toolNumber = 49,
        groupNumber = 5,
        titleSinhala = "ප්‍රකාශ රසායනික ප්‍රතික්‍රියා (ආලෝකය මත යැපෙන)",
        titleEnglish = "Photochemical Reactions Tool",
        category = "රසායන විද්‍යාව",
        icon = "📸",
        quickSummary = "ආලෝක ශක්තිය අවශෝෂණය කර සිදුවන රසායනික ප්‍රතික්‍රියා.",
        formulaOrRule = "2AgCl (සුදු) + ආලෝකය -> 2Ag (අළු/කළු) + Cl₂ | ප්‍රභාසංස්ලේෂණය",
        practicalApplication = "සාම්ප්‍රදායික ඡායාරූප ශිල්පයේදී රිදී හේලයිඩවල (AgBr) ආලෝක සංවේදීතාව යොදාගනී; රසායනාගාරයේදී AgNO₃ දුඹුරු බෝතල්වල අසුරන්නේ වියෝජනය වැළැක්වීමටයි.",
        examTip = "💡 හයිඩ්‍රජන් පෙරොක්සයිඩ් (H₂O₂) ද ආලෝකයෙන් වියෝජනය වන බැවින් අඳුරු බෝතල්වල අසුරයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_50",
        subject = "විද්‍යාව",
        toolNumber = 50,
        groupNumber = 5,
        titleSinhala = "ලවණ වර්ගීකරණය සහ ද්‍රාව්‍යතා නීති",
        titleEnglish = "Salts Classification & Solubility Rules",
        category = "රසායන විද්‍යාව",
        icon = "🧂",
        quickSummary = "සාමාන්‍ය ලවණ, අම්ල ලවණ, භස්මික ලවණ සහ ජලයේ දියවන/නොදියවන ලවණ.",
        formulaOrRule = "සියලුම සෝඩියම් (Na⁺), පොටෑසියම් (K⁺), ඇමෝනියම් (NH₄⁺) සහ නයිට්‍රේට (NO₃⁻) ලවණ ජලයේ ද්‍රාව්‍ය වේ.",
        practicalApplication = "අද්‍රාව්‍ය ලවණ: BaSO₄, AgCl, CaCO₃, PbSO₄ (අවක්ෂේප ලෙස සෑදේ).",
        examTip = "💡 සල්ෆේට අයන (SO₄²⁻) හඳුනා ගැනීමට BaCl₂ ද්‍රාවණයක් එක් කළ විට සුදු පැහැති BaSO₄ අවක්ෂේපයක් ලැබේ."
      ),

      // --- GROUP 6: කාබනික රසායනය සහ බහුඅවයවික (51-60) ---
      OlSubjectToolItem(
        id = "sci_tool_51",
        subject = "විද්‍යාව",
        toolNumber = 51,
        groupNumber = 6,
        titleSinhala = "හයිඩ්‍රොකාබන: ඇල්කේන සහ ඇල්කීන සංසන්දකය",
        titleEnglish = "Hydrocarbons: Alkanes vs Alkenes Comparator",
        category = "කාබනික රසායනය",
        icon = "⛽",
        quickSummary = "කාබන් සහ හයිඩ්‍රජන් පමණක් අඩංගු සංතෘප්ත (ඇල්කේන) සහ අසංතෘප්ත (ඇල්කීන) කාබනික සංයෝග.",
        formulaOrRule = "ඇල්කේන C_n H_{2n+2} (තනි බන්ධන) | ඇල්කීන C_n H_{2n} (ද්විත්ව බන්ධන C=C)",
        practicalApplication = "මීතේන් CH₄, ඊතේන් C₂H₆, එතීන් C₂H₄. බ්‍රෝමීන් ජලයේ දුඹුරු පැහැය අවර්ණ කරන්නේ අසංතෘප්ත ඇල්කීන මගිනි.",
        examTip = "💡 ද්‍රව පෙට්‍රෝලියම් වායුවේ (LPG) ප්‍රධාන සංඝටක වන්නේ ප්‍රොපේන් (C₃H₈) සහ බියුටේන් (C₄H₁₀) ය."
      ),
      OlSubjectToolItem(
        id = "sci_tool_52",
        subject = "විද්‍යාව",
        toolNumber = 52,
        groupNumber = 6,
        titleSinhala = "ඇල්කොහොල සහ එතනෝල් නිෂ්පාදනය",
        titleEnglish = "Alcohols & Ethanol Fermentation",
        category = "කාබනික රසායනය",
        icon = "🍷",
        quickSummary = "-OH ක්‍රියාකාරී කාණ්ඩය සහිත කාබනික සංයෝග සහ යීස්ට් මගින් පැසවීම.",
        formulaOrRule = "C₆H₁₂O₆ (ග්ලූකෝස්) + යීස්ට් (සයිමේස් එන්සයිමය) -> 2C₂H₅OH (එතනෝල්) + 2CO₂",
        practicalApplication = "එතනෝල් විෂබීජ නාශකයක් (Hand sanitizer), කාබනික ද්‍රාවකයක් සහ මධ්‍යසාර පාන නිෂ්පාදනයට යොදාගනී.",
        examTip = "💡 එතනෝල් පූර්ණ දහනයේදී CO₂ සහ H₂O නිල් පැහැ දැල්ලකින් සාදයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_53",
        subject = "විද්‍යාව",
        toolNumber = 53,
        groupNumber = 6,
        titleSinhala = "කාබොක්සිලික් අම්ල සහ එස්ටරීකරණය",
        titleEnglish = "Carboxylic Acids & Esterification",
        category = "කාබනික රසායනය",
        icon = "🍎",
        quickSummary = "-COOH කාණ්ඩය සහිත අම්ල (ඇසිටික් අම්ලය) සහ ඇල්කොහොල සමග ප්‍රතික්‍රියා කර සුවඳැති එස්ටර සෑදීම.",
        formulaOrRule = "කාබොක්සිලික් අම්ලය + ඇල්කොහොලය (සාන්ද්‍ර H₂SO₄) -> එස්ටරය + ජලය",
        practicalApplication = "එස්ටරවලට පලතුරු සුවඳක් ඇති බැවින් කෘතිම රසකාරක සහ සුවඳ විලවුන් සඳහා යොදාගනී.",
        examTip = "💡 විනාකිරිවල අඩංගු වන්නේ ඇසිටික්/එතනොයික් අම්ලය (CH₃COOH) 4-5% ද්‍රාවණයකි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_54",
        subject = "විද්‍යාව",
        toolNumber = 54,
        groupNumber = 6,
        titleSinhala = "ස්වාභාවික සහ කෘතිම බහුඅවයවික",
        titleEnglish = "Natural vs Synthetic Polymers",
        category = "කාබනික රසායනය",
        icon = "🧵",
        quickSummary = "ඒකඅවයවික (Monomers) විශාල සංඛ්‍යාවක් එකතු වී සෑදෙන දිගු දාම අණු.",
        formulaOrRule = "ස්වාභාවික: රබර් (අයිසොප්‍රීන්), සෙලියුලෝස්, ප්‍රෝටීන | කෘතිම: පොලිතීන් (එතීන්), PVC, නයිලෝන්",
        practicalApplication = "ස්වාභාවික රබර් සල්ෆර් සමග රත් කිරීමෙන් (වල්කනයිස් කිරීම) ප්‍රත්‍යාස්ථතාව සහ දෘඪතාව වැඩි කළ හැක.",
        examTip = "💡 තාපස්ථාපන ප්ලාස්ටික් රත් කළ විට මෘදු නොවේ (උදා: බේක්ලයිට්); තාපසැකසුම් ප්ලාස්ටික් රත් කර නැවත හැඩ ගැස්විය හැක (උදා: පොලිතීන්)."
      ),
      OlSubjectToolItem(
        id = "sci_tool_55",
        subject = "විද්‍යාව",
        toolNumber = 55,
        groupNumber = 6,
        titleSinhala = "සබන් සහ ඩිටර්ජන්ට් ක්‍රියාකාරිත්වය",
        titleEnglish = "Soap & Detergent Action Mechanism",
        category = "කාබනික රසායනය",
        icon = "🧼",
        quickSummary = "තෙල්/මේද සමග ජලභීතික (හයිඩ්‍රොකාබන් වලිගය) සහ ජලකාමී (අයනික හිස) කොටස් ක්‍රියාකිරීම.",
        formulaOrRule = "මේදය/තෙල් + NaOH -> සබන් (ග්ලිසරෝල් අතුරු ඵලයකි)",
        practicalApplication = "සබන්වල ජලභීතික වලිගය තෙල් කුණු බිඳිත්තට ඇතුළු වී, ජලකාමී හිස පිටත ජලයට යොමුවී මිසෙල (micelles) සාදා කුණු ඉවත් කරයි.",
        examTip = "💡 කිවුල් ජලයේදී (Hard water) සබන් පෙණ නොදමයි; නමුත් ඩිටර්ජන්ට් කිවුල් ජලයේදීත් හොඳින් පෙණ දමයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_56",
        subject = "විද්‍යාව",
        toolNumber = 56,
        groupNumber = 6,
        titleSinhala = "ජෛව ඉන්ධන සහ පරිසර හිතකාමී ශක්තිය",
        titleEnglish = "Bio-fuels & Green Energy Tool",
        category = "කාබනික රසායනය",
        icon = "🌱",
        quickSummary = "ජෛව ස්කන්ධයෙන් ලබාගන්නා බයෝගෑස් (මීතේන්), බයෝඩීසල් සහ බයෝඑතනෝල්.",
        formulaOrRule = "ගොම සහ ශාක අපද්‍රව්‍ය නිර්වායු බැක්ටීරියා මගින් පැසවීමෙන් ජීව වායුව (Biogas - CH₄ 60%) සෑදේ.",
        practicalApplication = "පොසිල ඉන්ධන වෙනුවට භාවිතයෙන් හරිතාගාර වායු විමෝචනය අවම කළ හැක.",
        examTip = "💡 බයෝගෑස් ජනකයේ පතුලේ ඉතිරිවන රොන්මඩ උසස් කාබනික පොහොරක් ලෙස යොදාගත හැක."
      ),
      OlSubjectToolItem(
        id = "sci_tool_57",
        subject = "විද්‍යාව",
        toolNumber = 57,
        groupNumber = 6,
        titleSinhala = "ආහාර සංරක්ෂණ රසායනය",
        titleEnglish = "Food Preservation Chemistry",
        category = "රසායන විද්‍යාව",
        icon = "🥫",
        quickSummary = "ක්ෂුද්‍රජීවී ක්‍රියාකාරිත්වය සහ එන්සයිම ක්‍රියා අඩපණ කර ආහාර කල්තබා ගැනීමේ ක්‍රම.",
        formulaOrRule = "ලුණු දැමීම & සීනි දැමීම -> බහිස්-ආස්‍රැතිය මගින් විජලනය | විනාකිරි -> අඩු pH අගය මගින් බැක්ටීරියා විනාශය",
        practicalApplication = "ජෑම් සෑදීමේදී 65% සීනි සාන්ද්‍රණය මගින් ක්ෂුද්‍රජීවී සෛලවල ජලය ඉවත් කරයි.",
        examTip = "💡 පාස්චරීකරණය යනු කිරි 72 °C ට තත්පර 15ක් රත් කර වහාම 10 °C ට අඩු උෂ්ණත්වයකට සිසිල් කිරීමයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_58",
        subject = "විද්‍යාව",
        toolNumber = 58,
        groupNumber = 6,
        titleSinhala = "පොසිල ඉන්ධන භාගික ආසවනය",
        titleEnglish = "Fractional Distillation of Crude Oil",
        category = "කාබනික රසායනය",
        icon = "🛢️",
        quickSummary = "තාපාංක වෙනස අනුව බොරතෙල් ප්‍රයෝජනවත් භාගවලට වෙන්කිරීම.",
        formulaOrRule = "ඉහළින් (අඩු තාපාංක): පෙට්‍රෝලියම් වායු, ගැසොලින්/පෙට්‍රල්, භූමිතෙල්, ඩීසල්, ලිහිසි තෙල්, තාර (පතුලේ)",
        practicalApplication = "ගුවන්යානා සඳහා භාවිත කරන්නේ පිරිසිදු කරන ලද භූමිතෙල් (Kerosene/Aviation fuel) භාගයයි.",
        examTip = "💡 භාගික ආසවන කුළුණේ ඉහළට යනවිට කාබන් දාමයේ දිග අඩු වන අතර තාපාංකයද අඩුවේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_59",
        subject = "විද්‍යාව",
        toolNumber = 59,
        groupNumber = 6,
        titleSinhala = "ප්ලාස්ටික් ප්‍රතිචක්‍රීකරණ සංකේත (1 සිට 7)",
        titleEnglish = "Plastic Recycling Identification Codes",
        category = "පාරිසරික විද්‍යාව",
        icon = "♻️",
        quickSummary = "PETE (1), HDPE (2), PVC (3), LDPE (4), PP (5), PS (6), OTHER (7).",
        formulaOrRule = "ප්ලාස්ටික් වර්ගය අනුව නැවත භාවිතය සහ ප්‍රතිචක්‍රීකරණ හැකියාව වර්ගීකරණය කිරීම.",
        practicalApplication = "පානීය ජල බෝතල් PETE (1) වලින් සාදනු ලබන අතර ඒවා නැවත නැවත භාවිතය සෞඛ්‍යයට අහිතකරය.",
        examTip = "💡 ආහාර ඇසිරීම සඳහා වඩාත් ආරක්ෂිත වන්නේ PP (5) සහ HDPE (2) ප්ලාස්ටික් වර්ගයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_60",
        subject = "විද්‍යාව",
        toolNumber = 60,
        groupNumber = 6,
        titleSinhala = "හරිත රසායන විද්‍යා මූලධර්ම",
        titleEnglish = "Green Chemistry Principles Tool",
        category = "රසායන විද්‍යාව",
        icon = "🌿",
        quickSummary = "පරිසර හානිය අවම වන ලෙස රසායනික ක්‍රියාවලි සැලසුම් කිරීමේ සංකල්පය.",
        formulaOrRule = "අපද්‍රව්‍ය වැළැක්වීම, පරමාණුක ආර්ථිකය, විෂ රහිත ද්‍රාවක, පුනර්ජනනීය අමුද්‍රව්‍ය භාවිතය.",
        practicalApplication = "CFC වායු වෙනුවට ඕසෝන් වියෝජනය නොකරන HFC වායු ශීතකරණ සඳහා යොදාගැනීම.",
        examTip = "💡 ඕසෝන් ස්ථරය ක්ෂය කරන ප්‍රධාන වායුව ක්ලෝරෝෆ්ලෝරෝකාබන් (CFC) ය."
      ),

      // --- GROUP 7: ජීවයේ ඒකකය සහ පටක (61-70) ---
      OlSubjectToolItem(
        id = "sci_tool_61",
        subject = "විද්‍යාව",
        toolNumber = 61,
        groupNumber = 7,
        titleSinhala = "ශාක සහ සත්ව සෛල සැසඳුම්කරු",
        titleEnglish = "Plant vs Animal Cell Comparative Tool",
        category = "ජීව විද්‍යාව",
        icon = "🔬",
        quickSummary = "ශාක සෛල හා සත්ව සෛලවල ඉන්ද්‍රියිකා සහ ව්‍යුහාත්මක වෙනස්කම්.",
        formulaOrRule = "ශාක සෛලවල පමණක්: සෙලියුලෝස් සෛල බිත්තිය, හරිතලව, විශාල මධ්‍ය රික්තකය | සත්ව සෛලවල: සෙන්ට්‍රියෝල",
        practicalApplication = "මයිටොකොන්ඩ්‍රියා දෙවර්ගයේම පවතී (සෛලීය ශ්වසනය මගින් ATP නිපදවීම).",
        examTip = "💡 සෛල බිත්තිය පූර්ණ පාරගම්‍ය වන අතර ප්ලාස්ම පටලය අර්ධ පාරගම්‍ය (වරණීය පාරගම්‍ය) වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_62",
        subject = "විද්‍යාව",
        toolNumber = 62,
        groupNumber = 7,
        titleSinhala = "සංයුක්ත ආලෝක අන්වීක්ෂ භාවිත මෙවලම",
        titleEnglish = "Compound Light Microscope Tool",
        category = "ජීව විද්‍යාව",
        icon = "🔬",
        quickSummary = "අක්ෂි කාචය, වස්තු කාච, රළු/සියුම් සීරුමාරු සහ විශාලනය ගණනය කිරීම.",
        formulaOrRule = "මුළු විශාලනය = අක්ෂි කාචයේ විශාලනය × වස්තු කාචයේ විශාලනය",
        practicalApplication = "10x අක්ෂි කාචයක් සහ 40x වස්තු කාචයක් යෙදූ විට මුළු විශාලනය = 10 × 40 = 400 ගුණයකි.",
        examTip = "💡 අධිබල කාච භාවිතයේදී රූපය පැහැදිලි කරගැනීමට භාවිත කළ යුත්තේ සියුම් සීරුමාරුව පමණි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_63",
        subject = "විද්‍යාව",
        toolNumber = 63,
        groupNumber = 7,
        titleSinhala = "අනුනන සෛල විභාජනය (Mitosis) අදියර",
        titleEnglish = "Mitosis Cell Division Stages",
        category = "ජීව විද්‍යාව",
        icon = "➗",
        quickSummary = "දේහ සෛල වර්ධනය හා ප්‍රතිස්ථාපනය සඳහා සිදුවන වර්ණදේහ සංඛ්‍යාව නොවෙනස්ව පවතින විභාජනය.",
        formulaOrRule = "පූර්ව කලාව -> මධ්‍ය කලාව (මැද පේළි ගැසීම) -> අප කලාව (වෙන්වීම) -> අන්ත කලාව",
        practicalApplication = "මව් සෛලයේ වර්ණදේහ 2n නම් සෑදෙන දුහිතෘ සෛල 2කම වර්ණදේහ ගණන 2n ම වේ.",
        examTip = "💡 මධ්‍ය කලාවේදී වර්ණදේහ සෛලයේ සමක තලයේ පේළි ගැසේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_64",
        subject = "විද්‍යාව",
        toolNumber = 64,
        groupNumber = 7,
        titleSinhala = "ඌනන සෛල විභාජනය (Meiosis) සහ ප්‍රවේණිය",
        titleEnglish = "Meiosis Cell Division & Gametogenesis",
        category = "ජීව විද්‍යාව",
        icon = "🧬",
        quickSummary = "ජන්මාණු (ශුක්‍රාණු/ඩිම්බ) සෑදීමේදී වර්ණදේහ සංඛ්‍යාව අඩක් (n) බවට පත්වන විභාජනය.",
        formulaOrRule = "2n මව් සෛලයකින් n වර්ණදේහ සහිත දුහිතෘ සෛල 4ක් සෑදේ; හරස්වීම නිසා ප්‍රවේණික විවිධත්වය ඇතිවේ.",
        practicalApplication = "මිනිසාගේ දේහ සෛලයක වර්ණදේහ 46ක් (23 යුගල්) ඇති අතර ජන්මාණුවල ඇත්තේ 23කි.",
        examTip = "💡 පරම්පරාවෙන් පරම්පරාවට විශේෂයේ වර්ණදේහ සංඛ්‍යාව නියතව පවත්වා ගැනීමට ඌනන විභාජනය අත්‍යවශ්‍ය වේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_65",
        subject = "විද්‍යාව",
        toolNumber = 65,
        groupNumber = 7,
        titleSinhala = "ශාක පටක: සනාල පටක (දැවය සහ බස්ටය)",
        titleEnglish = "Plant Vascular Tissues: Xylem & Phloem",
        category = "ජීව විද්‍යාව",
        icon = "🪵",
        quickSummary = "දැවය මගින් ජලය හා ඛණිජ ලවණද, බස්ටය මගින් නිපදවූ ආහාරද පරිවහනය කරයි.",
        formulaOrRule = "දැවය (Xylem): වාහිනී, වාහිකා (මළ සෛල, ලිග්නින් සහිතයි) | බස්ටය (Phloem): පෙනේර නළ, සහචර සෛල (සජීවී)",
        practicalApplication = "කඳ වටා පොත්ත (බස්ටය සහිත) මුදුවක් ලෙස ඉවත් කළ විට මුල් වෙත ආහාර ගමන් නොකර මුල් මියයයි.",
        examTip = "💡 දැවය ඔස්සේ පරිවහනය සිදුවන්නේ පහළ සිට ඉහළට පමණි; බස්ටය ඔස්සේ ඉහළට හා පහළට දෙපසටම සිදුවේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_66",
        subject = "විද්‍යාව",
        toolNumber = 66,
        groupNumber = 7,
        titleSinhala = "සරල ශාක පටක (මෘදුක, ස්ථූලකෝණ, දෘඪකෝණ)",
        titleEnglish = "Simple Plant Tissues (Parenchyma, Collenchyma, Sclerenchyma)",
        category = "ජීව විද්‍යාව",
        icon = "🍃",
        quickSummary = "මෘදුක (ආහාර සංචිතය), ස්ථූලකෝණ (නම්‍යශීලී යාන්ත්‍රික ශක්තිය), දෘඪකෝණ (දැඩි යාන්ත්‍රික ශක්තිය).",
        formulaOrRule = "දෘඪකෝණ පටකය මළ පටකයකි (ලිග්නින් තැන්පත්ව ඇත, උදා: පොල්කටු, කෙඳි).",
        practicalApplication = "පත්‍ර නටුවල සහ ළපටි කඳුවල ස්ථූලකෝණ පටක පිහිටා සුළඟට නොකැඩී නැමීමට ඉඩදෙයි.",
        examTip = "💡 හරිතලව අඩංගු මෘදුක පටක 'හරිතක' ලෙස හඳුන්වන අතර ප්‍රභාසංස්ලේෂණය සිදුකරයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_67",
        subject = "විද්‍යාව",
        toolNumber = 67,
        groupNumber = 7,
        titleSinhala = "සත්ව පටක: අපිච්ඡද හා සම්බන්ධක පටක",
        titleEnglish = "Animal Epithelial & Connective Tissues",
        category = "ජීව විද්‍යාව",
        icon = "🩸",
        quickSummary = "දේහ පෘෂ්ඨ ආවරණය කරන අපිච්ඡද පටක සහ අවයව එකිනෙක සම්බන්ධ කරන සම්බන්ධක පටක (රුධිරය, අස්ථි, කාටිලේජ).",
        formulaOrRule = "රුධිරය යනු ප්ලාස්මාව නැමැති ද්‍රව පූරකයක සෛල ගිලී ඇති ද්‍රව සම්බන්ධක පටකයකි.",
        practicalApplication = "ශ්වාසනාලයේ ඇති පක්ෂ්මධර අපිච්ඡදය දූවිලි හා ක්ෂුද්‍රජීවීන් ඉවතට තල්ලු කිරීමට උපකාරී වේ.",
        examTip = "💡 රතු රුධිර සෛලවල න්‍යෂ්ටියක් නොමැති අතර හිමොග්ලොබින් මගින් ඔක්සිජන් පරිවහනය කරයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_68",
        subject = "විද්‍යාව",
        toolNumber = 68,
        groupNumber = 7,
        titleSinhala = "පේශි පටක වර්ගීකරණය (සැකිලි, සිනිඳු, කෘත්)",
        titleEnglish = "Muscle Tissues (Skeletal, Smooth, Cardiac)",
        category = "ජීව විද්‍යාව",
        icon = "💪",
        quickSummary = "සැකිලි පේශි (ඓච්ඡික, විලේඛිත), සිනිඳු පේශි (අනෛච්ඡික, අන්ත්‍ර/රුධිර නාල), කෘත් පේශි (අනෛච්ඡික, හෘදය, විඩාවට පත් නොවේ).",
        formulaOrRule = "හෘද පේශි ශාඛනය වී අන්තර්ස්ථාපිත තැටි සහිතව පිහිටයි; ජීවිත කාලය පුරාම නොනැවතී රිද්මයානුකූලව සංකෝචනය වේ.",
        practicalApplication = "ආහාර මාර්ගයේ ක්‍රමාකුංචන චලන සිදුකරන්නේ සිනිඳු පේශි මගිනි.",
        examTip = "💡 සැකිලි පේශි ඉක්මනින් විඩාවට පත්වේ; ලැක්ටික් අම්ලය තැන්පත් වීම ඊට හේතුවයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_69",
        subject = "විද්‍යාව",
        toolNumber = 69,
        groupNumber = 7,
        titleSinhala = "ස්නායු පටකය සහ නියුරෝන ව්‍යුහය",
        titleEnglish = "Nervous Tissue & Neuron Structure",
        category = "ජීව විද්‍යාව",
        icon = "🧠",
        quickSummary = "සෛල දේහය, ඩෙන්ඩ්‍රයිට සහ අක්සනය සහිත ආවේග සන්නයනය කරන මූලික ඒකකය.",
        formulaOrRule = "ආවේග ගමන් මග: ඩෙන්ඩ්‍රයිට -> සෛල දේහය -> අක්සනය -> අක්සන අග්‍රස්ථ -> උපාගමය",
        practicalApplication = "මයලින් කොපුව මගින් ආවේග සන්නයන වේගය වැඩි කරන අතර පරිවරණයක් සපයයි.",
        examTip = "💡 උපාගමයකදී (Synapse) ආවේගය ගමන් කරන්නේ රසායනික සම්ප්‍රේෂක (උදා: ඇසිටයිල්කෝලීන්) මගිනි; එය ඒකදිශානතියකි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_70",
        subject = "විද්‍යාව",
        toolNumber = 70,
        groupNumber = 7,
        titleSinhala = "ජෛව අණු: කාබෝහයිඩ්‍රේට, ලිපිඩ, ප්‍රෝටීන පරීක්ෂා",
        titleEnglish = "Biomolecules & Food Tests (Benedict, Biuret, Iodine)",
        category = "ජීව විද්‍යාව",
        icon = "🍞",
        quickSummary = "පිෂ්ටය (අයඩීන් - නිල්/කළු), ඔක්සිහාරක සීනි (බෙනඩික්ට් - ගඩොල් රතු), ප්‍රෝටීන් (බයියුරෙට් - දම්), ලිපිඩ (සුඩාන් III).",
        formulaOrRule = "කාබෝහයිඩ්‍රේට (C,H,O 1:2:1) | ප්‍රෝටීන (C,H,O,N,S) | ලිපිඩ (C,H,O)",
        practicalApplication = "ග්ලූකෝස් පරීක්ෂාවේදී බෙනඩික්ට් ද්‍රාවණය දමා ජල තාපකයක රත් කිරීම අනිවාර්ය වේ.",
        examTip = "💡 සුක්‍රෝස් යනු ඔක්සිහාරක නොවන සීනි වර්ගයකි; සෘජුවම බෙනඩික්ට් සමග රතු පාට නොදෙයි."
      ),

      // --- GROUP 8: මානව කායික විද්‍යාව (71-80) ---
      OlSubjectToolItem(
        id = "sci_tool_71",
        subject = "විද්‍යාව",
        toolNumber = 71,
        groupNumber = 8,
        titleSinhala = "මානව ජීර්ණ පද්ධතිය සහ එන්සයිම සටහන",
        titleEnglish = "Human Digestive System & Enzymes Map",
        category = "මානව කායික විද්‍යාව",
        icon = "🍔",
        quickSummary = "මුඛය (ඇමයිලේස්), ආමාශය (පෙප්සින් - ආම්ලික), ග්‍රහණිය/කුඩා අන්ත්‍රය (ට්‍රිප්සින්, ලයිපේස් - භස්මික).",
        formulaOrRule = "පෙප්සින්: ප්‍රෝටීන් -> පොලිපෙප්ටයිඩ | ලයිපේස්: ලිපිඩ -> මේද අම්ල + ග්ලිසරෝල් | ඇමයිලේස්: පිෂ්ටය -> මෝල්ටෝස්",
        practicalApplication = "ආමාශයික යුෂයේ අඩංගු තනුක HCl මගින් එන්සයිමවලට අවශ්‍ය ආම්ලික මාධ්‍යය සපයන අතර ආහාර සමග එන බැක්ටීරියා විනාශ කරයි.",
        examTip = "💡 පිතේ (Bile) කිසිදු එන්සයිමයක් අඩංගු නොවේ; එය මේදය කිරිදැඩි කිරීම (Emulsification) පමණක් සිදුකරයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_72",
        subject = "විද්‍යාව",
        toolNumber = 72,
        groupNumber = 8,
        titleSinhala = "ශ්වසන පද්ධතිය සහ වායු හුවමාරුව",
        titleEnglish = "Respiratory System & Alveoli Gas Exchange",
        category = "මානව කායික විද්‍යාව",
        icon = "🫁",
        quickSummary = "පෙනහැල්ලේ කූප සහ රුධිර කේෂනාලිකා අතර විසරණය මගින් O₂ සහ CO₂ හුවමාරුව.",
        formulaOrRule = "සෛලීය වායුගෝලීය ශ්වසනය: C₆H₁₂O₆ + 6O₂ -> 6CO₂ + 6H₂O + 38 ATP ශක්තිය",
        practicalApplication = "කූප බිත්ති තනි සෛල ස්ථරයකින් යුක්ත වීම, තෙත් වීම සහ මතුපිට වර්ගඵලය විශාල වීම කාර්යක්ෂම වායු හුවමාරුවට උපකාරී වේ.",
        examTip = "💡 උරස් කුහරයේ පරිමාව වැඩිවන විට පෙනහළු තුළ පීඩනය අඩුවී වාතය ඇතුළට ඇදගනී (ආශ්වාසය)."
      ),
      OlSubjectToolItem(
        id = "sci_tool_73",
        subject = "විද්‍යාව",
        toolNumber = 73,
        groupNumber = 8,
        titleSinhala = "රුධිර සංසරණ පද්ධතිය සහ හෘද චක්‍රය",
        titleEnglish = "Circulatory System & Heart Anatomy",
        category = "මානව කායික විද්‍යාව",
        icon = "❤️",
        quickSummary = "ද්විත්ව සංසරණය: පුප්ඵුසීය සංසරණය (හෘදය-පෙනහළු) සහ දේහික සංසරණය (හෘදය-මුළු දේහය).",
        formulaOrRule = "රුධිර පීඩනය: සිස්ටෝලික / ඩයස්ටෝලික = 120 / 80 mmHg (සාමාන්‍ය නිරෝගී පුද්ගලයෙකුගේ)",
        practicalApplication = "මහා ධමනිය ඔක්සිජනීකෘත රුධිරය මුළු සිරුරට ගෙනයන අතර පුප්ඵුසීය ධමනිය පමණක් ඔක්සිජන් විරහිත රුධිරය පෙනහළු වෙත ගෙනියයි.",
        examTip = "💡 වම් කෝෂිකාවේ බිත්තිය දකුණු කෝෂිකාවට වඩා ඝනකම් වන්නේ මුළු සිරුර පුරා වැඩි පීඩනයකින් රුධිරය පොම්ප කළ යුතු බැවිනි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_74",
        subject = "විද්‍යාව",
        toolNumber = 74,
        groupNumber = 8,
        titleSinhala = "රුධිර ඝන සහ රුධිර පාරවිලයන මෙවලම",
        titleEnglish = "ABO & Rh Blood Group Transfusion Tool",
        category = "මානව කායික විද්‍යාව",
        icon = "🩸",
        quickSummary = "A, B, AB, O රුධිර ඝන, ප්‍රතිදේහජනක (Antigen) සහ ප්‍රතිදේහ (Antibody) ගැලපීම.",
        formulaOrRule = "O රුධිර ඝනය = සර්වත්‍ර දායකයා (Universal donor) | AB රුධිර ඝනය = සර්වත්‍ර ප්‍රතිග්‍රාහකයා (Universal recipient)",
        practicalApplication = "Rh ධන රුධිරය ඇත්තේ D ප්‍රතිදේහජනකය ඇති අයටයි. Rh සෘණ මවකට Rh ධන දරුවෙකු ලැබීමේදී Rh අනුකූලතා ගැටලු ඇතිවිය හැක.",
        examTip = "💡 O රුධිර සෛලවල A හෝ B ප්‍රතිදේහජනක නොමැති බැවින් ඕනෑම අයෙකුට ලබාදිය හැක."
      ),
      OlSubjectToolItem(
        id = "sci_tool_75",
        subject = "විද්‍යාව",
        toolNumber = 75,
        groupNumber = 8,
        titleSinhala = "මානව වෘක්කය සහ නෙෆ්‍රෝනයේ මුත්‍ර සෑදීම",
        titleEnglish = "Kidney Nephron & Urine Formation",
        category = "මානව කායික විද්‍යාව",
        icon = "🫘",
        quickSummary = "අතිපෙරීම (ග්ලෝමරුලස), වරණීය ප්‍රතිශෝෂණය (සමීපස්ථ සංවලිත නාලිකාව) සහ ශ්‍රාවය.",
        formulaOrRule = "ප්‍රධාන බහිස්‍රාවී ඵලය: යූරියා (අක්මාවේදී ඇමයිනෝ අම්ල නිර්ඇමයිනීකරණයෙන් සෑදේ).",
        practicalApplication = "නිරෝගී පුද්ගලයෙකුගේ මුත්‍රාවල ග්ලූකෝස් අඩංගු නොවේ; සියලුම ග්ලූකෝස් නෙෆ්‍රෝනයේදී නැවත රුධිරයට ප්‍රතිශෝෂණය වේ.",
        examTip = "💡 මුත්‍රාවල ග්ලූකෝස් තිබීම මධුමේහය (දියවැඩියාව) රෝගී තත්ත්වයේ ලක්ෂණයකි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_76",
        subject = "විද්‍යාව",
        toolNumber = 76,
        groupNumber = 8,
        titleSinhala = "ස්නායු ආවේග සහ ප්‍රතිචාර චාපය (Reflex Arc)",
        titleEnglish = "Reflex Arc & Involuntary Actions Tool",
        category = "මානව කායික විද්‍යාව",
        icon = "⚡",
        quickSummary = "හදිසි උත්තේජනයකට මොළයේ මැදිහත්වීමකින් තොරව සුෂුම්නාව හරහා ක්ෂණිකව සිදුවන අනෛච්ඡික ප්‍රතිචාරය.",
        formulaOrRule = "ග්‍රාහකය -> සංවේදක නියුරෝනය -> සුෂුම්නාව (අන්තර්වාර නියුරෝනය) -> චාලක නියුරෝනය -> කාර්යාලකය (පේශිය)",
        practicalApplication = "උණුසුම් වස්තුවක අත ගැටුණු වහාම අත ඉවතට ගැනීම ප්‍රතීක ක්‍රියාවකට උදාහරණයකි.",
        examTip = "💡 ප්‍රතීක ක්‍රියාවල වැදගත්කම වන්නේ දේහයට සිදුවන හානිය අවම කර ආරක්ෂා කිරීමයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_77",
        subject = "විද්‍යාව",
        toolNumber = 77,
        groupNumber = 8,
        titleSinhala = "අන්තරාසර්ග පද්ධතිය සහ හෝමෝන",
        titleEnglish = "Endocrine Glands & Hormones Directory",
        category = "මානව කායික විද්‍යාව",
        icon = "🧬",
        quickSummary = "නාල රහිත ග්‍රන්ථි මගින් රුධිරයට සෘජුවම ශ්‍රාවය වන රසායනික පණිවිඩකරුවන්.",
        formulaOrRule = "පිටියුටරිය (වර්ධක හෝමෝනය) | තයිරොයිඩ් (තයිරොක්සින්) | අග්න්‍යාශය (ඉන්සියුලින්, ග්ලුකගොන්) | අධිවෘක්ක (ඇඩ්‍රිනලින්)",
        practicalApplication = "රුධිරයේ ග්ලූකෝස් මට්ටම වැඩිවූ විට ඉන්සියුලින් මගින් ග්ලූකෝස් ග්ලයිකොජන් බවට පත්කර අක්මාවේ තැන්පත් කරයි.",
        examTip = "💡 හදිසි අවස්ථාවලදී සටනට හෝ පලායාමට (Fight or Flight) සිරුර සූදානම් කරන්නේ ඇඩ්‍රිනලින් හෝමෝනයයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_78",
        subject = "විද්‍යාව",
        toolNumber = 78,
        groupNumber = 8,
        titleSinhala = "මානව අක්ෂිය සහ දෘෂ්ටි ක්‍රියාවලිය",
        titleEnglish = "Human Eye Vision & Photoreception",
        category = "මානව කායික විද්‍යාව",
        icon = "👁️",
        quickSummary = "දෘෂ්ටිවිතානයේ දණ්ඩ සෛල (අඩු ආලෝකයට සංවේදී) සහ කේතු සෛල (වර්ණ ආලෝකයට සංවේදී).",
        formulaOrRule = "ප්‍රතිබිම්බ ලක්ෂණ: තාත්වික, යටිකුරු සහ වස්තුවට වඩා කුඩාය.",
        practicalApplication = "කහ බින්දුවේ (Fovea) කේතු සෛල බහුල බැවින් වඩාත් තියුණු දෘෂ්ටියක් ලබාදෙයි.",
        examTip = "💡 විටමින් A ඌනතාවය නිසා රාත්‍රී අන්ධතාවය (Night blindness) ඇතිවේ; රොඩොප්සින් වර්ණකය නිපදවීමට විටමින් A අවශ්‍යයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_79",
        subject = "විද්‍යාව",
        toolNumber = 79,
        groupNumber = 8,
        titleSinhala = "මානව කණ සහ සමතුලිතතාවය",
        titleEnglish = "Human Ear Structure & Body Balance",
        category = "මානව කායික විද්‍යාව",
        icon = "👂",
        quickSummary = "ශ්‍රවණය සඳහා කර්ණශංඛයද (Cochlea), දේහ සමතුලිතතාවය සඳහා අඩවෘත්තාකාර නාලද දායක වේ.",
        formulaOrRule = "කර්ණපටහ පටලය -> කර්ණ අස්ථිකා (මිටිය, කිණිහිර, අඩිය) -> අණ්ඩාකාර කවුළුව -> කර්ණශංඛ තරලය -> කෝටි අවයවය",
        practicalApplication = "යුස්ටේකීය නාලය මගින් කර්ණපටහ පටලයේ දෙපස වායු පීඩනය සමාන කරයි.",
        examTip = "💡 අඩිය අස්ථිකාව (Stapes) මිනිස් සිරුරේ ඇති කුඩාම අස්ථියයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_80",
        subject = "විද්‍යාව",
        toolNumber = 80,
        groupNumber = 8,
        titleSinhala = "මානව ප්‍රජනන පද්ධතිය සහ ඔසප් චක්‍රය",
        titleEnglish = "Human Reproduction & Menstrual Cycle",
        category = "මානව කායික විද්‍යාව",
        icon = "👶",
        quickSummary = "ශුක්‍රාණු හා ඩිම්බ නිපදවීම, සංසේචනය (පැවැලෝපීය නාලයේදී) සහ හෝමෝන පාලනය (ඊස්ට්‍රජන්, ප්‍රොජෙස්ටරෝන්).",
        formulaOrRule = "ඔසප් චක්‍රයේ 14 වන දින පමණ ඩිම්බ මෝචනය (Ovulation) සිදුවේ.",
        practicalApplication = "සංසේචනය වූ යුක්තානුව ගර්භාෂ බිත්තියේ තැන්පත් වීම 'රෝපණය' නම් වේ.",
        examTip = "💡 වැදෑමහ (Planta) මගින් කලලයට පෝෂණය, ඔක්සිජන් ලබාදෙන අතර අපද්‍රව්‍ය මවගේ රුධිරයට බැහැර කරයි; මවගේ හා කලලයේ රුධිරය සෘජුව මිශ්‍ර නොවේ."
      ),

      // --- GROUP 9: ශාක කායික විද්‍යාව සහ ප්‍රවේණිය (81-90) ---
      OlSubjectToolItem(
        id = "sci_tool_81",
        subject = "විද්‍යාව",
        toolNumber = 81,
        groupNumber = 9,
        titleSinhala = "ප්‍රභාසංස්ලේෂණය: ආලෝක සහ අඳුරු ප්‍රතික්‍රියා",
        titleEnglish = "Photosynthesis: Light & Dark Reactions",
        category = "ශාක කායික විද්‍යාව",
        icon = "☀️",
        quickSummary = "හරිතලව තුළ ආලෝක ශක්තිය රසායනික ශක්තිය බවට පත්කර ග්ලූකෝස් සංස්ලේෂණය කිරීම.",
        formulaOrRule = "6CO₂ + 6H₂O (ආලෝකය/හරිතප්‍රද) -> C₆H₁₂O₆ + 6O₂",
        practicalApplication = "ආලෝක ප්‍රතික්‍රියාව තයිලකොයිඩ පටලවල සිදුවන අතර ජලය ප්‍රකාශ වියෝජනයෙන් O₂ පිටවේ; අඳුරු ප්‍රතික්‍රියාව පූරකයේදී (Stroma) සිදුවේ.",
        examTip = "💡 ප්‍රභාසංස්ලේෂණයේදී පිටවන ඔක්සිජන් ලැබෙන්නේ ජල අණුව (H₂O) බිඳවැටීමෙනි; කාබන් ඩයොක්සයිඩ් වලින් නොවේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_82",
        subject = "විද්‍යාව",
        toolNumber = 82,
        groupNumber = 9,
        titleSinhala = "උත්ස්වේදනය සහ පොටෝමීටර භාවිතය",
        titleEnglish = "Transpiration & Potometer Tool",
        category = "ශාක කායික විද්‍යාව",
        icon = "💧",
        quickSummary = "ශාකයේ පත්‍රවල ඇති පත්‍ර රන්ද්‍ර හරහා ජල වාෂ්ප ලෙස ජලය වායුගෝලයට පිටවීම.",
        formulaOrRule = "උත්ස්වේදන සීඝ්‍රතාව වැඩිවන සාධක: ආලෝක තීව්‍රතාව ↑, උෂ්ණත්වය ↑, සුළං වේගය ↑ | ආර්ද්‍රතාව වැඩිවන විට උත්ස්වේදනය ↓",
        practicalApplication = "පොටෝමීටරයක් මගින් මනින්නේ ශාකය ජලය උරාගන්නා සීඝ්‍රතාවයයි (එය උත්ස්වේදන සීඝ්‍රතාවයට ආසන්න වශයෙන් සමාන වේ).",
        examTip = "💡 උත්ස්වේදන වැයම මගින් ශාකයේ මුදුනට ජලය සහ ඛණිජ ලවණ ඉහළට ඇදගැනීමේ උත්ස්වේදන ආතතිය ඇතිකරයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_83",
        subject = "විද්‍යාව",
        toolNumber = 83,
        groupNumber = 9,
        titleSinhala = "ආස්‍රැතිය සහ ශාක සෛලවල ශූනතාව",
        titleEnglish = "Osmosis & Plant Cell Turgidity",
        category = "ශාක කායික විද්‍යාව",
        icon = "🥒",
        quickSummary = "වරණීය පාරගම්‍ය පටලයක් හරහා ජල අභිභවය වැඩි ස්ථානයක සිට අඩු ස්ථානයට ජල අණු විසරණය වීම.",
        formulaOrRule = "අවසාන්ද්‍ර ද්‍රාවණයක: ජලය ඇතුළු වී ශූන වේ (Turgid) | අධිසාන්ද්‍ර ද්‍රාවණයක: ජලය පිටවී ප්ලාස්මොලිසිස් (Plasmolysis) වේ",
        practicalApplication = "මැලවුණු එළවළු ජලයේ දැමූ විට ශූනතාව ලබාගෙන නැවුම් වේ; ලුණු දැමූ පිපිඤ්ඤා කැබලිවලින් ජලය පිටවේ.",
        examTip = "💡 සත්ව සෛලවලට සෛල බිත්තියක් නොමැති බැවින් අවසාන්ද්‍ර ද්‍රාවණයක තැබූ විට ජලය උරා පිපිරී යයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_84",
        subject = "විද්‍යාව",
        toolNumber = 84,
        groupNumber = 9,
        titleSinhala = "ශාක හෝමෝන (ඔක්සින්, ගිබරලින්, එතිලීන්)",
        titleEnglish = "Plant Growth Regulators / Hormones",
        category = "ශාක කායික විද්‍යාව",
        icon = "🌱",
        quickSummary = "ශාක වර්ධනය, බීජ ප්‍රරෝහණය සහ ඵල ඉදීම පාලනය කරන රසායනික ද්‍රව්‍ය.",
        formulaOrRule = "ඔක්සින්: අග්‍රස්ථ ප්‍රමුඛතාවය සහ ප්‍රකාශාවර්තනය | ගිබරලින්: බීජ ප්‍රරෝහණය | එතිලීන් (වායුවක්): පලතුරු ඉදවීම",
        practicalApplication = "කෙසෙල්, අඹ ඉදවීම කෘතිමව වේගවත් කිරීමට එතෆෝන්/එතිලීන් වායුව භාවිත කරයි.",
        examTip = "💡 ඔක්සින් ආලෝකය නොවැටෙන අඳුරු පැත්තට සංක්‍රමණය වන බැවින් එම පැත්තේ සෛල දිගින් වැඩිවී කඳ ආලෝකය දෙසට නැමේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_85",
        subject = "විද්‍යාව",
        toolNumber = 85,
        groupNumber = 9,
        titleSinhala = "මෙන්ඩල්ගේ ප්‍රවේණි නියම සහ පනට් කොටුව",
        titleEnglish = "Mendel's Laws & Punnett Square Solver",
        category = "ප්‍රවේණි විද්‍යාව",
        icon = "🧬",
        quickSummary = "විසංයෝජන නියමය සහ ස්වාධීන ව්‍යූහන නියමය: ප්‍රමුඛ සහ නිලීන ලක්ෂණ උරුම වීම.",
        formulaOrRule = "ඒකමුහුම් අනුපාතය (Tt × Tt): ප්‍රවේණිරූප 1 : 2 : 1 (TT:Tt:tt) | පෙනුමරූප 3 : 1 (උස : මිටි)",
        practicalApplication = "ප්‍රමුඛ ජානය (T) ඇති විට නිලීන ජානයේ (t) ප්‍රකාශනය යටපත් වේ.",
        examTip = "💡 විභාගයේදී පනට් කොටුවක් (Punnett square) ඇඳ ජන්මාණු සහ ප්‍රවේණිරූප පෙන්වීමෙන් සම්පූර්ණ ලකුණු ලබාගත හැක."
      ),
      OlSubjectToolItem(
        id = "sci_tool_86",
        subject = "විද්‍යාව",
        toolNumber = 86,
        groupNumber = 9,
        titleSinhala = "ලිංග නිර්ණය සහ ලිංග ප්‍රතිබද්ධ ප්‍රවේණිය",
        titleEnglish = "Sex Determination & Sex-Linked Inheritance",
        category = "ප්‍රවේණි විද්‍යාව",
        icon = "🚻",
        quickSummary = "මිනිසාගේ ලිංග නිර්ණය (XX - ස්ත්‍රී, XY - පුරුෂ) සහ X වර්ණදේහය මත පිහිටි ජාන නිසා ඇතිවන රෝග.",
        formulaOrRule = "දරුවාගේ ලිංගය තීරණය කරන්නේ පියාගෙන් ලැබෙන ශුක්‍රාණුවේ ඇති X හෝ Y වර්ණදේහය මගිනි.",
        practicalApplication = "හීමොෆීලියාව සහ රතු-කොළ වර්ණ අන්ධතාවය X-ප්‍රතිබද්ධ නිලීන රෝග වන අතර පිරිමින්ට වැළඳීමේ සම්භාවිතාව වැඩිය.",
        examTip = "💡 පිරිමියෙකුට X වර්ණදේහය උරුම වන්නේ මවගෙන් පමණි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_87",
        subject = "විද්‍යාව",
        toolNumber = 87,
        groupNumber = 9,
        titleSinhala = "DNA අණුවේ ව්‍යුහය සහ ද්විත්ව හෙලික්සය",
        titleEnglish = "DNA Molecular Structure & Double Helix",
        category = "ප්‍රවේණි විද්‍යාව",
        icon = "🧬",
        quickSummary = "වොට්සන් සහ ක්‍රික් ඉදිරිපත් කළ නියුක්ලියෝටයිඩ දාම දෙකකින් යුත් DNA ආකෘතිය.",
        formulaOrRule = "නයිට්‍රජනීය භස්ම යුගලනය: ඇඩිනින් (A) = තයිමින් (T) [ද්විත්ව හයිඩ්‍රජන් බන්ධන] | ගුවනින් (G) ≡ සයිටොසීන් (C) [ත්‍රිත්ව]",
        practicalApplication = "නියුක්ලියෝටයිඩයක් සෑදී ඇත්තේ ඩියොක්සිරයිබෝස් සීනි, පොස්පේට් කාණ්ඩයක් සහ නයිට්‍රජනීය භස්මයකිනි.",
        examTip = "💡 DNA වල ඇති ජානමය තොරතුරු ප්‍රෝටීන් සංස්ලේෂණයට මගපෙන්වයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_88",
        subject = "විද්‍යාව",
        toolNumber = 88,
        groupNumber = 9,
        titleSinhala = "ශාක ප්‍රජනනය: පුෂ්පයක ව්‍යුහය සහ පරාගනය",
        titleEnglish = "Flower Structure & Pollination Mechanisms",
        category = "ශාක කායික විද්‍යාව",
        icon = "🌸",
        quickSummary = "කලංකය, ජායාංගය (ඩිම්බ කෝෂය), පුමංගය (පරාගධානිය) සහ ස්වපරාගනය/පරපරාගනය.",
        formulaOrRule = "සුළඟින් පරාගනය වන මල්: කුඩා, වර්ණ රහිත, පරාග විශාල සංඛ්‍යාවක් නිපදවයි | කෘමීන්ගෙන්: විශාල, වර්ණවත්, මධු සහ සුවඳ සහිතයි",
        practicalApplication = "සංසේචනයෙන් පසු ඩිම්බ කෝෂය ගෙඩියක් බවටද, ඩිම්බ බීජ බවටද පත්වේ.",
        examTip = "💡 පරපරාගනය මගින් නව ප්‍රවේණික විවිධත්වයක් සහිත ශක්තිමත් ශාක බිහිවේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_89",
        subject = "විද්‍යාව",
        toolNumber = 89,
        groupNumber = 9,
        titleSinhala = "වර්ඩක ප්‍රචාරණය සහ කෘතිම ක්‍රම",
        titleEnglish = "Vegetative Propagation & Grafting Tool",
        category = "ශාක කායික විද්‍යාව",
        icon = "🪴",
        quickSummary = "බීජ රහිතව මුල්, කඳන්, පත්‍ර මගින් නව ශාක බිහිකිරීම (අතු බැඳීම, බද්ධ කිරීම, පටක රෝපණය).",
        formulaOrRule = "අංකුර බද්ධය: ග්‍රාහක ශාකයේ ලපටි පොත්ත කපා අවශ්‍ය ප්‍රභේදයේ අංකුරයක් තබා බැඳීම.",
        practicalApplication = "වාසි: මව් ශාකයේ ගුණ එලෙසම ලැබීම, ඉක්මනින් ඵලදැරීම. අවාසි: ප්‍රවේණික විවිධත්වයක් නොමැති වීම නිසා රෝගවලට ගොදුරුවීමේ අවදානම.",
        examTip = "💡 පටක රෝපණය (Tissue culture) මගින් රෝගවලින් තොර ශාක විශාල ප්‍රමාණයක් කෙටි කලකින් නිපදවිය හැක."
      ),
      OlSubjectToolItem(
        id = "sci_tool_90",
        subject = "විද්‍යාව",
        toolNumber = 90,
        groupNumber = 9,
        titleSinhala = "විකෘති සහ ජාන විකෘතිතා රෝග",
        titleEnglish = "Mutations & Genetic Disorders",
        category = "ප්‍රවේණි විද්‍යාව",
        icon = "☣️",
        quickSummary = "DNA අණුවේ හෝ වර්ණදේහ ව්‍යුහයේ/සංඛ්‍යාවේ හදිසියේ සිදුවන ස්ථිර වෙනස්වීම්.",
        formulaOrRule = "ඩවුන් සින්ඩ්‍රෝමය: 21 වන වර්ණදේහයේ අතිරේක පිටපතක් තිබීම (වර්ණදේහ 47ක් වීම - 2n+1).",
        practicalApplication = "විකෘතිජනක: X-කිරණ, පාරජම්බුල කිරණ, න්‍යෂ්ටික විකිරණ, ඇතැම් විෂ රසායනික ද්‍රව්‍ය.",
        examTip = "💡 සියලුම විකෘති අහිතකර නොවේ; පරිණාමයට අවශ්‍ය නව ප්‍රභේද බිහිවීමට හිතකර විකෘති ඉවහල් වේ."
      ),

      // --- GROUP 10: පරිසරය, ක්ෂුද්‍රජීවීන් සහ ජෛවතාක්ෂණය (91-100) ---
      OlSubjectToolItem(
        id = "sci_tool_91",
        subject = "විද්‍යාව",
        toolNumber = 91,
        groupNumber = 10,
        titleSinhala = "ආහාර දාම, ජාල සහ ශක්ති පිරමිඩ",
        titleEnglish = "Food Chains, Webs & Energy Pyramids",
        category = "පාරිසරික විද්‍යාව",
        icon = "🦅",
        quickSummary = "නිෂ්පාදකයින්ගේ සිට විලෝපිකයන් දක්වා පෝෂී මට්ටම් ඔස්සේ ශක්තිය ගලායාම.",
        formulaOrRule = "10% නීතිය: එක් පෝෂී මට්ටමකින් ඊළඟ මට්ටමට සම්ප්‍රේෂණය වන්නේ ශක්තියෙන් 10%ක් පමණි; 90%ක් ශ්වසනය හා අපද්‍රව්‍ය ලෙස හානිවේ.",
        practicalApplication = "ශක්ති පිරමිඩයක් සෑම විටම ඍජු (උඩුකුරු) වේ; කිසිවිටෙකත් යටිකුරු විය නොහැක.",
        examTip = "💡 ආහාර දාමයක පෝෂී මට්ටම් 4-5 කට වඩා නොපවතින්නේ ඉහළට යනවිට ශක්තිය ශීඝ්‍රයෙන් අඩුවන බැවිනි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_92",
        subject = "විද්‍යාව",
        toolNumber = 92,
        groupNumber = 10,
        titleSinhala = "නයිට්‍රජන් චක්‍රය සහ බැක්ටීරියා කාර්යය",
        titleEnglish = "Nitrogen Cycle & Bacterial Roles",
        category = "පාරිසරික විද්‍යාව",
        icon = "🔄",
        quickSummary = "නයිට්‍රජන් තිරකිරීම (Rhizobium, Azotobacter), නයිට්‍රීකරණය (Nitrosomonas, Nitrobacter) සහ විනයිට්‍රීකරණය (Pseudomonas).",
        formulaOrRule = "N₂ -> NH₄⁺ (නයිට්‍රජන් තිරකිරීම) -> NO₂⁻ -> NO₃⁻ (නයිට්‍රීකරණය) -> N₂ වායුව (විනයිට්‍රීකරණය)",
        practicalApplication = "රනිල බෝග මුල් ගැටිතිවල ජීවත්වන රයිසෝබියම් සහජීවී බැක්ටීරියාව වායුගෝලීය නයිට්‍රජන් තිරකර පස සරු කරයි.",
        examTip = "💡 ශාකවලට වායුගෝලීය N₂ සෘජුව උරාගත නොහැක; උරාගන්නේ නයිට්‍රේට (NO₃⁻) අයන ලෙස පමණි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_93",
        subject = "විද්‍යාව",
        toolNumber = 93,
        groupNumber = 10,
        titleSinhala = "කාබන් චක්‍රය සහ හරිතාගාර ආචරණය",
        titleEnglish = "Carbon Cycle & Global Warming",
        category = "පාරිසරික විද්‍යාව",
        icon = "🌍",
        quickSummary = "ප්‍රභාසංස්ලේෂණය මගින් CO₂ අවශෝෂණය සහ ශ්වසනය, දහනය මගින් CO₂ පරිසරයට එක්වීම.",
        formulaOrRule = "ප්‍රධාන හරිතාගාර වායු: CO₂ (කාබන් ඩයොක්සයිඩ්), CH₄ (මීතේන්), N₂O, ජල වාෂ්ප, CFC.",
        practicalApplication = "පොසිල ඉන්ධන අධික ලෙස දහනය නිසා වායුගෝලීය CO₂ වැඩිවී පෘථිවි සාමාන්‍ය උෂ්ණත්වය ඉහළ යාම (ගෝලීය උණුසුම).",
        examTip = "💡 ගෝලීය උණුසුම නිසා ධ්‍රැවාසන්න අයිස් දියවී මුහුදු මට්ටම ඉහළ යාම සහ කාලගුණ විපර්යාස සිදුවේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_94",
        subject = "විද්‍යාව",
        toolNumber = 94,
        groupNumber = 10,
        titleSinhala = "ක්ෂුද්‍රජීවීන් වර්ගීකරණය (බැක්ටීරියා, දිලීර, වයිරස)",
        titleEnglish = "Microorganisms Classification & Features",
        category = "ක්ෂුද්‍රජීව විද්‍යාව",
        icon = "🦠",
        quickSummary = "බැක්ටීරියා (ප්‍රාග්න්‍යෂ්ටික), දිලීර (සූන්‍යෂ්ටික, විෂමපෝෂී), වයිරස (අසෛලීය, සජීවී සත්කාරකයෙකු තුළ පමණක් ප්‍රජනනය කරයි).",
        formulaOrRule = "වයිරසයක් සෑදී ඇත්තේ ප්‍රෝටීන කොපුවක් (Capsid) සහ න්‍යෂ්ටික අම්ලයකින් (DNA හෝ RNA) පමණි.",
        practicalApplication = "ප්‍රතිජීවක (Antibiotics) ඖෂධ ඵලදායී වන්නේ බැක්ටීරියාවලට එරෙහිව පමණි; වයිරස රෝග සඳහා ප්‍රතිජීවක ක්‍රියා නොකරයි.",
        examTip = "💡 පෙනිසිලින් නම් මුල්ම ප්‍රතිජීවකය සොයාගත්තේ Penicillium notatum නම් දිලීරයෙනි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_95",
        subject = "විද්‍යාව",
        toolNumber = 95,
        groupNumber = 10,
        titleSinhala = "කාර්මික ක්ෂුද්‍රජීව විද්‍යාව සහ නිෂ්පාදන",
        titleEnglish = "Industrial Microbiology Applications",
        category = "ජෛවතාක්ෂණය",
        icon = "🧀",
        quickSummary = "යෝගට්/කිරි (Lactobacillus), පාන්/බීර (Yeast - Saccharomyces), විනාකිරි (Acetobacter).",
        formulaOrRule = "ලැක්ටෝස් සීනි -> ලැක්ටික් අම්ලය (ලැක්ටොබැසිලස් මගින් කිරි මිදවීම).",
        practicalApplication = "පාන් පිටි පිපීම සඳහා යීස්ට් මගින් පිටකරන CO₂ වායුව දායක වේ.",
        examTip = "💡 යීස්ට් නිර්වායු ශ්වසනයේදී එතනෝල් සහ CO₂ නිපදවයි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_96",
        subject = "විද්‍යාව",
        toolNumber = 96,
        groupNumber = 10,
        titleSinhala = "ප්‍රතිශක්තිකරණය සහ එන්නත් තාක්ෂණය",
        titleEnglish = "Immunization & Vaccine Technology",
        category = "වෛද්‍ය විද්‍යාව",
        icon = "💉",
        quickSummary = "සක්‍රිය ප්‍රතිශක්තිය (දේහය මගින් ප්‍රතිදේහ නිපදවීම) සහ අක්‍රිය ප්‍රතිශක්තිය (පිටතින් ප්‍රතිදේහ ලබාදීම).",
        formulaOrRule = "එන්නතක අඩංගු වන්නේ දුර්වල කළ හෝ අක්‍රිය කළ රෝගකාරක ක්ෂුද්‍රජීවීන් හෝ උන්ගේ විෂ ද්‍රව්‍ය (Toxoids) ය.",
        practicalApplication = "එන්නත් ලබාදුන් පසු දේහයේ මතක සෛල (Memory cells) සෑදී දිගුකාලීන ආරක්ෂාවක් සපයයි.",
        examTip = "💡 ධනුස්තම්භය (පිටගැස්ම) වැළඳීමේ අවදානමකදී වහාම ලබාදෙන්නේ සූදානම් කළ ප්‍රතිදේහ සහිත සෙරමයක් (Anti-tetanus serum - ATS) ය; එය අක්‍රිය ප්‍රතිශක්තියකි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_97",
        subject = "විද්‍යාව",
        toolNumber = 97,
        groupNumber = 10,
        titleSinhala = "ප්‍රවේණි ඉංජිනේරු විද්‍යාව සහ Recombinant DNA",
        titleEnglish = "Genetic Engineering & Recombinant DNA",
        category = "ජෛවතාක්ෂණය",
        icon = "🧬",
        quickSummary = "එක් ජීවියෙකුගේ වාසිදායක ජානයක් තවත් ජීවියෙකුගේ DNA තුළට බද්ධ කර අවශ්‍ය ඵල නිපදවා ගැනීම.",
        formulaOrRule = "සීමාකාරී එන්ඩොනියුක්ලියේස් එන්සයිම (කැපීම) + DNA ලයිගේස් එන්සයිමය (ඇලවීම) + ප්ලාස්මිඩ (වාහකයා).",
        practicalApplication = "මිනිස් ඉන්සියුලින් හෝමෝනය E. coli බැක්ටීරියා මගින් කාර්මිකව මහා පරිමාණයෙන් නිපදවීම.",
        examTip = "💡 රන් සහල් (Golden Rice) යනු විටමින් A පූර්වගාමී බීටා කැරොටින් නිපදවන ජාන බද්ධ කළ ප්‍රවේණිකව වෙනස් කළ (GMO) බෝගයකි."
      ),
      OlSubjectToolItem(
        id = "sci_tool_98",
        subject = "විද්‍යාව",
        toolNumber = 98,
        groupNumber = 10,
        titleSinhala = "ජල දූෂණය සහ BOD (ජෛව රසායනික ඔක්සිජන් ඉල්ලුම)",
        titleEnglish = "Water Pollution & BOD Indicator Tool",
        category = "පාරිසරික විද්‍යාව",
        icon = "🚱",
        quickSummary = "ජලයේ කාබනික අපද්‍රව්‍ය වියෝජනය කිරීමට ක්ෂුද්‍රජීවීන්ට අවශ්‍ය දියවූ ඔක්සිජන් ප්‍රමාණය.",
        formulaOrRule = "කාබනික දූෂණය වැඩිවන විට -> BOD අගය ↑ -> දියවූ ඔක්සිජන් (DO) අගය ↓ (ජලජ ජීවීන් මියයයි)",
        practicalApplication = "සුපෝෂණය (Eutrophication): පොහොර (නයිට්‍රේට, පොස්පේට) ජලාශවලට එකතුවීමෙන් ඇල්ගී පිපිරීම් ඇතිවී ජලය දූෂණය වීම.",
        examTip = "💡 පිරිසිදු පානීය ජලයේ BOD අගය 1 mg/L ට වඩා අඩු විය යුතුය."
      ),
      OlSubjectToolItem(
        id = "sci_tool_99",
        subject = "විද්‍යාව",
        toolNumber = 99,
        groupNumber = 10,
        titleSinhala = "ඝන අපද්‍රව්‍ය කළමනාකරණය සහ 3R සංකල්පය",
        titleEnglish = "Solid Waste Management & 3R Concepts",
        category = "පාරිසරික විද්‍යාව",
        icon = "🗑️",
        quickSummary = "අවම කිරීම (Reduce), නැවත භාවිතය (Reuse), ප්‍රතිචක්‍රීකරණය (Recycle).",
        formulaOrRule = "දිරාපත්වන කාබනික අපද්‍රව්‍ය -> කොම්පෝස්ට් පොහොර සෑදීම | නොදිරන අපද්‍රව්‍ය -> වර්ගීකරණය කර ප්‍රතිචක්‍රීකරණය",
        practicalApplication = "පොලිතීන් බෑග් වෙනුවට රෙදි බෑග් භාවිතය 'අවම කිරීම' (Reduce) සඳහා කදිම උදාහරණයකි.",
        examTip = "💡 විවෘතව කසළ පිළිස්සීමෙන් පිළිකාකාරක ඩයොක්සින් (Dioxins) වායුව වායුගෝලයට මුදාහැරේ."
      ),
      OlSubjectToolItem(
        id = "sci_tool_100",
        subject = "විද්‍යාව",
        toolNumber = 100,
        groupNumber = 10,
        titleSinhala = "තිරසාර සංවර්ධනය සහ ජෛව විවිධත්ව සංරක්ෂණය",
        titleEnglish = "Sustainable Development & Biodiversity Conservation",
        category = "පාරිසරික විද්‍යාව",
        icon = "🌳",
        quickSummary = "අනාගත පරපුරේ අවශ්‍යතා කැප නොකර වර්තමාන අවශ්‍යතා සපුරා ගැනීම සහ ආවේණික විශේෂ රැකගැනීම.",
        formulaOrRule = "ස්වස්ථානික සංරක්ෂණය (ජාතික වනෝද්‍යාන, රක්ෂිත - උදා: සිංහරාජය) | පරස්ථානික සංරක්ෂණය (සත්වෝද්‍යාන, උද්භිද උද්‍යාන, බීජ බැංකු)",
        practicalApplication = "ශ්‍රී ලංකාව ලොව ජෛව විවිධත්ව උණුසුම් කලාප 36න් එකක් (Biodiversity Hotspot) ලෙස නම් කර ඇත.",
        examTip = "💡 ආවේණික විශේෂයක් (Endemic species) යනු ලෝකයේ වෙනත් කිසිදු ස්වභාවික පරිසරයක හමුනොවන, යම් නිශ්චිත භූගෝලීය කලාපයකට පමණක් සීමාවූ ජීවී විශේෂයකි."
      )
    )
  }
}
