package com.example

object OlSubjectToolsMathsData {
  val tools: List<OlSubjectToolItem> by lazy {
    listOf(
      // --- GROUP 1: සංඛ්‍යා, භාග, දර්ශක සහ ලඝුගණක (1-10) ---
      OlSubjectToolItem(
        id = "math_tool_01",
        subject = "ගණිතය",
        toolNumber = 1,
        groupNumber = 1,
        titleSinhala = "දර්ශක නීති සහ සූත්‍ර මෙවලම",
        titleEnglish = "Laws of Indices Solver",
        category = "සංඛ්‍යා",
        icon = "🔢",
        quickSummary = "එකම පාදය සහිත දර්ශක ගුණ කිරීමේදී දර්ශක එකතු වන අතර බෙදීමේදී අඩු වේ.",
        formulaOrRule = "a^m × a^n = a^{m+n} | a^m ÷ a^n = a^{m-n} | (a^m)^n = a^{mn} | a⁰ = 1 | a^{-n} = 1 / a^n",
        practicalApplication = "2³ × 2⁴ = 2⁷ = 128; 5⁶ ÷ 5⁴ = 5² = 25; 16^{1/2} = √16 = 4.",
        examTip = "💡 ශුන්‍ය නොවන ඕනෑම සංඛ්‍යාවක ශුන්‍ය වෙනි බලය 1 වේ (a⁰ = 1)."
      ),
      OlSubjectToolItem(
        id = "math_tool_02",
        subject = "ගණිතය",
        toolNumber = 2,
        groupNumber = 1,
        titleSinhala = "ලඝුගණක නීති සහ ලඝු වගු භාවිතය",
        titleEnglish = "Laws of Logarithms & Tables Tool",
        category = "සංඛ්‍යා",
        icon = "📐",
        quickSummary = "දර්ශක සහ ලඝුගණක අතර සම්බන්ධය හා සංකීර්ණ ගණනය කිරීම් සරල කිරීමේ නීති.",
        formulaOrRule = "y = a^x <=> log_a(y) = x | log(xy) = log(x) + log(y) | log(x/y) = log(x) - log(y) | log(x^k) = k log(x)",
        practicalApplication = "log₁₀(1000) = 3 මක්නිසාද 10³ = 1000. log₁₀(2) = 0.3010 නම් log₁₀(20) = log₁₀(2 × 10) = 1.3010.",
        examTip = "💡 ලඝුගණක වගු භාවිතයේදී පූර්ණාංශය (Characteristic) සංඛ්‍යාවේ විශාලත්වය අනුවත්, දශමාංශය (Mantissa) වගුවෙනුත් ලබාගනී."
      ),
      OlSubjectToolItem(
        id = "math_tool_03",
        subject = "ගණිතය",
        toolNumber = 3,
        groupNumber = 1,
        titleSinhala = "විද්‍යාත්මක අංකනය (සම්මත ආකාරය)",
        titleEnglish = "Scientific Notation / Standard Form",
        category = "සංඛ්‍යා",
        icon = "🔬",
        quickSummary = "ඉතා විශාල හෝ ඉතා කුඩා සංඛ්‍යා A × 10^n (1 ≤ A < 10) ආකාරයෙන් දැක්වීම.",
        formulaOrRule = "A × 10^n (මෙහි 1 ≤ A < 10 සහ n යනු නිඛිලයකි)",
        practicalApplication = "384,000,000 m = 3.84 × 10⁸ m; 0.000025 g = 2.5 × 10⁻⁵ g.",
        examTip = "💡 දශම තිත වමට ගෙනියනවිට n ධන වේ; දකුණට ගෙනියනවිට n ඍණ වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_04",
        subject = "ගණිතය",
        toolNumber = 4,
        groupNumber = 1,
        titleSinhala = "භාග සුළු කිරීම සහ BODMAS නීතිය",
        titleEnglish = "Fractions Operations & BODMAS Rule",
        category = "සංඛ්‍යා",
        icon = "➗",
        quickSummary = "වරහන් (Brackets), හි (Of), බෙදීම (Division), ගුණ කිරීම (Multiplication), එකතු කිරීම (Addition), අඩු කිරීම (Subtraction).",
        formulaOrRule = "B -> O -> D -> M -> A -> S පිළිවෙලට සුළු කළ යුතුය.",
        practicalApplication = "2/3 + 1/4 × 2/5 හි පළමුව ගුණ කිරීම: (1/4 × 2/5 = 1/10). පසුව 2/3 + 1/10 = (20 + 3) / 30 = 23/30.",
        examTip = "💡 මිශ්‍ර භාග අනිවාර්යයෙන්ම විෂම භාග බවට පත් කරගෙන සුළු කිරීම පහසුය."
      ),
      OlSubjectToolItem(
        id = "math_tool_05",
        subject = "ගණිතය",
        toolNumber = 5,
        groupNumber = 1,
        titleSinhala = "අනුපාත සහ සමනුපාත (අනුලෝම / ප්‍රතිලෝම)",
        titleEnglish = "Ratios, Direct & Inverse Proportions",
        category = "අනුපාත",
        icon = "⚖️",
        quickSummary = "අනුලෝමව: එකක් වැඩිවන විට අනෙකද වැඩිවේ (y = kx) | ප්‍රතිලෝමව: එකක් වැඩිවන විට අනෙක අඩුවේ (xy = k).",
        formulaOrRule = "ප්‍රතිලෝම විචලනය: මිනිස්-දින ගණනය කිරීම්: මිනිසුන් ගණන × දින ගණන = නියත කාර්යය",
        practicalApplication = "මිනිසුන් 6 දෙනෙකුට දින 10ක් ගතවන කාර්යයක් මිනිසුන් 4 දෙනෙකුට කිරීමට: (6 × 10) / 4 = 15 දිනකි.",
        examTip = "💡 මිනිස් දින ගණන් විභාගයේ පළමු කොටසේ අනිවාර්යයෙන්ම ලැබෙන ප්‍රශ්නයකි."
      ),
      OlSubjectToolItem(
        id = "math_tool_06",
        subject = "ගණිතය",
        toolNumber = 6,
        groupNumber = 1,
        titleSinhala = "ප්‍රතිශත සහ ප්‍රතිශත වැඩිවීම / අඩුවීම",
        titleEnglish = "Percentages & Percentage Change",
        category = "සංඛ්‍යා",
        icon = "📈",
        quickSummary = "ප්‍රතිශත වෙනස = (වෙනස / මුල් අගය) × 100%.",
        formulaOrRule = "ප්‍රතිශත ලාභය = (ලාභය / ගැනුම් මිල) × 100% | වට්ටම් ප්‍රතිශතය = (වට්ටම / සලකුණු කළ මිල) × 100%",
        practicalApplication = "රු. 800 ට ගත් භාණ්ඩයක් රු. 1000 ට විකිණූ විට ලාභ ප්‍රතිශතය: (200 / 800) × 100% = 25%.",
        examTip = "💡 වට්ටම ගණනය කරන්නේ සෑම විටම සලකුණු කළ මිල (Marked price) මතය."
      ),
      OlSubjectToolItem(
        id = "math_tool_07",
        subject = "ගණිතය",
        toolNumber = 7,
        groupNumber = 1,
        titleSinhala = "වර්ගමූල ආසන්න කිරීම (දෙපස ආසන්න වර්ග සංඛ්‍යා)",
        titleEnglish = "Square Root Approximation Method",
        category = "සංඛ්‍යා",
        icon = "√",
        quickSummary = "පූර්ණ වර්ග නොවන සංඛ්‍යාවල වර්ගමූලය පළමු දශමස්ථානයට සෙවීමේ ක්‍රමය.",
        formulaOrRule = "උදා: √40 සෙවීම -> 6² = 36 සහ 7² = 49 අතර පිහිටයි. 6.3² = 39.69, 6.4² = 40.96. එබැවින් √40 ≈ 6.3.",
        practicalApplication = "ජ්‍යාමිතික හා පයිතගරස් ගැටලුවලදී නිවැරදි වර්ගමූල අගය ලබාගැනීමට යොදාගනී.",
        examTip = "💡 ආසන්න කිරීමේදී නිවැරදි බව තහවුරු කිරීමට වර්ග කර පෙන්වීම අත්‍යවශ්‍ය වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_08",
        subject = "ගණිතය",
        toolNumber = 8,
        groupNumber = 1,
        titleSinhala = "කු.පො.පො. සහ ම.පො.සා. සෙවුම් මෙවලම",
        titleEnglish = "LCM & HCF Solver for Numbers & Expressions",
        category = "සංඛ්‍යා",
        icon = "🧩",
        quickSummary = "ප්‍රථමක සාධක මගින් කුඩාම පොදු ගුණාකාරය (LCM) සහ මහත්තම පොදු සාධකය (HCF) සෙවීම.",
        formulaOrRule = "වීජීය ප්‍රකාශන සඳහා: එක් එක් පද සාධකවලට වෙන්කර උපරිම බල සහිත පොදු සාධක ගැනීම.",
        practicalApplication = "6x²y සහ 9xy²: HCF = 3xy; LCM = 18x²y².",
        examTip = "💡 වීජීය භාග එකතු කිරීමේදී හරයන්ගේ කු.පො.පො. සෙවීම අත්‍යවශ්‍ය පළමු පියවරයි."
      ),
      OlSubjectToolItem(
        id = "math_tool_09",
        subject = "ගණිතය",
        toolNumber = 9,
        groupNumber = 1,
        titleSinhala = "වටයෑම සහ අර්ථවත් සංඛ්‍යාංක",
        titleEnglish = "Rounding & Significant Figures Tool",
        category = "සංඛ්‍යා",
        icon = "🎯",
        quickSummary = "දී ඇති අර්ථවත් සංඛ්‍යාංක (Significant figures) ගණනට හෝ දශමස්ථාන ගණනට සංඛ්‍යා වටයෑම.",
        formulaOrRule = "වටයන ඉලක්කමට පසු ඉලක්කම 5 හෝ ඊට වැඩි නම් 1ක් එකතු කරයි; 5ට අඩු නම් නොවෙනස්ව තබයි.",
        practicalApplication = "0.004052 හි අර්ථවත් සංඛ්‍යාංක 3ට: 0.00405; 38,472 අර්ථවත් සංඛ්‍යාංක 2ට: 38,000.",
        examTip = "💡 දශම සංඛ්‍යාවක වම්පස ඇති ශුන්‍ය අර්ථවත් සංඛ්‍යාංක ලෙස නොගණී."
      ),
      OlSubjectToolItem(
        id = "math_tool_10",
        subject = "ගණිතය",
        toolNumber = 10,
        groupNumber = 1,
        titleSinhala = "කුලක සහ වෙන් රූප සටහන් සූත්‍රය",
        titleEnglish = "Sets & Venn Diagrams Formula (n(A∪B))",
        category = "කුලක",
        icon = "⭕",
        quickSummary = "කුලක දෙකක හෝ තුනක එක්වීම, ඡේදනය සහ අනුපූරකය සෙවීමේ මූලික සූත්‍ර.",
        formulaOrRule = "n(A ∪ B) = n(A) + n(B) - n(A ∩ B)",
        practicalApplication = "සිසුන් 40ක පන්තියක 25ක් ක්‍රිකට් ද, 20ක් පාපන්දු ද, 10ක් ක්‍රීඩා දෙකම කරන්නේ නම්: n(A ∪ B) = 25 + 20 - 10 = 35. ක්‍රීඩා දෙකම නොකරන සිසුන් = 40 - 35 = 5.",
        examTip = "💡 පළමුවෙන්ම මැද පොදු ඡේදනය (A ∩ B) වෙන් රූපයේ සටහන් කර පසුව අනෙක් කොටස් පිරවීමෙන් වැරදීම් වළක්වා ගත හැක."
      ),

      // --- GROUP 2: වීජ ගණිතය: ප්‍රකාශන, සාධක සහ සමීකරණ (11-20) ---
      OlSubjectToolItem(
        id = "math_tool_11",
        subject = "ගණිතය",
        toolNumber = 11,
        groupNumber = 2,
        titleSinhala = "වර්ග දෙකක අන්තරය සාධක සූත්‍රය",
        titleEnglish = "Difference of Two Squares (a² - b²)",
        category = "වීජ ගණිතය",
        icon = "✂️",
        quickSummary = "වර්ගජ පද දෙකක අන්තරය (a - b)(a + b) ලෙස ක්ෂණිකව සාධක වෙන්කිරීම.",
        formulaOrRule = "a² - b² = (a - b)(a + b)",
        practicalApplication = "4x² - 9 = (2x - 3)(2x + 3); 105² - 95² = (105 - 95)(105 + 95) = 10 × 200 = 2000.",
        examTip = "💡 පළමුවෙන්ම පොදු සාධකයක් ඇත්නම් එය ඉවතට ගන්න (උදා: 2x² - 18 = 2(x² - 9) = 2(x - 3)(x + 3))."
      ),
      OlSubjectToolItem(
        id = "math_tool_12",
        subject = "ගණිතය",
        toolNumber = 12,
        groupNumber = 2,
        titleSinhala = "පූර්ණ වර්ග ත්‍රිපද ප්‍රකාශන සූත්‍ර",
        titleEnglish = "Perfect Square Trinomials ((a ± b)²)",
        category = "වීජ ගණිතය",
        icon = "🔲",
        quickSummary = "ද්විපද ප්‍රකාශනයක වර්ගය ප්‍රසාරණය සහ සාධක සෙවීම.",
        formulaOrRule = "(a + b)² = a² + 2ab + b² | (a - b)² = a² - 2ab + b²",
        practicalApplication = "(2x + 3)² = (2x)² + 2(2x)(3) + 3² = 4x² + 12x + 9.",
        examTip = "💡 x² + 6x සඳහා පූර්ණ වර්ගයක් වීමට එකතු කළ යුතු නියතය වන්නේ (6/2)² = 3² = 9 ය."
      ),
      OlSubjectToolItem(
        id = "math_tool_13",
        subject = "ගණිතය",
        toolNumber = 13,
        groupNumber = 2,
        titleSinhala = "ax² + bx + c වර්ගජ ප්‍රකාශන සාධක",
        titleEnglish = "Quadratic Trinomial Factoring Tool",
        category = "වීජ ගණිතය",
        icon = "🧩",
        quickSummary = "ගුණිතය ac වන සහ එකතුව b වන සංඛ්‍යා යුගලය සොයා මැද පදය වෙන්කිරීම.",
        formulaOrRule = "x² + 5x + 6 = (x + 2)(x + 3) | 2x² + 7x + 3 = (2x + 1)(x + 3)",
        practicalApplication = "2x² + 7x + 3: ac = 6, b = 7 (සාධක 6 සහ 1). 2x² + 6x + x + 3 = 2x(x + 3) + 1(x + 3) = (2x + 1)(x + 3).",
        examTip = "💡 ලකුණු කෙරෙහි විශේෂයෙන් සැලකිලිමත් වන්න (ධන සහ ඍණ සංඛ්‍යා ගුණ කිරීමේ නීති)."
      ),
      OlSubjectToolItem(
        id = "math_tool_14",
        subject = "ගණිතය",
        toolNumber = 14,
        groupNumber = 2,
        titleSinhala = "වර්ගජ සූත්‍රය මගින් විසඳුම් සෙවීම",
        titleEnglish = "Quadratic Formula Solver (-b ± √(b² - 4ac))/2a",
        category = "වීජ ගණිතය",
        icon = "🧮",
        quickSummary = "සාධක වෙන්කළ නොහැකි වර්ගජ සමීකරණ සාර්ථකව විසඳීමේ සර්වත්‍ර ක්‍රමය.",
        formulaOrRule = "x = [-b ± √(b² - 4ac)] / (2a)",
        practicalApplication = "x² - 4x + 1 = 0: a=1, b=-4, c=1. x = [4 ± √(16 - 4)] / 2 = [4 ± √12] / 2 = 2 ± √3.",
        examTip = "💡 b² - 4ac (විවේචකය) > 0 නම් තාත්වික විසඳුම් 2ක්ද, = 0 නම් සමපාත විසඳුමක්ද, < 0 නම් තාත්වික විසඳුම් නොමැත."
      ),
      OlSubjectToolItem(
        id = "math_tool_15",
        subject = "ගණිතය",
        toolNumber = 15,
        groupNumber = 2,
        titleSinhala = "පූර්ණ වර්ග කිරීමෙන් වර්ගජ සමීකරණ විසඳීම",
        titleEnglish = "Completing the Square Method",
        category = "වීජ ගණිතය",
        icon = "🔲",
        quickSummary = "x හි සංගුණකයෙන් අඩක වර්ගය දෙපසටම එකතු කර පූර්ණ වර්ගයක් ගොඩනැගීම.",
        formulaOrRule = "x² + bx + (b/2)² = (x + b/2)²",
        practicalApplication = "x² + 6x = 7 => x² + 6x + 9 = 7 + 9 => (x + 3)² = 16 => x + 3 = ±4 => x = 1 හෝ x = -7.",
        examTip = "💡 x² හි සංගුණකය 1 ට වඩා වැඩි නම් ප්‍රථමයෙන් මුළු සමීකරණයම එම සංගුණකයෙන් බෙදිය යුතුය."
      ),
      OlSubjectToolItem(
        id = "math_tool_16",
        subject = "ගණිතය",
        toolNumber = 16,
        groupNumber = 2,
        titleSinhala = "සමගාමී සමීකරණ විසඳුම් මෙවලම (විලෝපනය / ආදේශය)",
        titleEnglish = "Simultaneous Equations Solver",
        category = "වීජ ගණිතය",
        icon = "⚖️",
        quickSummary = "විචල්‍යයන් දෙකක් සහිත සමීකරණ යුගලයක එක් විචල්‍යයක් ඉවත් කර විසඳීම.",
        formulaOrRule = "සංගුණක සමාන කර එකතු කිරීම හෝ අඩු කිරීම (විලෝපනය).",
        practicalApplication = "2x + y = 7 සහ x - y = 2. සමීකරණ දෙක එකතු කළ විට: 3x = 9 => x = 3, y = 1.",
        examTip = "💡 විභාගයේදී ලැබුණු විසඳුම් (x, y) මුල් සමීකරණවලට ආදේශ කර නිවැරදි බව පරීක්ෂා කරගන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_17",
        subject = "ගණිතය",
        toolNumber = 17,
        groupNumber = 2,
        titleSinhala = "වීජීය භාග සුළු කිරීම සහ සමීකරණ",
        titleEnglish = "Algebraic Fractions & Equations Tool",
        category = "වීජ ගණිතය",
        icon = "➗",
        quickSummary = "හරයන් සාධකවලට වෙන්කර පොදු හරය (LCM) මගින් භාග එකතු කිරීම හෝ බෙදීම.",
        formulaOrRule = "a/b ± c/d = (ad ± bc) / bd",
        practicalApplication = "1/(x-1) + 2/(x+1) = [1(x+1) + 2(x-1)] / [(x-1)(x+1)] = (3x - 1) / (x² - 1).",
        examTip = "💡 හරය ශුන්‍ය වන අගයන් (උදා: x = 1 හෝ -1) විසඳුම් ලෙස ගත නොහැක."
      ),
      OlSubjectToolItem(
        id = "math_tool_18",
        subject = "ගණිතය",
        toolNumber = 18,
        groupNumber = 2,
        titleSinhala = "සූත්‍රයක උක්තය වෙනස් කිරීමේ මෙවලම",
        titleEnglish = "Changing Subject of Formula Tool",
        category = "වීජ ගණිතය",
        icon = "🔄",
        quickSummary = "සූත්‍රයක අඩංගු එක් නිශ්චිත විචල්‍යයක් සමාන ලකුණින් එක පැත්තකට තනි කර ගැනීම.",
        formulaOrRule = "v² = u² + 2as හි s උක්ත කිරීම: 2as = v² - u² => s = (v² - u²) / (2a)",
        practicalApplication = "T = 2π√(l/g) හි l උක්ත කිරීම: T² = 4π²(l/g) => l = (T² g) / (4π²).",
        examTip = "💡 වර්ගමූලයක් ඇත්නම් පළමුව දෙපසම වර්ග කරන්න; හරයක විචල්‍යය ඇත්නම් හරස් ගුණනය කරන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_19",
        subject = "ගණිතය",
        toolNumber = 19,
        groupNumber = 2,
        titleSinhala = "සරල රේඛීය අසමානතා සහ සංඛ්‍යා රේඛා",
        titleEnglish = "Linear Inequalities & Number Line",
        category = "වීජ ගණිතය",
        icon = "↔️",
        quickSummary = "<, >, ≤, ≥ ලකුණු සහිත අසමානතා විසඳීම සහ සංඛ්‍යා රේඛාවක නිරූපණය.",
        formulaOrRule = "අසමානතාවක් ඍණ සංඛ්‍යාවකින් ගුණ කළ විට හෝ බෙදූ විට අසමානතා ලකුණ අනිවාර්යයෙන්ම මාරු වේ (ආපසු හැරේ).",
        practicalApplication = "-2x < 6 => x > -3 (ඍණ 2න් බෙදූ බැවින් < ලකුණ > බවට පත්විය).",
        examTip = "💡 සංඛ්‍යා රේඛාවේ ≤ හෝ ≥ නම් ලක්ෂ්‍යය පාට කළ කවයකින්ද (•), < හෝ > නම් හිස් කවයකින්ද (○) දක්වන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_20",
        subject = "ගණිතය",
        toolNumber = 20,
        groupNumber = 2,
        titleSinhala = "ද්විපද ප්‍රකාශන ප්‍රසාරණය (x+a)(x+b)",
        titleEnglish = "Binomial Expansion (FOIL Method)",
        category = "වීජ ගණිතය",
        icon = "✖️",
        quickSummary = "First, Outside, Inside, Last (FOIL) ක්‍රමයට වරහන් දෙකක් ගුණ කිරීම.",
        formulaOrRule = "(x + a)(x + b) = x² + (a + b)x + ab",
        practicalApplication = "(x + 4)(x - 3) = x² + (4 - 3)x + (4)(-3) = x² + x - 12.",
        examTip = "💡 එක් එක් පදයේ ලකුණු (+ / -) නිවැරදිව තබා ගැනීම ඉතා වැදගත් වේ."
      ),

      // --- GROUP 3: ප්‍රස්ථාර සහ ශ්‍රිත (21-30) ---
      OlSubjectToolItem(
        id = "math_tool_21",
        subject = "ගණිතය",
        toolNumber = 21,
        groupNumber = 3,
        titleSinhala = "සරල රේඛාවේ සමීකරණය සහ අනුක්‍රමණය (y = mx + c)",
        titleEnglish = "Straight Line Equation & Gradient (m = Δy/Δx)",
        category = "ප්‍රස්ථාර",
        icon = "📈",
        quickSummary = "m = අනුක්‍රමණය (බැවුම), c = y-අන්තඃඛණ්ඩය (රේඛාව y අක්ෂය ඡේදනය කරන ලක්ෂ්‍යය).",
        formulaOrRule = "අනුක්‍රමණය m = (y₂ - y₁) / (x₂ - x₁) | y = mx + c",
        practicalApplication = "(1, 2) සහ (3, 8) ලක්ෂ්‍ය හරහා යන රේඛාවේ අනුක්‍රමණය: m = (8 - 2) / (3 - 1) = 6 / 2 = 3. සමීකරණය: y = 3x - 1.",
        examTip = "💡 සමාන්තර රේඛාවල අනුක්‍රමණ සමාන වේ (m₁ = m₂)."
      ),
      OlSubjectToolItem(
        id = "math_tool_22",
        subject = "ගණිතය",
        toolNumber = 22,
        groupNumber = 3,
        titleSinhala = "පැරබෝලාව: වර්ගජ ශ්‍රිත ප්‍රස්ථාර ලක්ෂණ",
        titleEnglish = "Quadratic Function Graph (Parabola: y = ax² + bx + c)",
        category = "ප්‍රස්ථාර",
        icon = "〰️",
        quickSummary = "හැරවුම් ලක්ෂ්‍යය (උපරිම හෝ අවම), සමමිතික අක්ෂය සහ මූල හඳුනාගැනීම.",
        formulaOrRule = "a > 0 නම් 'U' හැඩැති අවම අගයක් සහිතයි | a < 0 නම් '∩' හැඩැති උපරිම අගයක් සහිතයි | සමමිතික අක්ෂය: x = -b / (2a)",
        practicalApplication = "y = (x - 2)² - 3 හි අවම හැරවුම් ලක්ෂ්‍යය (2, -3) වන අතර සමමිතික අක්ෂය x = 2 වේ.",
        examTip = "💡 ප්‍රස්ථාරය x අක්ෂය ඡේදනය කරන ලක්ෂ්‍යවල x ඛණ්ඩාංක මගින් ax² + bx + c = 0 සමීකරණයේ මූල (විසඳුම්) ලබාදේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_23",
        subject = "ගණිතය",
        toolNumber = 23,
        groupNumber = 3,
        titleSinhala = "ප්‍රස්ථාරයකින් සමීකරණ විසඳීම",
        titleEnglish = "Solving Equations Graphically",
        category = "ප්‍රස්ථාර",
        icon = "🎯",
        quickSummary = "y = f(x) ප්‍රස්ථාරය සහ තවත් සරල රේඛාවක් ඡේදනය වන ලක්ෂ්‍ය මගින් විසඳුම් සෙවීම.",
        formulaOrRule = "f(x) = mx + c විසඳීමට: y = f(x) වක්‍රය සහ y = mx + c රේඛාව කැපෙන ලක්ෂ්‍යවල x අගයන් සෙවීම.",
        practicalApplication = "y = x² ප්‍රස්ථාරය සහ y = 2x + 3 රේඛාව ඡේදනය වන ලක්ෂ්‍යවල x අගයන් වන්නේ x² - 2x - 3 = 0 හි විසඳුම්ය.",
        examTip = "💡 ප්‍රස්ථාරය මත අදාළ ලක්ෂ්‍ය පැහැදිලිව ලකුණු කර x අක්ෂයට ලම්භකව රේඛා ඇඳ පෙන්වන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_24",
        subject = "ගණිතය",
        toolNumber = 24,
        groupNumber = 3,
        titleSinhala = "ශ්‍රිතයක් ධන හෝ සෘණ වන පරාස සෙවීම",
        titleEnglish = "Range of Values where Function is Positive/Negative",
        category = "ප්‍රස්ථාර",
        icon = "📊",
        quickSummary = "ප්‍රස්ථාරය x අක්ෂයට ඉහළින් (y > 0) හෝ පහළින් (y < 0) පවතින x අගය පරාසය ලිවීම.",
        formulaOrRule = "y > 0 වන විට ප්‍රස්ථාරය x අක්ෂයට ඉහළින් පිහිටයි; y ≤ 0 වන විට x අක්ෂය මත හෝ ඊට පහළින් පිහිටයි.",
        practicalApplication = "x² - 4 = 0 හි මූල -2 සහ 2 නම්, y < 0 වන්නේ: -2 < x < 2 පරාසයේදීය.",
        examTip = "💡 විභාගයේදී 'ශ්‍රිතය වැඩිවන විට x හි අගය පරාසය' ඇසුවහොත් හැරවුම් ලක්ෂ්‍යයේ සිට ඉහළට යන කොටස සලකන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_25",
        subject = "ගණිතය",
        toolNumber = 25,
        groupNumber = 3,
        titleSinhala = "දුර - කාල ප්‍රස්ථාර විශ්ලේෂකය",
        titleEnglish = "Distance - Time Graph Analyzer",
        category = "ප්‍රස්ථාර",
        icon = "⏱️",
        quickSummary = "දුර-කාල ප්‍රස්ථාරයක අනුක්‍රමණයෙන් වේගය (ප්‍රවේගය) නිරූපණය වේ.",
        formulaOrRule = "වේගය = අනුක්‍රමණය = දුර වෙනස / කාල වෙනස",
        practicalApplication = "තිරස් රේඛාවක් (අනුක්‍රමණය = 0) මගින් වස්තුව නිශ්චලව පවතින බව දක්වයි.",
        examTip = "💡 සාමාන්‍ය වේගය = ගමන් කළ මුළු දුර / ගතවූ මුළු කාලය."
      ),
      OlSubjectToolItem(
        id = "math_tool_26",
        subject = "ගණිතය",
        toolNumber = 26,
        groupNumber = 3,
        titleSinhala = "ප්‍රවේග - කාල ප්‍රස්ථාර විශ්ලේෂකය",
        titleEnglish = "Velocity - Time Graph Analyzer",
        category = "ප්‍රස්ථාර",
        icon = "🏎️",
        quickSummary = "අනුක්‍රමණයෙන් ත්වරණය ද, ප්‍රස්ථාරය යට වර්ගඵලයෙන් ගමන් කළ දුර (විස්ථාපනය) ද ලැබේ.",
        formulaOrRule = "ත්වරණය = අනුක්‍රමණය | ගමන් කළ දුර = ප්‍රස්ථාරය යට වර්ගඵලය (ත්‍රිකෝණ, ත්‍රපීසියම් වර්ගඵල)",
        practicalApplication = "ත්‍රපීසියම් හැඩැති ප්‍රස්ථාරයක දුර = ½ × (සමාන්තර පාදවල එකතුව) × උස.",
        examTip = "💡 මන්දනය යනු සෘණ අනුක්‍රමණයයි (පහළට බසින රේඛාව)."
      ),
      OlSubjectToolItem(
        id = "math_tool_27",
        subject = "ගණිතය",
        toolNumber = 27,
        groupNumber = 3,
        titleSinhala = "සමකාලීන අසමානතා ප්‍රදේශය (අඳුරු කිරීම)",
        titleEnglish = "Region of Inequalities (Shading Graphs)",
        category = "ප්‍රස්ථාර",
        icon = "🖌️",
        quickSummary = "රේඛාව ඇඳ පරීක්ෂණ ලක්ෂ්‍යයක් (0,0) ආදේශ කර අදාළ නොවන පෙදෙස කපා හැරීම.",
        formulaOrRule = "රේඛාව ඇතුළත් නම් (≤, ≥) තද රේඛාවක්ද, ඇතුළත් නොවේ නම් (<, >) කඩඉරි රේඛාවක්ද අඳින්න.",
        practicalApplication = "y ≤ 2x + 1: (0,0) ආදේශ කළ විට 0 ≤ 1 සත්‍ය බැවින් (0,0) අඩංගු පැත්ත පිළිතුර වේ.",
        examTip = "💡 ප්‍රශ්නයේ ඉල්ලා ඇත්තේ 'අවශ්‍ය ප්‍රදේශය අඳුරු කරන්න' ද නැතහොත් 'අනවශ්‍ය පෙදෙස කපා හරින්න' දැයි ප්‍රවේශමෙන් කියවන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_28",
        subject = "ගණිතය",
        toolNumber = 28,
        groupNumber = 3,
        titleSinhala = "ප්‍රතිලෝම විචලන ප්‍රස්ථාරය (xy = c හෝ y = c/x)",
        titleEnglish = "Inverse Variation Hyperbola Graph",
        category = "ප්‍රස්ථාර",
        icon = "〰️",
        quickSummary = "හයිපර්බෝලා හැඩැති වක්‍රය: x වැඩිවන විට y ශීඝ්‍රයෙන් අඩුවේ.",
        formulaOrRule = "y = k / x (x ≠ 0, කිසිවිටෙකත් අක්ෂ ස්පර්ශ නොකරයි - අනන්තස්පර්ශී).",
        practicalApplication = "පීඩනය සහ පරිමාව (බොයිල් නියමය PV = k) මෙවැනි ප්‍රස්ථාරයකින් දැක්වේ.",
        examTip = "💡 වක්‍රය සුමටව අඳින්න; ලක්ෂ්‍ය යා කිරීමට අඩි රූලක් භාවිත නොකරන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_29",
        subject = "ගණිතය",
        toolNumber = 29,
        groupNumber = 3,
        titleSinhala = "ශ්‍රිත අංකනය f(x) සහ අගය සෙවීම",
        titleEnglish = "Function Notation f(x) & Evaluation",
        category = "ශ්‍රිත",
        icon = "ƒ",
        quickSummary = "f(x) ශ්‍රිතයක x වෙනුවට දී ඇති සංඛ්‍යාව ආදේශ කර ප්‍රතිදාන අගය සෙවීම.",
        formulaOrRule = "f(x) = 2x² - 3x + 1 නම් f(2) = 2(2)² - 3(2) + 1 = 8 - 6 + 1 = 3.",
        practicalApplication = "f(x) = 0 වන x අගයන් යනු ශ්‍රිතයේ ශුන්‍යයන් (Zeros of the function) වේ.",
        examTip = "💡 f(-x) සුළු කිරීමේදී සෘණ සංඛ්‍යා වරහන් තුළ තබා වර්ග කිරීමට වගබලාගන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_30",
        subject = "ගණිතය",
        toolNumber = 30,
        groupNumber = 3,
        titleSinhala = "ප්‍රස්ථාර පරිමාණ තේරීම සහ නිරවද්‍යතාව",
        titleEnglish = "Graph Scale Selection & Accuracy Tool",
        category = "ප්‍රස්ථාර",
        icon = "📏",
        quickSummary = "ප්‍රස්ථාර කඩදාසියේ කුඩා කොටස් 10කින් නිරූපණය වන අගය නිවැරදිව තීරණය කිරීම.",
        formulaOrRule = "පරිමාණය = (පරාසය) / (ප්‍රස්ථාරයේ ඇති කොටස් ගණන)",
        practicalApplication = "කුඩා කොටස් 10ක් ඒකක 1ක් නම් එක් කුඩා කොටසක් = 0.1 කි.",
        examTip = "💡 ප්‍රස්ථාරයේ ලක්ෂ්‍ය සලකුණු කිරීමට සියුම්ව උල් කළ පැන්සලක් භාවිත කර කුඩා කතිර (×) හෝ තිත් වටා කුඩා කව යොදන්න."
      ),

      // --- GROUP 4: සමාන්තර සහ ගුණෝත්තර ශ්‍රේඪි (31-40) ---
      OlSubjectToolItem(
        id = "math_tool_31",
        subject = "ගණිතය",
        toolNumber = 31,
        groupNumber = 4,
        titleSinhala = "සමාන්තර ශ්‍රේඪියක n වන පදය සෙවීම",
        titleEnglish = "Arithmetic Progression n-th Term (Tn = a + (n-1)d)",
        category = "ශ්‍රේඪි",
        icon = "🔢",
        quickSummary = "පළමු පදය a සහ පොදු අන්තරය d වන සමාන්තර ශ්‍රේඪියක ඕනෑම පදයක් සෙවීම.",
        formulaOrRule = "T_n = a + (n - 1)d (මෙහි d = T₂ - T₁ = T₃ - T₂)",
        practicalApplication = "3, 7, 11, 15... ශ්‍රේඪියේ a = 3, d = 4. 20 වන පදය: T₂₀ = 3 + (20 - 1) × 4 = 3 + 76 = 79.",
        examTip = "💡 ශ්‍රේඪියේ අගයන් අඩුවේ නම් d ඍණ අගයක් වේ (උදා: 20, 15, 10... හි d = -5)."
      ),
      OlSubjectToolItem(
        id = "math_tool_32",
        subject = "ගණිතය",
        toolNumber = 32,
        groupNumber = 4,
        titleSinhala = "සමාන්තර ශ්‍රේඪියක මුල් පද n හි එකතුව",
        titleEnglish = "Sum of AP (Sn = n/2 [2a + (n-1)d])",
        category = "ශ්‍රේඪි",
        icon = "➕",
        quickSummary = "අවසාන පදය l දන්නේ නම් S_n = n/2 (a + l) සූත්‍රයද භාවිත කළ හැක.",
        formulaOrRule = "S_n = n/2 [2a + (n - 1)d] හෝ S_n = n/2 (a + l)",
        practicalApplication = "2, 4, 6... 100 දක්වා ඉරට්ට සංඛ්‍යා 50 හි එකතුව: S₅₀ = 50/2 (2 + 100) = 25 × 102 = 2550.",
        examTip = "💡 ගැටලුවක 'පද කීයක එකතුව X වේද' ඇසුවහොත් n සෙවීමට වර්ගජ සමීකරණයක් විසඳිය යුතුය (n ධන නිඛිලයක් විය යුතුය)."
      ),
      OlSubjectToolItem(
        id = "math_tool_33",
        subject = "ගණිතය",
        toolNumber = 33,
        groupNumber = 4,
        titleSinhala = "ගුණෝත්තර ශ්‍රේඪියක n වන පදය සෙවීම",
        titleEnglish = "Geometric Progression n-th Term (Tn = a r^{n-1})",
        category = "ශ්‍රේඪි",
        icon = "✖️",
        quickSummary = "පළමු පදය a සහ පොදු අනුපාතය r වන ගුණෝත්තර ශ්‍රේඪියක පද සෙවීම.",
        formulaOrRule = "T_n = a × r^{n-1} (මෙහි r = T₂ / T₁)",
        practicalApplication = "3, 6, 12, 24... ශ්‍රේඪියේ a = 3, r = 2. 8 වන පදය: T₈ = 3 × 2⁷ = 3 × 128 = 384.",
        examTip = "💡 ලකුණු මාරුවන ශ්‍රේඪිවල (උදා: 2, -6, 18...) r ඍණ අගයකි (r = -3)."
      ),
      OlSubjectToolItem(
        id = "math_tool_34",
        subject = "ගණිතය",
        toolNumber = 34,
        groupNumber = 4,
        titleSinhala = "ගුණෝත්තර ශ්‍රේඪියක මුල් පද n හි එකතුව",
        titleEnglish = "Sum of GP (Sn = a(r^n - 1)/(r - 1))",
        category = "ශ්‍රේඪි",
        icon = "∑",
        quickSummary = "r > 1 විට S_n = a(r^n - 1)/(r - 1) ද, r < 1 විට S_n = a(1 - r^n)/(1 - r) ද භාවිත වේ.",
        formulaOrRule = "S_n = a(r^n - 1) / (r - 1) [r ≠ 1]",
        practicalApplication = "1, 2, 4, 8... හි මුල් පද 10 හි එකතුව: S₁₀ = 1(2¹⁰ - 1) / (2 - 1) = 1024 - 1 = 1023.",
        examTip = "💡 r = 1 නම් එකතුව සරලවම na වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_35",
        subject = "ගණිතය",
        toolNumber = 35,
        groupNumber = 4,
        titleSinhala = "ශ්‍රේඪි ආශ්‍රිත ව්‍යවහාරික ගැටලු විසඳීම",
        titleEnglish = "Applied Real-World Word Problems on Progressions",
        category = "ශ්‍රේඪි",
        icon = "💰",
        quickSummary = "මුදල් ඉතිරි කිරීම, බැක්ටීරියා ගුණනය, ත්‍රිකෝණාකාර සැකසුම් ආදී ගැටලු විසඳීම.",
        formulaOrRule = "නියත අගයකින් එකතු වේ නම් -> සමාන්තර ශ්‍රේඪියකි | නියත සාධකයකින් ගුණ වේ නම් -> ගුණෝත්තර ශ්‍රේඪියකි.",
        practicalApplication = "පළමු දින රු. 10ක්ද, දෙවන දින රු. 20ක්ද, තෙවන දින රු. 30ක්ද ලෙස දින 30ක් ඉතිරි කළහොත් මුළු මුදල: S₃₀ = 30/2 [2(10) + 29(10)] = 15 [310] = රු. 4650.",
        examTip = "💡 ගැටලුවේ අසන්නේ 'අවසාන දිනයේ මුදල' (Tn) ද නැතහොත් 'මුළු මුදල' (Sn) දැයි පැහැදිලිව වටහා ගන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_36",
        subject = "ගණිතය",
        toolNumber = 36,
        groupNumber = 4,
        titleSinhala = "ප්‍රථමක සංඛ්‍යා සහ සංයුක්ත සංඛ්‍යා පරීක්ෂක",
        titleEnglish = "Prime Numbers & Composite Numbers Checker",
        category = "සංඛ්‍යා",
        icon = "🔢",
        quickSummary = "සාධක 2ක් පමණක් ඇති සංඛ්‍යා (1 සහ එම සංඛ්‍යාව පමණි) ප්‍රථමක සංඛ්‍යා වේ.",
        formulaOrRule = "1 සිට 50 දක්වා ප්‍රථමක සංඛ්‍යා: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47 (එකතුව 15කි).",
        practicalApplication = "2 යනු ඇති එකම ඉරට්ට ප්‍රථමක සංඛ්‍යාවයි. 1 ප්‍රථමක සංඛ්‍යාවක්ද නොවේ; සංයුක්ත සංඛ්‍යාවක්ද නොවේ.",
        examTip = "💡 ප්‍රථමක සාධක ගසක් (Factor tree) ඇඳීමෙන් ඕනෑම සංඛ්‍යාවක් ප්‍රථමක සාධකවල ගුණිතයක් ලෙස ලිවිය හැක."
      ),
      OlSubjectToolItem(
        id = "math_tool_37",
        subject = "ගණිතය",
        toolNumber = 37,
        groupNumber = 4,
        titleSinhala = "ත්‍රිකෝණ සංඛ්‍යා සහ චතුරස්‍ර සංඛ්‍යා",
        titleEnglish = "Triangular & Square Number Patterns",
        category = "සංඛ්‍යා රටා",
        icon = "🔺",
        quickSummary = "ත්‍රිකෝණ සංඛ්‍යා: 1, 3, 6, 10, 15, 21... | චතුරස්‍ර සංඛ්‍යා: 1, 4, 9, 16, 25...",
        formulaOrRule = "n වන ත්‍රිකෝණ සංඛ්‍යාව = n(n + 1) / 2 | n වන චතුරස්‍ර සංඛ්‍යාව = n²",
        practicalApplication = "යාබද ත්‍රිකෝණ සංඛ්‍යා දෙකක එකතුව සෑම විටම චතුරස්‍ර සංඛ්‍යාවකි (උදා: 1+3=4, 3+6=9, 6+10=16).",
        examTip = "💡 8 වන ත්‍රිකෝණ සංඛ්‍යාව = 8 × 9 / 2 = 36."
      ),
      OlSubjectToolItem(
        id = "math_tool_38",
        subject = "ගණිතය",
        toolNumber = 38,
        groupNumber = 4,
        titleSinhala = "සමාන්තර මධ්‍යන්‍යය සහ ගුණෝත්තර මධ්‍යන්‍යය",
        titleEnglish = "Arithmetic & Geometric Means",
        category = "ශ්‍රේඪි",
        icon = "⚖️",
        quickSummary = "සංඛ්‍යා දෙකක් අතර සමාන්තර හෝ ගුණෝත්තර මධ්‍යන්‍යය සෙවීම.",
        formulaOrRule = "සමාන්තර මධ්‍යන්‍යය = (a + b) / 2 | ගුණෝත්තර මධ්‍යන්‍යය = √(ab)",
        practicalApplication = "4 සහ 16 හි සමාන්තර මධ්‍යන්‍යය = (4 + 16)/2 = 10; ගුණෝත්තර මධ්‍යන්‍යය = √(4 × 16) = √64 = 8.",
        examTip = "💡 සැමවිටම AM ≥ GM වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_39",
        subject = "ගණිතය",
        toolNumber = 39,
        groupNumber = 4,
        titleSinhala = "ෆිබොනාච්චි (Fibonacci) සංඛ්‍යා අනුක්‍රමය",
        titleEnglish = "Fibonacci Sequence Tool",
        category = "සංඛ්‍යා රටා",
        icon = "🐚",
        quickSummary = "කලින් ඇති සංඛ්‍යා දෙකේ එකතුවෙන් ඊළඟ සංඛ්‍යාව සෑදෙන සුප්‍රසිද්ධ ස්වභාවික රටාව.",
        formulaOrRule = "F_n = F_{n-1} + F_{n-2} (0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55...)",
        practicalApplication = "මල් පෙති ගණන, පයින් ගෙඩි සහ බෙලි කටුවල සර්පිල සැකැස්ම ෆිබොනාච්චි රටාව අනුගමනය කරයි.",
        examTip = "💡 යාබද පද අතර අනුපාතය ස්වර්ණමය අනුපාතයට (Golden Ratio ≈ 1.618) ආසන්න වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_40",
        subject = "ගණිතය",
        toolNumber = 40,
        groupNumber = 4,
        titleSinhala = "ද්විපද සංගුණක සහ පැස්කල් ත්‍රිකෝණය",
        titleEnglish = "Pascal's Triangle & Binomial Coefficients",
        category = "වීජ ගණිතය",
        icon = "📐",
        quickSummary = "(a + b)^n ප්‍රසාරණයේ සංගුණක පහසුවෙන් ලබාගන්නා ත්‍රිකෝණාකාර සංඛ්‍යා රටාව.",
        formulaOrRule = "පේළි: 1 / 1 1 / 1 2 1 / 1 3 3 1 / 1 4 6 4 1 ...",
        practicalApplication = "(a + b)³ = a³ + 3a²b + 3ab² + b³; (a + b)⁴ = a⁴ + 4a³b + 6a²b² + 4ab³ + b⁴.",
        examTip = "💡 පැස්කල් ත්‍රිකෝණයේ n වන පේළියේ සංඛ්‍යාවල එකතුව 2^n වේ."
      ),

      // --- GROUP 5: මිනුම් විද්‍යාව: වර්ගඵලය සහ පරිමාව (41-50) ---
      OlSubjectToolItem(
        id = "math_tool_41",
        subject = "ගණිතය",
        toolNumber = 41,
        groupNumber = 5,
        titleSinhala = "වෘත්තයක පරිධිය සහ වර්ගඵල සූත්‍ර",
        titleEnglish = "Circle Circumference & Area (C = 2πr, A = πr²)",
        category = "මිනුම් විද්‍යාව",
        icon = "⚪",
        quickSummary = "අරය r වන වෘත්තයක වට ප්‍රමාණය සහ අභ්‍යන්තර වර්ගඵලය ගණනය කිරීම.",
        formulaOrRule = "පරිධිය C = 2πr = πd | වර්ගඵලය A = πr² (π ≈ 22/7 හෝ 3.14)",
        practicalApplication = "අරය 7 cm වන වෘත්තයක: පරිධිය = 2 × (22/7) × 7 = 44 cm; වර්ගඵලය = (22/7) × 7² = 154 cm².",
        examTip = "💡 අර්ධ වෘත්තයක පරිමිතිය = πr + 2r (විෂ්කම්භය එකතු කිරීමට අමතක නොකරන්න)."
      ),
      OlSubjectToolItem(
        id = "math_tool_42",
        subject = "ගණිතය",
        toolNumber = 42,
        groupNumber = 5,
        titleSinhala = "කේන්ද්‍රික ඛණ්ඩයක චාප දිග සහ වර්ගඵලය",
        titleEnglish = "Sector Arc Length & Area Tool",
        category = "මිනුම් විද්‍යාව",
        icon = "🍕",
        quickSummary = "කේන්ද්‍ර කෝණය θ වන කේන්ද්‍රික ඛණ්ඩයක කොටස් ගණනය කිරීම.",
        formulaOrRule = "චාප දිග s = (θ / 360°) × 2πr | වර්ගඵලය A = (θ / 360°) × πr²",
        practicalApplication = "θ = 60° සහ r = 21 cm නම්: චාප දිග = (60/360) × 2 × (22/7) × 21 = 22 cm. වර්ගඵලය = (1/6) × (22/7) × 21² = 231 cm².",
        examTip = "💡 කේන්ද්‍රික ඛණ්ඩයක පරිමිතිය = චාප දිග + අරයන් දෙක (s + 2r)."
      ),
      OlSubjectToolItem(
        id = "math_tool_43",
        subject = "ගණිතය",
        toolNumber = 43,
        groupNumber = 5,
        titleSinhala = "ත්‍රපීසියමක සහ සමාන්තරාස්‍රයක වර්ගඵලය",
        titleEnglish = "Trapezium & Parallelogram Area Tool",
        category = "මිනුම් විද්‍යාව",
        icon = "⏢",
        quickSummary = "ත්‍රපීසියමේ සමාන්තර පාද a සහ b, ලම්භ උස h වන විට වර්ගඵලය.",
        formulaOrRule = "ත්‍රපීසියම් වර්ගඵලය = ½ (a + b) h | සමාන්තරාස්‍ර වර්ගඵලය = ආධාරකය × ලම්භ උස (b × h)",
        practicalApplication = "සමාන්තර පාද 10 cm සහ 14 cm ද, ලම්භ උස 6 cm ද වන ත්‍රපීසියමේ වර්ගඵලය = ½ (10 + 14) × 6 = 12 × 6 = 72 cm².",
        examTip = "💡 ලම්භ උස ඇල පාදයේ දිග නොවන බව සලකන්න; එය සමාන්තර පාද අතර සිරස් දුරයි."
      ),
      OlSubjectToolItem(
        id = "math_tool_44",
        subject = "ගණිතය",
        toolNumber = 44,
        groupNumber = 5,
        titleSinhala = "සිලින්ඩරයක පරිමාව සහ පෘෂ්ඨ වර්ගඵලය",
        titleEnglish = "Cylinder Volume & Surface Area (V = πr²h)",
        category = "මිනුම් විද්‍යාව",
        icon = "🛢️",
        quickSummary = "අරය r සහ උස h වන සිලින්ඩරයක පරිමාව, වක්‍ර පෘෂ්ඨ සහ මුළු පෘෂ්ඨ වර්ගඵලය.",
        formulaOrRule = "පරිමාව V = πr²h | වක්‍ර පෘෂ්ඨ වර්ගඵලය = 2πrh | මුළු පෘෂ්ඨ වර්ගඵලය = 2πrh + 2πr²",
        practicalApplication = "r = 7 cm, h = 10 cm: V = (22/7) × 7² × 10 = 1540 cm³; වක්‍ර පෘෂ්ඨ වර්ගඵලය = 2 × (22/7) × 7 × 10 = 440 cm².",
        examTip = "💡 1000 cm³ = 1 L (ලීටර්) වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_45",
        subject = "ගණිතය",
        toolNumber = 45,
        groupNumber = 5,
        titleSinhala = "කේතුවක පරිමාව සහ වක්‍ර පෘෂ්ඨ වර්ගඵලය",
        titleEnglish = "Cone Volume & Curved Surface Area (V = ⅓πr²h)",
        category = "මිනුම් විද්‍යාව",
        icon = "🍦",
        quickSummary = "අරය r, සිරස් උස h සහ ඇල උස l වන කේතුවක ගණනය කිරීම්.",
        formulaOrRule = "පරිමාව V = ⅓ πr² h | වක්‍ර පෘෂ්ඨ වර්ගඵලය = π r l (මෙහි l² = r² + h²)",
        practicalApplication = "r = 3 cm, h = 4 cm නම් l = √(3² + 4²) = 5 cm. V = ⅓ × π × 9 × 4 = 12π cm³; වක්‍ර පෘෂ්ඨය = π × 3 × 5 = 15π cm².",
        examTip = "💡 සිලින්ඩරයක සහ එකම අරය හා උස ඇති කේතුවක පරිමාවන් අතර අනුපාතය 3 : 1 වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_46",
        subject = "ගණිතය",
        toolNumber = 46,
        groupNumber = 5,
        titleSinhala = "ගෝලයක පරිමාව සහ පෘෂ්ඨ වර්ගඵලය",
        titleEnglish = "Sphere Volume & Surface Area (V = 4/3 πr³)",
        category = "මිනුම් විද්‍යාව",
        icon = "⚽",
        quickSummary = "අරය r වන ගෝලයක පරිමාව සහ මුළු මතුපිට වර්ගඵලය.",
        formulaOrRule = "පරිමාව V = (4/3) πr³ | පෘෂ්ඨ වර්ගඵලය A = 4πr²",
        practicalApplication = "අරය 7 cm වන ගෝලයක පෘෂ්ඨ වර්ගඵලය = 4 × (22/7) × 7² = 616 cm².",
        examTip = "💡 අර්ධ ගෝලයක මුළු පෘෂ්ඨ වර්ගඵලය = 3πr² (වක්‍ර පෘෂ්ඨය 2πr² + පතුලේ තල වෘත්තය πr²)."
      ),
      OlSubjectToolItem(
        id = "math_tool_47",
        subject = "ගණිතය",
        toolNumber = 47,
        groupNumber = 5,
        titleSinhala = "ප්‍රිස්මයක පරිමාව සහ මුළු පෘෂ්ඨ වර්ගඵලය",
        titleEnglish = "Prism Volume & Total Surface Area",
        category = "මිනුම් විද්‍යාව",
        icon = "📐",
        quickSummary = "ඕනෑම ඒකාකාර හරස්කඩක් සහිත ප්‍රිස්මයක පරිමාව.",
        formulaOrRule = "පරිමාව = හරස්කඩ වර්ගඵලය × දිග (A × L)",
        practicalApplication = "ත්‍රිකෝණාකාර හරස්කඩ වර්ගඵලය 15 cm² වන ප්‍රිස්මයක දිග 20 cm නම් පරිමාව = 15 × 20 = 300 cm³.",
        examTip = "💡 මුළු පෘෂ්ඨ වර්ගඵලය සෙවීමට හරස්කඩ 2 හි වර්ගඵලය සහ වටේ ඇති සෘජුකෝණාස්‍රවල වර්ගඵල එකතු කරන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_48",
        subject = "ගණිතය",
        toolNumber = 48,
        groupNumber = 5,
        titleSinhala = "පිරමිඩයක පරිමාව ගණක සූත්‍රය",
        titleEnglish = "Pyramid Volume Formula (V = ⅓ × Base Area × h)",
        category = "මිනුම් විද්‍යාව",
        icon = "🔺",
        quickSummary = "සමචතුරස්‍රාකාර හෝ සෘජුකෝණාස්‍රාකාර ආධාරකයක් සහිත පිරමිඩයක පරිමාව.",
        formulaOrRule = "පරිමාව V = ⅓ × ආධාරක වර්ගඵලය × සිරස් උස",
        practicalApplication = "පාදයක දිග 6 cm වන සමචතුරස්‍රාකාර පිරමිඩයක උස 10 cm නම්: V = ⅓ × (6 × 6) × 10 = ⅓ × 36 × 10 = 120 cm³.",
        examTip = "💡 සිරස් උස (h) සහ ඇල මුහුණතේ ඇල උස එකිනෙකට වෙනස් බව මතක තබාගන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_49",
        subject = "ගණිතය",
        toolNumber = 49,
        groupNumber = 5,
        titleSinhala = "සංයුක්ත ඝන වස්තුවල පරිමාව සහ ද්‍රව ගැලීම්",
        titleEnglish = "Composite Solids & Liquid Flow Rate",
        category = "මිනුම් විද්‍යාව",
        icon = "🚰",
        quickSummary = "සිලින්ඩරයක් මත කේතුවක් හෝ අර්ධ ගෝලයක් සහිත සංයුක්ත වස්තු සහ ජලය පිරීමේ කාලය.",
        formulaOrRule = "මුළු පරිමාව = V₁ + V₂ | පිරෙන කාලය = මුළු පරිමාව / ගලා ඒමේ සීඝ්‍රතාව",
        practicalApplication = "120 L ටැංකියකට මිනිත්තුවට 15 L බැගින් ජලය ගලා එන්නේ නම් පිරීමට ගතවන කාලය: 120 / 15 = මිනිත්තු 8.",
        examTip = "💡 ඝන මීටර 1ක් (1 m³) = ලීටර් 1000ක් (1000 L) වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_50",
        subject = "ගණිතය",
        toolNumber = 50,
        groupNumber = 5,
        titleSinhala = "ඒකක පරිවර්තනය (දිග, වර්ගඵලය, පරිමාව, ස්කන්ධය)",
        titleEnglish = "Units Converter (mm, cm, m, km, ha, L, kg, t)",
        category = "මිනුම් විද්‍යාව",
        icon = "🔄",
        quickSummary = "ජාත්‍යන්තර සම්මත ඒකක එකිනෙකට පරිවර්තනය කිරීමේ නීති.",
        formulaOrRule = "1 m² = 10,000 cm² | 1 m³ = 1,000,000 cm³ | 1 හෙක්ටයාරය (ha) = 10,000 m² | 1 ටොන් = 1000 kg",
        practicalApplication = "වර්ගඵල ඒකක පරිවර්තනයේදී පරිවර්තන සාධකය වර්ග කළ යුතුය (100² = 10,000).",
        examTip = "💡 විභාගයේදී සියලුම මිනුම් එකම ඒකකයට (උදා: සියල්ල cm වලට හෝ m වලට) හරවා ගණනය ආරම්භ කරන්න."
      ),

      // --- GROUP 6: ත්‍රිකෝණමිතිය සහ කෝණ (51-60) ---
      OlSubjectToolItem(
        id = "math_tool_51",
        subject = "ගණිතය",
        toolNumber = 51,
        groupNumber = 6,
        titleSinhala = "පයිතගරස් ප්‍රමේයය සහ ත්‍රික",
        titleEnglish = "Pythagoras Theorem & Pythagorean Triples",
        category = "ත්‍රිකෝණමිතිය",
        icon = "📐",
        quickSummary = "සෘජුකෝණී ත්‍රිකෝණයක කර්ණයේ වර්ගය අනෙක් පාද දෙකේ වර්ගවල එකතුවට සමාන වේ.",
        formulaOrRule = "c² = a² + b² (c = කර්ණය)",
        practicalApplication = "සුප්‍රසිද්ධ පයිතගරස් ත්‍රික: (3, 4, 5), (5, 12, 13), (7, 24, 25), (8, 15, 17).",
        examTip = "💡 කර්ණය යනු සෘජුකෝණයට (90°) ඉදිරියෙන් ඇති දිගම පාදයයි."
      ),
      OlSubjectToolItem(
        id = "math_tool_52",
        subject = "ගණිතය",
        toolNumber = 52,
        groupNumber = 6,
        titleSinhala = "මූලික ත්‍රිකෝණමිතික අනුපාත (Sin, Cos, Tan)",
        titleEnglish = "Trigonometric Ratios (SOH CAH TOA)",
        category = "ත්‍රිකෝණමිතිය",
        icon = "🔺",
        quickSummary = "සෘජුකෝණී ත්‍රිකෝණයක කෝණයක් ආශ්‍රිතව පාද අතර අනුපාතය.",
        formulaOrRule = "Sin θ = සම්මුඛ / කර්ණය | Cos θ = බද්ධ / කර්ණය | Tan θ = සම්මුඛ / බද්ධ = Sin θ / Cos θ",
        practicalApplication = "කෝණය 30° වන විට Sin 30° = 1/2, Cos 30° = √3/2, Tan 30° = 1/√3.",
        examTip = "💡 SOH-CAH-TOA මතක තබාගැනීමේ කෙටි ක්‍රමයකි: Sin = Opp/Hyp, Cos = Adj/Hyp, Tan = Opp/Adj."
      ),
      OlSubjectToolItem(
        id = "math_tool_53",
        subject = "ගණිතය",
        toolNumber = 53,
        groupNumber = 6,
        titleSinhala = "විශේෂ කෝණවල ත්‍රිකෝණමිතික අගයන් (30°, 45°, 60°)",
        titleEnglish = "Special Angles Exact Values (30°, 45°, 60°)",
        category = "ත්‍රිකෝණමිතිය",
        icon = "🎯",
        quickSummary = "වගු නොබලා ක්ෂණිකව ලිවිය හැකි සම්මත කෝණ අගයන්.",
        formulaOrRule = "Sin: 0°->0, 30°->1/2, 45°->1/√2, 60°->√3/2, 90°->1 | Tan 45° = 1",
        practicalApplication = "Tan 45° = 1 වන බැවින්, 45° ආරෝහණ කෝණයකදී ගසක උස සහ ගස පාමුලට ඇති දුර සමාන වේ.",
        examTip = "💡 විභාගයේදී √2 ≈ 1.414 සහ √3 ≈ 1.732 ලෙස ආදේශ කිරීමට උපදෙස් දිය හැක."
      ),
      OlSubjectToolItem(
        id = "math_tool_54",
        subject = "ගණිතය",
        toolNumber = 54,
        groupNumber = 6,
        titleSinhala = "ආරෝහණ කෝණ සහ අවරෝහණ කෝණ මෙවලම",
        titleEnglish = "Angles of Elevation & Depression",
        category = "ත්‍රිකෝණමිතිය",
        icon = "🔭",
        quickSummary = "තිරස් දෘෂ්ටි රේඛාවට සාපේක්ෂව ඉහළ බලන කෝණය (ආරෝහණ) සහ පහළ බලන කෝණය (අවරෝහණ).",
        formulaOrRule = "නිරීක්ෂකයාගේ අවරෝහණ කෝණය = වස්තුවේ සිට නිරීක්ෂකයා දෙසට ඇති ආරෝහණ කෝණය (ඒකාන්තර කෝණ සමාන බැවින්).",
        practicalApplication = "කුළුණක සිට 20 m ඈතින් සිට කුළුණු මුදුන දෙස බලන විට ආරෝහණ කෝණය 30° නම්: Tan 30° = h / 20 => h = 20 × (1/√3) ≈ 11.55 m.",
        examTip = "💡 නිරීක්ෂකයාගේ ඇසේ උස දී ඇත්නම්, ගණනය කළ h අගයට ඇසේ උසද එකතු කළ යුතුය."
      ),
      OlSubjectToolItem(
        id = "math_tool_55",
        subject = "ගණිතය",
        toolNumber = 55,
        groupNumber = 6,
        titleSinhala = "දිගංශය සහ නාවික ගමන් මාර්ග (Bearings)",
        titleEnglish = "Three-Figure Bearings (000° to 360°)",
        category = "ත්‍රිකෝණමිතිය",
        icon = "🧭",
        quickSummary = "උතුරු දිශාවේ (000°) සිට ඔරලෝසු කටු කැරකෙන දිශාවට මනින ත්‍රි-අංක කෝණය.",
        formulaOrRule = "උතුර = 000°/360°, නැගෙනහිර = 090°, දකුණ = 180°, බටහිර = 270° | A සිට B හි දිගංශය θ නම්, B සිට A හි දිගංශය = θ ± 180°",
        practicalApplication = "නැගෙනහිරට උතුරින් 30° යනු 060° දිගංශයයි. A සිට B හි දිගංශය 070° නම්, B සිට A හි පසු දිගංශය = 70° + 180° = 250°.",
        examTip = "💡 දිගංශය සෑම විටම ඉලක්කම් 3කින් ලිවිය යුතුය (උදා: 45° වෙනුවට 045°)."
      ),
      OlSubjectToolItem(
        id = "math_tool_56",
        subject = "ගණිතය",
        toolNumber = 56,
        groupNumber = 6,
        titleSinhala = "ත්‍රිකෝණයක වර්ගඵලය: ½ ab Sin C සූත්‍රය",
        titleEnglish = "Triangle Area using Sine Rule (Area = ½ ab Sin C)",
        category = "ත්‍රිකෝණමිතිය",
        icon = "📐",
        quickSummary = "ලම්භ උස නොදන්නා ඕනෑම ත්‍රිකෝණයක පාද දෙකක් සහ අන්තර්ගත කෝණය දන්නා විට වර්ගඵලය.",
        formulaOrRule = "වර්ගඵලය = ½ × a × b × Sin(C)",
        practicalApplication = "පාද 8 cm සහ 10 cm ද, අන්තර්ගත කෝණය 30° ද වන ත්‍රිකෝණයේ වර්ගඵලය = ½ × 8 × 10 × Sin(30°) = 40 × 0.5 = 20 cm².",
        examTip = "💡 අන්තර්ගත කෝණය 90° වන විට Sin 90° = 1 වී සූත්‍රය ½ × ආධාරකය × උස බවට පත්වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_57",
        subject = "ගණිතය",
        toolNumber = 57,
        groupNumber = 6,
        titleSinhala = "සයින් නීතිය (Sine Rule) විසඳුම් මෙවලම",
        titleEnglish = "Sine Rule: a/Sin(A) = b/Sin(B) = c/Sin(C)",
        category = "ත්‍රිකෝණමිතිය",
        icon = "🔺",
        quickSummary = "ඕනෑම ත්‍රිකෝණයක පාද සහ ඒවාට සම්මුඛ කෝණවල සයින් අගයන් අතර අනුපාතය නියතයකි.",
        formulaOrRule = "a / Sin(A) = b / Sin(B) = c / Sin(C)",
        practicalApplication = "කෝණ 2ක් සහ එක් පාදයක් දන්නා විට හෝ පාද 2ක් සහ එක් සම්මුඛ කෝණයක් දන්නා විට අඥාත පාද/කෝණ සෙවීමට යොදාගනී.",
        examTip = "💡 සෘජුකෝණී නොවන ත්‍රිකෝණ විසඳීමට සයින් නීතිය ඉතා ප්‍රබල මෙවලමකි."
      ),
      OlSubjectToolItem(
        id = "math_tool_58",
        subject = "ගණිතය",
        toolNumber = 58,
        groupNumber = 6,
        titleSinhala = "කොසයින් නීතිය (Cosine Rule)",
        titleEnglish = "Cosine Rule: c² = a² + b² - 2ab Cos(C)",
        category = "ත්‍රිකෝණමිතිය",
        icon = "📐",
        quickSummary = "පාද 3ම දන්නා විට කෝණ සෙවීමට හෝ පාද 2ක් හා අන්තර්ගත කෝණය දන්නා විට තුන්වන පාදය සෙවීම.",
        formulaOrRule = "c² = a² + b² - 2ab Cos(C) | Cos(C) = (a² + b² - c²) / (2ab)",
        practicalApplication = "C = 90° වන විට Cos 90° = 0 වී පයිතගරස් ප්‍රමේයය (c² = a² + b²) ලැබේ.",
        examTip = "💡 කෝණය මහා කෝණයක් (90° < C < 180°) නම් Cos C ඍණ අගයක් ගන්නා බව මතක තබාගන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_59",
        subject = "ගණිතය",
        toolNumber = 59,
        groupNumber = 6,
        titleSinhala = "ත්‍රිකෝණමිතික සර්වසාම්‍ය (Sin²θ + Cos²θ = 1)",
        titleEnglish = "Trigonometric Identity (Sin²θ + Cos²θ = 1)",
        category = "ත්‍රිකෝණමිතිය",
        icon = "1️⃣",
        quickSummary = "ඕනෑම θ කෝණයක් සඳහා Sin²θ + Cos²θ හි අගය නිරන්තරයෙන්ම 1 ට සමාන වේ.",
        formulaOrRule = "Sin²θ + Cos²θ = 1 | Sin²θ = 1 - Cos²θ | Cos²θ = 1 - Sin²θ",
        practicalApplication = "Sin θ = 3/5 නම් Cos θ = √(1 - (3/5)²) = √(1 - 9/25) = √(16/25) = 4/5.",
        examTip = "💡 Tan θ = Sin θ / Cos θ සම්බන්ධය සමග එක්ව සර්වසාම්‍ය සාධනයට භාවිත වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_60",
        subject = "ගණිතය",
        toolNumber = 60,
        groupNumber = 6,
        titleSinhala = "ස්වාභාවික සයින් සහ ටැන්ජන්ට් වගු කියවීම",
        titleEnglish = "Natural Sines & Tangents Tables Tool",
        category = "ත්‍රිකෝණමිතිය",
        icon = "📖",
        quickSummary = "අංශක සහ කලා (Minutes: 1° = 60') සහිත ත්‍රිකෝණමිතික වගු නිවැරදිව කියවීම.",
        formulaOrRule = "මධ්‍යන්‍ය අන්තරය (Mean difference) සයින් සහ ටැන්ජන්ට්වලදී එකතු කළ යුතුය; කොසයින්වලදී අඩු කළ යුතුය.",
        practicalApplication = "Sin(32° 24') සෙවීමට: 32° පේළියේ 24' තීරුවේ අගය ලබාගනී.",
        examTip = "💡 අංශක දශම කලා බවට පත්කිරීම: 0.1° = 6', 0.5° = 30'."
      ),

      // --- GROUP 7: ජ්‍යාමිතිය: කෝණ, ත්‍රිකෝණ සහ සමාන්තරාස්‍ර (61-70) ---
      OlSubjectToolItem(
        id = "math_tool_61",
        subject = "ගණිතය",
        toolNumber = 61,
        groupNumber = 7,
        titleSinhala = "කෝණ සම්බන්ධතා: බද්ධ, ප්‍රතිමුඛ, සමාන්තර රේඛා",
        titleEnglish = "Angle Relationships & Parallel Lines (F, Z, C)",
        category = "ජ්‍යාමිතිය",
        icon = "📐",
        quickSummary = "සරල රේඛාවක බද්ධ කෝණ එකතුව 180° වේ. ප්‍රතිමුඛ කෝණ සමාන වේ.",
        formulaOrRule = "Z හැඩය: ඒකාන්තර කෝණ සමානයි | F හැඩය: අනුරූප කෝණ සමානයි | C හැඩය: මිත්‍ර කෝණ එකතුව = 180°",
        practicalApplication = "සමාන්තර රේඛා දෙකක් තිරික්කයකින් ඡේදනය වන විට හටගන්නා කෝණ ගණනය කිරීම.",
        examTip = "💡 ජ්‍යාමිතික ප්‍රමේයයන් ලියන විට හේතුව (උදා: 'ඒකාන්තර කෝණ', 'සරල රේඛාවක බද්ධ කෝණ') වරහන් තුළ ලිවීම අනිවාර්ය වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_62",
        subject = "ගණිතය",
        toolNumber = 62,
        groupNumber = 7,
        titleSinhala = "ත්‍රිකෝණයක කෝණ සහ බාහිර කෝණ ප්‍රමේයය",
        titleEnglish = "Triangle Angle Sum & Exterior Angle Theorem",
        category = "ජ්‍යාමිතිය",
        icon = "🔺",
        quickSummary = "ත්‍රිකෝණයක අභ්‍යන්තර කෝණ 3 හි එකතුව 180° වේ.",
        formulaOrRule = "ත්‍රිකෝණයක පාදයක් දික්කිරීමෙන් සෑදෙන බාහිර කෝණය එහි අභ්‍යන්තර ප්‍රතිමුඛ කෝණ දෙකේ එකතුවට සමාන වේ.",
        practicalApplication = "ත්‍රිකෝණයක කෝණ දෙකක් 50° සහ 70° නම්, තුන්වන කෝණය = 180 - 120 = 60°. බාහිර කෝණය = 50 + 70 = 120°.",
        examTip = "💡 සමද්වීපාද ත්‍රිකෝණයක සමාන පාදවලට සම්මුඛ කෝණ එකිනෙකට සමාන වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_63",
        subject = "ගණිතය",
        toolNumber = 63,
        groupNumber = 7,
        titleSinhala = "බහුඅස්‍රයක අභ්‍යන්තර සහ බාහිර කෝණ සූත්‍ර",
        titleEnglish = "Polygon Interior & Exterior Angles ( (2n-4)×90° )",
        category = "ජ්‍යාමිතිය",
        icon = "🛑",
        quickSummary = "පාද n සංඛ්‍යාවක් ඇති ඕනෑම බහුඅස්‍රයක කෝණ එකතුව ගණනය කිරීම.",
        formulaOrRule = "අභ්‍යන්තර කෝණ එකතුව = (2n - 4) × 90° = (n - 2) × 180° | ඕනෑම බහුඅස්‍රයක බාහිර කෝණ එකතුව = 360°",
        practicalApplication = "සුවිධි අෂ්ටඅස්‍රයක (n=8): අභ්‍යන්තර එකතුව = (8 - 2) × 180 = 1080°. එක් බාහිර කෝණයක් = 360 / 8 = 45°.",
        examTip = "💡 සුවිධි බහුඅස්‍රයක එක් අභ්‍යන්තර කෝණයක් = 180° - එක් බාහිර කෝණයකි."
      ),
      OlSubjectToolItem(
        id = "math_tool_64",
        subject = "ගණිතය",
        toolNumber = 64,
        groupNumber = 7,
        titleSinhala = "ත්‍රිකෝණ අංගසාම්‍ය අවස්ථා 4 (SSS, SAS, AAS, RHS)",
        titleEnglish = "Triangle Congruency 4 Cases (පා.පා.පා, පා.කෝ.පා, කෝ.කෝ.පා, කර්ණ.පා)",
        category = "ජ්‍යාමිතිය",
        icon = "🔺",
        quickSummary = "ත්‍රිකෝණ දෙකක් හැඩයෙන් සහ විශාලත්වයෙන් පූර්ණ ලෙස සමාන වීමේ කොන්දේසි 4.",
        formulaOrRule = "1. පා.පා.පා (SSS) 2. පා.කෝ.පා (SAS - අන්තර්ගත කෝණය) 3. කෝ.කෝ.පා (AAS) 4. කර්ණ.පා (RHS - සෘජුකෝණී ත්‍රිකෝණවල)",
        practicalApplication = "අංගසාම්‍ය වූ පසු ඉතිරි අනුරූප පාද සහ අනුරූප කෝණ ස්වයංක්‍රීයව සමාන වේ.",
        examTip = "💡 'පා.පා.කෝ' (SSA) අංගසාම්‍ය අවස්ථාවක් නොවන බව මතක තබාගන්න (කෝණය අනිවාර්යයෙන්ම අන්තර්ගත කෝණය විය යුතුය)."
      ),
      OlSubjectToolItem(
        id = "math_tool_65",
        subject = "ගණිතය",
        toolNumber = 65,
        groupNumber = 7,
        titleSinhala = "ත්‍රිකෝණ සමරූපතාව (AAA සහ සමානුපාතික පාද)",
        titleEnglish = "Similar Triangles & Ratio of Sides",
        category = "ජ්‍යාමිතිය",
        icon = "📐",
        quickSummary = "හැඩය සමාන එහෙත් විශාලත්වය වෙනස් ත්‍රිකෝණ (අනුරූප කෝණ සමාන වන අතර අනුරූප පාද සමානුපාතික වේ).",
        formulaOrRule = "ΔABC ~ ΔPQR නම්: AB/PQ = BC/QR = AC/PR",
        practicalApplication = "ගසක සෙවණැල්ල සහ මීටර් රූලක සෙවණැල්ල සසඳා ගසේ සැබෑ උස සෙවීමට සමරූපී ත්‍රිකෝණ භාවිත වේ.",
        examTip = "💡 සමරූපී ත්‍රිකෝණවල වර්ගඵල අතර අනුපාතය අනුරූප පාදවල වර්ගවල අනුපාතයට සමාන වේ (A₁/A₂ = (a₁/a₂)²)."
      ),
      OlSubjectToolItem(
        id = "math_tool_66",
        subject = "ගණිතය",
        toolNumber = 66,
        groupNumber = 7,
        titleSinhala = "මධ්‍ය ලක්ෂ්‍ය ප්‍රමේයය (Midpoint Theorem)",
        titleEnglish = "Midpoint Theorem & Converse",
        category = "ජ්‍යාමිතිය",
        icon = "➗",
        quickSummary = "ත්‍රිකෝණයක පාද දෙකක මධ්‍ය ලක්ෂ්‍ය යා කරන රේඛාව තුන්වන පාදයට සමාන්තර වන අතර එයින් අඩක් වේ.",
        formulaOrRule = "D සහ E මධ්‍ය ලක්ෂ්‍ය නම්: DE || BC සහ DE = ½ BC",
        practicalApplication = "විලෝමය: ත්‍රිකෝණයක එක් පාදයක මධ්‍ය ලක්ෂ්‍යය හරහා තවත් පාදයකට සමාන්තරව අඳින රේඛාව තුන්වන පාදය සමච්ඡේදනය කරයි.",
        examTip = "💡 ජ්‍යාමිතික සාධන ප්‍රශ්නවල සමාන්තර රේඛා සහ දිග අඩක් බව පෙන්වීමට මෙය බහුලව භාවිත වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_67",
        subject = "ගණිතය",
        toolNumber = 67,
        groupNumber = 7,
        titleSinhala = "සමාන්තරාස්‍ර ප්‍රමේයයන් (පාද, කෝණ, විකර්ණ)",
        titleEnglish = "Parallelogram Properties & Theorems",
        category = "ජ්‍යාමිතිය",
        icon = "▰",
        quickSummary = "සම්මුඛ පාද සමාන්තර සහ සමාන වේ; සම්මුඛ කෝණ සමාන වේ; විකර්ණ එකිනෙක සමච්ඡේදනය වේ.",
        formulaOrRule = "චතුරස්‍රයක සම්මුඛ පාද යුගලක් සමාන්තර හා සමාන නම් එය සමාන්තරාස්‍රයකි.",
        practicalApplication = "රොම්බසයක විකර්ණ එකිනෙක ලම්භකව සමච්ඡේදනය වේ; සෘජුකෝණාස්‍රයක විකර්ණ එකිනෙකට දිගින් සමාන වේ.",
        examTip = "💡 සමාන්තරාස්‍රයක විකර්ණයකින් එහි වර්ගඵලය හරියටම දෙසමකඩ කරයි."
      ),
      OlSubjectToolItem(
        id = "math_tool_68",
        subject = "ගණිතය",
        toolNumber = 68,
        groupNumber = 7,
        titleSinhala = "එකම ආධාරකය හා සමාන්තර රේඛා අතර වර්ගඵල ප්‍රමේයය",
        titleEnglish = "Area of Parallelograms & Triangles on Same Base",
        category = "ජ්‍යාමිතිය",
        icon = "⏢",
        quickSummary = "එකම ආධාරකය මත සහ එකම සමාන්තර රේඛා යුගලය අතර පිහිටි සමාන්තරාස්‍රවල වර්ගඵල සමාන වේ.",
        formulaOrRule = "එකම ආධාරකය හා සමාන්තර රේඛා අතර පිහිටි ත්‍රිකෝණයක වර්ගඵලය සමාන්තරාස්‍රයේ වර්ගඵලයෙන් අඩකි (Area Δ = ½ Area Parallelogram).",
        practicalApplication = "එකම ආධාරකය හා සමාන්තර රේඛා අතර පිහිටි ත්‍රිකෝණවල වර්ගඵල එකිනෙකට සමාන වේ.",
        examTip = "💡 වර්ගඵල සමාන බව සාධනය කිරීමට මෙම ප්‍රමේයය ඉතා ප්‍රයෝජනවත් වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_69",
        subject = "ගණිතය",
        toolNumber = 69,
        groupNumber = 7,
        titleSinhala = "තලෙස්ගේ ප්‍රමේයය (සමානුපාතික ඡේද ප්‍රමේයය)",
        titleEnglish = "Thales' Theorem / Intercept Theorem",
        category = "ජ්‍යාමිතිය",
        icon = "📏",
        quickSummary = "ත්‍රිකෝණයක පාදයකට සමාන්තරව අඳින රේඛාවකින් අනෙක් පාද දෙක සමානුපාතිකව බෙදේ.",
        formulaOrRule = "ΔABC හි DE || BC නම්: AD / DB = AE / EC",
        practicalApplication = "සමාන්තර සරල රේඛා ත්‍රිත්වයකින් තිරික්ක රේඛා මත ඇති කරන ඡේදණ්ඩ සමානුපාතික වේ.",
        examTip = "💡 AB / DB = AC / EC ආකාරයෙන්ද ලිවිය හැක."
      ),
      OlSubjectToolItem(
        id = "math_tool_70",
        subject = "ගණිතය",
        toolNumber = 70,
        groupNumber = 7,
        titleSinhala = "ජ්‍යාමිතික නිර්මාණ: සමච්ඡේදක සහ ත්‍රිකෝණ නිර්මාණය",
        titleEnglish = "Geometric Constructions (Bisectors, Perpendiculars, 60°, 90°)",
        category = "ජ්‍යාමිතිය",
        icon = "🧭",
        quickSummary = "කවකටුව සහ අඩි රූල පමණක් භාවිතයෙන් කෝණ (60°, 90°, 45°, 30°) සහ ලම්භ සමච්ඡේදක නිර්මාණය.",
        formulaOrRule = "කෝණ සමච්ඡේදකය මත පිහිටි ඕනෑම ලක්ෂ්‍යයක් කෝණයේ බාහුවලට සමදුරින් පිහිටයි.",
        practicalApplication = "ත්‍රිකෝණයක අන්තර් කේන්ද්‍රය යනු කෝණ සමච්ඡේදක හමුවන ලක්ෂ්‍යයයි (අන්තර් වෘත්තය ඇඳීම).",
        examTip = "💡 නිර්මාණ චාප කිසිවිටෙකත් මකා නොදමන්න; පැන්සල් ඉරි ඉතා පැහැදිලි හා සිහින් විය යුතුය."
      ),

      // --- GROUP 8: වෘත්ත ජ්‍යාමිතිය (71-80) ---
      OlSubjectToolItem(
        id = "math_tool_71",
        subject = "ගණිතය",
        toolNumber = 71,
        groupNumber = 8,
        titleSinhala = "කේන්ද්‍ර කෝණය සහ පරිධි කෝණය අතර සම්බන්ධය",
        titleEnglish = "Angle at Center is Twice Angle at Circumference",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "⭕",
        quickSummary = "වෘත්තයක චාපයකින් කේන්ද්‍රයෙහි ආපාතනය කරන කෝණය එම චාපයෙන්ම පරිධිය මත ආපාතනය කරන කෝණය මෙන් දෙගුණයකි.",
        formulaOrRule = "කේන්ද්‍ර කෝණය = 2 × පරිධි කෝණය (AÔB = 2 × AP̂B)",
        practicalApplication = "පරිධි කෝණය 40° නම් කේන්ද්‍ර කෝණය = 80° කි.",
        examTip = "💡 චාපය ප්‍රත්‍යාවර්ත වූ විටද (Reflex angle) මෙම ප්‍රමේයය එලෙසම වලංගු වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_72",
        subject = "ගණිතය",
        toolNumber = 72,
        groupNumber = 8,
        titleSinhala = "අර්ධ වෘත්තයක කෝණය සෘජුකෝණයකි (90°)",
        titleEnglish = "Angle in a Semicircle is a Right Angle (90°)",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "🌓",
        quickSummary = "විෂ්කම්භයකින් පරිධිය මත ආපාතනය කරන ඕනෑම කෝණයක අගය 90° වේ.",
        formulaOrRule = "AB විෂ්කම්භයක් නම්: AP̂B = 90°",
        practicalApplication = "විෂ්කම්භය කර්ණය වන සෘජුකෝණී ත්‍රිකෝණයක් සැමවිටම අර්ධ වෘත්තයක් තුළ පිහිටයි (පයිතගරස් ප්‍රමේයය යෙදිය හැක).",
        examTip = "💡 කේන්ද්‍ර කෝණය 180° (සරල රේඛාවක්) බැවින් පරිධි කෝණය 180/2 = 90° වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_73",
        subject = "ගණිතය",
        toolNumber = 73,
        groupNumber = 8,
        titleSinhala = "එකම ඛණ්ඩයේ කෝණ එකිනෙකට සමාන වේ",
        titleEnglish = "Angles in the Same Segment are Equal",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "🦋",
        quickSummary = "එකම චාපයකින් පරිධිය මත ආපාතනය කරන සියලුම කෝණ එකිනෙකට සමාන වේ (සමනල හැඩය).",
        formulaOrRule = "AP̂B = AQ̂B (එකම AB චාපයෙන් උපදින)",
        practicalApplication = "වෘත්තීය චතුරස්‍රවල කෝණ සෙවීමට සහ සමරූපී ත්‍රිකෝණ සාධනයට නිතර භාවිත වේ.",
        examTip = "💡 'එකම ඛණ්ඩයේ කෝණ' යන්න කෙටි හේතුව ලෙස ලියන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_74",
        subject = "ගණිතය",
        toolNumber = 74,
        groupNumber = 8,
        titleSinhala = "වෘත්ත චතුරස්‍ර ප්‍රමේයය (සම්මුඛ කෝණ පරිපූරක වේ)",
        titleEnglish = "Cyclic Quadrilateral Opposite Angles Sum to 180°",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "🛑",
        quickSummary = "ශීර්ෂ 4ම වෘත්ත පරිධිය මත පිහිටි චතුරස්‍රයක සම්මුඛ කෝණ දෙකේ එකතුව 180° වේ.",
        formulaOrRule = "Â + Ĉ = 180° සහ B̂ + D̂ = 180°",
        practicalApplication = "වෘත්ත චතුරස්‍රයක එක් කෝණයක් 110° නම් ඊට ප්‍රතිමුඛ කෝණය = 180 - 110 = 70°.",
        examTip = "💡 චතුරස්‍රයක සම්මුඛ කෝණ එකතුව 180° නම් එම ශීර්ෂ 4 වෘත්තීය වේ (එකම වෘත්තයක් මත පිහිටයි)."
      ),
      OlSubjectToolItem(
        id = "math_tool_75",
        subject = "ගණිතය",
        toolNumber = 75,
        groupNumber = 8,
        titleSinhala = "වෘත්ත චතුරස්‍රයක බාහිර කෝණ ප්‍රමේයය",
        titleEnglish = "Cyclic Quadrilateral Exterior Angle Theorem",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "📐",
        quickSummary = "වෘත්ත චතුරස්‍රයක පාදයක් දික් කළ විට සෑදෙන බාහිර කෝණය අභ්‍යන්තර සම්මුඛ කෝණයට සමාන වේ.",
        formulaOrRule = "බාහිර කෝණය = අභ්‍යන්තර සම්මුඛ කෝණය",
        practicalApplication = "පාදය දික්කළ විට පිටත හැදෙන කෝණය 85° නම්, ඊට ඉදිරියෙන් ඇති ඇතුළත කෝණයද 85° වේ.",
        examTip = "💡 විභාගයේදී එක් පියවරකින් කෝණයක අගය සොයාගැනීමට මෙම ප්‍රමේයය කදිම කෙටිමගකි."
      ),
      OlSubjectToolItem(
        id = "math_tool_76",
        subject = "ගණිතය",
        toolNumber = 76,
        groupNumber = 8,
        titleSinhala = "වෘත්තයක කේන්ද්‍රයේ සිට ජ්‍යායකට අඳින ලම්භකය",
        titleEnglish = "Perpendicular from Center to a Chord Bisects Chord",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "⭕",
        quickSummary = "කේන්ද්‍රයේ සිට ජ්‍යායකට ඇඳි ලම්භකය මගින් ජ්‍යාය සමච්ඡේදනය කරයි.",
        formulaOrRule = "OM ⊥ AB නම් AM = MB | r² = d² + (AB/2)² (පයිතගරස් සම්බන්ධය)",
        practicalApplication = "අරය 10 cm වන වෘත්තයක 16 cm ජ්‍යායකට කේන්ද්‍රයේ සිට ලම්භ දුර: d = √(10² - 8²) = √(100 - 64) = √36 = 6 cm.",
        examTip = "💡 විලෝමය: කේන්ද්‍රයේ සිට ජ්‍යායක මධ්‍ය ලක්ෂ්‍යය යා කරන රේඛාව ජ්‍යායට ලම්භක වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_77",
        subject = "ගණිතය",
        toolNumber = 77,
        groupNumber = 8,
        titleSinhala = "ස්පර්ශකය සහ ස්පර්ශ ලක්ෂ්‍යයට අඳින අරය (90°)",
        titleEnglish = "Tangent is Perpendicular to Radius at Point of Contact",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "⚪",
        quickSummary = "වෘත්ත ස්පර්ශකයක් ස්පර්ශ ලක්ෂ්‍යයේදී අරයට ලම්භක වේ (කෝණය 90°).",
        formulaOrRule = "ස්පර්ශකය ⊥ අරය (OPT = 90°)",
        practicalApplication = "බාහිර ලක්ෂ්‍යයේ සිට වෘත්තයට ඇඳි ස්පර්ශක ඛණ්ඩයේ දිග සෙවීමට පයිතගරස් ප්‍රමේයය යෙදීම.",
        examTip = "💡 ස්පර්ශකයක් හමුවූ වහාම ස්පර්ශ ලක්ෂ්‍යයේ 90° කෝණය ලකුණු කරගන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_78",
        subject = "ගණිතය",
        toolNumber = 78,
        groupNumber = 8,
        titleSinhala = "බාහිර ලක්ෂ්‍යයක සිට අඳින ස්පර්ශක ප්‍රමේයය",
        titleEnglish = "Tangents from an External Point are Equal in Length",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "🍦",
        quickSummary = "වෘත්තයකින් පිටත ලක්ෂ්‍යයක සිට එම වෘත්තයට අඳින ස්පර්ශක දෙක දිගින් සමාන වේ.",
        formulaOrRule = "PA = PB (P යනු බාහිර ලක්ෂ්‍යය, A සහ B ස්පර්ශ ලක්ෂ්‍ය වේ) | OP රේඛාව මගින් APB කෝණය සමච්ඡේදනය කරයි.",
        practicalApplication = "ත්‍රිකෝණයක හෝ චතුරස්‍රයක අන්තර්ගත වෘත්තයක් ඇති විට පාදවල දිග සෙවීමට යොදාගනී.",
        examTip = "💡 ΔOAP සහ ΔOBP සර්වසම ත්‍රිකෝණ වේ (කර්ණ.පා අංගසාම්‍යය)."
      ),
      OlSubjectToolItem(
        id = "math_tool_79",
        subject = "ගණිතය",
        toolNumber = 79,
        groupNumber = 8,
        titleSinhala = "ඒකාන්තර ඛණ්ඩ ප්‍රමේයය (Alternate Segment Theorem)",
        titleEnglish = "Alternate Segment Theorem",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "🔺",
        quickSummary = "ස්පර්ශකය සහ ස්පර්ශ ලක්ෂ්‍යයෙන් අඳින ජ්‍යාය අතර කෝණය, ඒකාන්තර වෘත්ත ඛණ්ඩයේ කෝණයට සමාන වේ.",
        formulaOrRule = "TAB = ACB (T යනු ස්පර්ශකය, AB ජ්‍යාය, C ඒකාන්තර ඛණ්ඩයේ ලක්ෂ්‍යයකි)",
        practicalApplication = "O/L ජ්‍යාමිතික සාධන ප්‍රශ්නවල වඩාත්ම ලකුණු ලැබෙන තීරණාත්මක ප්‍රමේයයකි.",
        examTip = "💡 ස්පර්ශකය හා ජ්‍යාය හමුවන තැනින් පටන්ගෙන ඊට විරුද්ධ පැත්තේ පරිධි කෝණය හඳුනාගන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_80",
        subject = "ගණිතය",
        toolNumber = 80,
        groupNumber = 8,
        titleSinhala = "ඡේදනය වන ජ්‍යා ප්‍රමේයය (Intersecting Chords)",
        titleEnglish = "Intersecting Chords Theorem (AP × PB = CP × PD)",
        category = "වෘත්ත ජ්‍යාමිතිය",
        icon = "✖️",
        quickSummary = "වෘත්තයක් තුළ හෝ පිටතදී ජ්‍යා දෙකක් P හිදී ඡේදනය වන විට ඛණ්ඩවල ගුණිතයන් සමාන වේ.",
        formulaOrRule = "AP × PB = CP × PD | ස්පර්ශකයක් සහ ඡේදකයක් නම්: PT² = PA × PB",
        practicalApplication = "ජ්‍යා ඛණ්ඩවල දිග දී ඇති විට නොදන්නා දිගක් ක්ෂණිකව ගණනය කිරීම.",
        examTip = "💡 P ලක්ෂ්‍යයේ සිට එක් එක් ශීර්ෂයට ඇති දුරවල් ගුණ කළ යුතුය."
      ),

      // --- GROUP 9: සංඛ්‍යානය සහ සම්භාවිතාව (81-90) ---
      OlSubjectToolItem(
        id = "math_tool_81",
        subject = "ගණිතය",
        toolNumber = 81,
        groupNumber = 9,
        titleSinhala = "සමූහිත දත්තවල මධ්‍යන්‍යය (උපකල්පිත මධ්‍යන්‍ය ක්‍රමය)",
        titleEnglish = "Mean of Grouped Data (Assumed Mean Method: x̄ = A + Σfd/Σf)",
        category = "සංඛ්‍යානය",
        icon = "📊",
        quickSummary = "විශාල දත්ත සමූහයක සාමාන්‍යය පහසුවෙන් සෙවීමට උපකල්පිත මධ්‍යන්‍යයක් (A) තෝරා ගැනීම.",
        formulaOrRule = "x̄ = A + (Σfd / Σf) [මෙහි d = x - A, x = පන්ති මධ්‍ය අගය, f = සංඛ්‍යාතය]",
        practicalApplication = "A ලෙස වැඩිම සංඛ්‍යාතයක් සහිත මැද පන්තියේ මධ්‍ය අගය තෝරා ගැනීමෙන් ගණනය කිරීම් ඉතා කුඩා වේ.",
        examTip = "💡 පන්ති මධ්‍ය අගය x = (පහළ සීමාව + ඉහළ සීමාව) / 2."
      ),
      OlSubjectToolItem(
        id = "math_tool_82",
        subject = "ගණිතය",
        toolNumber = 82,
        groupNumber = 9,
        titleSinhala = "මාත පන්තිය සහ මධ්‍යස්ථ පන්තිය සෙවීම",
        titleEnglish = "Modal Class & Median Class Identifier",
        category = "සංඛ්‍යානය",
        icon = "🎯",
        quickSummary = "මාත පන්තිය = වැඩිම සංඛ්‍යාතයක් ඇති පන්තිය | මධ්‍යස්ථ පන්තිය = n/2 වන අගය අඩංගු පන්තිය.",
        formulaOrRule = "මුළු සංඛ්‍යාතය N නම්, N/2 සමුච්චිත සංඛ්‍යාතය ඉක්මවන පළමු පන්තිය මධ්‍යස්ථ පන්තිය වේ.",
        practicalApplication = "N = 60 නම්, N/2 = 30 වන අගය අඩංගු පන්ති ප්‍රාන්තරය මධ්‍යස්ථ පන්තියයි.",
        examTip = "💡 මාතය ඇසුවහොත් 'මාත පන්තියේ මධ්‍ය අගය' ලිවිය හැක."
      ),
      OlSubjectToolItem(
        id = "math_tool_83",
        subject = "ගණිතය",
        toolNumber = 83,
        groupNumber = 9,
        titleSinhala = "සමුච්චිත සංඛ්‍යාත වක්‍රය (Ogive) සහ චතුර්ථක",
        titleEnglish = "Cumulative Frequency Curve & Quartiles (Q1, Q2, Q3)",
        category = "සංඛ්‍යානය",
        icon = "📈",
        quickSummary = "ඉහළ පන්ති සීමා ඉදිරියේ සමුච්චිත සංඛ්‍යාතය ලකුණු කර අඳින 'S' හැඩැති සුමට වක්‍රය.",
        formulaOrRule = "Q₁ = N/4 (පළමු චතුර්ථකය) | Q₂ = N/2 (මධ්‍යස්ථය) | Q₃ = 3N/4 (තුන්වන චතුර්ථකය)",
        practicalApplication = "අන්තර් චතුර්ථක පරාසය (IQR) = Q₃ - Q₁.",
        examTip = "💡 වක්‍රය ආරම්භ කළ යුත්තේ පළමු පන්තියේ පහළ සීමාවේදී ශුන්‍යයෙන් (0) ය."
      ),
      OlSubjectToolItem(
        id = "math_tool_84",
        subject = "ගණිතය",
        toolNumber = 84,
        groupNumber = 9,
        titleSinhala = "හිස්ටොග්‍රෑමය සහ සංඛ්‍යාත බහුඅස්‍රය",
        titleEnglish = "Histogram & Frequency Polygon Tool",
        category = "සංඛ්‍යානය",
        icon = "📊",
        quickSummary = "පන්ති ප්‍රාන්තර සෘජුකෝණාස්‍ර ලෙස ඇඳීම (තීරුවල පළල පන්ති ප්‍රමාණය වන අතර උස සංඛ්‍යාතයයි).",
        formulaOrRule = "තීරුවල ඉහළ මැද ලක්ෂ්‍ය යා කිරීමෙන් සංඛ්‍යාත බහුඅස්‍රය ලැබේ.",
        practicalApplication = "හිස්ටොග්‍රෑමයේ උසම තීරුවේ මුදුන් කෙළවර යාබද තීරුවල මුදුන් සමග කතිර හැඩයට යා කිරීමෙන් මාතය ප්‍රස්ථාරිකව සෙවිය හැක.",
        examTip = "💡 හිස්ටොග්‍රෑමයේ තීරු අතර කිසිදු හිඩැසක් නොතිබිය යුතුය."
      ),
      OlSubjectToolItem(
        id = "math_tool_85",
        subject = "ගණිතය",
        toolNumber = 85,
        groupNumber = 9,
        titleSinhala = "තනි සිද්ධියක සම්භාවිතාව P(A)",
        titleEnglish = "Probability of Single Event (P(A) = n(A) / n(S))",
        category = "සම්භාවිතාව",
        icon = "🎲",
        quickSummary = "අවස්ථාවට අනුකූල ප්‍රතිඵල ගණන සහ නියැදි අවකාශයේ මුළු ප්‍රතිඵල ගණන අතර අනුපාතය.",
        formulaOrRule = "P(A) = n(A) / n(S) (0 ≤ P(A) ≤ 1) | P(A') = 1 - P(A)",
        practicalApplication = "දාදු කැටයක් දැමූ විට ප්‍රථමක සංඛ්‍යාවක් ලැබීමේ සම්භාවිතාව (2, 3, 5): P = 3/6 = 1/2.",
        examTip = "💡 සම්භාවිතාව කිසිවිටෙකත් 1ට වඩා වැඩි විය නොහැක; ඍණ අගයක් විය නොහැක."
      ),
      OlSubjectToolItem(
        id = "math_tool_86",
        subject = "ගණිතය",
        toolNumber = 86,
        groupNumber = 9,
        titleSinhala = "රුක් සටහන් (Tree Diagrams) මගින් සම්භාවිතාව",
        titleEnglish = "Tree Diagrams for Combined Events",
        category = "සම්භාවිතාව",
        icon = "🌳",
        quickSummary = "අනුයාත සිදුවීම්වල සියලු ශාඛා සහ සම්භාවිතා නිරූපණය කිරීම.",
        formulaOrRule = "ශාඛාවක් ඔස්සේ ඉදිරියට යනවිට ගුණ කරයි | විකල්ප ශාඛා අවසානයේ එකතු කරයි.",
        practicalApplication = "කාසියක් දෙවරක් දැමීම: P(HH) = 1/2 × 1/2 = 1/4; අවම වශයෙන් එක් සිරසක් ලැබීමේ සම්භාවිතාව = 1 - P(TT) = 1 - 1/4 = 3/4.",
        examTip = "💡 එක් ලක්ෂ්‍යයකින් විහිදෙන ශාඛාවල සම්භාවිතාවල එකතුව සෑම විටම 1 ක් විය යුතුය."
      ),
      OlSubjectToolItem(
        id = "math_tool_87",
        subject = "ගණිතය",
        toolNumber = 87,
        groupNumber = 9,
        titleSinhala = "නැවත දැමීම සහිත සහ රහිත තේරීම්",
        titleEnglish = "With Replacement vs Without Replacement",
        category = "සම්භාවිතාව",
        icon = "🎱",
        quickSummary = "බෑගයකින් බෝලයක් ගෙන නැවත නොදමා දෙවන බෝලය ගැනීමේදී මුළු සංඛ්‍යාව සහ සම්භාවිතාව අඩුවේ.",
        formulaOrRule = "රතු 5ක් හා නිල් 3ක් ඇති බෑගයකින් නැවත නොදමා බෝල 2ක් ගැනීමේදී: P(RR) = (5/8) × (4/7) = 20/56 = 5/14.",
        practicalApplication = "නැවත දැමීම සහිත විට සම්භාවිතාව වෙනස් නොවේ (ස්වාධීන වේ): P(RR) = (5/8) × (5/8) = 25/64.",
        examTip = "💡 ප්‍රශ්නයේ 'නැවත නොදමා' (Without replacement) යන වචනය තිබේදැයි ඉතා විමසිලිමත්ව බලන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_88",
        subject = "ගණිතය",
        toolNumber = 88,
        groupNumber = 9,
        titleSinhala = "කොටු දැල (Grid / Lattice) මගින් නියැදි අවකාශය",
        titleEnglish = "Lattice / Grid Diagram for Sample Space",
        category = "සම්භාවිතාව",
        icon = "▦",
        quickSummary = "සිද්ධි දෙකක ප්‍රතිඵල x සහ y අක්ෂවල ලකුණු කර ලක්ෂ්‍ය 36ක් හෝ නියැදි ලක්ෂ්‍ය දැක්වීම.",
        formulaOrRule = "අදාළ සිද්ධියට අයත් ලක්ෂ්‍ය වටකර (කවයකින් දක්වා) සම්භාවිතාව සෙවීම.",
        practicalApplication = "දාදු කැට 2ක් දැමූ විට ලැබෙන ලකුණු එකතුව 7 වන අවස්ථා: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) => 6/36 = 1/6.",
        examTip = "💡 නියැදි අවකාශයේ කිසිදු ලක්ෂ්‍යයක් අතපසු නොවන සේ පැහැදිලිව තිත් තබන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_89",
        subject = "ගණිතය",
        toolNumber = 89,
        groupNumber = 9,
        titleSinhala = "පරස්පර පරිවර්ජ්‍ය සහ ස්වාධීන සිද්ධි",
        titleEnglish = "Mutually Exclusive vs Independent Events",
        category = "සම්භාවිතාව",
        icon = "🔀",
        quickSummary = "එකවර සිදුවිය නොහැකි සිද්ධි (P(A ∩ B) = 0) සහ එකක සිදුවීම අනෙකට බලනොපාන සිද්ධි.",
        formulaOrRule = "පරිවර්ජ්‍ය: P(A ∪ B) = P(A) + P(B) | ස්වාධීන: P(A ∩ B) = P(A) × P(B)",
        practicalApplication = "කාසියකින් සිරස ලැබීම සහ දාදු කැටයකින් 6 ලැබීම ස්වාධීන සිද්ධි වේ: P = 1/2 × 1/6 = 1/12.",
        examTip = "💡 පරස්පර පරිවර්ජ්‍ය සිද්ධිවල පොදු ඡේදනයක් නොමැත."
      ),
      OlSubjectToolItem(
        id = "math_tool_90",
        subject = "ගණිතය",
        toolNumber = 90,
        groupNumber = 9,
        titleSinhala = "පයි ප්‍රස්ථාර (වට ප්‍රස්ථාර) කෝණ ගණකය",
        titleEnglish = "Pie Chart Sector Angles Calculator",
        category = "සංඛ්‍යානය",
        icon = "🥧",
        quickSummary = "දත්ත අගයන් කේන්ද්‍ර කෝණ (360° පදනමෙන්) බවට පරිවර්තනය කිරීම.",
        formulaOrRule = "කේන්ද්‍ර කෝණය = (අදාළ අගය / මුළු අගය) × 360°",
        practicalApplication = "සිසුන් 120න් 30ක් ගණිතයට කැමති නම් කෝණය: (30 / 120) × 360° = 90°.",
        examTip = "💡 සියලුම කේන්ද්‍ර කෝණවල එකතුව හරියටම 360° විය යුතුය; කෝණමානය නිවැරදිව භාවිත කරන්න."
      ),

      // --- GROUP 10: වාණිජ ගණිතය සහ ප්‍රායෝගික මූල්‍ය (91-100) ---
      OlSubjectToolItem(
        id = "math_tool_91",
        subject = "ගණිතය",
        toolNumber = 91,
        groupNumber = 10,
        titleSinhala = "සරල පොලී සූත්‍රය (I = Ptr / 100)",
        titleEnglish = "Simple Interest Calculator (I = Ptr / 100)",
        category = "වාණිජ ගණිතය",
        icon = "💵",
        quickSummary = "මුල් මුදල (P), කාලය වසරවලින් (t) සහ වාර්ෂික පොලී අනුපාතිකය (r) අනුව සරල පොලිය සෙවීම.",
        formulaOrRule = "I = (P × t × r) / 100 | මුළු මුදල A = P + I",
        practicalApplication = "රු. 50,000 ක මුදලක් 12% වාර්ෂික සරල පොලියට වසර 3කට තැන්පත් කළ විට පොලිය: I = (50,000 × 3 × 12) / 100 = රු. 18,000.",
        examTip = "💡 කාලය මාසවලින් දුනහොත් 12න් බෙදා වසර බවට පත්කර ගන්න (උදා: මාස 8 = 8/12 වසර)."
      ),
      OlSubjectToolItem(
        id = "math_tool_92",
        subject = "ගණිතය",
        toolNumber = 92,
        groupNumber = 10,
        titleSinhala = "වැල් පොලිය (Compound Interest) ගණනය කිරීම",
        titleEnglish = "Compound Interest Year-by-Year Calculation",
        category = "වාණිජ ගණිතය",
        icon = "📈",
        quickSummary = "පළමු වසරේ පොලිය මුල් මුදලට එකතු වී ඊළඟ වසරේ පොලිය එම මුළු මුදල මත ගණනය වීම.",
        formulaOrRule = "1 වන වසර අවසාන මුදල = P + I₁ | 2 වන වසරේ පොලිය I₂ ගණනය කරන්නේ එම මුළු මුදල මතය.",
        practicalApplication = "රු. 10,000 ක් 10% වැල් පොලියට: වසර 1 දී මුදල = 10,000 + 1,000 = 11,000. වසර 2 දී පොලිය = 11,000 × 10% = 1,100. මුළු මුදල = රු. 12,100.",
        examTip = "💡 වැල් පොලිය සැමවිටම සරල පොලියට වඩා වැඩිය."
      ),
      OlSubjectToolItem(
        id = "math_tool_93",
        subject = "ගණිතය",
        toolNumber = 93,
        groupNumber = 10,
        titleSinhala = "හීනවන ශේෂ ක්‍රමයට ණය පොලිය (මාසික ඒකක ක්‍රමය)",
        titleEnglish = "Reducing Balance Loan Method (Month-Units)",
        category = "වාණිජ ගණිතය",
        icon = "💳",
        quickSummary = "O/L විභාගයේ අංක 1 ප්‍රශ්න පත්‍රයේ දෙවන කොටසේ අනිවාර්යයෙන්ම ලැබෙන ණය වාරික ගණනය.",
        formulaOrRule = "මාස ඒකක ගණන = n(n + 1) / 2 | එක් මාස ඒකකයක ණය = ණය මුදල / n | මුළු පොලිය = මාස ඒකක ගණන × එක් ඒකකයක ණය × (r / 1200)",
        practicalApplication = "මාස 12 ක ණයක් සඳහා මාස ඒකක = 12 × 13 / 2 = 78. මාසික වාරිකය = (ණය මුදල + මුළු පොලිය) / n.",
        examTip = "💡 මාසික පොලී අනුපාතිකය ලබාගැනීමට වාර්ෂික අනුපාතිකය 12න් බෙදන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_94",
        subject = "ගණිතය",
        toolNumber = 94,
        groupNumber = 10,
        titleSinhala = "හිඟ මුදල් ගෙවීමේ (Hire Purchase) ක්‍රමය",
        titleEnglish = "Hire Purchase Cash Price vs Installments",
        category = "වාණිජ ගණිතය",
        icon = "📺",
        quickSummary = "මූලික ගෙවීමක් කර ඉතිරිය පොලියක් සමග සමාන මාසික වාරිකවලින් ගෙවා නිමකිරීම.",
        formulaOrRule = "ණය මුදල = අත්පිට මුදල - මූලික ගෙවීම | වාරිකවලින් ගෙවන මුළු මුදල = මූලික ගෙවීම + (වාරිකය × වාරික ගණන)",
        practicalApplication = "රු. 60,000 භාණ්ඩයකට රු. 10,000 මූලිකව ගෙවා රු. 5,000 බැගින් වාරික 12ක් ගෙවූ විට අමතරව ගෙවූ මුදල (පොලිය) = 10,000 + 60,000 - 60,000 = රු. 10,000.",
        examTip = "💡 අත්පිට මුදලට වඩා වාරික ක්‍රමයට ගැනීමේදී වැඩි මුදලක් වැයවේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_95",
        subject = "ගණිතය",
        toolNumber = 95,
        groupNumber = 10,
        titleSinhala = "තක්සේරු බදු (වරිපනම් බදු) ගණනය කිරීම",
        titleEnglish = "Rates & Municipal Assessment Tax Calculator",
        category = "වාණිජ ගණිතය",
        icon = "🏠",
        quickSummary = "නගර සභාව හෝ ප්‍රාදේශීය සභාව මගින් නිවාසවල වාර්ෂික තක්සේරු වටිනාකම මත අයකරන බද්ද.",
        formulaOrRule = "වාර්ෂික වරිපනම් බද්ද = වාර්ෂික තක්සේරු වටිනාකම × බදු ප්‍රතිශතය | කාර්තු බද්ද = වාර්ෂික බද්ද / 4",
        practicalApplication = "වාර්ෂික තක්සේරු වටිනාකම රු. 80,000 වන නිවසකට 10% වරිපනම් බද්දක් අය කරන්නේ නම් කාර්තුවකට ගෙවිය යුතු බද්ද: (80,000 × 10%) / 4 = 8,000 / 4 = රු. 2,000.",
        examTip = "💡 වසරකට කාර්තු 4ක් (මාස 3 බැගින් වූ කොටස්) ඇති බව මතක තබාගන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_96",
        subject = "ගණිතය",
        toolNumber = 96,
        groupNumber = 10,
        titleSinhala = "රේගු බදු සහ ආනයන බදු මෙවලම",
        titleEnglish = "Customs Duty & Import Tariff Tool",
        category = "වාණිජ ගණිතය",
        icon = "🚢",
        quickSummary = "විදේශයන්ගෙන් භාණ්ඩ ආනයනය කිරීමේදී වරායේදී අයකරන රේගු බද්ද.",
        formulaOrRule = "රේගු බද්ද = භාණ්ඩයේ වටිනාකම (CIF වටිනාකම) × තීරුබදු ප්‍රතිශතය",
        practicalApplication = "රු. 200,000 ක් වටිනා රූපවාහිනියකට 15% රේගු බද්දක් අය කළහොත්: බද්ද = 200,000 × 15/100 = රු. 30,000. මුළු පිරිවැය = රු. 230,000.",
        examTip = "💡 රේගු බද්ද පාරිභෝගිකයාට විකිණීමට පෙර ගැනුම් පිරිවැයට එකතු වේ."
      ),
      OlSubjectToolItem(
        id = "math_tool_97",
        subject = "ගණිතය",
        toolNumber = 97,
        groupNumber = 10,
        titleSinhala = "ආදායම් බදු සහ බදු නිදහස් සීමා",
        titleEnglish = "Income Tax Slabs & Tax Payable Tool",
        category = "වාණිජ ගණිතය",
        icon = "🧾",
        quickSummary = "පුද්ගල වාර්ෂික ශුද්ධ ආදායමෙන් බදු නිදහස් සීමාව අඩුකර ඉතිරිය මත අනුක්‍රමික ප්‍රතිශතවලින් අයකරන බද්ද.",
        formulaOrRule = "බදු අයවන ආදායම = මුළු ආදායම - බදු සහන සීමාව",
        practicalApplication = "වාර්ෂික ආදායම රු. 1,800,000 ක් වන විට, පළමු රු. 1,200,000 බද්දෙන් නිදහස් නම් ඉතිරි රු. 600,000 සඳහා 6% බද්ද = රු. 36,000.",
        examTip = "💡 විභාගයේදී දෙනු ලබන බදු ස්ලැබ් (Slabs) ප්‍රවේශමෙන් කියවා අදාළ කොටස්වලට වෙන්කර බද්ද ගණනය කරන්න."
      ),
      OlSubjectToolItem(
        id = "math_tool_98",
        subject = "ගණිතය",
        toolNumber = 98,
        groupNumber = 10,
        titleSinhala = "කොටස් වෙළඳපොල: කොටස් මිලදී ගැනීම සහ ලාභාංශ",
        titleEnglish = "Stock Market Shares & Dividend Yield Tool",
        category = "වාණිජ ගණිතය",
        icon = "🏢",
        quickSummary = "සමාගමක කොටස් මිලදී ගැනීම, කොටසකට ගෙවන ලාභාංශ සහ ආයෝජන ප්‍රතිලාභ ප්‍රතිශතය.",
        formulaOrRule = "මිලදී ගත හැකි කොටස් ගණන = ආයෝජිත මුදල / එක් කොටසක වෙළඳපොල මිල | මුළු ලාභාංශය = කොටස් ගණන × කොටසකට ලාභාංශය",
        practicalApplication = "රු. 50 බැගින් වන කොටස් මිලදී ගැනීමට රු. 100,000 ආයෝජනය කළ විට කොටස් 2000ක් ලැබේ. කොටසකට රු. 4 ක ලාභාංශයක් ගෙවන්නේ නම් මුළු ලාභාංශය = 2000 × 4 = රු. 8,000.",
        examTip = "💡 ලාභාංශ ප්‍රතිශතය = (මුළු ලාභාංශය / ආයෝජිත මුදල) × 100% = (8000 / 100000) × 100% = 8%."
      ),
      OlSubjectToolItem(
        id = "math_tool_99",
        subject = "ගණිතය",
        toolNumber = 99,
        groupNumber = 10,
        titleSinhala = "කොටස් විකිණීමේ ප්‍රාග්ධන ලාභය සහ තැරැව්කාර ගාස්තු",
        titleEnglish = "Capital Gain on Shares & Brokerage Fees",
        category = "වාණිජ ගණිතය",
        icon = "💹",
        quickSummary = "කොටස් වැඩි මිලකට විකිණීමේදී ලැබෙන ප්‍රාග්ධන ලාභය සහ අතරමැදි තැරැව්කරුගේ කොමිස් මුදල.",
        formulaOrRule = "ප්‍රාග්ධන ලාභය = (විකුණුම් මිල - ගැණුම් මිල) × කොටස් ගණන",
        practicalApplication = "රු. 40 ට ගත් කොටස් 1000ක් රු. 55 ට විකිණූ විට ප්‍රාග්ධන ලාභය = (55 - 40) × 1000 = රු. 15,000.",
        examTip = "💡 මුළු ආදායම යනු ලැබුණු ලාභාංශය සහ ප්‍රාග්ධන ලාභයේ එකතුවයි."
      ),
      OlSubjectToolItem(
        id = "math_tool_100",
        subject = "ගණිතය",
        toolNumber = 100,
        groupNumber = 10,
        titleSinhala = "විදේශ විනිමය සහ මුදල් පරිවර්තන මෙවලම",
        titleEnglish = "Foreign Currency Exchange Rate Converter",
        category = "වාණිජ ගණිතය",
        icon = "💱",
        quickSummary = "USD, GBP, EUR, JPY ආදී විදේශ මුදල් ශ්‍රී ලංකා රුපියල් (LKR) සමග හුවමාරු අනුපාත ගණනය.",
        formulaOrRule = "LKR වටිනාකම = විදේශ මුදල් ප්‍රමාණය × විනිමය අනුපාතිකය",
        practicalApplication = "1 USD = 305 LKR නම්, 500 USD = 500 × 305 = 152,500 LKR.",
        examTip = "💡 බැංකුවක් විදේශ මුදල් 'ගැණුම් මිල' (Buying rate) සහ 'විකුණුම් මිල' (Selling rate) ලෙස වෙනස් අනුපාත දෙකක් පවත්වා ගන්නා අතර බැංකුව විකුණන මිල සැමවිටම වැඩිය."
      )
    )
  }
}
