package com.example

object OlSubjectToolsEnglishData {
  val tools: List<OlSubjectToolItem> by lazy {
    listOf(
      // --- GROUP 1: TENSES & VERB FORMS (1-10) ---
      OlSubjectToolItem(
        id = "eng_tool_01",
        subject = "ඉංග්‍රීසි",
        toolNumber = 1,
        groupNumber = 1,
        titleSinhala = "සරල වර්තමාන කාලය (Simple Present Tense)",
        titleEnglish = "Simple Present Tense Master Rule",
        category = "Tenses",
        icon = "⏳",
        quickSummary = "දෛනික පුරුදු, විශ්ව සත්‍යයන් සහ සාමාන්‍ය සත්‍ය ප්‍රකාශ කිරීමට භාවිත වේ.",
        formulaOrRule = "Subject (He/She/It) + Verb + s/es/ies | Subject (I/We/You/They) + Verb (Base form)",
        practicalApplication = "He plays cricket every Saturday. / The sun rises in the east. / Water boils at 100°C.",
        examTip = "💡 'Always, usually, often, everyday, never' ආදී වචන තිබේ නම් එය Simple Present Tense බව හඳුනාගන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_02",
        subject = "ඉංග්‍රීසි",
        toolNumber = 2,
        groupNumber = 1,
        titleSinhala = "වර්තමාන අඛණ්ඩ කාලය (Present Continuous Tense)",
        titleEnglish = "Present Continuous (am/is/are + verb-ing)",
        category = "Tenses",
        icon = "🏃",
        quickSummary = "මේ මොහොතේ සිදුවෙමින් පවතින ක්‍රියාවක් හෝ ආසන්න අනාගත සැලැස්මක් දැක්වීම.",
        formulaOrRule = "Subject + am/is/are + Verb-ing",
        practicalApplication = "Look! The children are playing in the garden. / I am preparing for my O/L examination right now.",
        examTip = "💡 'Look!, Listen!, at the moment, currently, right now' ආදී වදන් තිබේ නම් Present Continuous යොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_03",
        subject = "ඉංග්‍රීසි",
        toolNumber = 3,
        groupNumber = 1,
        titleSinhala = "වර්තමාන පූර්ණ කාලය (Present Perfect Tense)",
        titleEnglish = "Present Perfect (have/has + Past Participle V3)",
        category = "Tenses",
        icon = "✅",
        quickSummary = "අතීතයේදී සිදුවී අවසන් වූ නමුත් එහි බලපෑම තවමත් පවතින ක්‍රියා.",
        formulaOrRule = "Subject + have/has + Past Participle (V3)",
        practicalApplication = "She has just finished her homework. / I have lived in Kandy for ten years.",
        examTip = "💡 'Just, already, yet, ever, never, since, for' තිබේ නම් Present Perfect Tense (have/has + V3) යෙදිය යුතුය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_04",
        subject = "ඉංග්‍රීසි",
        toolNumber = 4,
        groupNumber = 1,
        titleSinhala = "Since සහ For නිවැරදි භාවිතය",
        titleEnglish = "Since vs For in Perfect Tenses",
        category = "Grammar",
        icon = "⏱️",
        quickSummary = "ක්‍රියාවක් ආරම්භ වූ නිශ්චිත ලක්ෂ්‍යය සඳහා Since ද, කාල සීමාව (ගණන) සඳහා For ද යෙදේ.",
        formulaOrRule = "Since + Point in time (Since 2015, Since Monday, Since 8.00 am) | For + Period of time (For 3 hours, For 5 days)",
        practicalApplication = "He has been studying since morning. (උදෑසන සිට) / He has been studying for five hours. (පැය 5ක් තිස්සේ).",
        examTip = "💡 O/L Test 3 සහ Test 9 හි නිතරම අසන ප්‍රශ්නයකි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_05",
        subject = "ඉංග්‍රීසි",
        toolNumber = 5,
        groupNumber = 1,
        titleSinhala = "සරල අතීත කාලය (Simple Past Tense)",
        titleEnglish = "Simple Past Tense (Subject + V2)",
        category = "Tenses",
        icon = "📜",
        quickSummary = "අතීතයේ නිශ්චිත වේලාවකදී සිදුවී අවසන් වූ ක්‍රියා (කතන්දර ලිවීමේදී බහුලව යෙදේ).",
        formulaOrRule = "Subject + Past Form of Verb (V2) | ප්‍රශ්න සහ ඍණ: did + base verb (did not go)",
        practicalApplication = "We visited Anuradhapura yesterday. / Did you watch the news last night?",
        examTip = "💡 Did යෙදූ පසු ප්‍රධාන ක්‍රියා පදය අනිවාර්යයෙන්ම මූලික ස්වරූපයෙන් (Base verb) තිබිය යුතුය (Did you went වැරදිය; Did you go නිවැරදිය)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_06",
        subject = "ඉංග්‍රීසි",
        toolNumber = 6,
        groupNumber = 1,
        titleSinhala = "අතීත අඛණ්ඩ කාලය (Past Continuous Tense)",
        titleEnglish = "Past Continuous (was/were + verb-ing)",
        category = "Tenses",
        icon = "⏮️",
        quickSummary = "අතීතයේ යම් වේලාවක සිදුවෙමින් පැවති ක්‍රියාවක් හෝ තවත් ක්‍රියාවකින් බාධා වූ ක්‍රියාවක්.",
        formulaOrRule = "Subject + was/were + Verb-ing | While + Past Continuous, Simple Past",
        practicalApplication = "I was reading a book when the phone rang. / While we were walking, it started raining.",
        examTip = "💡 'When' සමග බොහෝ විට Simple Past ද, 'While' සමග Past Continuous ද යෙදේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_07",
        subject = "ඉංග්‍රීසි",
        toolNumber = 7,
        groupNumber = 1,
        titleSinhala = "අතීත පූර්ණ කාලය (Past Perfect Tense)",
        titleEnglish = "Past Perfect (had + Past Participle V3)",
        category = "Tenses",
        icon = "⏮️",
        quickSummary = "අතීතයේ සිදුවීම් දෙකක් අතරින් පළමුවෙන් සිදුවූ ක්‍රියාව දැක්වීම.",
        formulaOrRule = "පළමු ක්‍රියාව: had + V3 | දෙවන ක්‍රියාව: Simple Past (V2)",
        practicalApplication = "The train had already left before we reached the station.",
        examTip = "💡 Before සමග Simple Past ද, After සමග Past Perfect ද (After he had eaten, he went out) යෙදේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_08",
        subject = "ඉංග්‍රීසි",
        toolNumber = 8,
        groupNumber = 1,
        titleSinhala = "අනාගත කාලය: Will vs Going to",
        titleEnglish = "Future Tense: Will vs Going to",
        category = "Tenses",
        icon = "🔮",
        quickSummary = "හදිසි තීරණ/අනුමාන සඳහා will ද, කලින් සැලසුම් කළ ක්‍රියා/සාක්ෂි සහිත අනාගත ක්‍රියා සඳහා be going to ද යෙදේ.",
        formulaOrRule = "Will + Base verb (ක්ෂණික තීරණ) | am/is/are + going to + Base verb (සැලසුම්)",
        practicalApplication = "Look at those dark clouds! It is going to rain. / I think our team will win the match.",
        examTip = "💡 ඇසට පෙනෙන සාක්ෂි (Evidence) ඇති විට සැමවිටම 'going to' තෝරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_09",
        subject = "ඉංග්‍රීසි",
        toolNumber = 9,
        groupNumber = 1,
        titleSinhala = "අක්‍රමවත් ක්‍රියා පද (Irregular Verbs) ත්‍රිත්වය",
        titleEnglish = "Top 50 Irregular Verbs (V1 - V2 - V3)",
        category = "Verbs",
        icon = "🔄",
        quickSummary = "-ed එකතු නොවන, වෙනස් වන ක්‍රියා පද ස්වරූප මතක තබා ගැනීම.",
        formulaOrRule = "go-went-gone, write-wrote-written, see-saw-seen, take-took-taken, speak-spoke-spoken, begin-began-begun",
        practicalApplication = "Write (ලිවීම) -> wrote (ලිව්වා) -> written (ලියා ඇත).",
        examTip = "💡 Past Participle (V3) යෙදෙන්නේ Perfect tenses සහ Passive Voice වලදී පමණි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_10",
        subject = "ඉංග්‍රීසි",
        toolNumber = 10,
        groupNumber = 1,
        titleSinhala = "උක්තය සහ ආඛ්‍යාතය අතර එකඟතාව (Subject-Verb Agreement)",
        titleEnglish = "Subject-Verb Agreement Rules",
        category = "Grammar",
        icon = "⚖️",
        quickSummary = "ඒකවචන උක්තයකට ඒකවචන ක්‍රියාවක්ද, බහුවචන උක්තයකට බහුවචන ක්‍රියාවක්ද යෙදීම.",
        formulaOrRule = "Everyone, someone, each, neither of -> ඒකවචන ක්‍රියා (is/has/plays) | Both, many, several -> බහුවචන (are/have)",
        practicalApplication = "Each of the boys has received a certificate. / Neither of the answers is correct.",
        examTip = "💡 'Along with, together with, as well as' යෙදුණු විට ක්‍රියාව තීරණය වන්නේ පළමු උක්තය අනුවය (The teacher as well as the students is present)."
      ),

      // --- GROUP 2: MODAL VERBS & CONDITIONALS (11-20) ---
      OlSubjectToolItem(
        id = "eng_tool_11",
        subject = "ඉංග්‍රීසි",
        toolNumber = 11,
        groupNumber = 2,
        titleSinhala = "Can, Could සහ Be able to භාවිතය",
        titleEnglish = "Can / Could / Be able to (Ability & Permission)",
        category = "Modals",
        icon = "💪",
        quickSummary = "හැකියාව (Ability), අවසරය (Permission) සහ ආචාරශීලී ඉල්ලීම් (Polite requests).",
        formulaOrRule = "Modal + Base Verb (Can + do / Could + help)",
        practicalApplication = "Could you please lend me your dictionary? (ඉතා ආචාරශීලී ඉල්ලීමකි).",
        examTip = "💡 Could යනු can හි අතීත කාලය මෙන්ම වර්තමානයේ ආචාරශීලී ඉල්ලීම් සඳහාද යෙදේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_12",
        subject = "ඉංග්‍රීසි",
        toolNumber = 12,
        groupNumber = 2,
        titleSinhala = "May, Might සහ සම්භාවිතාව",
        titleEnglish = "May / Might (Possibility & Formal Permission)",
        category = "Modals",
        icon = "🎲",
        quickSummary = "යම් දෙයක් සිදුවීමට ඇති හැකියාව/අවදානම (50% සම්භාවිතාව) සහ නිල අවසර ඉල්ලීම.",
        formulaOrRule = "May I come in, Sir? | It might rain this evening (අවම සම්භාවිතාව).",
        practicalApplication = "The doctor may arrive late today due to heavy traffic.",
        examTip = "💡 May වඩාත් විධිමත් (formal) වන අතර might වඩා අඩු සම්භාවිතාවක් පෙන්වයි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_13",
        subject = "ඉංග්‍රීසි",
        toolNumber = 13,
        groupNumber = 2,
        titleSinhala = "Must, Have to සහ Should (අනිවාර්යතාව සහ උපදෙස්)",
        titleEnglish = "Must, Have to & Should (Obligation & Advice)",
        category = "Modals",
        icon = "⚠️",
        quickSummary = "Must = අභ්‍යන්තර දැඩි අනිවාර්යතාව | Have to = බාහිර නීති රීති | Should = හිතවත් උපදෙස්.",
        formulaOrRule = "You must wear a helmet. / You should eat more vegetables. / Must not = තහනම්.",
        practicalApplication = "Candidates must bring their admission cards to the examination hall.",
        examTip = "💡 Don't have to යන්නෙන් අදහස් වන්නේ 'අවශ්‍ය නොවේ' (Not necessary) මිස 'තහනම්' (Forbidden) යන්න නොවේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_14",
        subject = "ඉංග්‍රීසි",
        toolNumber = 14,
        groupNumber = 2,
        titleSinhala = "පළමු කොන්දේසි වාක්‍ය (Type 1 Conditional - Real)",
        titleEnglish = "First Conditional (If + Present, will + verb)",
        category = "Conditionals",
        icon = "🔀",
        quickSummary = "අනාගතයේදී ඉටුවීමට බොහෝ දුරට ඉඩ ඇති සැබෑ කොන්දේසි.",
        formulaOrRule = "If + Simple Present, Subject + will/can + Base Verb",
        practicalApplication = "If you study hard, you will pass the exam with an 'A' grade.",
        examTip = "💡 'If' අඩංගු වාක්‍ය ඛණ්ඩය තුළ කිසිවිටෙකත් 'will' නොයොදන්න (If you will study hard වැරදිය)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_15",
        subject = "ඉංග්‍රීසි",
        toolNumber = 15,
        groupNumber = 2,
        titleSinhala = "දෙවන කොන්දේසි වාක්‍ය (Type 2 Conditional - Imaginary)",
        titleEnglish = "Second Conditional (If + Past, would + verb)",
        category = "Conditionals",
        icon = "💭",
        quickSummary = "වර්තමානයේ හෝ අනාගතයේ සිදුවිය නොහැකි, උපකල්පිත හෝ මනඃකල්පිත සිදුවීම්.",
        formulaOrRule = "If + Simple Past (were/V2), Subject + would + Base Verb",
        practicalApplication = "If I were the President, I would provide free education for all.",
        examTip = "💡 මෙහිදී I සමග 'was' වෙනුවට 'were' යෙදීම සම්මත ව්‍යාකරණ නීතියයි (If I were you...)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_16",
        subject = "ඉංග්‍රීසි",
        toolNumber = 16,
        groupNumber = 2,
        titleSinhala = "තුන්වන කොන්දේසි වාක්‍ය (Type 3 Conditional - Regret)",
        titleEnglish = "Third Conditional (If + Past Perfect, would have + V3)",
        category = "Conditionals",
        icon = "🕰️",
        quickSummary = "අතීතයේදී සිදුනොවූ දෙයක් ගැන පසුතැවීම හෝ අතීත මනඃකල්පිත විවරණය.",
        formulaOrRule = "If + had + V3, Subject + would have + V3",
        practicalApplication = "If they had invited me, I would have attended the wedding party.",
        examTip = "💡 O/L විභාගයේ Test 9 හි හිස්තැන් පිරීම සඳහා නිතරම ලැබෙන ප්‍රශ්නයකි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_17",
        subject = "ඉංග්‍රීසි",
        toolNumber = 17,
        groupNumber = 2,
        titleSinhala = "Unless (If not) භාවිතය",
        titleEnglish = "Unless = If ... not Rule",
        category = "Conditionals",
        icon = "⛔",
        quickSummary = "'Unless' යන්න තුළම ඍණ අර්ථය (නොකළහොත්) අඩංගු බැවින් ඊළඟට ඍණ පද නොයෙදේ.",
        formulaOrRule = "Unless + ධන ක්‍රියාව = If + ඍණ ක්‍රියාව",
        practicalApplication = "Unless you work hard, you will fail. = If you do not work hard, you will fail.",
        examTip = "💡 'Unless you don't work hard' ලෙස ලිවීම වැරදිය (ද්විත්ව ඍණ නොයොදන්න)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_18",
        subject = "ඉංග්‍රීසි",
        toolNumber = 18,
        groupNumber = 2,
        titleSinhala = "Wish සහ If only ප්‍රකාශන",
        titleEnglish = "Wish / If only (Unreal Wishes)",
        category = "Conditionals",
        icon = "✨",
        quickSummary = "වර්තමාන තත්ත්වය වෙනස් වීමට කැමති බව ප්‍රකාශ කිරීම (Simple Past සමග).",
        formulaOrRule = "I wish + Subject + Past Simple (were / had / knew)",
        practicalApplication = "I wish I had a car. / If only I knew the answer!",
        examTip = "💡 අනාගත බලාපොරොත්තු සඳහා 'I hope' ද, කළ නොහැකි දේ සඳහා 'I wish' ද යොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_19",
        subject = "ඉංග්‍රීසි",
        toolNumber = 19,
        groupNumber = 2,
        titleSinhala = "Had better සහ Would rather",
        titleEnglish = "Had better (Warning) & Would rather (Preference)",
        category = "Modals",
        icon = "💡",
        quickSummary = "Had better = නොකළහොත් කරදරයක් විය හැකි බැවින් කළ යුතුම උපදෙස් | Would rather = කැමැත්ත.",
        formulaOrRule = "Had better + Base Verb | Would rather + Base Verb",
        practicalApplication = "You had better leave now or you will miss the train. / I would rather drink tea than coffee.",
        examTip = "💡 'Had better' අතීත කාලයක් නොවේ; එය වර්තමාන හෝ අනාගත උපදෙසකි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_20",
        subject = "ඉංග්‍රීසි",
        toolNumber = 20,
        groupNumber = 2,
        titleSinhala = "Used to vs Be used to",
        titleEnglish = "Used to (Past Habit) vs Be used to (Accustomed)",
        category = "Verbs",
        icon = "🔄",
        quickSummary = "Used to = අතීතයේ පුරුද්දක්ව පැවති දැන් නොකරන දේ | Be used to = යමකට හුරුවී සිටීම.",
        formulaOrRule = "Subject + used to + Base Verb | Subject + am/is/are + used to + Verb-ing",
        practicalApplication = "My grandfather used to ride a bicycle. / I am used to waking up early.",
        examTip = "💡 'Be used to' පිටුපසින් ක්‍රියා පදයේ -ing ස්වරූපය යෙදිය යුතුය."
      ),

      // --- GROUP 3: ACTIVE & PASSIVE VOICE (21-30) ---
      OlSubjectToolItem(
        id = "eng_tool_21",
        subject = "ඉංග්‍රීසි",
        toolNumber = 21,
        groupNumber = 3,
        titleSinhala = "කර්ම කාරකයේ (Passive Voice) මූලික රීතිය",
        titleEnglish = "Passive Voice Master Principle (be + V3)",
        category = "Voice",
        icon = "🔄",
        quickSummary = "ක්‍රියාව කළ පුද්ගලයාට (කර්තෘට) වඩා සිදුවූ ක්‍රියාව හෝ කර්මය වැදගත් වන විට යෙදේ.",
        formulaOrRule = "Object -> Subject බවට පත්වේ + be ක්‍රියා පදය + Past Participle (V3) + (by + Agent)",
        practicalApplication = "Active: The chef prepares delicious meals. -> Passive: Delicious meals are prepared by the chef.",
        examTip = "💡 ඕනෑම Passive Voice වාක්‍යයක ප්‍රධාන ක්‍රියා පදය අනිවාර්යයෙන්ම Past Participle (V3) වේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_22",
        subject = "ඉංග්‍රීසි",
        toolNumber = 22,
        groupNumber = 3,
        titleSinhala = "Simple Present & Simple Past Passive",
        titleEnglish = "Simple Present & Past Passive Transformations",
        category = "Voice",
        icon = "📝",
        quickSummary = "වර්තමානයේ: am/is/are + V3 | අතීතයේ: was/were + V3.",
        formulaOrRule = "Active: Shakespeare wrote Hamlet. -> Passive: Hamlet was written by Shakespeare.",
        practicalApplication = "Active: Millions of people speak English. -> Passive: English is spoken by millions of people.",
        examTip = "💡 කර්මය බහුවචන නම් ක්‍රියාවද බහුවචන (are / were) විය යුතුය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_23",
        subject = "ඉංග්‍රීසි",
        toolNumber = 23,
        groupNumber = 3,
        titleSinhala = "Continuous Tenses Passive (Being + V3)",
        titleEnglish = "Continuous Passive (am/is/are/was/were + being + V3)",
        category = "Voice",
        icon = "🏃",
        quickSummary = "සිදුවෙමින් පවතින ක්‍රියාවක කර්ම කාරකය සෑදීමට 'being' එක් කළ යුතුය.",
        formulaOrRule = "Subject + is/are/was/were + BEING + Past Participle (V3)",
        practicalApplication = "Active: The workers are repairing the road. -> Passive: The road is being repaired by the workers.",
        examTip = "💡 Continuous Passive වලදී 'being' අතපසු නොකරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_24",
        subject = "ඉංග්‍රීසි",
        toolNumber = 24,
        groupNumber = 3,
        titleSinhala = "Perfect Tenses Passive (Been + V3)",
        titleEnglish = "Perfect Passive (have/has/had + been + V3)",
        category = "Voice",
        icon = "✅",
        quickSummary = "පූර්ණ කාලවල කර්ම කාරකය සෑදීමට 'been' එක් කරයි.",
        formulaOrRule = "Subject + have/has/had + BEEN + Past Participle (V3)",
        practicalApplication = "Active: Someone has stolen my bicycle. -> Passive: My bicycle has been stolen.",
        examTip = "💡 කර්තෘ නොදන්නා හෝ වැදගත් නොවන විට (someone, they, people) 'by someone' ලිවීම අනවශ්‍යය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_25",
        subject = "ඉංග්‍රීසි",
        toolNumber = 25,
        groupNumber = 3,
        titleSinhala = "Modal Verbs Passive (Can be, Must be + V3)",
        titleEnglish = "Passive Voice with Modals (Modal + be + V3)",
        category = "Voice",
        icon = "🛡️",
        quickSummary = "Can, could, must, should, will පිටුපසින් 'be' යොදා V3 එක්කිරීම.",
        formulaOrRule = "Subject + Modal + BE + Past Participle (V3)",
        practicalApplication = "Active: You must submit the assignment on Monday. -> Passive: The assignment must be submitted on Monday.",
        examTip = "💡 Plastic can be recycled easily. (විද්‍යාත්මක හා විස්තරාත්මක රචනාවලට අත්‍යවශ්‍ය වේ)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_26",
        subject = "ඉංග්‍රීසි",
        toolNumber = 26,
        groupNumber = 3,
        titleSinhala = "කර්ම දෙකක් සහිත වාක්‍ය Passive කිරීම",
        titleEnglish = "Verbs with Two Objects (Direct & Indirect)",
        category = "Voice",
        icon = "🎁",
        quickSummary = "Give, send, offer, teach වැනි ක්‍රියා පදවල පුද්ගල කර්මය හෝ ද්‍රව්‍යමය කර්මය මුලට ගෙන Passive කළ හැක.",
        formulaOrRule = "Active: The teacher gave me a prize. -> Passive 1: I was given a prize. / Passive 2: A prize was given to me.",
        practicalApplication = "පුද්ගලයා මුලට ගෙන සෑදීම වඩාත් ස්වභාවික ඉංග්‍රීසි රටාවයි (I was offered a new job).",
        examTip = "💡 ද්‍රව්‍ය මුලට ගන්නා විට පුද්ගලයා ඉදිරියට 'to' යෙදිය යුතුය (A book was given to him)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_27",
        subject = "ඉංග්‍රීසි",
        toolNumber = 27,
        groupNumber = 3,
        titleSinhala = "ප්‍රශ්න වාක්‍ය Passive කිරීම",
        titleEnglish = "Passive Questions (Do/Did/Does -> Am/Is/Are/Was/Were)",
        category = "Voice",
        icon = "❓",
        quickSummary = "ප්‍රශ්නාර්ථ වාක්‍ය කර්ම කාරකයට හැරවීමේ ක්‍රමය.",
        formulaOrRule = "Active: Did she bake the cake? -> Passive: Was the cake baked by her?",
        practicalApplication = "Active: Who wrote this poem? -> Passive: By whom was this poem written?",
        examTip = "💡 ප්‍රශ්නාර්ථ රටාව (Auxiliary verb + Subject + Main verb) එලෙසම රැකගත යුතුය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_28",
        subject = "ඉංග්‍රීසි",
        toolNumber = 28,
        groupNumber = 3,
        titleSinhala = "අවවාද සහ විධාන Passive කිරීම (Imperatives)",
        titleEnglish = "Imperatives in Passive (Let + Object + be + V3)",
        category = "Voice",
        icon = "📢",
        quickSummary = "විධාන වාක්‍යයක් 'Let' මගින් හෝ 'You are requested/ordered to' මගින් Passive කිරීම.",
        formulaOrRule = "Let + Object + be + V3 | හෝ You are requested/advised to + Verb",
        practicalApplication = "Active: Close the door. -> Passive: Let the door be closed. / You are requested to close the door.",
        examTip = "💡 නිල දැන්වීම්වල (Notices) නිතරම මෙම රටාව දැකිය හැක."
      ),
      OlSubjectToolItem(
        id = "eng_tool_29",
        subject = "ඉංග්‍රීසි",
        toolNumber = 29,
        groupNumber = 3,
        titleSinhala = "විධිමත් වාර්තාකරණ Passive (It is said that...)",
        titleEnglish = "Impersonal Passive (It is believed/reported that...)",
        category = "Voice",
        icon = "📰",
        quickSummary = "පුවත්පත් සහ නිල වාර්තාවල මහජන මතය දැක්වීමට යොදන ආචාරශීලී ක්‍රමය.",
        formulaOrRule = "It is + said/believed/expected/reported + that ...",
        practicalApplication = "Active: People say that he is honest. -> Passive: It is said that he is honest. / He is said to be honest.",
        examTip = "💡 රචනා සහ ලිපි ලිවීමේදී (Articles) උසස් භාෂා ශෛලියක් පෙන්වීමට මෙය භාවිත කරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_30",
        subject = "ඉංග්‍රීසි",
        toolNumber = 30,
        groupNumber = 3,
        titleSinhala = "ක්‍රියාවලියක් විස්තර කිරීමේදී Passive Voice භාවිතය",
        titleEnglish = "Process Description using Passive Voice",
        category = "Writing",
        icon = "🏭",
        quickSummary = "තේ සෑදීම, කඩදාසි නිෂ්පාදනය හෝ වට්ටෝරු විස්තර කිරීමේදී Simple Present Passive යෙදීම.",
        formulaOrRule = "First, tea leaves are plucked. Then they are withered and crushed.",
        practicalApplication = "Next, the mixture is heated at 80°C for 20 minutes.",
        examTip = "💡 O/L Test 16 හි 'Describe a process' ප්‍රශ්නයට පිළිතුරු ලිවීමේදී 100% ක්ම Passive Voice යොදන්න."
      ),

      // --- GROUP 4: DIRECT & INDIRECT (REPORTED) SPEECH (31-40) ---
      OlSubjectToolItem(
        id = "eng_tool_31",
        subject = "ඉංග්‍රීසි",
        toolNumber = 31,
        groupNumber = 4,
        titleSinhala = "කථනය මාරු කිරීමේ කාල විතැන්වීම් (Tense Backshift)",
        titleEnglish = "Tense Shifts in Reported Speech",
        category = "Reported Speech",
        icon = "🗣️",
        quickSummary = "වාර්තාකරණ ක්‍රියා පදය අතීත කාලීන වූ විට (said, told), ප්‍රකාශයේ කාලය එක් පියවරක් අතීතයට යයි.",
        formulaOrRule = "Present Simple -> Past Simple | Present Continuous -> Past Continuous | Present Perfect -> Past Perfect | will -> would | can -> could",
        practicalApplication = "Direct: \"I work in Colombo,\" Kamal said. -> Indirect: Kamal said that he worked in Colombo.",
        examTip = "💡 විශ්ව සත්‍යයක් ප්‍රකාශ කළ විට කාලය වෙනස් නොවේ (The teacher said that the earth moves round the sun)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_32",
        subject = "ඉංග්‍රීසි",
        toolNumber = 32,
        groupNumber = 4,
        titleSinhala = "කාලය සහ ස්ථානීය වචන මාරුවන ආකාරය",
        titleEnglish = "Time & Place Expressions Changes",
        category = "Reported Speech",
        icon = "🗺️",
        quickSummary = "Reported Speech බවට පත්වීමේදී කාලය හා ස්ථානය නිරූපණය වන වචන ඈත්වේ.",
        formulaOrRule = "now -> then | today -> that day | yesterday -> the previous day | tomorrow -> the next day / following day | here -> there | this -> that",
        practicalApplication = "\"I will meet you tomorrow,\" she said. -> She said that she would meet me the next day.",
        examTip = "💡 විභාගයේදී 'tomorrow' සහ 'yesterday' වෙනස් කිරීමට අමතක නොකරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_33",
        subject = "ඉංග්‍රීසි",
        toolNumber = 33,
        groupNumber = 4,
        titleSinhala = "සාමාන්‍ය ප්‍රකාශන වාර්තා කිරීම (Statements)",
        titleEnglish = "Reporting Statements (said that / told me that)",
        category = "Reported Speech",
        icon = "💬",
        quickSummary = "Told යෙදූ විට කතා කළ පුද්ගලයා (Object) දැක්විය යුතුය; Said යෙදූ විට පුද්ගලයා දැක්වීම අනිවාර්ය නොවේ.",
        formulaOrRule = "Said that ... | Told + person + that ... (He told me that...)",
        practicalApplication = "Direct: \"I have lost my key,\" Nimal said to me. -> Indirect: Nimal told me that he had lost his key.",
        examTip = "💡 'He told to me' ලිවීම වැරදිය; 'He told me' හෝ 'He said to me' විය යුතුය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_34",
        subject = "ඉංග්‍රීසි",
        toolNumber = 34,
        groupNumber = 4,
        titleSinhala = "Wh- ප්‍රශ්න වාර්තා කිරීම",
        titleEnglish = "Reporting Wh- Questions (What, Where, Why)",
        category = "Reported Speech",
        icon = "❓",
        quickSummary = "Wh- වචනයම සම්බන්ධක පදය ලෙස යොදා වාක්‍යය ප්‍රකාශන රටාවට (Subject + Verb) හරවයි.",
        formulaOrRule = "Subject + asked + Wh-word + Subject + Verb",
        practicalApplication = "Direct: \"Where do you live?\" the officer asked. -> Indirect: The officer asked where I lived.",
        examTip = "💡 'The officer asked where did I live' වැරදිය; ප්‍රශ්නාර්ථ ලකුණද ඉවත් වේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_35",
        subject = "ඉංග්‍රීසි",
        toolNumber = 35,
        groupNumber = 4,
        titleSinhala = "Yes/No ප්‍රශ්න වාර්තා කිරීම (If / Whether)",
        titleEnglish = "Reporting Yes/No Questions (asked if / whether)",
        category = "Reported Speech",
        icon = "❔",
        quickSummary = "Yes හෝ No පිළිතුරු ලැබෙන ප්‍රශ්න සඳහා සම්බන්ධක පදය ලෙස 'if' හෝ 'whether' යොදයි.",
        formulaOrRule = "Subject + asked + if/whether + Subject + Verb",
        practicalApplication = "Direct: \"Are you coming to school?\" Amal asked. -> Indirect: Amal asked if I was coming to school.",
        examTip = "💡 If වෙනුවට whether යෙදීම වඩාත් විධිමත් වේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_36",
        subject = "ඉංග්‍රීසි",
        toolNumber = 36,
        groupNumber = 4,
        titleSinhala = "විධාන සහ ඉල්ලීම් වාර්තා කිරීම (Told to / Asked to)",
        titleEnglish = "Reporting Commands & Requests (to + infinitive)",
        category = "Reported Speech",
        icon = "📢",
        quickSummary = "විධාන සඳහා 'ordered/told to' ද, ඉල්ලීම් සඳහා 'requested/asked to' ද යෙදේ; ඍණ නම් 'not to'.",
        formulaOrRule = "Subject + told/ordered/requested + person + TO / NOT TO + Base Verb",
        practicalApplication = "Direct: \"Don't make a noise,\" the teacher said. -> Indirect: The teacher told the students not to make a noise.",
        examTip = "💡 Please ඉවත් කර ඒ වෙනුවට 'requested' හෝ 'politely asked' යොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_37",
        subject = "ඉංග්‍රීසි",
        toolNumber = 37,
        groupNumber = 4,
        titleSinhala = "උපදෙස් සහ යෝජනා වාර්තා කිරීම (Advised / Suggested)",
        titleEnglish = "Reporting Advice & Suggestions",
        category = "Reported Speech",
        icon = "💡",
        quickSummary = "Let's ... -> Suggested + verb-ing / suggested that we should...",
        formulaOrRule = "He suggested going for a walk. / The doctor advised me to drink more water.",
        practicalApplication = "Direct: \"Let's play football,\" Ruwan said. -> Indirect: Ruwan suggested playing football.",
        examTip = "💡 'Suggested to go' නොලියා 'suggested going' ලෙස ලිවීම නිවැරදිය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_38",
        subject = "ඉංග්‍රීසි",
        toolNumber = 38,
        groupNumber = 4,
        titleSinhala = "විශේෂ වාර්තාකරණ ක්‍රියා පද (Reporting Verbs)",
        titleEnglish = "Advanced Reporting Verbs (Refused, Promised, Warned)",
        category = "Reported Speech",
        icon = "🎯",
        quickSummary = "Said වෙනුවට නිශ්චිත අර්ථය දෙන ක්‍රියා පද: promised, refused, warned, apologized, admitted.",
        formulaOrRule = "He promised to help me. / She apologized for being late. / He warned us not to go there.",
        practicalApplication = "Direct: \"I will definitely return your money,\" he said. -> He promised to return my money.",
        examTip = "💡 රචනා සහ කෙටි කතාවලදී මෙම උසස් ක්‍රියා පද භාවිතයෙන් වැඩි ලකුණු ලැබේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_39",
        subject = "ඉංග්‍රීසි",
        toolNumber = 39,
        groupNumber = 4,
        titleSinhala = "සර්වනාම (Pronouns) මාරුවීමේ නීති",
        titleEnglish = "Pronoun Shifts in Reported Speech",
        category = "Reported Speech",
        icon = "👥",
        quickSummary = "කතා කළ පුද්ගලයා සහ අසන්නා අනුව I, you, we සර්වනාම he, she, they බවට පත්වීම.",
        formulaOrRule = "I -> he/she | my -> his/her | we -> they | our -> their | you -> I/he/she/they",
        practicalApplication = "\"My brother is waiting for me,\" Mala said. -> Mala said that her brother was waiting for her.",
        examTip = "💡 වාක්‍යයේ අර්ථය හොඳින් තේරුම් ගෙන සර්වනාම මාරු කරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_40",
        subject = "ඉංග්‍රීසි",
        toolNumber = 40,
        groupNumber = 4,
        titleSinhala = "සංවාදයක් ඡේදයක් ලෙස වාර්තා කිරීම (Dialogue to Paragraph)",
        titleEnglish = "Converting Dialogue into Reported Paragraph",
        category = "Reported Speech",
        icon = "📜",
        quickSummary = "O/L Test 10 හි නිතර ලැබෙන දෙදෙනෙකුගේ සංවාදය ඡේදයක් ලෙස Reported speech මගින් ලිවීම.",
        formulaOrRule = "වාක්‍ය එකිනෙක යා කිරීමට furthermore, then, he also added that වැනි සම්බන්ධක භාවිත කරන්න.",
        practicalApplication = "A asked B where he was going. B replied that he was going to the library and invited A to join him.",
        examTip = "💡 සංවාදයේ ඇති සෑම පේළියක්ම අතපසු නොකර අනුපිළිවෙලින් වාර්තා කරන්න."
      ),

      // --- GROUP 5: PREPOSITIONS & PHRASAL VERBS (41-50) ---
      OlSubjectToolItem(
        id = "eng_tool_41",
        subject = "ඉංග්‍රීසි",
        toolNumber = 41,
        groupNumber = 5,
        titleSinhala = "කාලය දැක්වීමේ නිපාත පද (Prepositions of Time: In, On, At)",
        titleEnglish = "Prepositions of Time: In, On, At Triad",
        category = "Prepositions",
        icon = "⏰",
        quickSummary = "At = නිශ්චිත වේලාව | On = දිනයන් සහ වාර | In = මාස, වර්ෂ, දිගු කාල සීමා.",
        formulaOrRule = "At: at 5.00 pm, at night, at noon | On: on Monday, on 15th May, on my birthday | In: in July, in 2024, in the morning",
        practicalApplication = "The exam begins at 8.30 am on Monday in December.",
        examTip = "💡 'at night' නමුත් 'in the morning / in the evening' වන බව මතක තබාගන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_42",
        subject = "ඉංග්‍රීසි",
        toolNumber = 42,
        groupNumber = 5,
        titleSinhala = "ස්ථාන නිපාත පද (Prepositions of Place: In, On, At)",
        titleEnglish = "Prepositions of Place: In, On, At Guidelines",
        category = "Prepositions",
        icon = "📍",
        quickSummary = "At = නිශ්චිත ලක්ෂ්‍යයක්/ස්ථානයක් | On = පෘෂ්ඨයක් මත | In = සංවෘත ඉඩකඩක්, නගරයක්, රටක්.",
        formulaOrRule = "at school, at the bus stop | on the table, on the wall | in the classroom, in Kandy, in Sri Lanka",
        practicalApplication = "He is waiting at the entrance of the building.",
        examTip = "💡 ලිපිනයක නිශ්චිත අංකය සඳහන් නම් 'at' යෙදේ (at No. 25, Temple Road); පාරේ නම පමණක් නම් 'on' යෙදේ (on Temple Road)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_43",
        subject = "ඉංග්‍රීසි",
        toolNumber = 43,
        groupNumber = 5,
        titleSinhala = "චලිතය දැක්වීමේ නිපාත පද (Into, Onto, Across, Through)",
        titleEnglish = "Prepositions of Movement & Direction",
        category = "Prepositions",
        icon = "🏃",
        quickSummary = "Into = පිටත සිට ඇතුළට | Onto = මතුපිටකට | Through = යමක් මැදින් හරහා | Across = එක් කෙළවරක සිට අනෙක් කෙළවරට.",
        formulaOrRule = "jumped into the river / walked through the tunnel / ran across the road",
        practicalApplication = "The cat jumped onto the table.",
        examTip = "💡 'Enter' ක්‍රියා පදය පිටුපසින් 'into' නොයෙදේ (He entered the room - He entered into the room වැරදිය)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_44",
        subject = "ඉංග්‍රීසි",
        toolNumber = 44,
        groupNumber = 5,
        titleSinhala = "විශේෂ නිපාත සංයෝජන (Dependent Prepositions)",
        titleEnglish = "Essential Dependent Prepositions List",
        category = "Prepositions",
        icon = "🔗",
        quickSummary = "නිශ්චිත නාමවිශේෂණ හා ක්‍රියා සමග පමණක් බැඳී එන නිපාත පද.",
        formulaOrRule = "good at, proud of, afraid of, interested in, believe in, depend on, congratulated on, keen on, famous for",
        practicalApplication = "She is very good at Mathematics. / We are proud of our country.",
        examTip = "💡 'Good in English' ලිවීම වැරදිය; 'Good at English' නිවැරදිය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_45",
        subject = "ඉංග්‍රීසි",
        toolNumber = 45,
        groupNumber = 5,
        titleSinhala = "LOOK ආශ්‍රිත වාක්‍යාංශ ක්‍රියා (Phrasal Verbs with Look)",
        titleEnglish = "High-Frequency Phrasal Verbs with 'Look'",
        category = "Phrasal Verbs",
        icon = "👀",
        quickSummary = "Look for (සෙවීම), Look after (බලාකියා ගැනීම), Look up (වචන සෙවීම), Look forward to (ආශාවෙන් බලා සිටීම).",
        formulaOrRule = "look after = take care of | look for = search | look into = investigate | look forward to + Verb-ing",
        practicalApplication = "Please look after my dog while I am away. / I am looking forward to meeting you.",
        examTip = "💡 'Looking forward to' පිටුපසින් ක්‍රියාවේ -ing ස්වරූපය යෙදිය යුතුය (looking forward to hearing from you)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_46",
        subject = "ඉංග්‍රීසි",
        toolNumber = 46,
        groupNumber = 5,
        titleSinhala = "GIVE සහ TAKE ආශ්‍රිත වාක්‍යාංශ ක්‍රියා",
        titleEnglish = "Phrasal Verbs with 'Give' & 'Take'",
        category = "Phrasal Verbs",
        icon = "🤲",
        quickSummary = "Give up (අත්හැරීම), Give in (යටත්වීම), Give away (නොමිලේ බෙදාදීම), Take off (ගුවන්ගත වීම/ඇඳුම් ගැලවීම), Take after (පෙනුමෙන් සමාන වීම).",
        formulaOrRule = "give up = stop trying | take after = resemble | take place = happen",
        practicalApplication = "Never give up your dreams. / The plane took off on time. / The annual sports meet will take place next Friday.",
        examTip = "💡 'Take place' යනු 'සිදුවීම' (Happen) යන අර්ථයයි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_47",
        subject = "ඉංග්‍රීසි",
        toolNumber = 47,
        groupNumber = 5,
        titleSinhala = "TURN සහ PUT ආශ්‍රිත වාක්‍යාංශ ක්‍රියා",
        titleEnglish = "Phrasal Verbs with 'Turn' & 'Put'",
        category = "Phrasal Verbs",
        icon = "🔄",
        quickSummary = "Turn on/off (ක්‍රියාත්මක/අක්‍රිය කිරීම), Turn down (ප්‍රතික්ෂේප කිරීම), Put off (කල් දැමීම), Put out (ගිනි නිවීම), Put on (ඇඳීම).",
        formulaOrRule = "put off = postpone | put out = extinguish (fire) | turn down = reject",
        practicalApplication = "The fire brigade put out the fire quickly. / The meeting was put off due to heavy rain.",
        examTip = "💡 විභාග ප්‍රශ්න පත්‍රවල 'put out the fire' සහ 'put off the match' නිතරම අසයි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_48",
        subject = "ඉංග්‍රීසි",
        toolNumber = 48,
        groupNumber = 5,
        titleSinhala = "Between vs Among භාවිතය",
        titleEnglish = "Between vs Among Differentiation",
        category = "Prepositions",
        icon = "👥",
        quickSummary = "Between = පුද්ගලයන් හෝ ද්‍රව්‍ය දෙදෙනෙකු අතර | Among = දෙදෙනෙකුට වැඩි පිරිසක් අතර.",
        formulaOrRule = "Between two people/things | Among three or more",
        practicalApplication = "Divide the sweets between Kasun and Dasun. / Share the books among all the students in the class.",
        examTip = "💡 දෙදෙනෙකු ගැන කියවෙන විට සැමවිටම 'between' යොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_49",
        subject = "ඉංග්‍රීසි",
        toolNumber = 49,
        groupNumber = 5,
        titleSinhala = "Beside vs Besides භාවිතය",
        titleEnglish = "Beside (Next to) vs Besides (In addition to)",
        category = "Prepositions",
        icon = "➕",
        quickSummary = "Beside = යමකට යාබදව (Next to) | Besides = ඊට අමතරව (In addition to).",
        formulaOrRule = "beside = by the side of | besides = apart from, as well as",
        practicalApplication = "He sat beside me in the bus. / Besides English, she speaks French fluently.",
        examTip = "💡 's' අකුර එකතු වූ විට 'අමතරව' යන අර්ථය ලැබෙන බව මතක තබාගන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_50",
        subject = "ඉංග්‍රීසි",
        toolNumber = 50,
        groupNumber = 5,
        titleSinhala = "Die of vs Die from නිවැරදි භාවිතය",
        titleEnglish = "Die of vs Die from Usage Rules",
        category = "Prepositions",
        icon = "⚕️",
        quickSummary = "රෝගයකින් මියයාම සඳහා 'die of' ද, බාහිර අනතුරකින් හෝ කුසගින්නෙන් මියයාම සඳහා 'die from' ද යෙදේ.",
        formulaOrRule = "die of + disease (cancer, malaria) | die from + external cause (wound, starvation, thirst)",
        practicalApplication = "The old man died of cancer. / Many animals died from starvation during the drought.",
        examTip = "💡 O/L Test 3 හි නිතරම අසන ප්‍රශ්නයකි."
      ),

      // --- GROUP 6: RELATIVE CLAUSES & CONJUNCTIONS (51-60) ---
      OlSubjectToolItem(
        id = "eng_tool_51",
        subject = "ඉංග්‍රීසි",
        toolNumber = 51,
        groupNumber = 6,
        titleSinhala = "සම්බන්ධක සර්වනාම: Who, Whom, Whose",
        titleEnglish = "Relative Pronouns: Who, Whom, Whose",
        category = "Relative Clauses",
        icon = "👤",
        quickSummary = "Who = පුද්ගල උක්තය | Whom = පුද්ගල කර්මය | Whose = අයිතිය (කාගේද).",
        formulaOrRule = "Who + Verb | Whom + Subject + Verb | Whose + Noun",
        practicalApplication = "The boy who won the race is my friend. / The boy whose father is a doctor won the prize.",
        examTip = "💡 අයිතියක් දක්වන විට (his, her, their වෙනුවට) සැමවිටම 'whose' යොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_52",
        subject = "ඉංග්‍රීසි",
        toolNumber = 52,
        groupNumber = 6,
        titleSinhala = "Which සහ That භාවිතය",
        titleEnglish = "Which vs That for Things & Animals",
        category = "Relative Clauses",
        icon = "📦",
        quickSummary = "ද්‍රව්‍ය සහ සතුන් සම්බන්ධ කිරීමට which හෝ that යොදයි (කොමා සහිත විට which පමණි).",
        formulaOrRule = "The book which/that I bought yesterday is very interesting.",
        practicalApplication = "This is the dog that barked all night.",
        examTip = "💡 කොමා (commas) සහිත අතිරේක තොරතුරු දෙන non-defining clauses වලදී 'that' භාවිත නොකර 'which' යොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_53",
        subject = "ඉංග්‍රීසි",
        toolNumber = 53,
        groupNumber = 6,
        titleSinhala = "FANBOYS සම්බන්ධක (Coordinating Conjunctions)",
        titleEnglish = "FANBOYS: For, And, Nor, But, Or, Yet, So",
        category = "Conjunctions",
        icon = "🔗",
        quickSummary = "ස්වාධීන වාක්‍ය ඛණ්ඩ දෙකක් එකතු කරන මූලික සම්බන්ධක 7.",
        formulaOrRule = "F=For (හේතුව), A=And (එකතු කිරීම), N=Nor (දෙකම නොවේ), B=But (වෙනස), O=Or (විකල්පය), Y=Yet (එහෙත්), S=So (ප්‍රතිඵලය)",
        practicalApplication = "He studied hard, so he passed the exam. / She was tired, yet she finished the project.",
        examTip = "💡 ස්වාධීන වාක්‍ය දෙකක් සම්බන්ධ කරන විට FANBOYS ඉදිරියට කොමාවක් (comma) යොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_54",
        subject = "ඉංග්‍රීසි",
        toolNumber = 54,
        groupNumber = 6,
        titleSinhala = "Although, Even though සහ Though",
        titleEnglish = "Although, Even though, Though (Contrast)",
        category = "Conjunctions",
        icon = "⚖️",
        quickSummary = "අපේක්ෂිත දෙයට ප්‍රතිවිරුද්ධ දෙයක් සිදුවූ විට (කෙසේ වෙතත් / වුවද).",
        formulaOrRule = "Although + Subject + Verb, Main Clause",
        practicalApplication = "Although it rained heavily, we went to school on time.",
        examTip = "💡 'Although ... but' එකවර නොයොදන්න (Although it rained heavily, but we went වැරදිය)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_55",
        subject = "ඉංග්‍රීසි",
        toolNumber = 55,
        groupNumber = 6,
        titleSinhala = "In spite of සහ Despite භාවිතය",
        titleEnglish = "In spite of / Despite + Noun or Verb-ing",
        category = "Conjunctions",
        icon = "🌧️",
        quickSummary = "Although හි අර්ථයම ලබාදෙන නමුත් පිටුපසින් නාම පදයක් හෝ -ing ක්‍රියාවක් යෙදිය යුතුය.",
        formulaOrRule = "Despite / In spite of + Noun / Verb-ing",
        practicalApplication = "Despite the heavy rain, we enjoyed the trip. / In spite of being tired, she completed the work.",
        examTip = "💡 'Despite of' ලිවීම බරපතල වැරැද්දකි; Despite සමග 'of' කිසිවිටෙකත් නොයෙදේ (In spite of නිවැරදිය; Despite නිවැරදිය)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_56",
        subject = "ඉංග්‍රීසි",
        toolNumber = 56,
        groupNumber = 6,
        titleSinhala = "Either ... or සහ Neither ... nor",
        titleEnglish = "Either...or / Neither...nor Parallel Structure",
        category = "Conjunctions",
        icon = "⚖️",
        quickSummary = "Either...or = දෙකෙන් එකක් | Neither...nor = දෙකම නොවේ.",
        formulaOrRule = "ක්‍රියාව තීරණය වන්නේ දෙවන උක්තය අනුවය (Neither Nimal nor his friends WERE present).",
        practicalApplication = "You can have either tea or coffee. / Neither the teacher nor the students were late.",
        examTip = "💡 Nor පිටුපසින් ඇති පදය ඒකවචන නම් ක්‍රියාවද ඒකවචන වේ; බහුවචන නම් ක්‍රියාවද බහුවචන වේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_57",
        subject = "ඉංග්‍රීසි",
        toolNumber = 57,
        groupNumber = 6,
        titleSinhala = "Not only ... but also භාවිතය",
        titleEnglish = "Not only... but also (Correlative)",
        category = "Conjunctions",
        icon = "⭐",
        quickSummary = "එපමණක් නොව ... ද වේ යනුවෙන් කරුණු දෙකක් අවධාරණය කිරීම.",
        formulaOrRule = "Subject + is not only [Adjective 1] + but also [Adjective 2]",
        practicalApplication = "He is not only intelligent but also very hardworking.",
        examTip = "💡 දෙපසම එකම ව්‍යාකරණ රටාව (Parallel structure) තිබිය යුතුය (නාමවිශේෂණ දෙකක් හෝ ක්‍රියා දෙකක්)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_58",
        subject = "ඉංග්‍රීසි",
        toolNumber = 58,
        groupNumber = 6,
        titleSinhala = "However, Therefore සහ Furthermore (ඡේද සම්බන්ධක)",
        titleEnglish = "Discourse Markers: However, Therefore, Furthermore",
        category = "Writing",
        icon = "📝",
        quickSummary = "රචනාවක ඡේද එකිනෙක සුමටව යා කිරීමට යොදන විධිමත් සම්බන්ධක පද.",
        formulaOrRule = "However (කෙසේ වෙතත් - වෙනසක්) | Therefore / As a result (එබැවින් - ප්‍රතිඵලය) | Furthermore / Moreover (තවද - අමතර කරුණු)",
        practicalApplication = "He prepared well for the exam. Therefore, he scored high marks.",
        examTip = "💡 මෙම වචන වාක්‍යයක මුලට යෙදූ විට පිටුපසින් කොමාවක් (comma) යෙදිය යුතුය (However, ...)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_59",
        subject = "ඉංග්‍රීසි",
        toolNumber = 59,
        groupNumber = 6,
        titleSinhala = "Because vs Because of",
        titleEnglish = "Because (Clause) vs Because of (Noun)",
        category = "Conjunctions",
        icon = "❓",
        quickSummary = "Because පිටුපසින් සම්පූර්ණ වාක්‍යයක්ද (Subject + Verb), Because of පිටුපසින් නාම පදයක්ද යෙදේ.",
        formulaOrRule = "Because + Subject + Verb | Because of + Noun / Pronoun",
        practicalApplication = "We stayed indoors because it was raining. / We stayed indoors because of the rain.",
        examTip = "💡 Test 3 හි හිස්තැනට පසුව නාම පදයක් පමණක් ඇත්නම් 'because of' තෝරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_60",
        subject = "ඉංග්‍රීසි",
        toolNumber = 60,
        groupNumber = 6,
        titleSinhala = "So that සහ In order to (අරමුණ දැක්වීම)",
        titleEnglish = "So that (Purpose Clause) vs In order to",
        category = "Conjunctions",
        icon = "🎯",
        quickSummary = "ක්‍රියාවක අරමුණ ප්‍රකාශ කිරීම (යමක් කරගත හැකි වන පරිදි).",
        formulaOrRule = "In order to + Base Verb | So that + Subject + can/could/may + Base Verb",
        practicalApplication = "He woke up early in order to catch the train. / He woke up early so that he could catch the train.",
        examTip = "💡 In order to පිටුපසින් ක්‍රියා පදය පමණක්ද, so that පිටුපසින් සම්පූර්ණ වාක්‍ය ඛණ්ඩයක්ද යෙදේ."
      ),

      // --- GROUP 7: FORMAL & INFORMAL LETTER WRITING (61-70) ---
      OlSubjectToolItem(
        id = "eng_tool_61",
        subject = "ඉංග්‍රීසි",
        toolNumber = 61,
        groupNumber = 7,
        titleSinhala = "විධිමත් ලිපි ආකෘතිය (Formal Letter Layout)",
        titleEnglish = "Official / Formal Letter Standard Layout",
        category = "Letter Writing",
        icon = "✉️",
        quickSummary = "ලිපිනයන් දෙක (Sender's & Receiver's), දිනය, ආමන්ත්‍රණය, මාතෘකාව සහ නිමා කිරීම.",
        formulaOrRule = "Sender's Address -> Date -> Receiver's Designation & Address -> Salutation (Dear Sir/Madam) -> Heading -> Body (3 paragraphs) -> Subscription (Yours faithfully) -> Signature",
        practicalApplication = "විදුහල්පති, ප්‍රාදේශීය ලේකම් හෝ කළමනාකරු වෙත යවන ලිපි සඳහා භාවිත වේ.",
        examTip = "💡 O/L Test 14 හි ලකුණු 10න් ආකෘතියට (Format) පමණක් ලකුණු 2ක් වෙන්කර ඇත."
      ),
      OlSubjectToolItem(
        id = "eng_tool_62",
        subject = "ඉංග්‍රීසි",
        toolNumber = 62,
        groupNumber = 7,
        titleSinhala = "විධිමත් ලිපි ආරම්භක වාක්‍ය (Opening Lines)",
        titleEnglish = "Formal Letter Effective Opening Sentences",
        category = "Letter Writing",
        icon = "✍️",
        quickSummary = "ලිපිය ලිවීමේ අරමුණ මුල් වාක්‍යයෙන්ම ඉතා පැහැදිලිව හා ගෞරවාන්විතව දැක්වීම.",
        formulaOrRule = "I am writing this letter to bring to your kind notice that... / I am writing to apply for the post of... / With reference to your advertisement...",
        practicalApplication = "I am writing this letter on behalf of the English Literary Association of our school.",
        examTip = "💡 'How are you?' වැනි සුහද වදන් විධිමත් ලිපිවලට කිසිසේත්ම නොයොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_63",
        subject = "ඉංග්‍රීසි",
        toolNumber = 63,
        groupNumber = 7,
        titleSinhala = "විධිමත් ලිපි නිමා කිරීම සහ අත්සන (Subscriptions)",
        titleEnglish = "Formal Letter Sign-offs: Yours faithfully vs Yours sincerely",
        category = "Letter Writing",
        icon = "🖋️",
        quickSummary = "ආමන්ත්‍රණය 'Dear Sir/Madam' නම් Yours faithfully ද, නම සඳහන් නම් (Dear Mr. Perera) Yours sincerely ද යෙදේ.",
        formulaOrRule = "Dear Sir/Madam -> Yours faithfully | Dear Mr./Ms. [Name] -> Yours sincerely",
        practicalApplication = "Thanking you, Yours faithfully, [Your Signature], [Your Full Name].",
        examTip = "💡 'Yours' හි 'Y' අකුර කැපිටල් විය යුතු අතර 'faithfuly' අග 'y' කුඩා විය යුතුය (කොමාවක් යොදන්න: Yours faithfully,)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_64",
        subject = "ඉංග්‍රීසි",
        toolNumber = 64,
        groupNumber = 7,
        titleSinhala = "පැමිණිලි ලිපි ලිවීමේ රාමුව (Letter of Complaint)",
        titleEnglish = "Letter of Complaint Writing Framework",
        category = "Letter Writing",
        icon = "⚠️",
        quickSummary = "ගැටලුව, එයින් සිදුවූ අපහසුතාවය සහ අපේක්ෂිත විසඳුම පියවරෙන් පියවර දැක්වීම.",
        formulaOrRule = "Para 1: ගැටලුව හඳුන්වා දීම | Para 2: විස්තර හා බලපෑම | Para 3: කඩිනම් පියවර ගන්නා ලෙස ඉල්ලීම",
        practicalApplication = "I am writing to express my strong dissatisfaction regarding the broken streetlights on Temple Road.",
        examTip = "💡 කෝපයෙන් තොරව, ආචාරශීලී නමුත් දැඩි ස්වරූපයකින් (Polite yet firm tone) ලිවිය යුතුය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_65",
        subject = "ඉංග්‍රීසි",
        toolNumber = 65,
        groupNumber = 7,
        titleSinhala = "අවසර ඉල්ලීමේ ලිපිය (Letter of Permission / Leave)",
        titleEnglish = "Letter Requesting Permission / Absence Leave",
        category = "Letter Writing",
        icon = "🏫",
        quickSummary = "විදුහල්පතිතුමාගෙන් නිවාඩු හෝ අධ්‍යාපනික චාරිකාවක් සඳහා අවසර ඉල්ලීම.",
        formulaOrRule = "I would be grateful if you could kindly grant me permission to...",
        practicalApplication = "I would like to kindly request three days' leave from 10th to 12th October due to a sudden illness.",
        examTip = "💡 අදාළ දින වකවානු සහ හේතුව පැහැදිලිව සඳහන් කරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_66",
        subject = "ඉංග්‍රීසි",
        toolNumber = 66,
        groupNumber = 7,
        titleSinhala = "මිත්‍රශීලී / අවිධිමත් ලිපි ආකෘතිය (Informal Letter)",
        titleEnglish = "Informal / Friendly Letter Writing Layout",
        category = "Letter Writing",
        icon = "💌",
        quickSummary = "මිතුරෙකුට හෝ ඥාතියෙකුට ලියන ලිපිය (එක් ලිපිනයක් පමණි, ආචාරශීලී සුහද ආරම්භය).",
        formulaOrRule = "Sender's Address & Date -> Salutation (Dear Nimal,) -> Friendly Opening -> Body -> Friendly Closing -> Yours lovingly / Your friend",
        practicalApplication = "How are you? I hope this letter finds you in good health and happiness.",
        examTip = "💡 කෙටි යෙදුම් (I'm, don't, can't) අවිධිමත් ලිපිවල භාවිත කළ හැක."
      ),
      OlSubjectToolItem(
        id = "eng_tool_67",
        subject = "ඉංග්‍රීසි",
        toolNumber = 67,
        groupNumber = 7,
        titleSinhala = "කෙටි පණිවිඩ සහ Postcard ලිවීම (Test 6 - ලකුණු 5)",
        titleEnglish = "Short Note / Message & Postcard (Test 6 Guide)",
        category = "Writing",
        icon = "📝",
        quickSummary = "වචන 40-50 කින් අත්‍යවශ්‍ය කරුණු 3-4 ක් ඇතුළත් කර කෙටියෙන් පණිවිඩයක් ලිවීම.",
        formulaOrRule = "දිනය සහ වේලාව -> ආමන්ත්‍රණය -> පණිවිඩයේ ප්‍රධාන කරුණු -> නිමාව සහ නම",
        practicalApplication = "Dear Kasun, I am writing to inform you that our cricket practice has been postponed to tomorrow due to rain. Please bring your bat. Amal.",
        examTip = "💡 ප්‍රශ්නයේ දී ඇති කරුණු (bullet points) සියල්ලම එකක් නෑර අනිවාර්යයෙන්ම ඇතුළත් කළ යුතුය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_68",
        subject = "ඉංග්‍රීසි",
        toolNumber = 68,
        groupNumber = 7,
        titleSinhala = "දැන්වීම් ලිවීම (Notice Writing Master Template)",
        titleEnglish = "Notice Writing 5-Element Template",
        category = "Writing",
        icon = "📌",
        quickSummary = "පාසල් දැන්වීම් පුවරුවේ ප්‍රදර්ශනය සඳහා: කුමක්ද, කවදාද, වේලාව, ස්ථානය සහ සහභාගී විය යුත්තේ කවුරුන්ද යන්න.",
        formulaOrRule = "මාතෘකාව (NOTICE - BOLD) -> Event Name -> Date -> Time -> Venue -> Target Audience -> Contact Person",
        practicalApplication = "NOTICE: Annual Blood Donation Campaign organized by the Interact Club on 25th Nov at 9.00 am in the Main Hall.",
        examTip = "💡 දැන්වීම වටා කොටුවක් (border box) ඇඳීම අනිවාර්ය වන අතර කරුණු ලක්ෂ්‍ය ලෙස ඉදිරිපත් කිරීම පැහැදිලිය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_69",
        subject = "ඉංග්‍රීසි",
        toolNumber = 69,
        groupNumber = 7,
        titleSinhala = "ආරාධනා පත්‍ර සැකසීම (Invitation Card Layout)",
        titleEnglish = "Formal Invitation Card Format (RSVP)",
        category = "Writing",
        icon = "💌",
        quickSummary = "උත්සවයකට ගෞරවනීය ලෙස ආරාධනා කිරීම සහ RSVP (පිළිතුරු එවිය යුතු දුරකථන අංකය).",
        formulaOrRule = "Cordially invite you to the ... on [Date] at [Time] in the [Venue]. RSVP: [Contact]",
        practicalApplication = "The Principal and Staff cordially invite you to the Annual Prize Giving Ceremony.",
        examTip = "💡 RSVP යනු ප්‍රංශ බසින් 'කරුණාකර පිළිතුරු එවන්න' (Répondez s'il vous plaît) යන්නයි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_70",
        subject = "ඉංග්‍රීසි",
        toolNumber = 70,
        groupNumber = 7,
        titleSinhala = "විද්‍යුත් තැපැල් (Email Writing) ආකෘතිය",
        titleEnglish = "Formal & Informal Email Writing Rules",
        category = "Writing",
        icon = "📧",
        quickSummary = "To, Subject, Salutation, Body, Sign-off සහිත ඩිජිටල් සන්නිවේදන ආකෘතිය.",
        formulaOrRule = "To: [email address] | Subject: [පැහැදිලි කෙටි මාතෘකාව] | Body | Best regards, [Name]",
        practicalApplication = "Subject: Request for English Club Meeting Hall Reservation.",
        examTip = "💡 Subject line එක හිස්ව නොතැබිය යුතු අතර අකුරු 5-8 කින් අරමුණ පැහැදිලි කළ යුතුය."
      ),

      // --- GROUP 8: ESSAY & SPEECH WRITING (71-80) ---
      OlSubjectToolItem(
        id = "eng_tool_71",
        subject = "ඉංග්‍රීසි",
        toolNumber = 71,
        groupNumber = 8,
        titleSinhala = "රචනාවක හැඳින්වීමේ ඡේද සූත්‍රය (Introduction Hook)",
        titleEnglish = "Essay Introduction 3-Sentence Formula",
        category = "Essay Writing",
        icon = "🎯",
        quickSummary = "1. ආකර්ෂණීය ආරම්භක වැකිය (Hook) 2. මාතෘකාව පිළිබඳ සාමාන්‍ය පසුබිම 3. ප්‍රධාන තර්කය (Thesis).",
        formulaOrRule = "Hook (Quote/Question/Fact) + Background Context + Thesis Statement",
        practicalApplication = "\"A book is a dream that you hold in your hand.\" Reading is undoubtedly one of the most beneficial habits a person can cultivate in life.",
        examTip = "💡 ආරම්භක ඡේදය කියවන පරීක්ෂකවරයාගේ සිත් ඇදගන්නා සුළු ප්‍රබල වාක්‍යයකින් පටන් ගන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_72",
        subject = "ඉංග්‍රීසි",
        toolNumber = 72,
        groupNumber = 8,
        titleSinhala = "ශරීර ඡේද ගොඩනැගීමේ PEEL ක්‍රමය",
        titleEnglish = "Body Paragraph PEEL Method (Point, Explain, Example, Link)",
        category = "Essay Writing",
        icon = "🧱",
        quickSummary = "Point (ප්‍රධාන අදහස), Explain (විස්තර කිරීම), Example (උදාහරණය), Link (මාතෘකාවට සම්බන්ධ කිරීම).",
        formulaOrRule = "P = Topic Sentence | E = Elaboration | E = Concrete Evidence/Example | L = Connection to Topic",
        practicalApplication = "First and foremost, reading improves our vocabulary. When we read various books, we encounter new words. For instance, reading English newspapers helps students learn formal phrases. Therefore, it enhances our communication skills.",
        examTip = "💡 සෑම ශරීර ඡේදයකටම එක් ප්‍රධාන අදහසක් පමණක් තබාගෙන එය හොඳින් විස්තර කරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_73",
        subject = "ඉංග්‍රීසි",
        toolNumber = 73,
        groupNumber = 8,
        titleSinhala = "රචනාවක් නිමා කිරීමේ ඡේදය (Conclusion Formula)",
        titleEnglish = "Essay Conclusion Formula (Restate, Summarize, Final Thought)",
        category = "Essay Writing",
        icon = "🏁",
        quickSummary = "ප්‍රධාන අදහස් සාරාංශ කර අනාගතයට වැදගත් පණිවිඩයක් හෝ අවවාදයක් ලබාදීම.",
        formulaOrRule = "In conclusion / To sum up, [Restate thesis] + [Summary of main points] + [Call to action/Final prediction]",
        practicalApplication = "To sum up, while modern technology offers many entertainments, nothing can replace the value of reading books. Therefore, everyone should make reading a daily habit.",
        examTip = "💡 නිගමන ඡේදයට කිසිවිටෙකත් අලුත් අදහස් (New ideas) එකතු නොකරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_74",
        subject = "ඉංග්‍රීසි",
        toolNumber = 74,
        groupNumber = 8,
        titleSinhala = "කථාවක් පැවැත්වීමේ ආරම්භක ආමන්ත්‍රණය (Speech Openings)",
        titleEnglish = "Speech Writing Formal & Engaging Openings",
        category = "Speech Writing",
        icon = "🎤",
        quickSummary = "ප්‍රධාන ආරාධිතයාගේ සිට සහෝදර ශිෂ්‍යයන් දක්වා ගෞරවාන්විතව ආමන්ත්‍රණය කර මාතෘකාව හඳුන්වා දීම.",
        formulaOrRule = "Respected Principal, beloved teachers, and my dear school friends, Good morning to you all! Today, I stand before you to speak on the topic...",
        practicalApplication = "It gives me immense pleasure to share my thoughts on 'The Importance of Protecting the Environment'.",
        examTip = "💡 කථාවක් ලියන විට ශ්‍රාවකයන් අමතන වදන් (Dear friends, You may agree with me that...) නිතර යොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_75",
        subject = "ඉංග්‍රීසි",
        toolNumber = 75,
        groupNumber = 8,
        titleSinhala = "කථාවක් අවසන් කිරීමේ ස්තුති කතාව (Speech Closings)",
        titleEnglish = "Speech Writing Inspiring Closings & Thank You",
        category = "Speech Writing",
        icon = "👏",
        quickSummary = "ශ්‍රාවකයන්ගේ අවධානයට ස්තුති කර ප්‍රබල අවසන් ඉල්ලීමක් සිදුකිරීම.",
        formulaOrRule = "Let us join hands to [Action]. Thank you very much for listening to me patiently. Have a wonderful day!",
        practicalApplication = "Let us all pledge today to plant at least one tree in our home garden. Thank you all!",
        examTip = "💡 අවසානයේ 'Thank you' ලිවීම අනිවාර්ය වේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_76",
        subject = "ඉංග්‍රීසි",
        toolNumber = 76,
        groupNumber = 8,
        titleSinhala = "ප්‍රවෘත්ති වාර්තාවක් ලිවීම (News Report Format)",
        titleEnglish = "News Report Writing (Headline, Lead, Body, Byline)",
        category = "Writing",
        icon = "📰",
        quickSummary = "ආකර්ෂණීය සිරස්තලය, ස්ථානය, දිනය, වාර්තාකරු සහ ප්‍රධාන තොරතුරු.",
        formulaOrRule = "HEADLINE in bold -> COLOMBO (Special Correspondent): [5 Ws: Who, What, When, Where, Why]",
        practicalApplication = "COLOMBO: Over 500 students participated in the National Science Fair held at BMICH yesterday.",
        examTip = "💡 වාර්තාවක සිරස්තලය Simple Present Tense මගින් ලිවීම පුවත්පත් සම්ප්‍රදායයි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_77",
        subject = "ඉංග්‍රීසි",
        toolNumber = 77,
        groupNumber = 8,
        titleSinhala = "චරිතාපදානයක් ලිවීම (Biographical Sketch)",
        titleEnglish = "Biographical Sketch Writing Frame",
        category = "Writing",
        icon = "👤",
        quickSummary = "උපත, අධ්‍යාපනය, ජයග්‍රහණ, සේවාව සහ මරණය අනුපිළිවෙලින් Simple Past Tense මගින් ලිවීම.",
        formulaOrRule = "Early Life & Birth -> Education -> Major Achievements & Career -> Contributions to Society -> Legacy",
        practicalApplication = "Kumaratunga Munidasa was born on 25th July 1887. He dedicated his entire life to the revival of the Sinhala language.",
        examTip = "💡 දින වකවානු නිවැරදි අනුපිළිවෙලට ගළපා ලියන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_78",
        subject = "ඉංග්‍රීසි",
        toolNumber = 78,
        groupNumber = 8,
        titleSinhala = "කෙටි කතාවක් ගොඩනැගීම (Story Writing Elements)",
        titleEnglish = "Story Writing: Plot, Climax & Moral Formula",
        category = "Creative Writing",
        icon = "📖",
        quickSummary = "ආරම්භක පසුබිම, ගැටුම (Conflict), උච්චතම අවස්ථාව (Climax) සහ සාධනීය විසඳුම.",
        formulaOrRule = "Once upon a time / It was a dark rainy night -> Problem arises -> Turning point -> Happy / Meaningful Ending",
        practicalApplication = "Sudden twist: Just as he gave up hope, he saw a flickering light in the distance.",
        examTip = "💡 කතාවක සජීවී බව වැඩි කිරීමට චරිත අතර දෙබස් (Direct dialogue) කීපයක් යොදන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_79",
        subject = "ඉංග්‍රීසි",
        toolNumber = 79,
        groupNumber = 8,
        titleSinhala = "වාසි සහ අවාසි රචනා (Pros and Cons / Balanced Essay)",
        titleEnglish = "Advantages & Disadvantages Essay Balance",
        category = "Essay Writing",
        icon = "⚖️",
        quickSummary = "මාතෘකාවක දෙපැත්තම සාධාරණව විමසා බලා අවසානයේ පෞද්ගලික මතය දැක්වීම.",
        formulaOrRule = "Introduction -> Advantages (Para 2) -> Disadvantages (Para 3) -> Balanced Conclusion",
        practicalApplication = "Mobile phones: Instant communication vs Distraction from studies.",
        examTip = "💡 'On the one hand... On the other hand...' යෙදුම දෙපැත්ත සන්සන්දනයට කදිමයි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_80",
        subject = "ඉංග්‍රීසි",
        toolNumber = 80,
        groupNumber = 8,
        titleSinhala = "ප්‍රස්ථාර සහ වගු විස්තර කිරීම (Graph Description)",
        titleEnglish = "Describing Bar Charts & Pie Charts (Trends & Percentages)",
        category = "Information Transfer",
        icon = "📊",
        quickSummary = "O/L Test 15 හි ලකුණු 10ක් ලැබෙන ප්‍රස්ථාරයක් විස්තර කිරීමේ වචන මාලාව.",
        formulaOrRule = "The bar chart illustrates... / increased sharply / remained constant / the highest proportion was / in contrast",
        practicalApplication = "According to the chart, 45% of students preferred science, which is the highest percentage recorded.",
        examTip = "💡 තමන්ගේ මතය නොලියා ප්‍රස්ථාරයේ පෙනෙන දත්ත පමණක් නිවැරදිව වාර්තා කරන්න."
      ),

      // --- GROUP 9: IDIOMS, PROVERBS & VOCABULARY (81-90) ---
      OlSubjectToolItem(
        id = "eng_tool_81",
        subject = "ඉංග්‍රීසි",
        toolNumber = 81,
        groupNumber = 9,
        titleSinhala = "O/L විභාගයට අත්‍යවශ්‍ය රූඪි (Idioms 1-10)",
        titleEnglish = "Top 10 O/L Exam Idioms with Sinhala Meanings",
        category = "Idioms",
        icon = "💎",
        quickSummary = "වාච්‍යාර්ථයට වඩා වෙනස් ගැඹුරු අර්ථයක් දෙන ඉංග්‍රීසි රූඪි යෙදුම්.",
        formulaOrRule = "A piece of cake = ඉතා පහසු කාර්යයකි | Once in a blue moon = කලාතුරකින් | Break a leg = සුබ පැතුම් | Under the weather = අසනීපයෙන්",
        practicalApplication = "The Maths exam was a piece of cake for Kasun because he studied thoroughly.",
        examTip = "💡 රචනාවක හෝ කථාවක නිවැරදි තැනක රූඪියක් යෙදීමෙන් භාෂා ඥානයට ඉහළ ලකුණු ලැබේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_82",
        subject = "ඉංග්‍රීසි",
        toolNumber = 82,
        groupNumber = 9,
        titleSinhala = "ප්‍රසිද්ධ ඉංග්‍රීසි ප්‍රස්ථාව පිරුළු (Proverbs 1-10)",
        titleEnglish = "Top 10 English Proverbs & Life Lessons",
        category = "Proverbs",
        icon = "📜",
        quickSummary = "ප්‍රඥාවන්ත පිරුළු සහ ඒවායේ ප්‍රායෝගික ජීවිත පාඩම්.",
        formulaOrRule = "Practice makes perfect (පුහුණුවෙන් පරිපූර්ණ වේ) | Actions speak louder than words (ක්‍රියාව වචනයට වඩා බලවත්ය) | Where there is a will, there is a way (උවමනාව ඇත්නම් මගක් ඇත)",
        practicalApplication = "Better late than never. (ප්‍රමාද වී හෝ කිරීම නොකර සිටීමට වඩා හොඳය).",
        examTip = "💡 රචනාවක ආරම්භයට හෝ නිමාවට අදාළ පිරුළක් එක් කිරීම විශිෂ්ට උපක්‍රමයකි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_83",
        subject = "ඉංග්‍රීසි",
        toolNumber = 83,
        groupNumber = 9,
        titleSinhala = "Make vs Do නිවැරදි සමපාත (Collocations)",
        titleEnglish = "Make vs Do Collocations Matrix",
        category = "Collocations",
        icon = "⚙️",
        quickSummary = "යමක් නිර්මාණය කිරීම/නිපදවීම සඳහා 'Make' ද, ක්‍රියාකාරකම්/රාජකාරි සඳහා 'Do' ද යෙදේ.",
        formulaOrRule = "MAKE: a mistake, a decision, an effort, friends, money, noise | DO: homework, research, business, exercises, your best",
        practicalApplication = "I did my best, but I made a few careless mistakes in the test.",
        examTip = "💡 'Do a mistake' වැරදිය; 'Make a mistake' නිවැරදිය. 'Make homework' වැරදිය; 'Do homework' නිවැරදිය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_84",
        subject = "ඉංග්‍රීසි",
        toolNumber = 84,
        groupNumber = 9,
        titleSinhala = "සමානාර්ථ පද (Synonyms) සහ විරුද්ධාර්ථ පද (Antonyms)",
        titleEnglish = "Essential O/L Synonyms & Antonyms Vault",
        category = "Vocabulary",
        icon = "📚",
        quickSummary = "එකම වචනය නැවත නැවත නොලියා විවිධ සමානාර්ථ පද භාවිතයෙන් රචනා ඔප්නැංවීම.",
        formulaOrRule = "Important = crucial, vital, significant | Difficult = challenging, arduous | Happy = delighted, thrilled",
        practicalApplication = "Beautiful = attractive, gorgeous | Ancient = modern | Generous = stingy/selfish.",
        examTip = "💡 Test 7 සහ Test 11 කියවීමේ ප්‍රශ්නවල 'Find a word which has the same meaning' ලෙස අසයි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_85",
        subject = "ඉංග්‍රීසි",
        toolNumber = 85,
        groupNumber = 9,
        titleSinhala = "උපසර්ග (Prefixes) සහ ප්‍රත්‍ය (Suffixes) මගින් වචන තැනීම",
        titleEnglish = "Word Formation: Prefixes & Suffixes",
        category = "Word Formation",
        icon = "🧩",
        quickSummary = "විරුද්ධ පද සෑදීමට un-, dis-, im-, in-, il- උපසර්ග සහ පද බෙදීම් සඳහා -tion, -ment, -ful, -less ප්‍රත්‍ය.",
        formulaOrRule = "happy -> unhappy | possible -> impossible | legal -> illegal | care -> careless / careful",
        practicalApplication = "Develop (verb) -> development (noun) -> developing (adjective).",
        examTip = "💡 O/L Test 12 හි අනිවාර්යයෙන්ම වචන ස්වරූපය (noun, verb, adjective, adverb) වෙනස් කිරීමේ ප්‍රශ්නයක් ලැබේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_86",
        subject = "ඉංග්‍රීසි",
        toolNumber = 86,
        groupNumber = 9,
        titleSinhala = "පටලැවෙන වචන යුගල (Easily Confused Words)",
        titleEnglish = "Commonly Confused Words (Accept/Except, Affect/Effect)",
        category = "Vocabulary",
        icon = "🔀",
        quickSummary = "උච්චාරණය සමාන නමුත් අක්ෂර වින්‍යාසය සහ අර්ථය වෙනස් වචන.",
        formulaOrRule = "Accept (පිළිගන්නවා) vs Except (හැර) | Affect (බලපානවා - verb) vs Effect (ප්‍රතිඵලය - noun) | Lose (නැතිවෙනවා) vs Loose (ලිහිල්)",
        practicalApplication = "Smoking has a bad effect on health. / I accepted all the gifts except one.",
        examTip = "💡 Principal (විදුහල්පති) සහ Principle (මූලධර්මය) අතර වෙනස මතක තබාගන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_87",
        subject = "ඉංග්‍රීසි",
        toolNumber = 87,
        groupNumber = 9,
        titleSinhala = "සමූහ වාචී නාම පද (Collective Nouns)",
        titleEnglish = "Collective Nouns for Animals & People",
        category = "Vocabulary",
        icon = "🐝",
        quickSummary = "කණ්ඩායමක් නිරූපණය කිරීමට යොදන විශේෂිත නාම පද.",
        formulaOrRule = "a flock of birds/sheep | a herd of cattle/elephants | a swarm of bees | a pack of wolves | a bunch of flowers/grapes",
        practicalApplication = "A swarm of bees attacked the villagers.",
        examTip = "💡 Collective noun එකක් සාමාන්‍යයෙන් සලකන්නේ ඒකවචනයක් ලෙසය (A herd of elephants is crossing the road)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_88",
        subject = "ඉංග්‍රීසි",
        toolNumber = 88,
        groupNumber = 9,
        titleSinhala = "නාමවිශේෂණවල සංසන්දනාත්මක සහ අතිශයෝක්ති ස්වරූප",
        titleEnglish = "Degrees of Comparison (Positive, Comparative, Superlative)",
        category = "Grammar",
        icon = "📶",
        quickSummary = "Tall - taller - tallest | Beautiful - more beautiful - most beautiful | Good - better - best.",
        formulaOrRule = "Comparative + than | The + Superlative (the highest, the best)",
        practicalApplication = "Mount Everest is the highest mountain in the world. / Sri Lanka is smaller than India.",
        examTip = "💡 Superlative අගයට ඉදිරියෙන් අනිවාර්යයෙන්ම 'the' යෙදිය යුතුය."
      ),
      OlSubjectToolItem(
        id = "eng_tool_89",
        subject = "ඉංග්‍රීසි",
        toolNumber = 89,
        groupNumber = 9,
        titleSinhala = "ක්‍රියාවිශේෂණ (Adverbs of Manner, Time, Place)",
        titleEnglish = "Adverbs Formation & Correct Positioning",
        category = "Grammar",
        icon = "⚡",
        quickSummary = "ක්‍රියාව සිදුවූ ආකාරය දක්වන -ly සහිත පද (slowly, carefully, beautifully).",
        formulaOrRule = "Adjective + ly = Adverb (quick -> quickly) | Fast -> Fast (Fastly කියා වචනයක් නොමැත)",
        practicalApplication = "He drove carefully on the slippery road. / She speaks English fluently.",
        examTip = "💡 Hard යන්නෙහි Adverb ස්වරූපයද Hard ම වේ; 'Hardly' යනු 'කලාතුරකින්/නැති තරම්' යන සම්පූර්ණයෙන්ම වෙනස් අර්ථයකි."
      ),
      OlSubjectToolItem(
        id = "eng_tool_90",
        subject = "ඉංග්‍රීසි",
        toolNumber = 90,
        groupNumber = 9,
        titleSinhala = "ප්‍රශ්න පෝච්චි (Question Tags) නීති",
        titleEnglish = "Question Tags Master Rules",
        category = "Grammar",
        icon = "🏷️",
        quickSummary = "වාක්‍යය ධන නම් tag එක ඍණ වේ; වාක්‍යය ඍණ නම් tag එක ධන වේ.",
        formulaOrRule = "You are a student, aren't you? | She doesn't like milk, does she? | Let's go, shall we? | Open the door, will you?",
        practicalApplication = "He can swim, can't he? / They arrived late, didn't they?",
        examTip = "💡 'I am' සඳහා tag එක වන්නේ 'aren't I?' ය ('amn't I' නොවේ)."
      ),

      // --- GROUP 10: O/L EXAM PAPER SCORING STRATEGIES (91-100) ---
      OlSubjectToolItem(
        id = "eng_tool_91",
        subject = "ඉංග්‍රීසි",
        toolNumber = 91,
        groupNumber = 10,
        titleSinhala = "Test 1: පින්තූර ගැලපීම (Matching Pictures - ලකුණු 5)",
        titleEnglish = "Test 1: Picture Matching Strategy",
        category = "Exam Strategy",
        icon = "🖼️",
        quickSummary = "ප්‍රකාශයේ ඇති ප්‍රධාන මූල පද (Key words) පින්තූරයේ ඇති ක්‍රියා හා සසඳා බැලීම.",
        formulaOrRule = "පළමුව සියලු පින්තූරවල සිදුවන දේ නිරීක්ෂණය කරන්න; පසුව වාක්‍යවල ක්‍රියා පද යටින් ඉරි අඳින්න.",
        practicalApplication = "'A boy reading under a tree' -> ගස යට පොතක් කියවන ළමයා සිටින අදාළ අකුර (A, B, C...) ලියන්න.",
        examTip = "💡 අකුරු පැහැදිලිව ලියන්න; එකම අකුර දෙවරක් යෙදෙන්නේ නැත."
      ),
      OlSubjectToolItem(
        id = "eng_tool_92",
        subject = "ඉංග්‍රීසි",
        toolNumber = 92,
        groupNumber = 10,
        titleSinhala = "Test 2: වචන ගැලපීම සහ අර්ථ හඳුනාගැනීම (ලකුණු 5)",
        titleEnglish = "Test 2: Word Association & Categorization",
        category = "Exam Strategy",
        icon = "🔤",
        quickSummary = "දී ඇති වචන පෙට්ටියෙන් සුදුසු වචනය තෝරා හිස්තැන් පිරවීම.",
        formulaOrRule = "හිස්තැනට පෙර සහ පසු ඇති වචන කියවා අවශ්‍ය වන්නේ නාම පදයක්ද, ක්‍රියාවක්ද, ගුණ පදයක්ද යන්න තීරණය කරන්න.",
        practicalApplication = "පරිසරය, ක්‍රීඩා හෝ පාසල ආශ්‍රිත වචන මාලාව සාමාන්‍යයෙන් අසයි.",
        examTip = "💡 එක් වචනයක් යෙදූ පසු එය පැන්සලෙන් කපා ඉවත් කරන්න (elimination method)."
      ),
      OlSubjectToolItem(
        id = "eng_tool_93",
        subject = "ඉංග්‍රීසි",
        toolNumber = 93,
        groupNumber = 10,
        titleSinhala = "Test 3: නිපාත පද හිස්තැන් පිරීම (Prepositions - ලකුණු 5)",
        titleEnglish = "Test 3: Prepositions Cloze Test Strategy",
        category = "Exam Strategy",
        icon = "✏️",
        quickSummary = "In, on, at, with, for, to, from, by, of නිවැරදිව තෝරා ගැනීම.",
        formulaOrRule = "කාලය, ස්ථානය හෝ Dependent preposition රටාව හඳුනාගන්න.",
        practicalApplication = "He is keen on sports / interested in science / arrived at the airport.",
        examTip = "💡 පූර්ණ ලකුණු 5ම ලබාගත හැකි පහසුම ප්‍රශ්නයකි; නීති මතකයේ තබාගන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_94",
        subject = "ඉංග්‍රීසි",
        toolNumber = 94,
        groupNumber = 10,
        titleSinhala = "Test 4: තොරතුරු නිස්සාරණය (Information Transfer - ලකුණු 5)",
        titleEnglish = "Test 4: Information Extraction & Table Completion",
        category = "Exam Strategy",
        icon = "📋",
        quickSummary = "කෙටි ඡේදයක් කියවා වගුවක හෝ සටහනක අසන තොරතුරු කෙටියෙන් ලිවීම.",
        formulaOrRule = "දිනය, ස්ථානය, සහභාගිවන්නන්, ප්‍රවේශ පත්‍ර ගාස්තු ආදී නිශ්චිත දත්ත සෘජුව උපුටා දක්වන්න.",
        practicalApplication = "සම්පූර්ණ වාක්‍ය ලිවීම අනවශ්‍යයි; අදාළ තොරතුර (short phrase) පමණක් ලියන්න.",
        examTip = "💡 අක්ෂර වින්‍යාස වැරදි (spelling mistakes) නොවීමට ඡේදයෙන්ම බලා නිවැරදිව ලියන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_95",
        subject = "ඉංග්‍රීසි",
        toolNumber = 95,
        groupNumber = 10,
        titleSinhala = "Test 5: සංවාද හිස්තැන් පිරීම (Dialogue Completion - ලකුණු 5)",
        titleEnglish = "Test 5: Conversational Flow Completion",
        category = "Exam Strategy",
        icon = "💬",
        quickSummary = "දෙදෙනෙකුගේ සංවාදයක ප්‍රතිචාර සහ ප්‍රශ්න නිවැරදිව තෝරා පිරවීම.",
        formulaOrRule = "හිස්තැනට පහළින් ඇති පිළිතුර කියවන්න; එම පිළිතුරෙන් ඉහළින් ඇසිය යුතු ප්‍රශ්නය හෙළිවේ.",
        practicalApplication = "පිළිතුර 'At 4.00 pm' නම්, ඉහළ ප්‍රශ්නය 'What time does the film start?' විය යුතුය.",
        examTip = "💡 ප්‍රශ්න වචන (What, When, Where, Why, How) කෙරෙහි අවධානය යොමු කරන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_96",
        subject = "ඉංග්‍රීසි",
        toolNumber = 96,
        groupNumber = 10,
        titleSinhala = "Test 7: කෙටි ඡේද කියවා තේරුම් ගැනීම (Comprehension - ලකුණු 5)",
        titleEnglish = "Test 7: Reading Comprehension 5-Mark Technique",
        category = "Exam Strategy",
        icon = "📖",
        quickSummary = "පළමුව ප්‍රශ්න කියවා, පසුව ඡේදය කියවීමේ (Questions First) උපායමාර්ගය.",
        formulaOrRule = "ප්‍රශ්නයේ ඇති Key words ඡේදයේ ඇති තැන සොයා ඒ වටා ඇති වාක්‍ය ප්‍රවේශමෙන් කියවන්න.",
        practicalApplication = "සෘජු පිළිතුරු, True/False සහ සර්වනාමවලින් අදහස් කරන පුද්ගලයා සෙවීම.",
        examTip = "💡 'What does the word \"it\" in line 4 refer to?' වැනි ප්‍රශ්නවලට එම වාක්‍යයට කලින් ඇති නාම පදය සොයන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_97",
        subject = "ඉංග්‍රීසි",
        toolNumber = 97,
        groupNumber = 10,
        titleSinhala = "Test 9: ව්‍යාකරණ සංශෝධන (Grammar Cloze - ලකුණු 5)",
        titleEnglish = "Test 9: Advanced Grammar Fill-in Strategy",
        category = "Exam Strategy",
        icon = "⚙️",
        quickSummary = "වරහන් තුළ දී ඇති ක්‍රියා පදයේ නිවැරදි ස්වරූපය (Tense, Voice, Infinitive, Gerund) ලිවීම.",
        formulaOrRule = "වාක්‍යයේ කාලය (past or present), කර්තෘ ඒකවචනද බහුවචනද, සහ Active ද Passive දැයි බලන්න.",
        practicalApplication = "Yesterday, a cricket match was (play) -> played (was + V3).",
        examTip = "💡 To පිටුපසින් Base verb ද (to go), Preposition පිටුපසින් -ing ද (after going) යෙදේ."
      ),
      OlSubjectToolItem(
        id = "eng_tool_98",
        subject = "ඉංග්‍රීසි",
        toolNumber = 98,
        groupNumber = 10,
        titleSinhala = "Test 11: දීර්ඝ කියවීම් ඡේදය (Reading Comprehension - ලකුණු 7-8)",
        titleEnglish = "Test 11: Long Passage Skimming & Scanning",
        category = "Exam Strategy",
        icon = "🔍",
        quickSummary = "Skimming (ප්‍රධාන අදහස වටහා ගැනීම) සහ Scanning (නිශ්චිත නම්, වර්ෂ, දත්ත සෙවීම).",
        formulaOrRule = "ප්‍රශ්නවල අනුපිළිවෙල අනුව ඡේදවල තොරතුරුද බොහෝවිට අනුපිළිවෙලින් පිහිටයි.",
        practicalApplication = "පළමු ප්‍රශ්නය පළමු ඡේදයෙන්ද, අවසාන ප්‍රශ්නය අවසාන ඡේදයෙන්ද හමුවේ.",
        examTip = "💡 තමන්ගේ දැනුමෙන් නොව ඡේදයේ සඳහන් තොරතුරුවලින් පමණක් පිළිතුරු සපයන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_99",
        subject = "ඉංග්‍රීසි",
        toolNumber = 99,
        groupNumber = 10,
        titleSinhala = "Test 14: විධිමත්/අවිධිමත් ලිපි ලකුණු කිරීමේ නිර්ණායක (ලකුණු 10)",
        titleEnglish = "Test 14 Letter Marking Rubric (Content, Format, Language)",
        category = "Exam Strategy",
        icon = "💯",
        quickSummary = "ලකුණු 10 බෙදී යන ආකාරය: අන්තර්ගතය (Content - 3), ආකෘතිය (Format - 2), භාෂාව (Language - 3), සංවිධානය (Organization - 2).",
        formulaOrRule = "දී ඇති සියලු උපදෙස් ඇතුළත් කිරීම + නිවැරදි ආකෘතිය + ව්‍යාකරණ වැරදි අවම කිරීම.",
        practicalApplication = "වචන 100 ක පමණ ප්‍රමාණයක් ඡේද 3 කට ලියන්න.",
        examTip = "💡 අත් අකුරු ඉතා පැහැදිලිව තබා ගන්න; වචන අතර නිසි පරතරය තබන්න."
      ),
      OlSubjectToolItem(
        id = "eng_tool_100",
        subject = "ඉංග්‍රීසි",
        toolNumber = 100,
        groupNumber = 10,
        titleSinhala = "Test 16: රචනා / ලිපි / කථා 15න් 15ම ලබාගැනීමේ උපායමාර්ගය",
        titleEnglish = "Test 16: 15-Mark Master Strategy (Essay, Speech, Article)",
        category = "Exam Strategy",
        icon = "🏆",
        quickSummary = "O/L ඉංග්‍රීසි ප්‍රශ්න පත්‍රයේ වැඩිම ලකුණු හිමිවන අවසන් ප්‍රශ්නය ජයගැනීමේ පියවර.",
        formulaOrRule = "Content (4), Language (5), Format & Organization (3), Mechanics of writing - Spelling/Punctuation (3) = Total 15 Marks",
        practicalApplication = "වචන 200ක පමණ ප්‍රමාණයක් ඡේද 4-5කට සංවිධානය කර විවිධ tenses, passive voice, සම්බන්ධක සහ උසස් වචන මාලාවකින් ලියන්න.",
        examTip = "💡 ලිවීමෙන් පසු අවම වශයෙන් මිනිත්තු 3ක් ගෙන අක්ෂර වින්‍යාස (spelling), තිත, කොමාව සහ ප්‍රාග්ධන අකුරු (capital letters) පරීක්ෂා කරගන්න."
      )
    )
  }
}
